- packages/af-webpack/src/getConfig.js
修改`css-modules`hash规则
在开发环境下由原来`[local]___[hash:base64:5]`修改为`[name]__[local]___[hash:base64:5]`
其他环境不变
> update cssModules config

- .eslintrc
Add eslint rules to fix warnings below:
- [eslint] 'window' is  not defined. (no-undef).
- [eslint] The href attribute is required on an anchor. Provide a valid, navigable address as the href value. (jsx-a11y/anchor-is-valid).
- [eslint] Visible, non-interactive elements with click handlers must have at least one keyboard listener. (jsx-a11y/click-events-have-key-events).
- [eslint] Unexpected use of 'self'. (no-restricted-globals).
> Add some eslint rules

- packages/af-webpack/src/getConfig.js
支持tsconfig.json中使用路径映射
`    "paths": {
"ApiService": [ "src/services/service-proxies.ts" ]
},
`
> Advanced path resolution in TypeScript 2.0

- .vscode/settings.json
- packages/babel-preset-umi/src/index.js
```js
[require.resolve('@babel/preset-env'),
{
targets: opts.targets || { browsers },
debug: opts.debug,
useBuiltIns: opts.useBuiltIns,
modules: false,
....
}
]
```
> babel-preset-umi support useBuiltIns customization

- packages/af-webpack/src/getConfig.js
> fix(af-webpack): image loader match failed when have directory named *.html

- packages/umi-build-dev/src/getWebpackConfig.js
> fix(umi-build-dev): extraBabelPresets and extraBabelPlugins don't work

- packages/af-webpack/src/patchConnection.js
Make disconnet messages  look better
Before:
After:
Use Ant Design Calendula Gold.
> :lipstick: Polish the disconnet Message Interface

- packages/umi-plugin-dll/src/index.js
Refused to execute script from 'http://localhost:55943/__umi.dll.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
> Fixed MIME type error

- examples/with-dva/src/dva.js
- examples/with-dva/src/plugins/onError.js
- packages/umi-plugin-dva/src/index.js
- packages/umi-plugin-dva/template/DvaContainer.js
Close #261 
新建 src/dva.js，通过导出的 config 方法来返回额外配置项，比如：
```js
import { message } from 'antd';
export function config() {
return {
onError(err) {
err.preventDefault();
message.error(err.message);
},
initialState: {
global: {
text: 'hi umi + dva',
},
},
};
}
```
> feat(umi-plugin-dva): config dva via dva.js

- package.json
- packages/af-webpack/src/getConfig.js
Changes:
1. 如果有指定 APP_ROOT，会从 APP_ROOT 下找 tsconfig.json
2. 支持在 .webpackrc 中通过 tsConfigFile 配置 tsconfig.json 的路径
> feat(af-webpack): support opts.tsConfigFile and resolve default tsconfig.json under cwd

- packages/af-webpack/package.json
- packages/af-webpack/src/getConfig.js
As the title said, when using `ant-design-pro-cli` with `npm run start`, the console prints nothing but:
```
Starting the development server...
[babel-plugin-dva-hmr][INFO] got routerPath ./router
```
which is not very convenient to get the progress of build process, so how about add [progress-bar-webpack-plugin](https://www.npmjs.com/package/progress-bar-webpack-plugin) to webpack configuration?
> feat(af-webpack):add progress-bar-webpack-plugin for indicating progress of build process

- packages/umi/bin/umi.js
A help command might make umi more friendly to the developers.
Comparing with the help command of [Gatsby][1] and [next][2]. In consideration, umi only own few commands now... add a simple help command temporarily.
+ `help() {}`:
```javascript
const cmds = {
"build": "create a production build",
"dev": "start a development server",
"help": "show help",
"-v, --version": "show version",
};
function help(aliasedScript) {
let usage = "\nUsage: umi <command>\n";
let helpArea = "";
for(var cmd in cmds) {
helpArea += ("  " + cmd + Array(25 - cmd.length).join(' ') + cmds[cmd] + '\n');
};
console.log([usage,helpArea].join("\nCommands:\n"));
aliasedScript !== "help" && console.log(`Unknown script ${chalk.cyan(aliasedScript)}.`);
}
```
```shell
$ time ./umi.js help
real	0m0.133s
user	0m0.097s
sys …
```
> add help command

- packages/umi-build-dev/src/getWebpackConfig.js
Close #306 
1. 项目中有 react 和 react-dom 依赖，会取依赖的版本
2. preact 则取 preact-compat
> feat(umi-build-dev): resolve local react and react-dom if specified in package.json

- packages/af-webpack/src/dev.js
1. HTTPS=true roadhog server
2. HTTPS=true contentBase=./ roadhog server ( contentBase is static folder, eg1:  demo/index.html )
> run https server

- packages/umi-plugin-dva/package.json
- packages/umi-plugin-dva/src/index.js
内置常用依赖，其中使用 dva-immer 时肯定会用到 obect-assign 。
> feat(umi-plugin-dva): built-in path-to-regexp and object-assign

- packages/af-webpack/src/getUserConfig/index.js
支持对config在校验前做一些预处理， 方便roadhog之类的工具定制， 简化配置或者加些默认配置、自定义配置
> feat(af-webpack): add preprocessor for config

- packages/umi-build-dev/src/getRouteConfig.js
> fix: winPath problem with dynamic routes

- packages/umi-plugin-dva/package.json
> fix(umi-plugin-dva): path-to-regexp's version is uncompatible with react-router@4

- packages/umi-build-dev/src/plugins/global-css.js
https://github.com/umijs/umi/issues/390
在Windows下测试通过，不知道为什么要写
```js
‘\\r\\n’
```
> fix: import global css failed when have multiple global css files

- packages/umi-plugin-es5-imcompatible-versions/README.md
- packages/umi-plugin-es5-imcompatible-versions/package.json
- packages/umi-plugin-es5-imcompatible-versions/src/index.js
Related links:
* https://github.com/umijs/umi-examples/tree/master/es5-imcompatible-versions
* https://github.com/umijs/es5-imcompatible-versions
* https://github.com/sorrycc/blog/issues/68
> new plugin: umi-plugin-es5-imcompatible-versions

- packages/umi-plugin-dva/src/index.js
```tsx
import { message } from 'antd';
....
effects: {
*fetch(action, { put, call }) {
message.loading(<div>Loading some data</div>, 0);
const result = yield call(fetch);
message.destory();
...
...
```
> feat: support load model.tsx, model.jsx

- packages/umi-build-dev/src/FilesGenerator.js
> fix: router replace don't work with dynamic routes in windows

- packages/umi-build-dev/package.json
- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js
- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.test.js
- packages/umi-build-dev/src/routes/patchRoutes.js
- packages/umi-build-dev/src/routes/patchRoutes.test.js
- packages/umi/src/renderRoutes.js
Close #404 
---
Checkout [routes-via-config](https://github.com/umijs/umi-examples/tree/master/routes-via-config) for example.
> feat: support redirect via config

- packages/af-webpack/getUserConfigPlugins.js
- packages/af-webpack/src/getUserConfig/getPlugins.js
- packages/af-webpack/src/getUserConfig/index.js
- packages/umi-build-dev/src/getConfig/configPlugins/routes.js
- packages/umi-build-dev/src/getPlugins.js
- packages/umi-build-dev/src/getWebpackConfig.js
- packages/umi-build-dev/src/plugins/afwebpack-config.js
- packages/umi/src/scripts/realDev.js
So, we don't need .webpackrc anymore.
> feat: use umirc for webpack config

- packages/umi-build-dev/src/getWebpackConfig.js
- packages/umi-build-dev/src/routes/routesToJSON.js
- packages/umi-build-dev/src/routes/routesToJSON.test.js
* dynamicLevel 默认为 1
* 根节点下 path 为 / 的 route 如果有 routes，则 dynamicLevel 为 2
```
+ pages
- a.js
- b.js
+ c
- _layout.js
- c1.js
- c2.js
```
note: 
* dynamicLevel 为 1
* 拆 a.js、b.js、c.js（包含 c1、c2 及其 _layout.js）
```
+ layouts/index.js
+ pages
- a.js
- b.js
+ c
- _layout.js
- c1.js
- c2.js
```
note:
* dynamicLevel 为 2
* layouts/index.js 会合并到 common-umi 里
* 拆 a.js、b.js、c.js（包含 c1、c2 及其 _layout.js）
```
[
{ path: '/login' },
{ path: '/', routes: [
{ path: '/a' },
{ path: '/b' },
{ path: '/c', routes: [
{ path: '/c1' },
{ path: '/c2' },
] },
]},
]
```
* dynamicLevel 为 2
* 拆 /login 和 /，由于有差异，所以不会自动合并到 common-umi
* 拆 a.js、b.js、c.js（包含 c1、c2 及其 _layout.js）
> fix(umi-build-dev): dynamic import code splitting

- packages/af-webpack/package.json
- packages/af-webpack/src/getConfig.js
- packages/umi-plugin-dll/src/index.js
以 [umi-antd-admin](https://github.com/umijs/umi-antd-admin) 为例，dll + hard-source-webpack-plugin 后编译时间 0.9s，启动时间 7.7s。
> feat(af-webpack): enable hard-source-webpack-plugin to boost performance

- packages/umi-build-dev/src/getPlugins.js
- packages/umi-build-dev/src/plugins/mock/index.js
$ MOCK=none umi dev
Respond #486
> can be closed mock

- packages/umi-build-dev/package.json
- packages/umi-build-dev/src/UserConfig.js
- packages/umi-build-dev/src/UserConfig.test.js
- packages/umi-build-dev/src/fixtures/UserConfig/config-config/config/config.custom.js
- packages/umi-build-dev/src/fixtures/UserConfig/config-config/config/config.local.js
- packages/umi-build-dev/src/fixtures/UserConfig/umirc/.umirc.custom.js
- packages/umi-build-dev/src/fixtures/UserConfig/umirc/.umirc.local.js
- packages/umi-build-dev/src/registerBabel.js
Notes:
* 如果有配 `UMI_ENV`，比如 UMI_ENV=cloud，则会用 `config/config.cloud.js` 合并 `config/config.js`
* dev 模式下时会额外加载 `.local.js`，并合并到配置里
* 此方式同样支持 `.umirc.js`，比如 `.umirc.local.js`
* `*.local.js` 的配置文件通常需要添加到 .gitignore，不要提交
> feat(umi-build-dev): support config via env, e.g. config.{env}.js

- packages/af-webpack/src/getConfig.js
- packages/umi-build-dev/src/UserConfig.js
ref: #521 
---
依赖一个不存在的模块时，会导致 cpu 100%+，原因是 https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/WatchMissingNodeModulesPlugin.js 这个插件引起的，cnpm/tnpm 下明显会卡，yarn 有一点感觉，但不明显，create-react-app 也有这个问题，但他们用 yarn，所以不明显（换成 cnpm/tnpm 安装就很明显了）。
> fix: import from lost dep will cause 100% cpu

- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js
- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.test.js
例子：https://github.com/umijs/umi-examples/tree/master/routes-via-config-bigfish
> fix(umi-build-dev): redirect don't compatible with bigfish's style

- packages/umi-build-dev/package.json
- packages/umi-build-dev/src/getPlugins.js
- packages/umi-build-dev/src/plugins/afwebpack-config.js
- packages/umi-build-dev/src/plugins/proxy.js
> feat(umi-build-dev): improve proxy

- packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
Close #562 
Close #556 
Thanks for the [PR](https://github.com/umijs/umi/pull/562) from @hansnow .
> fix(umi-build-dev): winPath causes NotFound route crash

- packages/af-webpack/src/getConfig.js
由于反馈比较多，所以默认禁用以下两个功能：
1. hard-source-webpack-plugin，这个提效明显，关闭他其实很犹豫
2. awesome-typescript-loader 的 ts_config_paths_plugin
可通过 HARD_SOURCE=1 和 TS_CONFIG_PATHS_PLUGIN=1 开启。
Close #521
> feat(af-webpack): disable hard source and tsconfigpathsplugin by default

- packages/af-webpack/src/getConfig.js
- packages/af-webpack/src/getUserConfig/configs/typescript.js
Close #450
Close #451
在webpackrc中增加
```js
typescript:{
reportFiles: ["pages/**/*.{ts,tsx}"],
transpileOnly:false
}
};
```
> feat: add config typescript for awesome-typescript-loader

- docs/guide/examples-and-boilerplates.md
> fix: incorrect links in examples-and-boilerplates.md

- scripts/build.js
之前的配置一直是错的， `@babel/preset-env` 的最新版会做[校验](https://github.com/babel/babel/commit/3de053cc6c94be9411deb213cfc53c1392b5f6eb#diff-511b392361cfba9fae7bdc816eae9308)导致 build 报错。
配置参考： https://new.babeljs.io/docs/en/next/babel-preset-env.html#targetsbrowsers
另外 umi 里面锁死了 `@babel/preset-env` 为 7.0.0-beta.46，这个问题暂时不会暴露。
> fix @babel/preset-env browsers config

- packages/af-webpack/src/getConfig.js
when exec `"APP_ROOT=yunfengdie/app/assets umi build"` in [egg](https://github.com/eggjs/examples/blob/master/assets-with-umi/package.json#L36), af-webpack still look eslintrc in `/.eslintrc`, which should be `/yunfengdie/app/assets/.eslintrc`
> fix: af-webpack should resolve eslintrc according to APP_ROOT

- packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
Not just `post`, `['put', 'patch']` should working with `bodyParser` as well, this is usually helpful in customized mocking
> feat: put, patch methods should available for bodyParser as well

- packages/umi-plugin-polyfill/README.md
- packages/umi-plugin-polyfill/package.json
- packages/umi-plugin-polyfill/src/global.js
针对当前IE9+兼容性问题引入对应的polyfill包，而不是把全部的babel/polyfill都引入
Close #652
> feat: improve umi-plugin-polyfill, reduce bundle size

- packages/af-webpack/src/getConfig/css.js
af-webpack 默认配置项中css-loader dev环境下没有开启sourceMap
修改为不区分是否是dev环境，均根据disableCSSSourceMap配置项配置是否开启sourceMap
> af-webpack sourceMap bug fix

- packages/umi-build-dev/src/DefaultLayout.js
- packages/umi-build-dev/src/plugins/404/index.js
- packages/umi-build-dev/src/routes/patchRoutes.js
路由不 exact 匹配，自动跳转到 /404
会自动在所有嵌套子路由数组的最后添加 umi not found 页面路由，不做自动跳转
> feat: redirect to 404 if none router exact match

- packages/umi-build-dev/src/html/HTMLGenerator.js
- packages/umi-build-dev/src/html/HTMLGenerator.test.js
umi 的样式应该在其它引入的第三方样式之后，这样才能使得用户在应用中的样式的优先级是最高的，不会被第三方样式覆盖。
> fix: move umi.css to the last

- packages/umi/bin/umi.js
- packages/umi/package.json
- Use atool-monitor@0.x, because there is no demands to report more data for now.
> Feat: Add atool monitor for umi@1.x

- packages/af-webpack/src/getConfig/dev.js
- packages/af-webpack/src/webpackHotDevClient.js
cheap-module-eval-source-map 会导致 `window.addEventListener('error')` 不工作。
> fix: runtime error overlay don't work

- packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
babel7 里面 module 会有一个  `__esModule` 标记是否是 es module，会导致这里的 assert 报错。
> fix: mock bug with babel7

- packages/umi-build-dev/src/routes/getYamlConfig.js
- packages/umi-build-dev/src/routes/getYamlConfig.test.js
发现生成的 routes 信息包含无关的信息，所以简单过滤下 yaml 加载进来的数据。
> fix: simple filter not yaml comment

- packages/umi-build-dev/package.json
- packages/umi-build-dev/src/UserConfig.js
- packages/umi-build-dev/src/UserConfig.test.js
- packages/umi-build-dev/src/fixtures/UserConfig/config-config/config/config.custom.js
- packages/umi-build-dev/src/fixtures/UserConfig/config-config/config/config.js
原先的 getConfig 方式不会 deep merge，都会以后一个完整覆盖前一个对象。
这就造成了比较深的对象要在每个 config 都完成声明一遍，比如 define 配置。
extend2 是保持和 egg 一致的配置合并方式。
> feat: use extend2 for deep merge config

- packages/af-webpack/src/getConfig/css.js
给 css-loader 的参数 cssLoaderOptions 中，localIdentName 这个用户没法自定义，应该给加上。另外如果不启用 css module 的话 localIdentName 还是不给用户配好了。
> feat: add css-loader option localIdentName

- packages/umi/package.json
- packages/umi/src/buildDevOpts.js
目前 APP_ROOT 比较特殊，需要在跑 Service 之前确定 cwd 的地址。
而目前要改变这个值，只能通过命令行传值。
支持 .env 的方式会比较方便，跑 `umi g page` 的时候也不需要 alias 了。
> feat: builddevoptions cwd support dot env

- packages/umi/src/scripts/realDev.js
SIGINT 信号应该通知进程正常退出。
现在 CTRL + C 会报一堆红色的错误信息，让人误解。
> fix: process receive sigint should exit 0

- packages/af-webpack/bin/af-webpack.js
修复 af-webpack cli 脚本中的两个问题：
- entry 覆盖顺序有误
- 函数调用有误
> fix: 修复 af-webpack bin 函数调用和变量覆盖错误的问题

- packages/af-webpack/src/getUserConfig/configs/chainConfig.js
支持通过 cli 调用 af-webpack 时配置 chainConfig：
- 比如自定义额外的 webpack plugin
.webpackrc.js
```js
.chainConfig(c) {}
}
```
```
$ af-webpack dev
```
> feat: 开放 af-webpack chainConfig 配置

- packages/af-webpack/src/getConfig/index.js
> feat(af-webpack): .json 的优先级应该比 js, ts 低

- packages/af-webpack/bin/af-webpack.js
支持传入 `AF_CONFIG_FILE` 环境变量指定 af-webpack 的配置文件地址。
需求来源：
- 某些部署工具执行文件复制时，会忽略 `.` 开头的文件（如 chair-script），于是 `.webpackrc` 文件被跳过
- 不同的构建目标需要不同的配置，希望能直接指定配置文件路径，类似 `webpack --config xxx` 的用法
> feat: af-webpack 支持指定 config file 路径

- packages/umi-plugin-locale/package.json
- packages/umi-plugin-locale/src/index.js
- packages/umi-plugin-locale/template/wrapper.jsx.tpl
- packages/umi-plugin-locale/test/index.test.js
close https://github.com/ant-design/ant-design-pro/issues/2184
> fix: locale moment bug [在 locale 插件中引入 moment 相关文件]

- packages/af-webpack/src/dev.js
- packages/af-webpack/src/getConfig/dev.js
- packages/af-webpack/src/getUserConfig/configs/devServer.js
> feat: add webpack-dev-server config entry (#1016)

- packages/af-webpack/package.json
高版本的 webpack-dev-server 中移除了 `webpack-dev-server/lib/optionsSchema.json` 这个文件（目前最高 3.1.8），本地调试 umi 时会报错，锁定到 3.1.5
> fix: lock version of webpack-dev-server

- packages/af-webpack/src/getConfig/dev.js
Close #1071
``` 
environmentHash: {
root: process.cwd(),
directories: [],
files: ['package-lock.json', 'yarn.lock'],
},
```
默认情况下 他之监听了这2个文件
https://github.com/mzgoddard/hard-source-webpack-plugin#environmenthash
> 修改开启hard-source后，修改.umirc配置文件DefinePlugin无效的问题

- docs/config/README.md
- docs/guide/faq.md
- docs/zh/config/README.md
- packages/umi-build-dev/src/getConfig/configPlugins/disableRedirectHoist.js
- packages/umi-build-dev/src/routes/patchRoutes.js
- packages/umi-build-dev/src/routes/patchRoutes.test.js
出于一些原因的考虑，我们在处理路由时把所有 redirect 声明提到路由最前面进行匹配，但这导致了一些问题，所以添加了这个配置项，禁用 redirect 上提。
比如：
1. https://github.com/ant-design/ant-design-pro/issues/2259
2. 下面的路由配置，访问 `/console` 会访问到 `/console/overview`，因为 redirect 规则往前提了。
```
routes: [{
path: '/',
component: 'Index/App',
indexRoute: { redirect: '/console' },
routes: [
{
path: '/',
component: '../components/layout/Default',
routes: [
{
path: '/console',
component: 'Index/Dashboard',
},
{
path: '/:productName',
indexRoute: { redirect: '/:productName/overview' },
routes: [
{
path: '/:productName/overview',
component: 'Index/product/Overview'
},
]
},
]
}
],
}],
```
> feat: add config.disableRedirectHoist

- packages/babel-preset-umi/package.json
fix errors like
```bash
Duplicate declaration "React"
> 1 | import React, { Component, Fragment } from '@alipay/bigfish/react';
|        ^
```
> fix: lock babel-plugin-react-require to 3.0.0

- packages/umi-build-dev/src/plugins/targets.js
默认引入 `@babel/polyfill`，值为 none 时不引入。比如：
```bash
$ BABEL_POLYFILL=none umi build
```
> feat: support don't include @babel/polyfill

- packages/umi-build-dev/src/html/HTMLGenerator.js
- packages/umi-build-dev/src/html/HTMLGenerator.test.js
Support object type chunk, if you want to insert chunk script to `<head>`.
```
chunks: [
'a',
{ name: 'b', headScript: true },
'umi',
]
```
Then the output will be,
```html
<head>
<link rel="stylesheet" href="/a.css" />
<link rel="stylesheet" href="/b.css" />
<link rel="stylesheet" href="/umi.css" />
<script>
window.routerBase = "/";
</script>
<script src="/b.js"></script>
</head>
<body>
<div id="root"></div>
<script src="/a.js"></script>
<script src="/umi.js"></script>
</body>
```
> feat: support insert chunk scripts in head

- packages/af-webpack/package.json
避免出现类似 `Unknown option .customize` 的问题，如图：
> feat: upgrade babel-loader to 8.0.4, since it supported .customize in 8.0.3

- packages/umi-plugin-dva/package.json
> feat: upgrade dva-loading to 2.1.0-beta.2

- packages/umi/src/renderRoutes.js
Close #971
layout 里需 clone 两级，因为第一级是 Switch，然后才是 Route。
```js
React.Children.map(children, child => {
return React.cloneElement(child, null, React.Children.map(child.props.children, child => {
return React.cloneElement(child, { test: 'test' });
}));
})
```
* https://www.npmjs.com/package/react-router-with-props
* https://github.com/ReactTraining/react-router/issues/4627
* https://github.com/ReactTraining/react-router/pull/5693
* https://github.com/ReactTraining/react-router/issues/4942
> feat: support pass props from layouts to child routes

- packages/umi-build-dev/src/FilesGenerator.js
- packages/umi/src/renderRoutes.js
- packages/umi/src/renderRoutes.test.js
- packages/umi/src/runtimePlugin.js
想到的一些使用场景，这些场景之前用 Routes 也能做，但比较繁琐，而且会多套一层 react 组件。
```js
import { matchRoutes } from 'react-router-config';
export function modifyRouteProps(memo, { route }) {
if (/* is layout */route.routes) {
const m = matchRoutes(route.routes, memo.location.pathname);
if (m && m.length) {
memo.match = m[m.length - 1].match;
}
}
return memo;
}
```
可以在这一层针对 title 做运行时的转换。
> feat: support modifyRouteProps in runtime

- packages/umi-test/src/index.js
current run 'umi test' show
```
> umi test
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
```
[Related document](https://kulshekhar.github.io/ts-jest/user/config/babelConfig)
> fix: suppress ts-jest warning

- packages/umi-plugin-react/src/plugins/dynamicImport.js
- packages/umi-plugin-react/src/utils/isReactComponent.js
- packages/umi-plugin-react/src/utils/isReactComponent.test.js
e.g.
```js
plugins: [
['umi-plugin-react', {
dynamicImport: {
loadingComponent: `() => <div>...</div>`,
},
}],
],
}
```
> feat: support dynamicImport.loadingComponent as stateless function str

- packages/umi-plugin-react/src/plugins/title/TitleWrapper.js
> fix: avoid unexpect title change when ues title plugin with tween

- packages/umi-build-dev/src/plugins/afwebpack-config.js
build 的时候支持下设置没有前缀 ‘/’ 的 publicPath
> feat: manifest publicPath support empty prefix

- packages/af-webpack/src/dev.js
`Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel`
> fix: ci env no clipboardy

- packages/af-webpack/webpack-chain.js
- packages/umi-build-dev/src/getPlugins.js
- packages/umi-build-dev/src/plugins/commands/inspect/index.js
- packages/umi/src/cli.js
- packages/umi/src/scripts/inspect.js
Close #1314 
e.g.
```bash
umi help inspect
Usage: umi inspect [options]
Options:
--mode                specify env mode (development or production, default is development)
--rule <ruleName>     inspect a specific module rule
--plugin <pluginName> inspect a specific plugin
--rules               list all module rule names
--plugins             list all plugin names
--verbose             show full function definitions in output
```
> feat: support inspect command to inspect internal webpack config (#1314)

- packages/umi-build-dev/src/html/HTMLGenerator.js
- packages/umi-build-dev/src/html/HTMLGenerator.test.js
> fix: location.origin compatible with ie10

- docs/plugin/umi-plugin-react.md
- docs/zh/plugin/umi-plugin-react.md
- packages/umi-plugin-react/src/plugins/pwa/index.js
- packages/umi-plugin-react/src/plugins/pwa/registerServiceWorker.js
- packages/umi-plugin-react/test/generateWebManifest.test.js
Fix #1380 
* 如果用户配置了 `swDest`，在注册 service worker 时使用作为输出文件名
* 相关更新文档
> fix: use swDest in register-sw.js

- packages/af-webpack/src/getConfig/css.js
- 当项目目录路径中包含 `.css` 时会导致 `css` 解析错误:
> Fix the directory path that containes .css

- packages/umi-build-dev/src/html/HTMLGenerator.test.js
- packages/umi-build-dev/template/document.ejs
避免出现 `<title></title>` 这样的情况。在 chair 里面 title 可能是后端渲染的，避免引用了 umi 生产的 html 碎片后出现重复的 title。
> fix: remove empty title when context.title is undefined

- packages/af-webpack/src/getConfig/css.js
> :wrench:  cssModulesExcludes use RegExp

- packages/umi-plugin-locale/examples/base/src/page/index.js
- packages/umi-plugin-locale/examples/base/src/page/temp/locale/en-US.js
- packages/umi-plugin-locale/examples/base/src/page/temp/locale/zh-CN.js
- packages/umi-plugin-locale/package.json
- packages/umi-plugin-locale/src/index.js
- packages/umi-plugin-locale/template/wrapper.jsx.tpl
- packages/umi-plugin-locale/test/index.test.js
```
- src
- locales
- zh-CN.js
- pages
- testpage
- locales
- zh-CN.js
- .umirc.js
```
现在的策略是把  locales 和 pages 下面的 locales 的资源都合并在一起加载。后续还要实现和页面一起动态加载。
> feat: support set locale file in page folder

- packages/umi-build-dev/src/plugins/commands/block/block.js
- packages/umi-build-dev/src/plugins/commands/block/block.test.js
- packages/umi-build-dev/src/plugins/commands/block/download.js
- packages/umi-build-dev/src/plugins/commands/block/download.test.js
```
- src
- models
- locales
- components
- index.js
```
to
```
- page
- demo
- model
- locale
- component
- index.js
```
> feat: code in block src folder support singular

- packages/umi-build-dev/src/getPaths.js
When PAGES_PATH exist and  pages folder exits too, should use PAGES_PATH.
> feat: use PAGES_PATH as the first choice

- packages/umi-build-dev/src/PluginAPI.js
- packages/umi-build-dev/src/plugins/commands/block/block.js
app plugin api _modifyBlockTarget.
用于修改区块代码下载的时候可以对目录结构做一些调整，比如可以把区块的 `_mock.js` 文件下载到项目的 mock 文件夹下。
> feat: add _modifyBlockTarget

- packages/umi-build-dev/src/plugins/commands/block/download.js
- packages/umi-build-dev/src/plugins/commands/block/download.test.js
Fix block usage like: `umi block ant-design-pro/Analysis`.
> fix: can not recognize block path pattern like ant-design-pro/Analysis

- packages/af-webpack/src/getConfig/index.js
Close #1658
这里还要确认下 extraBabelPlugins 是否应该要应用到 extraBabelIncludes 这个上面？我理解 extraBabelIncludes 中的 babel 的配置应该和 src 中保持一致才对。
@sorrycc babelOptsForDeps 和 babelOpts 直接保持一致会不会有问题？
> fix: extraBabelIncludes not use extraBabelPlugins

- packages/af-webpack/src/getUserConfig/configs/proxy.js
If you want to proxy multiple, specific paths to the same target, you can use an array of one or more objects with a context property:
```
proxy: [{
context: ['/auth', '/api'],
target: 'http://localhost:3000',
}]
```
> feat: support proxy multiple, specific paths to the same target

- packages/umi-build-dev/src/plugins/afwebpack-config.js
Close #1364
---
e.g. a project used lodash-es
before tree-shaking
```bash
$ umi build && ll ./dist
✔ Webpack
Compiled successfully in 4.08s
DONE  Compiled successfully in 4082ms                                                                                                                                 11:37:46
File sizes after gzip:
112.28 KB  dist/umi.js
56 B       dist/umi.css
total 704
drwxr-xr-x  5 chencheng  wheel   160B  1  8 11:37 .
drwx------  7 chencheng  wheel   224B  1  8 11:37 ..
-rw-r--r--  1 chencheng  wheel   324B  1  8 11:37 index.html
-rw-r--r--  1 chencheng  wheel    36B  1  8 11:37 umi.css
-rw-r--r--  1 chencheng  wheel   343K  1  8 11:37 umi.js
```
after tree-shaking
```bash
$ umi build && ll ./dist
✔ Webpack
Compiled successfully in 4.49s
DONE  Compiled …
```
> feat: support tree-shaking

- packages/af-webpack/src/getConfig/index.js
Related: 
* https://github.com/umijs/umi/issues/1658
* https://github.com/webpack/webpack/issues/4039#issuecomment-419284940
> fix: some dep(e.g. query-string) compile failed when enabled tree-shaking

- packages/umi-plugin-locale/index.d.ts
- packages/umi-plugin-locale/src/locale.js
- packages/umi-plugin-locale/test/locale.test.js
类似 `formatMessage` 这样的 API 在 `react-intl` 在用法是需要通过 context 然后在组件中通过 `this.formatMessage` 来使用。在 `umi-plugin-locale` 中为了更方便，通过封装了一层之后使得用户可以直接调用 formatMessage 来使用，但是有一个问题是必须要 react app 挂载之后 formatMessage 才能实际可用。 
也就是说如果直接在模块初始化部分使用的话是无效了，最初是有一个空的方法做容错处理，后来在 https://github.com/umijs/umi/pull/1730 这个 PR 中去掉了容错的方法，会导致如果再模块初始化阶段拿到的方法是 undefined。
在这个 PR 中重新加上了容错的方法，并且在模块初始化调用的时候给出警告提示。另外去掉了 https://github.com/umijs/umi/pull/1730 这个 PR 中添加的 locale 这些非方法的内容，如果这些内容需要用到的话建议还是类似提供 `getLocale` 这样的方法来调用。
> fix: locale api is undefined before react app mounted

- packages/umi-build-dev/src/routes/patchRoutes.js
- packages/umi-build-dev/src/routes/patchRoutes.test.js
> fix: patchRoutes failed with no path route when exportStatic.htmlSuffix is true

- packages/af-webpack/src/getConfig/css.js
> fix: css hmr don't work in firefox

- packages/af-webpack/package.json
- packages/af-webpack/yarn.lock
由于引用 alias 文件的方式不同，导致不可避免的 break-change，所以回滚。
比如引用 `@/assets/a.png`。
css-loader@1 是：
```css
.a { background: url(@/assets/a.png); }
```
css-loader@2 是：
```css
.a { background: url(~@/assets/a.png); }
```
* https://github.com/webpack-contrib/css-loader/releases/tag/v2.0.0
> fix: downgrade css-loader to 1

- packages/umi-build-dev/src/routes/routesToJSON.js
- packages/umi-build-dev/src/routes/routesToJSON.test.js
- packages/umi-plugin-react/src/plugins/title/index.js
- packages/umi-plugin-react/src/plugins/title/template/TitleWrapper.js.tpl
- packages/umi-plugin-react/test/normal.e2e.js
- packages/umi-plugin-react/test/normal/.umirc.js
- packages/umi-plugin-react/test/normal/locales/en-US.js
- packages/umi-plugin-react/test/normal/locales/zh-CN.js
- packages/umi-plugin-react/test/normal/pages/a.js
- 添加 title 和国际化的 e2e 测试
- 查找 title 的 locale 资源的时候添加 trim，避免找不到对应的 key
- 修复 routesToJSON.js 中 Route 的路径可能不包含 `.` 的情况
> fix: title locale bug when separator not include space

- packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.js
由于在 WebManifestPlugin 里面使用了 srcPath 读取文件，因此需要处理下
> fix: manifest srcPath with query build error

- docs/plugin/develop.md
- docs/zh/plugin/develop.md
- packages/umi-build-dev/src/FilesGenerator.js
- packages/umi-build-dev/template/router.js.tpl
- packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/umi.js
- packages/umi/test/fixtures/build/export-static/expected/umi.js
- packages/umi/test/fixtures/build/simple/expected/umi.js
- packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/umi.js
- packages/umi/test/fixtures/e2e/normal/app.js
- packages/umi/test/normal.e2e.js
app.js
```js
export function onRouteChange({ location, routes, action }) {
console.log(`current url: ${location.pathname}`);
}
```
* location：`Object`, history 提供的 location 对象
* routes: `Array`, 路由配置
* action: `PUSH|POP|REPLACE|undefined`，初次加载时为 `undefined`
注：
1. 初次加载时也会执行，但 action 为 `undefined`
> feat: support onRouteChange({ location, routes }) in app.js

- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js
> fix: route.component could be absolute

- packages/umi/package.json
missing prompt.d.ts in umi package
> fix: missing prompt.d.ts in package files

- .yarnrc
新增功能原因：
因为本机设置了全局的 `npm` 镜像源，导致安装新的依赖包时 yarn.lock 来源(`resolved`)不一致。
```shell
npm config set registry https://registry.npm.taobao.org 
```
> feat: The official mirror source is used by everyone

- packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
- packages/umi-plugin-dva/src/index.test.js
getRouteConfigFromDir Convert Windows backslash paths to slash paths
> fix: getRouteConfigFromDir Convert Windows backslash paths to slash paths

- docs/config/README.md
- docs/zh/config/README.md
- packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
- packages/umi-build-dev/src/plugins/mock/index.js
比如要忽略 mock 下的所有 `_` 前缀的文件和文件夹，可以这么配：
```js
mock: {
exclude: [
'mock/**/_*.js',
'mock/_*/**/*.js'
],
}
}
```
> feat: support config mock.exclude

- docs/config/README.md
The default fileName of manifest option is `asset-manifest.json`(check `af-webpack/lib/getConfig/prod.js`:51),
different with webpack-manifest-plugin's default `manifest.json`(check https://github.com/danethurber/webpack-manifest-plugin/blob/1.x/README.md).
> fix: manifest fileName

- docs/zh/config/README.md
The default fileName of manifest option is `asset-manifest.json`(check `af-webpack/lib/getConfig/prod.js`:51),
different with webpack-manifest-plugin's default `manifest.json`(check https://github.com/danethurber/webpack-manifest-plugin/blob/1.x/README.md).
>  fix: manifest fileName

- packages/umi-serve/bin/umi-serve.js
修复 Linux 环境下剪切板崩溃问题， Linux 图形界面可以通过设置环境变量 `process.env.DISPLAY` 开启。
```bash
/usr/local/share/.config/yarn/global/node_modules/clipboardy/lib/linux.js:10
throw err;
^
Error: xsel: Can't open display: (null)
: Inappropriate ioctl for device
```
> fix: `xsel` crashes in debian/ubuntu server

- packages/umi-types/config.d.ts
- packages/umi-types/index.d.ts
```diff
- export interface IRoute {
-   path: string;
-   component: string;
-   routes?: IRoute[];
-   Routes?: string[];
-   [key: string]: any;
- }
+ export type IRoute =
+   | {
+       path: string;
+       component: string;
+       routes?: IRoute[];
+       Routes?: string[];
+       redirect?: never;
+       [key: string]: any;
+     }
+   | {
+       path: string;
+       redirect: string;
+       component?: never;
+       [key: string]: any;
+     };
```
> fix: 修复 CheerioSelector 类型丢失 & 为 IRoute 添加 `redirect` 类型路由

- packages/umi-build-dev/src/plugins/commands/test.js
Related: https://github.com/facebook/jest/issues/7857
> fix: umi test don't work if have console.log

- packages/umi-types/config.d.ts
上次的修复虽然允许在 route 中添加其他字段，但使用了 type 导致无法拓展接口，例如 Ant Design Pro 的路由结构：
```ts
import { IRoute } from 'umi-types';
interface MyRoute extends IRoute {
icon?: string;
name?: string;
}
```
> feat: allow the interface to be extended from IRoute

- packages/umi-library/src/doczrc.ts
1. docz 无需再手动配置 `typescript: true`
> feat(umi-library): auto detect typescript in docz

- packages/umi-types/index.d.ts
ts: add _modifyHelpInfo definition
另外修正了 IModify 和 IAdd 的定义，主要对应 umi API 的如下规则：
- modifyXxx 第一个参数必定存在，返回也必须要返回（有的可以返回 undefined 的也应该是通过 `IModify<Xxx | undefined>` 来指定，不应该默认给 IModify 都加上 undefined）。
- 第二个参数 args 也必定存在（umi 中的代码逻辑是至少是 `{}`），不需要加 `?`（不然会导致插件中需要多一次判断）
> ts: add _modifyHelpInfo definition && fix IModify and IAdd definition

- packages/umi/index.d.ts
- packages/umi/routerTypes.d.ts
- packages/umi/withRouter.d.ts
- TypeScript, router
```ts
// maybe the type's name can discuss.
import { RouterTypes } from 'umi';
const App: React.SFC<RouterTypes> = (props) => {
console.log('index props', props.route...);
return (
<div>Index page</div>
)
}
```
You can define your own route config:
```ts
// config.js|ts / .umirc.js|ts
routes: [
{
path: '/',
component: '../layout',
routes: [
{ path: '/', component: 'index' },
{
path: 'about', 
component: 'A',
title: 'Title',
}
],
}
],
}
```
```ts
// pages/A.tsx
interface RouteExtend {
title?: string;
}
const App: React.SFC<RouterTypes<RouteExtend>> = (props) => {
// `props.route` has `title` property you defined.
return (
<div>Index page</div>
)
}
```
> feat: add umi router types

- packages/umi-test/src/index.js
- packages/umi-test/src/transformers/jsTransformer.js
- 支持 `--transform-include` cli 参数，用于指定额外需要做 babel 编译的 npm 包
- 顺便解决了 enzyme-adapter-react-16 里引用了 enzyme 却没有通过 babel 编译为正确路径，从而导致多个 enzyme 实例的问题
- close https://github.com/umijs/umi/issues/2159
记录下调 umi-test 里的 transformer 的方法，
1. `umi-test --no-cache` 才会让 transformer 或 babel 插件的修改生效，否则会走缓存
2. transformer 或 babel 插件的 console.log 日志不会显示到输出里，但 console.error 会，所以应该是 pipe 了 stderr 但没有 pipe stdout
> feat(umi-test): support --transform-include option

- packages/umi-plugin-react/src/plugins/dynamicImport.js
- packages/umi-plugin-react/src/utils/isRelativePath.js
- packages/umi-plugin-react/src/utils/isRelativePath.test.js
支持 loadingComponent 来源与 npm 包而不是单纯的相对路径
- any feature?
> feat: support loadingComponent from npm

- .prettierrc
- package.json
虽然在 commit 时会有 prettier 去格式化，但是在本地开发时，没有 prettier config 导致保存时格式不统一导致 eslint 一片红。添加一个本地的 prettierrc 方便开发。配置与 lint-staged 阶段一致。
> chore: add prettier config

- packages/umi-library/src/doczrc.ts
修复windows环境下 umi-lib doc dev 生成的docz 主题路径错误的问题
修复前路径bug：
修复后：
Close https://github.com/umijs/umi-plugin-library/issues/95
> fix(umi-library): theme path problem in windows

- docs/plugin/develop.md
- docs/zh/plugin/develop.md
- packages/af-webpack/src/dev.js
- packages/umi-build-dev/src/plugins/commands/dev/index.js
在cordova支持，或者其他需要再另起一个服务器时，需要获取到umi启动的端口号
> feat: pass port to api.afterDevServer

- packages/umi-test/src/index.js
tnpm 的目录结构是 `_umi-test@1.5.5@umi-test`，npm 和 tnpm 兼容的正则表达式应该是 `[^/]*?` 而不是 `[^/]+?`.
修改正则表达式后可以修复：
- jest 单元测试中涉及到 Link及router时报错 #1862
- npm test时出现的错误，npm start没问题，不知道怎么纠正？ #2076
> fix(umi-test): jest 兼容 tnpm 目录结构的正则表达式

- docs/zh/guide/getting-started.md
按照文档操作时，报错umi:command not found，虽然与umi无关，是yarn环境配置导致，不过对于一个umi新手，会产生各种怀疑，因此在这里附带一个解决方法
> doc: add intro for `umi:command not found`

- packages/umi-plugin-locale/index.d.ts
默认读取 `locales/zh-CN.js` 的所有 `keys`，`formatMessage` 与 `FormattedMessage` 时开发者无感知，可使用智能提示。
试了下即使没 `locales/zh-CN.js` 文件，编译和开发时也不会报错。
- any feature?
> feat: locale intellisense

- packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
- packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js
> fix: insert new block element in redirect return function

- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js
- packages/umi-build-dev/src/routes/getRouteConfigFromConfig.test.js
…wrong path (#1998)
- any feature?
- close https://github.com/umijs/umi/issues/1998
这个问题的出现是因为：lodash.cloneDeep 为了处理 circular references 的问题，每次 clone 过每个部分以后就会记录在一个 Stack 中，对指向同一个对象的 clone 不会重复处理。
lodash.cloneDeep 的行为不能配置，所以我换了下实现，性能上应该不受影响。
> fix: same reference to common route config will lead to wrong path

- packages/af-webpack/src/dev.js
- packages/af-webpack/src/prepareUrls.js
- packages/umi-build-dev/src/Service.js
- packages/umi-build-dev/src/plugins/commands/dev/index.js
Fix the problem that umi dev generate wrong url when the history type is hash and the base is set. 
base value should be in hash part of the url rather than the pathname.
> fix: generate wrong dev url when history is hash

- packages/umi-plugin-locale/index.d.ts
- packages/umi-plugin-locale/src/locale.js
> feat(umi-plugin-locale): dispatch languagechange event

- packages/af-webpack/src/errorOverlayMiddleware.js
修复点击报错代码打开编辑器功能。
https://github.com/facebook/create-react-app/blob/a98337c257677bad0c7b235886d5dd6776c3c374/packages/react-dev-utils/launchEditor.js#L283-L285
```javascript
if (!(Number.isInteger(lineNumber) && lineNumber > 0)) {
return;
}
```
`react-dev-utils/launchEditor.js` 中校验了 `lineNumber` 参数的类型，直接传入的话是个字符串，导致启动编辑器功能失败。
这里没有直接用 `react-dev-utils/errorOverlayMiddleware.js` 不知是出于什么考虑？二者并没有区别。
> fix: open editor feature when click on error overlay

- packages/umi-build-dev/src/plugins/afwebpack-config/index.js
- packages/umi-build-dev/src/plugins/targets.js
If user decides to turn of auto inclusion of `@babel/polyfill` with `BABEL_POLYIFLL=none`, skip the `lockCoreJSVersionPlugin.js` too.
> refactor: skip lock core-js plugin if possible

- packages/umi-build-dev/src/plugins/commands/block/download.js
修正了在window环境中使用“umi block add”命令添加绝对路径错误的问题
Fix an issue with adding an absolute path error using the 'umi block add' command in a window environment
> fix: umi block add 命令支持添加 window 环境下包的绝对路径

- packages/umi-build-dev/src/getWebpackConfig.js
`umi` shouldn't be external.
- any feature?
> fix: umi external bug

- docs/.vuepress/config.js
- docs/guide/module-processor.md
- docs/zh/guide/module-processor.md
- add documentation about module processor, in case developers have no idea what module can be handled correctly
> docs: add module process explaination

- docs/config/README.md
- docs/zh/config/README.md
可能后面 umi 内部升级 `autoprefixer >= 9.6.0` 版本时，要把 `browsers` 改成 `overrideBrowserslist`。
[autoprefixer.js#L11](https://github.com/postcss/autoprefixer/blob/7980d0ac3ebb0d1adbbe6a75d248ca3702b2d5f3/lib/autoprefixer.js#L11)
- any feature?
> doc: autoprefixer

- packages/umi/index.d.ts
- packages/umi/package.json
- any feature?
- close https://github.com/ant-design/ant-design-pro/issues/4406
> fix: import { Route } from 'umi';

- packages/umi-build-dev/yarn.lock
- packages/umi-plugin-hd/template/index.js
> Fix ssr hd

- packages/umi-plugin-locale/src/locale.js
> fix navigator set error

- packages/af-webpack/package.json
- packages/af-webpack/src/getConfig/index.js
- packages/af-webpack/test/build.test.js
- To preventing publish, `bundleStats.json` will generate to `process.cwd()` like `speedmesure.json`,
> feat: set stats report file path to process.cwd()

- packages/af-webpack/src/getConfig/index.js
...because the generated config is gonna be compared against the new version if use modifies config.
create new copy of `opts.extraBabelIncludes` when adding custom include function to prevent false alarm on `extraBabelIncludes` when config change.
> fix: don't tamper the original opts.extraBabelIncludes

- docs/plugin/umi-plugin-prerender.md
- docs/zh/plugin/umi-plugin-prerender.md
- packages/umi-build-dev/src/FilesGenerator.js
- packages/umi-build-dev/src/plugins/commands/build/index.js
- packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.js
背景 https://github.com/umijs/umi/pull/2543#issuecomment-502342760
方案是：
- webpack build 时，server 和 client 同时运行，`chunkMaps` 里的资源用占位符 `__UMI_SERVER__` 代替，server 的 map 是 `/__UMI_SERVER__.js/css`。
- server 和 client 构建完成后，执行 `replaceChunkMaps` 方法，将 `umi.server.js` 中的占位符里替换成 `manifest` 中正确的文件名
- any feature?
> Fix chunk map

- packages/af-webpack/package.json
- packages/af-webpack/yarn.lock
- packages/eslint-config-umi/src/index.js
- packages/umi-core/src/error.js
- scripts/startDevServers.js
- react version 警告
- babel-eslint 丢失
- eslint 报错后不能显示到浏览器里
> fix: eslint's react version warning and babel-eslint dep lost

- packages/umi-plugin-prerender/src/index.ts
- packages/umi-plugin-prerender/test/index.test.js
prerender 插件不渲染动态路由
- any feature?
> fix: prerender not render dynamic routing

- packages/af-webpack/src/getConfig/css.js
- packages/umi-plugin-dll/src/buildDll.js
- 修复 id 冲突问题，但在 dev 时且开启 dll 之后初始加载会闪一下（css 有个动态加载的过程）
- close https://github.com/ant-design/ant-design-pro/issues/4537
> fix: css module id conflicts when use dll plugin

- packages/umi-build-dev/template/entry.js.tpl
umi-plugin-qiankun 会添加 entryCode，而 entryCode 内容依赖 moduleBeforeRendererPromises 
see https://github.com/umijs/umi-plugin-qiankun/blob/master/src/plugins/slave/index.ts#L59
> fix(umi-build-dev): make moduleBeforeRendererPromises available for entry code

- packages/umi-build-dev/package.json
- packages/umi-build-dev/src/plugins/commands/dev/index.js
- packages/umi-build-dev/yarn.lock
`umi.server.js` 在 dev 时，是直接写入本地文件系统。已经走的 `webpack-dev-sever` ，这里没必要加。
> fix: remove unnecessary webpack-dev-middleware

- packages/umi-plugin-locale/src/locale.js
在第一次进入页面时，`getLocale()` 会返回 `undefined`。
> fix getLocale() return undefined

- packages/umi-build-dev/src/getWebpackConfig.ts
- packages/umi-types/config.d.ts
- packages/umi-types/index.d.ts
> fix: webpack-chain types

- packages/umi-plugin-dva/src/index.js
Close #2672 
Close #2753 
重构 dva 的依赖项导入处理
fix ``` Please use `require("dva").xxx` instead of `require("dva/xxx")` ```
- close https://github.com/umijs/umi/issues/2672
- close https://github.com/umijs/umi/issues/2753
> fix: refactoring dva dependencies import

- packages/umi-build-dev/template/router.js.tpl
开启 disableGlobalVariables 后由于没有 window.g_history，导致 qiankun 的 history 监听失效，从而不能正确的卸载 history
合理的做法应该是 Router 卸载后自动 unlisten 掉相应的监听
> fix(umi-build-dev): unlisten the history listener automatically while app unmount

- packages/umi-build-dev/src/plugins/afwebpack-config/index.js
- umi@2.8 后全局安装 umi 时出现
- 试过 cnpm/tnpm 复现，yarn 未复现，npm 未尝试
- close #2791
> fix: module not found for umi dev when global install via cnpm

- packages/umi-mock/package.json
- packages/umi-mock/src/createMiddleware.js
发现module cache 在 Windows 和 Linux 平台有些不同，所以导致文件更改后，mock文件并没有重新加载。因不知这种如何写测试，所以自己在两平台手动测试了。 close [#2796](https://github.com/umijs/umi/issues/2796)
> fix: 修复windows 平台，Mock文件不能热更新的问题

- packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
- packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js
default set upperCamelCase for block import identifier for avoid react component grammar error.
> fix: upperCamelCase block import identifier

- docs/config/README.md
- docs/zh/config/README.md
- packages/umi-build-dev/template/entry.js.tpl
> feat: ssr getInitialProps add req, res params

- packages/umi-plugin-locale/template/wrapper.jsx.tpl
- packages/umi-plugin-locale/test/index.test.js
Close #2962 #2966  https://github.com/ant-design/ant-design-pro/issues/5014
- any feature?
> fix: LocaleProvider warning after antd@3.21

- packages/umi-plugin-locale/examples/base/src/locale/sk.js
- packages/umi-plugin-locale/examples/base/src/page/temp/locale/sk.js
- packages/umi-plugin-locale/src/index.js
- packages/umi-plugin-locale/test/index.test.js
This PR is fix for incorrect locale detection for locales with language code only (like 'sk') as described in https://github.com/umijs/umi/issues/2972
- close https://github.com/umijs/umi/issues/2972
> fix: locale detection for lang only locales

- packages/umi-plugin-locale/template/wrapper.jsx.tpl
- packages/umi-plugin-locale/test/index.test.js
This reverts commit e35aaaa25c60a8a9f30871c7751565a073648014.
- any feature?
> Revert "fix: LocaleProvider warning after antd@3.21 (#2941)"

- packages/af-webpack/src/getUserConfig/configs/styleLoader.js
- any feature? 
Giving the ability for users to quickly leverage `style-loader` instead of `mini-extract-css-plugin`.
Users'll have 3 ways to enable and modify the options of `style-loader` without using `chanWebpack`:
```js
module.exports = {
styleLoader: {}
}
```
```js
api.modifyAFWebpackOpts(memo => {
return Object.assign(memo, {
styleLoader: {}
})
})
```
```js
api.modifyDefaultConfig(memo => {
return Object.assign(memo, {
styleLoader: {}
})
})
```
---
https://github.com/umijs/umi/blob/5e1b507e8916e6d5cca23bd30b7eca089eeef824/packages/umi-build-dev/src/plugins/afwebpack-config/index.js#L135-L137
---
Since `style-loader` has reach [1.0.0](https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md#100-2019-08-06):
> The `style-loader/useable` loader was removed in favor …
> feat: expose internal "styleLoader" option.

- docs/guide/env-variables.md
- docs/zh/guide/env-variables.md
- packages/af-webpack/src/build.js
- any feature?
Add a new env `UMI_DO_NOT_CLEAN_OUTPUT` to make is possible to tell `build` process not to remove the dist files.
- close https://github.com/umijs/umi/issues/2448
> feat: add env CLEAR_OUTPUT

- packages/af-webpack/src/build.js
- any feature?
`umi` shouldn't exit current build process when users enable `watch` under build.
> feat: do not exit process when build is under watch mode

- packages/umi-build-dev/src/getWebpackConfig.ts
ssr dev should not only `umi.server.js` if using `config.entry` across `chainWebpack`
> fix: umi ssr dev when add independent entry

- packages/umi/src/runtimePlugin.js
- packages/umi/src/runtimePlugin.test.js
- packages/umi/src/utils.js
> feat(umi): add mergeAsyncConfig api to support async runtime config

- packages/umi-build-dev/src/UserConfig.js
- output the original error stack instead of the cloaked error message
> fix: original error stack should be preferred

- .travis.yml
> chore: travis ci not exit

- packages/umi-types/index.d.ts
- [umi-types](https://github.com/umijs/umi/blob/master/packages/umi-types/index.d.ts#L189)：`IBeforeDevServerFunc` 和 `IAfterDevServerFunc` 类型错误。钩子[`beforeDevServer`](https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/plugins/commands/dev/index.js#L139) 和 [`afterDevServer`](https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/plugins/commands/dev/index.js#L144) 在 `umi-build-dev`内传递的参数和`umi-types`定义的类型不一致。
> fix: IBeforeDevServerFunc and IAfterDevServerFunc type errors

- packages/umi-ui/client/.umirc.ts
- packages/umi-ui/client/src/app.ts
- packages/umi-ui/src/UmiUI.ts
- packages/umi-ui/src/scripts.ts
Why：
- 初始化 URL 跳转到 `/project/select` 还是 `/dashboard` 的逻辑放在服务端，避免在 `mini` 时页面会闪烁。
- 客户端路由改成 `browser` ，更好的判断 `isMini` 等参数。 
- any feature?
> fix(umi-ui): init path redirect in server

- packages/af-webpack/src/build.js
- packages/umi-core/src/error.js
1. 修复 MultiStats 时 error 校验的 bug。现在 umi 链路中基本都是 MultiStats，对 MultiStats 的操作与单个 Stats 是不同的
2. 支持通过开启环境变量 DUMP_ERROR_PATH 将 umi 探测到的 error 进行 dump。适用于上层框架通过 fork 使用的 umi 的情况
> feat: support dump error info to file

- package.json
1. update_deps.sh not exist. 
2. use `sh ./scripts/reinstall_deps.sh` to run command on git-bash in windows.
- fix: `npm run chore:update-deps` error fix.
> fix: npm run chore:update-deps error fix

- docs/guide/env-variables.md
- docs/zh/guide/env-variables.md
- packages/af-webpack/src/getWebpackConfig/resolveDefine.js
- packages/af-webpack/src/webpackHotDevClient.js
因为`react-error-overlay`没有提供禁用overlay的api，但我们又需要`startReportingRuntimeErrors`的回调来做错误后恢复刷新的提醒，所以采用了一些workaround
- `UMI_APP_ERROR_OVERLAY` supported for [3093](https://github.com/umijs/umi/issues/3093)
- Close #3093
-----
[View rendered docs/guide/env-variables.md](https://github.com/leftstick/umi/blob/master/docs/guide/env-variables.md)
[View rendered docs/zh/guide/env-variables.md](https://github.com/leftstick/umi/blob/master/docs/zh/guide/env-variables.md)
> feat: support ERROR_OVERLAY env

- docs/plugin/umi-ui.md
- docs/zh/plugin/umi-ui.md
- packages/umi-plugin-ui/src/plugins/configuration/ui.tsx
- packages/umi-plugin-ui/src/plugins/dashboard/ui.tsx
- packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
- packages/umi-types/ui.d.ts
- packages/umi-ui/client/src/PluginAPI.ts
将所有 intl api ，统一挂在 `api.intl.*` 上，便于后续国际化扩展及 api 收敛 [docs](https://umi-26krv3a04.now.sh/plugin/umi-ui.html#api-intl)：
同时兼容之前的 `api.intl({ id:  })` 写法：
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-intl-proxy/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-intl-proxy/docs/zh/plugin/umi-ui.md)
> refactor(Umi UI): api.intl.* to mount intlApi

- packages/umi-build-dev/src/FilesGenerator.js
- packages/umi-build-dev/src/Service.js
- packages/umi-build-dev/src/utils/writeContent.js
> fix: generate file only when file content changes

- CONTRIBUTING.md
y ui:build --watch 只是启动 webpack dev server，尚未完成构建；启动UIServer进行本地开发调试，需要设置环境 LOCAL_DEBUG 或者切换到 examples/func-test 目录运行 umi dev --ui 命令
- Update CONTRIBUTING.md how to debug umi ui in local.
-----
[View rendered CONTRIBUTING.md](https://github.com/billfeller/umi/blob/patch-1/CONTRIBUTING.md)
> docs: debug umi dev in local

- docs/plugin/umi-plugin-react.md
- docs/zh/plugin/umi-plugin-react.md
- packages/umi-plugin-react/src/plugins/pwa/registerServiceWorker.js
documentation is changed or added
pwa 的配置中只使用 `updated` 及 `offline` 事件，由于用户可能有其他需求，比如监听 `registered` 进行更新的轮询等，所以将 [register-service-worker](https://www.npmjs.com/package/register-service-worker) 中所有事件一下子都同步了过来，并更新了文档。
同步service-worker 方法 && 补充相关文档说明
-----
[View rendered docs/zh/plugin/umi-plugin-react.md](https://github.com/cnahliu/umi/blob/sync-sw-event/docs/zh/plugin/umi-plugin-react.md)
> 同步service-worker 方法 && 补充相关文档说明

- packages/af-webpack/package.json
- packages/af-webpack/src/getUserConfig/configs/stylus.js
- packages/af-webpack/src/getWebpackConfig/css.js
- packages/af-webpack/src/getWebpackConfig/index.js
- packages/af-webpack/test/fixtures/stylus/expected/index.css
- packages/af-webpack/test/fixtures/stylus/expected/index.js
- packages/af-webpack/test/fixtures/stylus/index.js
- packages/af-webpack/test/fixtures/stylus/index.styl
- packages/umi-build-dev/src/getWebpackConfig.ts
- packages/umi-build-dev/src/plugins/global-css.js
修改了两个模块 af-webpack 和 umi-build-dev
- any feature?
- close https://github.com/umijs/umi/issues/2598
> feat(stylus): 添加stylus支持

- packages/umi-plugin-locale/template/wrapper.jsx.tpl
- packages/umi-plugin-react/locale/index.js
umi SSR target 改成 node 后 #3491 不兼容 umi-plugin-locale 插件。
看了下 umi-plugin-locale 插件实现，在 browser 时，引入 `./lib/locale`，node 端引用 `./lib/index` 给 `umi-plugin-react` 组装 locale 插件。
但 ssr 中改成 node 后，会引用到 `./lib/index` ，自然导致 `locale`  api  undefined。
Close https://github.com/umijs/umi-server/issues/19.
- any feature?
> fix:  umi-plugin-locale ssr node env module bug

- docs/config/README.md
- docs/zh/config/README.md
- packages/umi-build-dev/src/getConfig/configPlugins/outputPath.js
- packages/umi-build-dev/src/getConfig/test/outputPath.test.js
当设置 `outputPath` 为约定的目录时，会有很多意想不到的错误。
比如 设置 `outputPath:public`，会导致再次dev的时候，都失效。因为这时候的 `index.html` 被生成后的 `index.html` 覆盖，这与约定 `public` 下的文件会被原样拷贝有关。
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/outputPath-blacklist/docs/config/README.md)
[View rendered docs/zh/config/README.md](https://github.com/umijs/umi/blob/outputPath-blacklist/docs/zh/config/README.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3527)
> chore: add outputPath blacklist

- packages/af-webpack/src/getPort.js
Fix `Provided options.stopPort is less than options.startPort`
- ❌ tests are included
- ❌ documentation is changed or added
- close https://github.com/umijs/umi/3586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3587)
> fix: highestPort should always higher than basePort

- packages/umi-build-dev/src/plugins/importFromUmi.js
此改动不能直接修复问题，但为修复该问题的前置条件
余下需要在 ts 项目中 tsconfig.json 中增加对 `@tmp` 目录的 paths 配置
```json
{
"compilerOptions": {
"paths": {
"@tmp/*": ["src/pages/.umi/*"]
}
}
}
```
[create-umi](https://github.com/umijs/create-umi) 与此问题的协作 PR ：https://github.com/umijs/create-umi/pull/93
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3600)
> fix: TS 项目下 addUmiExports 缺乏 API 类型推导的问题

- packages/umi-build-dev/src/FilesGenerator.js
- packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js
`window.g_initialData` 数据量很大时，会阻碍首屏渲染。提到 `body` 里，`umi.js` 前。
- any feature?
> fix: window.g_initialData block render thread when ssr

- docs/guide/router.md
- docs/zh/guide/router.md
-----
[View rendered docs/zh/guide/router.md](https://github.com/Xiphap/umi/blob/master/docs/zh/guide/router.md)
> doc update: 补充指南文档中「约定式路由」可能因配置式路由失效的提醒。

- packages/umi-build-dev/src/plugins/commands/block/ui/client/index.tsx
- packages/umi-types/ui.d.ts
- packages/umi-ui/client/src/layouts/Dashboard.tsx
```diff
api.addPanel({
title: 'org.umi.ui.tasks.title',
+   renderTitle: (title) => <span style={{ letterSpacing: -3 }}>{title}</span>,
path: '/tasks',
icon: {
type: 'project',
theme: 'filled',
},
component: api.connect(state => ({ taskManager: state[model.namespace] }))(TasksView),
});
```
- any feature?
> feat: addPanel add renderTitle attribute for user custom

- packages/umi-build-dev/src/FilesGenerator.js
- packages/umi-build-dev/template/entry.js.tpl
- packages/umi-plugin-react/src/plugins/antd.js
Close https://github.com/umijs/umi-server/issues/35.
- getInitialProps 函数内建议使用 return，不然会直接返回整个 model
- 优化 serialize-javascript ，只 require 一次。
- any feature?
> fix: ssr perf

- packages/umi-build-dev/src/plugins/commands/config/setConfig.js
- packages/umi-build-dev/src/plugins/commands/config/setConfig.test.js
> fix: setConfig uppercase strings

- docs/zh/guide/mock-data.md
”访问/api/users“ 描述错误， 改为”访问/api/currentUser“
- any feature?
-----
[View rendered docs/zh/guide/mock-data.md](https://github.com/jiangxunyue/umi/blob/patch-1/docs/zh/guide/mock-data.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3437)
> doc: ”访问/api/users“ 描述错误， 改为”访问/api/currentUser“

- docs/guide/develop-umi-ui-plugin.md
- docs/zh/guide/develop-umi-ui-plugin.md
- packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js
- packages/umi-build-dev/src/plugins/commands/block/sdk/constants.ts
- packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/GUmiUIFlag.tsx
- packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/ibp-component-flag/expected.js
- packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/ibp-component-flag/origin.js
- packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
- packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.ts
- packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Flow.ts
- packages/umi/.fatherrc.js
- packages/umi/UmiUIFlag.d.ts
- packages/umi/index.d.ts
- packages/umi/src/UmiUIFlag.tsx
```jsx
import React from 'react';
import { UmiUIFlag } from 'umi';
import { Button } from 'antd';
export default () => (
<div>Hello
<div>
<p>World</p>
<UmiUIFlag />
<p>
aaaaa
<div>
<UmiUIFlag inline />Hello Inline<UmiUIFlag inline />
</div>
</p>
</div>
<Button type="primary">World</Button>
</div>
);
```
- any feature?
> feat: support UI flag component from umi

- docs/plugin/develop.md
- docs/zh/plugin/develop.md
- packages/umi-plugin-modern-mode/src/index.js
- packages/umi-types/index.d.ts
`modifyHTMLWithAST` api 应该返回 cheerio 实例，不然存在多个 `modifyHTMLWithAST` 时后续 callback 会拿不到 `$` 实例
-----
[View rendered docs/plugin/develop.md](https://github.com/umijs/umi/blob/bugfix-modifyHTMLWithAST/docs/plugin/develop.md)
[View rendered docs/zh/plugin/develop.md](https://github.com/umijs/umi/blob/bugfix-modifyHTMLWithAST/docs/zh/plugin/develop.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3968)
> fix(plugin-api): fix modifyHTMLWithAST returned type

- docs/config/README.md
- docs/zh/config/README.md
- docs/zh/plugin/develop.md
- packages/umi-build-dev/src/html/HTMLGenerator.js
- packages/umi-build-dev/src/html/HTMLGenerator.test.js
- packages/umi-types/config.d.ts
- runtimePublicPath 支持设置成指定 string，类似 [modifyPublicPathStr](https://umijs.org/zh/plugin/develop.html#modifypublicpathstr)
有一些场景在部署的时候平台会注入一些自己的动态 publicPath 变量，比如 basement deployMode 为 render 和 sff 时，这些场景可以直接将这些变量赋给 `window.publicPath`
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat/runtimePublicPath-str/docs/config/README.md)
[View rendered docs/zh/config/README.md](https://github.com/umijs/umi/blob/feat/runtimePublicPath-str/docs/zh/config/README.md)
[View rendered docs/zh/plugin/develop.md](https://github.com/umijs/umi/blob/feat/runtimePublicPath-str/docs/zh/plugin/develop.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3975)
> feat(runtimePublicPath): runtimePublicPath supports string setting

- packages/core/src/Service/Service.test.ts
- packages/core/src/Service/Service.ts
- packages/core/src/Service/fixtures/normal/approot/nextlevel/pages/test.tsx
- packages/preset-built-in/src/fixtures/build/package.json
- packages/umi/src/cli.ts
- packages/umi/src/forkedDev.ts
- packages/umi/src/utils/fixtures/normal/package.json
- packages/umi/src/utils/getPkg.test.ts
- packages/umi/src/utils/getPkg.ts
While env `APP_ROOT` is specified, `service.resolvePackageI()` returns info incorrectly.
Check my repo: [hosts-master](https://github.com/leftstick/hosts-high)
`@umijs/plugin-model` will not be discovered properly
> fix: service.resolvePackage not working properly while APP_ROOT specified

- packages/umi/src/utils/getPkg.test.ts
- packages/umi/src/utils/getPkg.ts
handle `APP_ROOT` scenario properly in `getPkg.ts`. 
related to https://github.com/umijs/umi/pull/4044
> refactor: handle APP_ROOT scenario in getPkg.ts

- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/getConfig/getConfig.ts
- yarn.lock
We should support plaintext import scenario, as below:
```javascript
import txt from '@/assets/content.txt'
console.log('txt is', txt)
```
> feat: plaintext shall be imported

- docs/docs/runtime-config.md
- scripts/docs.js
`docs/runtime-config.md` translated
-----
[View rendered docs/docs/runtime-config.md](https://github.com/leftstick/umi/blob/master/docs/docs/runtime-config.md)
> docs: translate runtime-config.md

- packages/core/src/Service/utils/pluginUtils.ts
如果是相对路径的话，应该是可以使用ts去写插件的。
- any feature?
> feat: local plugin resolve support .ts files

- docs/docs/routing.zh-CN.md
- any feature?
-----
[View rendered docs/docs/routing.zh-CN.md](https://github.com/swaghua/umi/blob/patch-1/docs/docs/routing.zh-CN.md)
> docs: typo in routing.md, wrappers users => user

- packages/umi-build-dev/src/plugins/commands/block/download.js
- packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_clone.ts
- packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_update.ts
- packages/umi-build-dev/src/plugins/commands/block/util.ts
close https://github.com/ant-design/ant-design-pro/issues/6138#issuecomment-599159613
主要改动有两处
* 判断 antd 的版本切换分支
* 修改了分支切换的逻辑，从原来的默认 clone -b 到现在 checkout。这样可以保证 antd@3 分支不存在的情况下也可以继续流程
- any feature?
> Automatically switch to the branch of umi@3

- packages/ast/src/getExportProps/getExportProps.test.ts
- packages/ast/src/getExportProps/getExportProps.ts
- packages/ast/src/getExportProps/propertyResolver.ts
support `object`, `array`, 'null', 'undefined' property on exported component, as below:
```javascript
function Login({}) {
return <div>hello</div>
}
Login.propTypes = {}
Login.title = 'Login'
Login.menu = false
Login.layout = {
hideNav: true,
hideMenu: true
}
Login.access = 'canReadLogin'
Login.aaa = null
Login.bbb = undefined
export default Login
```
> feat: assign array, object property on exported Component is supported now

- packages/umi/src/renderRoutes.js
- No new failed tests
- Closes https://github.com/umijs/umi/issues/4328
- Provides a `fetchingProps` prop when CSR is running `getInitialProps()`
> fix(umi): drop SSR init props on route change

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/bundler-webpack/src/fixtures/chainWebpack-delay/config.ts
- packages/bundler-webpack/src/fixtures/chainWebpack-delay/expect.ts
- packages/bundler-webpack/src/fixtures/chainWebpack-delay/index.ts
- packages/bundler-webpack/src/fixtures/chainWebpack-delay/react.ts
- packages/bundler-webpack/src/getConfig/getConfig.ts
- any feature?
- close #4336
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat/chainWebpack-config-async/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/feat/chainWebpack-config-async/docs/config/README.zh-CN.md)
> feat: chainWebpack config support async

- packages/bundler-webpack/src/fixtures/import-from-outside/expect.ts
- packages/bundler-webpack/src/fixtures/import-from-outside/import-from-outside.ts
- packages/bundler-webpack/src/fixtures/import-from-outside/index.ts
- packages/bundler-webpack/src/getConfig/getConfig.ts
在配置了include的情况下，不符合条件的文件不会触发编译。当某文件引用了cwd祖先目录下的js mjs jsx ts等文件时，就会出现不触发编译导致报错的问题。考虑移除include cwd，依赖webpack自动查找引用并编译。
- any feature?
> fix: 修复cwd祖先目录下的文件不触发编译的bug

- packages/ast/src/getExportProps/getExportProps.test.ts
- packages/ast/src/getExportProps/getExportProps.ts
- packages/ast/src/getExportProps/propertyResolver.test.ts
- packages/ast/src/getExportProps/propertyResolver.ts
- packages/core/src/Route/getConventionalRoutes.ts
- support for extracting functions declaration from export
- support for extracting directly exported values
> feat(ast): getExportProps() supports more common export syntax

- packages/umi/src/renderRoutes.js
- packages/umi/yarn.lock
- yarn.lock
- no new failed tests
- Fixes https://github.com/umijs/umi/issues/4329
- Fixes https://github.com/umijs/umi/issues/4328 again
- Optimizations for navigating between dynamic routes sharing the same page components:
- SSR props are persisted before the new `getInitialProps` returns
- SSR props are provided as `prevInitialProps` for convenient reuse
> fix: prevent getInitialProps refire on hash change

- packages/umi/src/renderRoutes.js
- fixes "object is not extensible" in HOC getInitialProps
> fix(ssr): clone extraProps in SSR HOC

- packages/types/index.d.ts
把 路由 props 里的 `IRoute` 定义页暴露出去给开发者。因为和之前导出的路由定义名字相同，顾改名为 `IRouteProps`
> feat: export IRouteProps since developer might use it for their own purpose

- docs/plugins/plugin-layout.md
- docs/plugins/plugin-layout.zh-CN.md
针对小白用户文档阅读体验提升。大部分人对`icon name` 没有概念，所以`layout` 插件总是配不出图片，这个部分给一点详细介绍
-----
[View rendered docs/plugins/plugin-layout.md](https://github.com/leftstick/umi/blob/master/docs/plugins/plugin-layout.md)
[View rendered docs/plugins/plugin-layout.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/plugins/plugin-layout.zh-CN.md)
> docs: add description of icon name

- packages/ast/src/isReactComponent/isReactComponent.test.ts
- packages/ast/src/isReactComponent/isReactComponent.ts
Close https://github.com/umijs/umi/issues/4452
- any feature?
> fix: is React Component

- packages/types/index.d.ts
- rm unnecessary `false` type in BaseIConfig in package @umijs/types.
Otherwise, it is also reported as an "extends error" between BaseIConfig and IConfigCore
> fix: remove unnecessary false

- packages/create-umi-app/templates/AppGenerator/tsconfig.json
不加 `typings.d.ts`，代码里引用 图片，css，less文件会提示错误，因为`typings.d.ts`没生效
> fix: typings.d.ts should be added in include section

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/preset-built-in/src/plugins/features/forkTSChecker.ts
- packages/types/index.d.ts
> fix typo: forkTSCheker -> forkTSChecker 

- scripts/release.js
- scripts/tsIngoreDefineConfig.js
- 为 defineConfig.d.ts 添加 ts-ignore，避免依赖 umi 时的 tsc 报错
> chore: add ts-ignore for defineConfig.d.ts

- packages/create-umi-app/templates/AppGenerator/typings.d.ts
优化 `.svg` 引用时的 编程体验。 之前只加了作为 `ReactComponent` 时的体验。
但如果当做 url 引入时，使用的时候可能会提示类型不对。
所以又加了作为url时的类型声明，效果如下：
> feat: improve svg usage. import as url shall be supported

- packages/ast/src/getExportProps/getExportProps.test.ts
- packages/ast/src/getExportProps/getExportProps.ts
- packages/ast/src/getExportProps/propertyResolver.ts
- getExportProps 支持类的静态属性 
- close https://github.com/umijs/umi/issues/4638
> feat(ast): support static property

- packages/preset-built-in/src/plugins/features/ssr/templates/clientExports.tpl
- 为`IGetInitialProps`接口提供泛型支持，编写如下代码时将因为类型不一致而提示错误。
```js
import React from 'react';
import { IGetInitialProps } from 'umi';
interface InitialProps {
title: string;
}
export default class extends React.PureComponent<InitialProps> {
static getInitialProps: IGetInitialProps<InitialProps> = async () => {
const data = {
// title: 'Hello World',
};
return Promise.resolve(data);
};
render() {
return (
<div>
<h1>{this.props.title}</h1>
</div>
);
}
}
```
> chore: added generic support for `IGetInitialProps` interface

- docs/config/README.md
- docs/docs/contributing.zh-CN.md
- docs/docs/html-template.md
- docs/docs/routing.md
- docs/docs/routing.zh-CN.md
- docs/docs/ssr.md
- docs/guide/boost-compile-speed.md
- docs/guide/plugin-develop.md
- docs/plugins/plugin-helmet.md
- docs/plugins/plugin-request.md
- packages/renderer-react/src/renderRoutes/renderRoutes.test.tsx
- packages/renderer-react/src/renderRoutes/renderRoutes.tsx
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat/props-routes/docs/config/README.md)
[View rendered docs/docs/contributing.zh-CN.md](https://github.com/umijs/umi/blob/feat/props-routes/docs/docs/contributing.zh-CN.md)
[View rendered docs/docs/html-template.md](https://github.com/umijs/umi/blob/feat/props-routes/docs/docs/html-template.md)
[View rendered docs/docs/routing.md](https://github.com/umijs/umi/blob/feat/props-routes/docs/docs/routing.md)
[View rendered docs/docs/routing.zh-CN.md](https://github.com/umijs/umi/blob/feat/props-routes/docs/docs/routing.zh-CN.md)
[View rendered docs/docs/ssr.md](https://github.com/umijs/umi/blob/feat/props-routes/docs/docs/ssr.md)
[View rendered …
> feat: add props.routes for route components

- packages/preset-built-in/src/plugins/features/exportStatic.ts
- packages/preset-built-in/src/plugins/features/ssr/fixtures/normal/.umirc.ts
- packages/preset-built-in/src/plugins/features/ssr/fixtures/normal/customDist/umi.server.js
- packages/preset-built-in/src/plugins/features/ssr/ssr.test.ts
- packages/preset-built-in/src/plugins/features/ssr/ssr.ts
- packages/types/index.d.ts
- 修复 `hash: true` 下 `umi.server.js` 中默认 HTML 模板里的 js 和 css 没有被 hash 的问题
- 修复开启 dynamicImport 的预渲染，加载不正确的 chunks 
- any feature?
> fix: ssr default HTML assets not hash

- packages/preset-built-in/src/plugins/features/ssr/ssr.ts
- packages/preset-built-in/src/plugins/features/ssr/templates/clientExports.tpl
- packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl
- packages/types/index.d.ts
```ts
app.use(async (req, res) => {
const render: IRender = require('./dist/umi.server.js');
res.setHeader('Content-Type', 'text/html');
const { html, error, rootContainer } = await render({
path: req.url,
getInitialPropsCtx: {
req,
},
});
})
```
在使用如上代码时，期望给从`umi.server.js`导入的`render`函数加上类型提示，为此作如下修改：
- 通过调用`api.addUmiExports`，在生成的`umiExports.ts`文件中新增导出`IRender`，`IParams`，`IRenderResult`三个类型
- 根据`render`函数代码，完善`IParams`类型提示
https://github.com/umijs/umi/blob/7f7d51f5287c12a82b0caded34e98c8bd3bbbde7/packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl#L48-L59
---
```ts
Page.getInitialProps = (async (ctx) => {
if (ctx.isServer) {
console.log(ctx.req);
}
return {};
}) as IGetInitialProps
```
如将服务端参数扩展到`ctx`中，在使用如上代码时，会提示`ctx`上不存在`req`属性。
因此给`IParams`类型加上索引签名。
> chore: Update typings

- docs/docs/getting-started.md
- 添加npm在英文版说明中的Scaffold的命令（该命令在中文版中有，但是英文版中被遗漏了）
- 将中国大陆/阿里用户这块的说明单独分开。因为对英文用户（一般就是海外用户）而言这块没有用处，当前版本这块的内容非常让人迷惑。其实我个人建议在英文版本里面直接删除。
-----
[View rendered docs/docs/getting-started.md](https://github.com/neekey/umi/blob/patch-1/docs/docs/getting-started.md)
> Add Scaffold command for npm users in document

- docs/docs/faq.zh-CN.md
参考
* Close https://github.com/umijs/umi/issues/1421, Close https://github.com/umijs/umi/issues/5053
* https://v2.umijs.org/zh/guide/faq.html
* https://alitajs.com/faq/build
- any feature?
-----
[View rendered docs/docs/faq.zh-CN.md](https://github.com/umijs/umi/blob/docs-faqs/docs/docs/faq.zh-CN.md)
> docs: add faqs

- docs/plugins/api.zh-CN.md
add `addEntryImports` example code
-----
[View rendered docs/plugins/api.zh-CN.md](https://github.com/djyde/umi/blob/patch-1/docs/plugins/api.zh-CN.md)
> add `addEntryImports` example code

- docs/docs/runtime-config.md
- docs/docs/runtime-config.zh-CN.md
- packages/preset-built-in/src/plugins/generateFiles/umi.tpl
支持修改 clientRender 参数。
比如：
```js
export function modifyClientRenderOpts(memo) {
return {
...memo,
foo: 'bar',    
};
}
```
Close #5067
Ref #4979
Close #5020
-----
[View rendered docs/docs/runtime-config.md](https://github.com/umijs/umi/blob/feat/modifyClientRenderOpts/docs/docs/runtime-config.md)
[View rendered docs/docs/runtime-config.zh-CN.md](https://github.com/umijs/umi/blob/feat/modifyClientRenderOpts/docs/docs/runtime-config.zh-CN.md)
> feat: runtime plugin support modifyClientRenderOpts

- packages/core/src/Service/Service.ts
onPluginReady event 没有 await 处理，可能导致 onPluginReady 里的变更因为时序问题而被忽略（比如在 onPluginReady 通过环境变量启用了另一个插件，另一个插件的 modifyDefaultConfig就会失效）
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5139)
> fix(Service): await onPluginReady events to avoid concurrent issue

- docs/docs/config.md
- docs/docs/config.zh-CN.md
有内部用户反馈看不懂拆分 `config/config.ts` 的意思，且理解为只有 `.umirc.ts` 支持 env 后缀，所以尝试把文档描述写得更详细，以减少答疑成本
-----
[View rendered docs/docs/config.md](https://github.com/umijs/umi/blob/support/env-config-doc/docs/docs/config.md)
[View rendered docs/docs/config.zh-CN.md](https://github.com/umijs/umi/blob/support/env-config-doc/docs/docs/config.zh-CN.md)
> docs: improve explanation for env config

- packages/core/src/Route/getConventionalRoutes.ts
> fix: show explict error message when parsing conventional route components failed

- packages/bundler-webpack/src/index.ts
原因是以 `dist` 开头的文件被忽略了。
- any feature?
Close: https://github.com/umijs/umi/issues/5416
> fix: watch ignored outputPath

- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/getConfig/getConfig.ts
- yarn.lock
更新 copy-webpack-plugin@6.1.0。
由于 patterns 不能是一个空数组，所以改成按需引入。
Close: https://github.com/umijs/umi/issues/5208
> feat: update copy-webpack-plugin@6.1.0

- packages/umi/src/cli.ts
> fix: dev's exit code when Service init failed

- packages/core/src/Route/routesToJSON.ts
- packages/preset-built-in/src/plugins/generateFiles/core/routes.tpl
> feat: export umiExports and React in core/routes.ts

- packages/preset-built-in/src/plugins/generateFiles/core/history.tpl
- packages/preset-built-in/src/plugins/generateFiles/core/history.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5461)
> optimize: 仅 runtimeHistory 开启时才导出 setCreateHistoryOptions 和 getCreateHistoryOptions 方法

- packages/core/src/Route/Route.ts
- 修复在 windows 平台下 wrappers 的地址错误的情况
- close https://github.com/umijs/umi/issues/5401
> fix: resolve correct component and wrappers path in windows

- docs/docs/ssr.md
- docs/docs/ssr.zh-CN.md
- examples/ssr-koa/package.json
- examples/ssr-koa/server.js
- examples/ssr-koa/src/pages/index.js
- examples/ssr-normal/package.json
- examples/ssr-with-eggjs/app/controller/home.js
- examples/ssr-with-eggjs/package.json
- packages/preset-built-in/src/index.test.ts
- packages/preset-built-in/src/plugins/features/ssr/ssr.ts
- packages/preset-built-in/src/plugins/features/ssr/templates/renderServer/renderServer.test.tsx
- packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.tsx
Close https://github.com/umijs/umi/issues/5118
Close https://github.com/umijs/umi/issues/5099
> fix: ssr stream helmet bug and node runtime engines

- .github/workflows/ci.yml
- azure-pipelines.yml
- docs/config/README.md
- docs/config/README.zh-CN.md
- examples/ssr-normal/.umirc.ts
- examples/ssr-normal/layouts/index.tsx
- examples/ssr-normal/pages/about.tsx
- examples/ssr-normal/pages/index.tsx
- packages/bundler-webpack/src/getConfig/css.ts
- packages/preset-built-in/package.json
- packages/preset-built-in/src/plugins/features/ssr/ssr.ts
- packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl
- packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.tsx
- packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts
- packages/renderer-react/src/renderClient/renderClient.test.tsx
- packages/renderer-react/src/renderClient/renderClient.tsx
- packages/renderer-react/src/renderRoutes/renderRoutes.test.tsx
- packages/renderer-react/src/renderRoutes/renderRoutes.tsx
- packages/runtime/src/dynamic/dynamic.test.tsx
- packages/types/index.d.ts
- yarn.lock
增加一个配置 `ssr: { removeWindowInitialProps: true }`，可用来隐藏 `window.g_initialProps`
Close https://github.com/umijs/umi/issues/5509
Close https://github.com/umijs/umi/issues/4734, ref https://github.com/umijs/umi/pull/5513/commits/3cfc8c6f90ba2edfcdd481bcb424d6c86ec05042
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat-ssr-hide-initData/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/feat-ssr-hide-initData/docs/config/README.zh-CN.md)
> feat: SSR removeWindowInitialProps & fix warning in autoprefixer

- packages/umi-ui/client/src/layouts/Footer.tsx
- packages/umi-ui/package.json
- packages/umi-ui/src/UmiUI.ts
ref: https://github.com/umijs/umi-ui/pull/94/files
https://github.com/schnerd/d3-scale-cluster/issues/7#issuecomment-550579897
https://github.com/nodejs/node-gyp/blob/1e2e94d9851a1685d80d591262d0730681b5481d/macOS_Catalina.md
- any feature?
> chore: remove ui terminal node-pty

- packages/preset-built-in/src/plugins/commands/htmlUtils.ts
ref https://github.com/umijs/umi/pull/5630
window.resourceBaseUrl 放到 publicPathStr 变量里，这样才能确保外部通过 api.modifyPublicPathStr 复写 publicPath
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5653)
> fix: put window.resourceBaseUrl into publicPathStr that we could modify it by modifyPublicPathStr

- packages/preset-built-in/src/plugins/features/ssr/templates/clientExports.tpl
修复 TypeScript 类型声明缺失。
```tsx
import React from "react";
import { IGetInitialProps } from "umi";
interface GetInitialProps {
matchId: string;
}
interface DemoProps extends GetInitialProps {}
const Demo: React.FC<DemoProps> & {
getInitialProps: IGetInitialProps<GetInitialProps, { id: string }>;
} = ({ matchId }) => {
//  路由 /demo/4
return (
<div>
<h1>Page demo</h1>
{/* 4 | null */}
<p>{matchId}</p>
</div>
);
};
Demo.getInitialProps = async (params) => {
console.log(params.match.params.id);
return {
matchId: params.match.params.id,
};
};
export default Demo;
```
- any feature?
> fix: IGetInitialProps match.params

- docs/plugins/plugin-layout.md
- docs/plugins/plugin-layout.zh-CN.md
- any feature?
-----
[View rendered docs/plugins/plugin-layout.md](https://github.com/umijs/umi/blob/docs_layouts/docs/plugins/plugin-layout.md)
[View rendered docs/plugins/plugin-layout.zh-CN.md](https://github.com/umijs/umi/blob/docs_layouts/docs/plugins/plugin-layout.zh-CN.md)
> 📖 docs(layout): 优化文档中令人费解的部分

- packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js
Process require statements in core-js lock plugin, but the real reason that caused the import statements transform to require statements still not found.
- close #5715
> fix: workaround to resolve core-js path error bug

- docs/plugins/plugin-webpack-5.md
官方的说法是：[persistent-caching](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#persistent-caching) （持久缓存）
看到「物理缓存」吓得我虎躯一震，以为 webpack5 还能改造硬盘了。。
- any feature?
-----
[View rendered docs/plugins/plugin-webpack-5.md](https://github.com/aweiu/umi/blob/patch-2/docs/plugins/plugin-webpack-5.md)
> docs: 物理缓存 => 持久缓存

- packages/preset-built-in/src/plugins/commands/dev/dev.ts
现在 `env` 是在 `Service` 初始化之前设置的，如果在 `Service` 初始化的过程中其他插件（集）修改 `env` 为 `development`、并且尝试手动调用 `runCommand:dev`，则会导致命令启动失败。
应用场景：基于 Umi 的工具映射子命令到 `dev`，比如执行 `dumi doc dev` 等同于执行 `dumi dev`。
更好的方式：提供 `setEnv` 和 `getEnv` 让 plugin 读写 `Service` 的值。
> refactor: allow other plugin run dev command

- docs/docs/config.md
- docs/docs/config.zh-CN.md
- docs/docs/faq.md
- docs/docs/faq.zh-CN.md
1. config：配置的描述歧义，会引发了一些错误的使用方式（例如认为routes可自动化配置，在route未被引用生效时，约定式路由会起作用，让人误以为拆分的routes是有效果的）
2. faq：关于取消全局loading的描述是错误的
- any feature?
-----
[View rendered docs/docs/config.zh-CN.md](https://github.com/Jfreey/umi/blob/master/docs/docs/config.zh-CN.md)
[View rendered docs/docs/faq.zh-CN.md](https://github.com/Jfreey/umi/blob/master/docs/docs/faq.zh-CN.md)
> docs: 修改一处(config)描述歧义，修改一处(faq)描述错误

- packages/babel-plugin-auto-css-modules/package.json
- packages/babel-plugin-auto-css-modules/src/index.ts
- packages/babel-plugin-import-to-await-require/package.json
- packages/babel-plugin-import-to-await-require/src/index.ts
Move `@umijs/babel-plugin-auto-css-modules`'s dependencies to devDependencies because only types are [used](https://npmfs.com/package/@umijs/babel-plugin-auto-css-modules/3.2.28/lib/index.js), but will produces [![install size](https://packagephobia.com/badge?p=@umijs/babel-plugin-auto-css-modules)](https://packagephobia.com/result?p=@umijs/babel-plugin-auto-css-modules) in published package.
---
Updated: did the same thing to `babel-plugin-import-to-await-require`
> chore: move babel-plugin-auto-css-modules deps to devDeps

- packages/create-umi-app/templates/AppGenerator/package.json.tpl
- any feature?
<br>
<br>
- 当前初始化的项目中 @ant-design/pro-layout  版本是 5.x，而近期 @ant-design/pro-layout [迎来了一大波 fix](https://procomponents.ant.design/changelog/pro-layout)，希望 create umi app 时初始化模板中的依赖版本能够更新
- `lint-staged ` 和 `prettier`  和业务无关，但是被放到了 dependencies 中
<br>
<br>
``` shell
$ mkdir myapp && cd myapp
$ yarn create @umijs/umi-app
```
<br>
<br>
``` js
@ant-design/pro-layout@^5.0.12  =>  @ant-design/pro-layout@^6.5.0
```
``` shell
"devDependencies": {
"lint-staged": "^10.0.7",
"prettier": "^1.19.1",
}
```
<br>
<br>
<br>
@ycjcl868   @sorrycc 
有空帮忙 review 一下吗
<br>
<br>
> chore: update the init template when the app is created

- packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts
ssr模式下， replace（）方法中出现美元符号会引起模板渲染异常
Close #5840
- any feature?
> fix: ssr replace() method dollar signs

- packages/renderer-react/src/renderRoutes/renderRoutes.tsx
csr时, g_initialProps 为 undefined
修复 csr时, 不自动调用 handleGetInitialProps
> fix(renderer-react): wrapInitialPropsFetch

- packages/renderer-react/src/renderRoutes/renderRoutes.tsx
according to [doc](https://umijs.org/zh-CN/docs/ssr#%E9%A1%B5%E9%9D%A2%E7%BA%A7%E6%95%B0%E6%8D%AE%E8%8E%B7%E5%8F%96)
> getInitialProps 中有几个固定参数：
> history：history 对象
> fix(ssr): getInitialProps should has `history` in csr

- packages/create-umi-app/templates/AppGenerator/typings.d.ts
> style(template): unify 'typings.d.ts' code style

- packages/types/index.d.ts
- fix: cssModulesTypescriptLoader.mode should be optional
- close #5678
-----
[View rendered docs/docs/cli.md](https://github.com/yingzhiji/umi/blob/fix/css-modules-typescript-loader-typing/docs/config/README.md#cssmodulestypescriptloader-31)
[View rendered docs/docs/cli.zh-CN.md](https://github.com/yingzhiji/umi/blob/fix/css-modules-typescript-loader-typing/docs/config/README.zh-CN.md#cssmodulestypescriptloader-31)
> fix: cssModulesTypescriptLoader.mode should be optional

- .github/workflows/ci.yml
- packages/preset-built-in/src/index.test.ts
> chore: remove --max_old_space_size from ci

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/bundler-utils/src/getBabelOpts.ts
- packages/preset-built-in/src/plugins/features/dynamicImportSyntax.ts
- packages/types/index.d.ts
> feat: support config.dynamicImportSyntax for syntax only

- packages/preset-built-in/src/plugins/commands/dev/mock/createMiddleware.ts
- packages/preset-built-in/src/plugins/commands/dev/mock/mock.ts
- packages/preset-built-in/src/plugins/commands/dev/mock/utils.ts
一次性生成很多 mock 时，会卡住服务器，加一个 debounce
- any feature?
> fix: mock too much files block server

- docs/plugins/plugin-access.md
- Translated plugin-access documentation.
-----
[View rendered docs/plugins/plugin-access.md](https://github.com/crudo/umi/blob/c-eng-access/docs/plugins/plugin-access.md)
> docs: English translation of plugin-access

- packages/renderer-react/src/renderRoutes/renderRoutes.test.tsx
- packages/renderer-react/src/renderRoutes/renderRoutes.tsx
Close https://github.com/umijs/umi/issues/5881
改变 Component 会导致一次强制重渲染. 而这样, 会让组件中的 didMount 被调用两次.
事实上, 只需要将新的 initialProps 传给 LoadableComponent, LoadableComponent 会将这个 props 传递下去.
这样, 第二次渲染就不是强制渲染了.
> fix(ssr): csr 和 dynamicImport 一起使用导致组件 2 次 mount

- docs/plugins/plugin-layout.md
- docs/plugins/plugin-layout.zh-CN.md
- any feature?
-----
[View rendered docs/plugins/plugin-layout.zh-CN.md](https://github.com/umijs/umi/blob/add-target-blank/docs/plugins/plugin-layout.zh-CN.md)
> docs: add target blank in example code

- docs/plugins/plugin-qiankun.md
- docs/plugins/plugin-qiankun.zh-CN.md
- any feature?
-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/6128)
> docs(qiankun): 优化文档

- .prettierignore
- docs/plugins/plugin-layout.md
- docs/plugins/plugin-layout.zh-CN.md
- package.json
close  https://github.com/ant-design/pro-components/issues/1786
[View rendered docs/plugins/plugin-layout.md](https://github.com/umijs/umi/blob/layout-demo/docs/plugins/plugin-layout.md)
[View rendered docs/plugins/plugin-layout.zh-CN.md](https://github.com/umijs/umi/blob/layout-demo/docs/plugins/plugin-layout.zh-CN.md)
> docs: update layout docs

- packages/bundler-webpack/src/fixtures/t++/config.ts
- packages/bundler-webpack/src/fixtures/t++/expect.ts
- packages/bundler-webpack/src/fixtures/t++/index.tsx
- packages/bundler-webpack/src/index.ts
- packages/utils/src/routes.test.ts
- packages/utils/src/routes.ts
> fix(utils): routeToChunkName with invalid regular expression

- packages/core/src/Config/types.d.ts
- packages/core/src/Html/Html.ts
- packages/preset-built-in/src/plugins/commands/generateFiles.ts
- packages/preset-built-in/src/plugins/generateFiles/core/routes.ts
- packages/types/index.d.ts
> feat: reduce the chance of regenerating conventional routes

- packages/babel-plugin-no-anonymous-default-export/src/index.test.ts
- packages/bundler-webpack/src/DevCompileDonePlugin.ts
- packages/bundler-webpack/src/index.ts
- yarn.lock
> chore: ci broken

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/fixtures/worker-loader/config.ts
- packages/bundler-webpack/src/fixtures/worker-loader/expect.ts
- packages/bundler-webpack/src/fixtures/worker-loader/index.ts
- packages/bundler-webpack/src/fixtures/worker-loader/worker.js
- packages/bundler-webpack/src/getConfig/getConfig.ts
- packages/core/package.json
- packages/preset-built-in/package.json
- packages/preset-built-in/src/index.ts
- packages/preset-built-in/src/plugins/features/workerLoader.ts
- packages/server/package.json
- packages/types/package.json
- packages/umi/package.json
- packages/utils/package.json
- yarn.lock
- any feature?
- close #6247
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat/workerLoader/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/feat/workerLoader/docs/config/README.zh-CN.md)
> feat: support worker-loader with config workerLoader

- packages/babel-plugin-import-to-await-require/src/index.test.ts
- packages/babel-plugin-import-to-await-require/src/index.ts
`babel-plugin-import-to-await-require` 支持传递 `exportAllMembers`配置项，用于将 `export * from 'x'` 转换为 静态的 member exports，使得 mfsu 能对 `export *` 语法生效，但词法是手动挡，未来找到更合适的方案再换成自动挡
> feat(import-to-await): support to process export * with user config

- packages/babel-plugin-import-to-await-require/src/index.test.ts
- packages/babel-plugin-import-to-await-require/src/index.ts
`babel-plugin-import-to-await-require` 支持传递 `exportAllMembers`配置项，用于将 `export * from 'x'` 转换为 静态的 member exports，使得 mfsu 能对 `export *` 语法生效，但词法是手动挡，未来找到更合适的方案再换成自动挡
和 https://github.com/umijs/umi/pull/6260 一致，用于 3.3.x
> feat(import-to-await): support to process export * with user config (3.3.x)

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/preset-built-in/src/index.ts
- packages/preset-built-in/src/plugins/features/404.test.ts
- packages/preset-built-in/src/plugins/features/404.ts
增加约定式的 404 逻辑，文档里都有，这个功能应该是漏了。
没有实现 “umi dev 404 page” ，重复答疑次数太多了。（ dev 的时候，自定义的 404 页面无效，需要 build 之后才会生效。）
- any feature?
- close https://github.com/umijs/umi/issues/5092
> feat: add 404 plugin

- packages/preset-built-in/src/plugins/features/webpack5.ts
lazyCompilation开启后build时会少生成文件，只生成默认路由的文件，故只在dev模式下启用。
> fix: use lazyCompilation in development mode only

- packages/bundler-webpack/src/index.ts
- 修复webpack5 build模式下物理缓存失效
- see https://github.com/webpack/webpack/issues/12345#issuecomment-755273757
- close #6266
> fix: webpack5 build 模式下没有生成物理缓存

- packages/preset-built-in/src/plugins/features/webpack5.ts
…rod mode
依赖文件变化时，比如echarts4 => echarts5，再build的时候会出现报错。
故使用webpack5 doc推荐的buildDependencies配置监控全依赖，当依赖变化时可以使缓存失效重新构建。
另外dev模式下也有此问题。
> fix(webpack5): fix webpack5 cache cannot be invalidated when package.json changes

- packages/babel-preset-umi/package.json
- packages/babel-preset-umi/src/index.test.ts
- packages/babel-preset-umi/src/index.ts
- packages/bundler-webpack/package.json
- packages/core/package.json
- packages/preset-built-in/package.json
- packages/server/package.json
- packages/types/package.json
- packages/umi/package.json
- packages/utils/package.json
- yarn.lock
Records and Tuples 语法支持 
HOW：基于 @babel/plugin-proposal-record-and-tuple 和 @bloomberg/record-tuple-polyfill
- any feature?
> feat: record and tuple

- packages/core/src/Service/Service.test.ts
- packages/core/src/Service/utils/pluginUtils.ts
配置plugin：
```
{
plugins: [[
'umi-plugin-dva',
{
immer: true,
},
]],
}
```
修改前：
```
Path must be a string.
TypeError: Path must be a string.
```
修改后：
```
Plugin resolved failed, Please check your plugins config, it must be array of string.
Error Plugin Config: ["umi-plugin-dva",{"immer":true}]
```
- any feature?
-  https://github.com/umijs/umi/issues/6303
> chore: improve error message when plugin resolved failed

- packages/preset-built-in/src/plugins/features/webpack5.ts
首先modifyBabelOpts放在modifyBundleConfig里是不生效的，拿出来以后会执行，但设置cacheDirectory = false也不能阻止babel-loader生成cache，猜测可能是执行顺序之类的。
因为有BABEL_CACHE的环境变量，所以直接改在onPluginReady设置BABEL_CACHE = 'none'来阻止babel-loader生成cache。
> fix(webpack5): fix the failure of abandoning babel-loader cache

- packages/bundler-webpack/bundled/webpackHotDevClient.js
> fix: remove react-error-overlay warning in dev

- docs/plugins/plugin-dva.md
- docs/plugins/plugin-dva.zh-CN.md
Refs: https://github.com/umijs/plugins/pull/523
- any feature?
-----
[View rendered docs/plugins/plugin-dva.md](https://github.com/umijs/umi/blob/docs-dva/docs/plugins/plugin-dva.md)
[View rendered docs/plugins/plugin-dva.zh-CN.md](https://github.com/umijs/umi/blob/docs-dva/docs/plugins/plugin-dva.zh-CN.md)
> docs: dva disableModelsReExport and lazyLoad

- packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts
Condition 'windowInitialVars' is always true,  remove `{}`
- any feature?
> style(preset-built-in): Condition 'windowInitialVars' is always true

- docs/plugins/plugin-esbuild.md
- docs/plugins/plugin-esbuild.zh-CN.md
resolve #6422
esbuild-loader没有pure字段的配置。
[https://github.com/privatenumber/esbuild-loader](esbuild-loader)
-----
[View rendered docs/plugins/plugin-esbuild.md](https://github.com/Map1en/umi/blob/doc-rm-esbuild-pure/docs/plugins/plugin-esbuild.md)
[View rendered docs/plugins/plugin-esbuild.zh-CN.md](https://github.com/Map1en/umi/blob/doc-rm-esbuild-pure/docs/plugins/plugin-esbuild.zh-CN.md)
> docs(plugin-esbuild): rm esbuild pure setting

- packages/bundler-webpack/bundled/webpackHotDevClient.js
- packages/bundler-webpack/config.ts
- packages/bundler-webpack/package.json
- packages/bundler-webpack/scripts/patchWebpackHotDevClient.js
- packages/bundler-webpack/src/webpack/plugins/mini-css-extract-plugin/src/hmr/hotModuleReplacement.js
> fix: ie 11 dev support

- packages/umi/src/initWebpack.ts
> chore: improve webpack 5 initial test

- packages/preset-built-in/src/fixtures/exportStatic/.umirc.ts
- packages/preset-built-in/src/fixtures/exportStatic/pages/index.tsx
- packages/preset-built-in/src/index.test.ts
- packages/preset-built-in/src/plugins/features/exportStatic.test.ts
- packages/preset-built-in/src/plugins/features/exportStatic.ts
> fix: exportStatic no work on windows

- packages/preset-built-in/src/plugins/features/exportStatic.ts
- packages/preset-built-in/src/plugins/features/ssr/ssr.ts
- packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts
- packages/preset-built-in/src/plugins/utils.test.ts
- packages/preset-built-in/src/plugins/utils.ts
- fix error when `ssr.mode = 'stream'` and `exportStatic`
- replace fs sync methods into asynchronous in `ssr`. refs: https://github.com/nodejs/node/issues/37583
Close https://github.com/lifegit/myapp2/issues/1
- any feature?
> fix(ssr): stream mode throw error in exportStatic

- docs/config/README.zh-CN.md
- any feature?
-----
[View rendered docs/config/README.zh-CN.md](https://github.com/mqyun/umi/blob/patch-1/docs/config/README.zh-CN.md)
> ignoreMomentLocale Type

- examples/basic-wrappers/README.md
- examples/basic-wrappers/package.json
- examples/basic-wrappers/pages/index.tsx
- examples/basic-wrappers/pages/login.tsx
- examples/basic-wrappers/tsconfig.json
- examples/basic-wrappers/wrappers/auth.tsx
添加约定式的 wrappers 例子，为了回复 https://github.com/umijs/umi/issues/6562
- any feature?
-----
[View rendered examples/basic-wrappers/README.md](https://github.com/umijs/umi/blob/chore-example-basic-wrappers/examples/basic-wrappers/README.md)
> chore: add example for basic wrappers

- .circleci/config.yml
- .github/workflows/ci.yml
- azure-pipelines.yml
- packages/bundler-webpack/src/fixtures/.noExtraBabelIncludes/too.js
- packages/bundler-webpack/src/fixtures/extraBabelIncludes/expect.ts
- packages/bundler-webpack/src/fixtures/extraBabelIncludes/index.ts
- packages/bundler-webpack/src/getConfig/getConfig.ts
修复当 extraBabelIncludes 配置的是绝对路径的时候，会自动编译所有的模块。
感觉应该是逻辑bug
举例子：
目录结构如下：
```base
.
├── README.md
├── package.json
├── packages
│   ├── app
│   │   ├── package.json
│   │   └── pages
│   │       └── index.js
│   ├── footer
│   │   ├── index.jsx
│   │   └── package.json
│   └── head
│       ├── index.jsx
│       └── package.json
├── tsconfig.json
└── yarn.lock
```
```ts
import { defineConfig } from 'umi';
import { join } from 'path';
export default defineConfig({
extraBabelIncludes: [
join(__dirname, '../head'),
],
})
```
因为我没有配置了 footer，因此引用 footer 的文件应该报错才对，但是此时却全都正确运行了。
- any feature?
> fix: config extraBabelIncludes is absolute, nodeModules all transform

- packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.test.ts
- packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts
`json` as dependency used in `mfsu` should be supported
for example, following code would cause exception while enable `mfsu`
```ts
import pkg from 'antd/package.json'
console.log(pkg)
```
- close https://github.com/umijs/umi/issues/6923
> fix: support json import in mfsu

- packages/preset-built-in/src/plugins/commands/dev/mock/createMiddleware.ts
- packages/preset-built-in/src/plugins/features/mfsu/getFilePath.test.ts
> type: fix tsc ICreateMiddleware error

- docs/config/README.md
- 修正` history 类型和配置项`链接（依赖仓库在[这次commit](https://github.com/ReactTraining/history/commit/9532fb2170ab8000bddf69116661a9cb400c1ed6#diff-31bcba2ccafa41d46fbbd6d1219f7f1e3b1fb3cad9faa8e4dc521bbb579dd7b3)有做重命名）
-----
[View rendered docs/config/README.md](https://github.com/careteenL/umi-1/blob/master/docs/config/README.md)
> doc: fix config history link typo

- packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
在配合`electron`做开发时，`publicPath` 不能使用默认值或者 以 `/` 之类绝对路径的值，这样会导致打包后的文件加载不正常（electron应用启动并不是web 容器）。
所以在`electron`开发下，`publicPath` 需要设置成 `./`之类相对路径。
然后问题就来了，`mfsu` 在dev serve 文件时，直接字符串拼接`${api.config.publicPath}mf-va_` 是match不到文件的。就出现了如下错误：
```
Unhandled Rejection (ScriptExternalLoadError): Loading script failed.
(missing: http://localhost:8000/mf-va_remoteEntry.js)
while loading "./core-js" from webpack/container/reference/mf
while loading ".//Users/howard.zuo/github/electron-awesome/node_modules/@umijs/runtime" from webpack/container/reference/mf
while loading "./react" from webpack/container/reference/mf
```
可复现repo: https://github.com/leftstick/electron-awesome
复现步骤：
```
yarn
yarn start
```
就会看到上述错误
> fix: resolve publicPath properly especially for electron env

- packages/preset-built-in/src/plugins/features/mfsu/mfsu.test.ts
- packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
-  添加更为通用的`publicPath`适配
mfsu模式下, 由于`api.config.publicPath = 'http://10.0.0.1:10086/'`导致开发环境无法获取`mfsu`相关静态资源.
与 #7013 遇到的情况是一类问题, 只是我这边的情况更为特殊, `publicPath`需要设置成本机`ip`对应的绝对地址, 不能直接设置成`./`或`/`.
说一下我的使用场景:
1.  微前端qiankun主容器是常年部署到一个固定的环境中, 域名是`http://a.work.co`
2.  开发子应用时是在本地启动的服务,  假设本地ip是`10.0.0.1`
3.  如果`publicPath`设置成了`/`或者`./`等相对路径, `webpack runtime`在请求资源时会以`http://a.work.co`为base, 导致无法请求本机上的资源.
-  我的项目也不方便开启`runTimePublicPath`配置. (因为我的项目中`html`文件不是`umi`自动生成的, 所以开了也不顶用)
4. 所以直截了当的方式是在开发环境把`publicPath`设置一个绝对地址, 比如: `http://10.0.0.1:10086/`这种形式顺利访问本机资源
> fix(preset-built-in): fix mfsu assets mismatch with various publicPath (#7013)

- packages/preset-built-in/src/plugins/commands/plugin/plugin.ts
if user just run `umi plugin`, they will get a more friendly error message
> optimize tip for `umi plugin`

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts
- packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
- packages/preset-built-in/src/plugins/features/mfsu/utils.ts
- packages/types/index.d.ts
- ref: #6932
- 解的问题是 `import { EventEmitter } from 'events'; console.log(EventEmitter);` 拿到 `undefined` 的问题
- 提供 `mfsu.ignoreNodeBuiltInModules` 配置，忽略 node 原生库
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/fix/mfsu-node-builtin-modules/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/fix/mfsu-node-builtin-modules/docs/config/README.zh-CN.md)
> fix: mfsu problem with node built-in modules

- packages/preset-built-in/src/plugins/features/ssr/ssr.ts
实测下来 alinode v4 中 `promises` 在 `fs` 对象上是不可枚举的，和[文档](https://help.aliyun.com/document_detail/60811.html)中对应的 Node.js v10 的行为不一致，导致 `import * as fs from 'fs'` 经过 babel 编译后在 alinode 环境下无法取得 `fs.promises`、构建会报错，所以改为 `import fs from 'fs'` 以兼容 alinode
测试代码：
```js
// 在原生 Node.js v10.1.0 输出 true，在 alinode v4.8.0 下输出 false
console.log(require('fs').propertyIsEnumerable('promises'));
```
> fix(preset-built-in): ssr failed with alinode 4

- packages/babel-preset-umi/src/index.ts
修复 `src/.umi` 下 babel 缓存过期导致项目启动失败的问题，过期的原因是 cache 中记录的 `@babel/runtime` 版本是用户上一次安装的版本，在重装依赖后 cache 继续找上一个版本，但包已经没有了。
但这里有另一个问题，Umi 层对 `@babel/runtime` 做过[锁定](https://github.com/umijs/umi/blob/master/packages/babel-preset-umi/src/index.ts#L131)但并未生效，原因是 `@babel/plugin-transform-runtime` 内部在使用 `absoluteRuntime` 这项配置时用了 `require.resolve(path, { paths: [absoluteRuntime] })` 的方式，所以要传入锁定 `@babel/runtime` 的包（即 `@umijs/babel-preset-umi`）的绝对路径才能奏效。
refer: https://github.com/babel/babel/blob/v7.16.12/packages/babel-plugin-transform-runtime/src/get-runtime-path/index.ts#L19
> fix(babel-preset-umi): correct absoluteRuntime option

- packages/babel-preset-umi/src/index.ts
- packages/bundler-webpack/src/fixtures/unicode-regex/expect.ts
- packages/bundler-webpack/src/fixtures/unicode-regex/index.ts
目前遇到两个 cases 会用到这个插件，所以重新开启：
1. IE11 等传统浏览器对 unicode 字符集的支持问题，`Invalid range in character set error`，refer: https://stackoverflow.com/a/51031050
2. 常规 Umi 项目中如果使用了部分 unicode 正则写法（例如：`/\p{Script=Han}+|\p{Punctuation}/ug`）也会导致 babel 编译失败
> refactor(babel-preset-umi): enable unicode-regex

- packages/deps/package.json
- yarn.lock
修复由于幽灵依赖 `regenerate-unicode-properties` 引起的 unicode 正则编译失败的问题，锁定 `regenerate-unicode-properties` 在依赖预打包时的 `9.0.0` 版本，确保 `compiled/babel/bundle.js` 中的代码始终能 require 到正确的版本
ref: #7837
> fix(deps): unicode regex compile failed due to phantom dep

- packages/test/package.json
- packages/test/src/createDefaultConfig/createDefaultConfig.ts
- yarn.lock
- 当前 jest 版本为 v26,默认支持 jsdom16 ，去除用于支持旧版本 jest 24 的 jest-environment-jdom-fourteen 包
- close  https://github.com/umijs/umi/issues/8035
> fix: remove the useless jest-environment-jdom-fourteen package

- packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts
- close https://github.com/umijs/umi/issues/7000
解决了打包产物包含绝对路径的问题，我在app.ts和 plugin-dva遇到了，然后在issue里发现还有已知的plugin-locale
app.ts的在这个MR解决，另外两个在plugin的仓库提交PR解决
> fix(preset-built-in): fix addRuntimePlugin use absolute path

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
防止 3 、4 版本的 issue 分不清，3.x 的 issue 模板搬过来了。
-----
[View rendered .github/ISSUE_TEMPLATE/bug_report.md](https://github.com/MoeYc/umi/blob/chore/issue-tpl/.github/ISSUE_TEMPLATE/bug_report.md)
[View rendered .github/ISSUE_TEMPLATE/feature_request.md](https://github.com/MoeYc/umi/blob/chore/issue-tpl/.github/ISSUE_TEMPLATE/feature_request.md)
> chore: add issue template

- packages/plugin-docs/client/theme-doc/NavBar.tsx
- packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx
> feat(plugin-docs): external-link-support-dark

- packages/plugins/src/qiankun/master.ts
- packages/preset-umi/src/features/tmpFiles/routes.ts
这里 suspense lazy load 之后，只接受默认导出的组件，修复他。
https://github.com/umijs/umi/blob/b24a0781ff7167c3e5ede6f7fdf43922cc1f52e0/packages/preset-umi/src/features/tmpFiles/routes.ts#L199-L206
> fix(qiankun): master lazy load child app entry

- packages/plugins/src/locale.ts
```typescript
import { getIntl, getLocale } from 'umi';
function test() {
const intl = getIntl(getLocale());
console.log(
intl.formatMessage({
id: 'system.hello',
description: 'Hello',
})
);
}
```
Closes: https://github.com/umijs/umi/issues/8263
> fix(plugin/locale): add getIntl api

- package.json
- packages/preset-umi/src/commands/lint.ts
- pnpm-lock.yaml
修复 `umi lint` 在结合 `lint-staged` 使用时，没有 lint 指定文件的 bug
> fix(preset-umi): lint-staged args not working bug for lint

- packages/bundler-webpack/src/server/server.ts
- packages/preset-umi/src/commands/preview.ts
From
```
onProxyRes(proxyRes, req: any) 
```
to
```
onProxyRes(proxyRes, req: any, res) 
```
> fix: The parameter [res] is not passed (#8259)

- .gitignore
- examples/ant-design-pro/src/layouts/index.tsx
- packages/plugins/src/layout.ts
- packages/preset-umi/src/features/tmpFiles/__snapshots__/routes.test.ts.snap
- packages/preset-umi/src/features/tmpFiles/routes.test.ts
- packages/preset-umi/src/features/tmpFiles/routes.ts
-  layout 插件支持与约定式布局混用
-  `preset-umi/getRoutes` 增加单测
Closes: https://github.com/umijs/umi/issues/8174
> feat(plugins): layout plugin support conventional layout

- packages/lint/src/config/stylelint/index.ts
stylelint对类名的命名强限制为中划线，但是使用css modules 很多项目都直接用小驼峰命名class名，这样进行lint时会报很多错误，希望将规则改为中划线或小驼峰
> feat: 更改stylelint规则,允许小驼峰和中划线命名

- packages/babel-preset-umi/package.json
给 `@umijs/babel-preset-umi` 添加缺失的 `@umijs/utils` 依赖，避免使用幽灵依赖，`app.js` 和 `node.js` 里有用到
> fix(babel-preset-umi): declare @umijs/utils in dependencies

- docs/docs/guides/lint.md
- packages/lint/src/linter/eslint.ts
- packages/lint/src/linter/stylelint.ts
- packages/preset-umi/src/commands/lint.ts
默认禁用 `quiet` 参数，与 ESLint/Stylelint 默认值保持一致
Close #8269 
-----
[View rendered docs/docs/guides/lint.md](https://github.com/umijs/umi/blob/feature/lint-quiet/docs/docs/guides/lint.md)
> refactor(lint): disable quiet by default

- packages/plugin-docs/client/theme-doc/Search.tsx
> fix(plugin-docs): search result anchor location failure

- packages/bundler-webpack/src/getConfig/getConfig.ts
修正 `terser-webpack-plugin` 的 `sourcemap` 参数，用户没配置 `devtool` 的时候默认不开启
> fix(bundler-webpack): terser sourcmap option

- scripts/release.js
优化 Umi 3 的发布脚本：
1. 默认发 `3.x` 和 `next-3` tag，避免影响 Umi 4 的 latest
2. `otp` 是一段时间内有效、只需要询问一次，现在要输入 21 遍 otp...
> chore: improve release script

- docs/docs/max/dva.md
> 首先你需要配置 dva: {} 打开 Umi 内置的 [dva 插件](https://umijs.org/docs/max/plugin-dva)。
链接错误
-----
[View rendered docs/docs/max/dva.md](https://github.com/wanghaida/umi/blob/fix/maxDvaTypo/docs/docs/max/dva.md)
> fix: docs max dva typo

- docs/docs/api/config.md
看了下，目前该配置仅支持 `React`
增加了在 `win` 电脑的快捷键
-----
[View rendered docs/docs/api/config.md](https://github.com/ahwgs/umi-start/blob/feat_doc/docs/docs/api/config.md)
> docs: add clickToComponent doc

- packages/server/src/server.ts
1. `base` 请求的时候 dev server 始终返回 `index.html`、不校验 `headers.accept`
2. 参考 `webpack-dev-server` 使用的 [`connect-history-api-fallback` 的行为](https://github.com/bripkens/connect-history-api-fallback#htmlacceptheaders)，在 `accpet: */*` 的时候也返回 HTML
Close #8427
> refactor(server): always return html for base path request

- packages/bundler-webpack/src/server/server.ts
debug  mfsu 的 `mf-va_remoteEntry.js` 发现这个 middleware 应该尽早安装，
不然无法拦截到 beforeMiddlewares 里面提供的 js 资源请求。
> fix: 🐛  debug js file middleware should mounted eariler

- packages/preset-umi/src/features/apiRoute/request.test.ts
- packages/preset-umi/src/features/apiRoute/request.ts
- packages/preset-umi/src/features/apiRoute/response.ts
#8410 
为 API 路由功能添加了 request body 是 `multipart/form-data` 和 `application/x-www-form-urlencoded` 时的请求体解析支持。
当 request body 是上述两种格式时且请求头带有正确的 `Content-Type` 时，可以直接在 API 路由用 `req.body` 访问解析完成的 object 格式的请求体。
> feat(api-route): parse request body in type of form

- .github/workflows/ci.yml
- .github/workflows/compressed-size.yml
新增 ci 自动检测 `dist`、`compiled` 下文件体积的变动。
这可以从一定程度衡量 npm 下载该包的成本。
这近似可以代表安装 umi 时下载的所有 `@umijs/*` 包的成本，也就是：
> ci: add package size analyze

- packages/renderer-react/src/browser.tsx
如果 `window.__umi_manifest__` 为以下代码：
```js
window.__umi_manifest__ = {
"umi.css": "/umi.aa4342fc.css",
"umi.js": "/umi.ffdad893.js",
"1.css": "/1.f5fecf30.chunk.css",
"1.js": "/1.57fecd0a.async.js",
"2.css": "/2.f5fecf30.chunk.css",
"2.js": "/2.0f29443f.async.js",
"3.css": "/3.f5fecf30.chunk.css",
"3.js": "/3.405c6284.async.js",
"4.css": "/4.f8550f09.chunk.css",
"4.js": "/4.3a0a27b4.async.js",
"@@_global_layout.js": "/@@_global_layout.fb948677.async.js",
"258.1df5da00.async.js": "/258.1df5da00.async.js",
"62.02fa153b.async.js": "/62.02fa153b.async.js",
"37.fd560c60.async.js": "/37.fd560c60.async.js",
"376.009af299.async.js": "/376.009af299.async.js"
}
```
那么 `Object.keys(manifest)` 获得的数组中 css 文件名永远在 js 文件名之前，这样就导致 `k.startsWith(routeIdReplaced + '.')` 一直获得是 css 文件名。
> fix: get preload key always ends with css

- packages/preset-umi/src/features/mock/getMockData.ts
fix #8499
改动点：mock file 加载逻辑
- 改动前：只有当每次 `require` 完 mock file 并且解析成功才会删除 mock file 的 `require.cache` 缓存，导致当解析 mock file 出错时无法热重载修改后的的 mock file。
- 改动后：每次 `require` mock file 前，先删除对应文件的 `require.cache` 缓存。
> fix: mock file reload fail

- examples/boilerplate/.umirc.ts
- packages/server/src/server.ts
fix #8538
解决在 `metas` 里自定义 `viewport` 等不会覆盖默认值的问题。
> fix: html default meta overrides

- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/getConfig/getConfig.ts
- packages/preset-built-in/src/plugins/commands/dev/devCompileDone/devCompileDone.ts
- yarn.lock
1. dev 编译错误的时候输出错误信息
2. 启用 `@umijs/case-sensitive-paths-webpack-plugin`
效果截图：
> feat: enable case-sensitive-paths-webpack-plugin

- packages/mfsu/src/dep/getExposeFromContent.ts
fix #8564
比如 `@headlessui/react` 这个包的 esm 产物是：
```ts
export*from'some'
```
这样的，空格可有可无。
FYI：
- https://cdn.jsdelivr.net/npm/@headlessui/react@1.6.6/dist/headlessui.esm.js
> fix(mfsu): exports space optional when only has exports dep

- packages/preset-umi/src/features/configPlugins/configPlugins.ts
fix #8572
react < 18 时由于兼容了 `react-dom/client` 的导入，所以这要求他和 `react-dom` 的 `external` 一致（如果有），否则 `react-dom` 仍将打包进产物。
> fix(external): external compatible when react < 18

- packages/preset-umi/src/features/favicons/favicons.ts
一个 favicon 插件的 typo ，没有 `api.config.favicon` 这个东西。
这导致用户配了自己的 `favicons` ，还会收集 `src/favicon` ，这是不对的。
> fix(favicon): typo

- packages/renderer-react/src/routes.tsx
处理 Navigate 时有个误拼，传入 `<Navigate />` 中的参数应该为传入 `<NavigateWithParams />` 的原始参数 `props` 加上渲染后的 `to`，而不是 `params` 和 `to`。。。
> fix(renderer-react): propsWithParams should be {...props, to} , not {...params, to}

- packages/babel-preset-umi/src/index.ts
- packages/preset-umi/src/commands/dev/getBabelOpts.ts
- packages/preset-umi/src/registerMethods.ts
- packages/preset-umi/src/types.ts
- packages/preset-vue/src/features/default.ts
babel 配置支持自定义解 老项目使用 TS 尖括号断言导致的编译错误
- babel-preset-umi  移除 vue 特有配置
- preset-umi 支持自定义babel 预设配置
- preset-vue 传入vue 特有预设配置
增加 `modifyBabelPresetOpts` 的 原因是 想在 支持时自定义这个配置(之前计划想实现 vue jsx 支持会需要, 或者一些vue 独有但是react 不需要的配置)
> feat(preset-umi): babel preset config support custom

- packages/preset-umi/src/commands/verify-commit.ts
在 `package.json` 配置 `gitHooks` 时报错，`msgPath is required`
```json
"gitHooks": {
"commit-msg": "umi verify-commit"
}
```
> feat: verify commit support git hooks

- packages/bundler-webpack/src/build.ts
- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/dev.ts
- packages/preset-umi/src/commands/dev/dev.ts
在 tnpm 安装的项目中，自动根据项目的依赖扫描 link 的本地 NPM 包，避免 tnpm 的 node_modules 目录结构导致 webpack 缓存序列化 OOM
> feat: auto-generate snapshot paths from pkg deps for tnpm project

- docs/docs/api/api.md
- docs/docs/introduce/upgrade-to-umi-4.md
目前设计的是import { history } from 'umi';用来做命令式路由跳转，这里面的获取的信息就没有价值了吗。uselocation和window.location获取location信息。以前堆栈长度那些怎么获取呢
> docs: history

- packages/bundler-webpack/src/plugins/RuntimePublicPathPlugin.ts
修复 `runtimePublicPath` 注入代码在旧版本浏览器上的兼容性，`globalThis is not defined`
> fix(bundler-webpack): runtimePublicPath compatibility

- packages/plugins/src/antd.ts
修复 antd 插件通过 `UMI_PLUGIN_ANTD_ENABLE` 环境变量开启时，用户的配置会被强制覆盖的问题
> fix(plugins): antd user config be overwritten by env config

- packages/bundler-utils/src/https.ts
Change `mkcert --version` to `mkcert -help`  for checking if mkcert is installed, cause `mkcert --version` not exists in Linux.
> fix(bundler-utils): change `mkcert --version` to `mkcert -help`

- packages/plugins/package.json
- pnpm-lock.yaml
7.0.1-beta.20 以及之前的版本 导出的 type 名为 `BasicLayoutProps`
```ts
export type { FooterProps, PageContainerProps, TopNavHeaderProps, ProLayoutProps as BasicLayoutProps, RouteContextType, HeaderProps, SettingDrawerProps, SettingDrawerState, };
```
7.0.1-beta.21 之后去掉了 `as BasicLayoutProps` 才和 layout.ts 插件的导出类型一致
> chore(plugin): ⬆️ update pro-layout to  7.0.1-beta.28

- docs/docs/tutorials/getting-started.md
- packages/create-umi/src/index.ts
- packages/create-umi/templates/app/.npmrc.tpl
- packages/create-umi/templates/max/.npmrc.tpl
- packages/create-umi/templates/max/package.json.tpl
- packages/create-umi/templates/plugin/.npmrc.tpl
- packages/create-umi/templates/vue-app/.npmrc.tpl
创建项目时，支持 `--no-install` 关闭自动安装依赖。
1. 新 feature ：支持自动 git init （可以 `--no-git` 关闭）。
**原因**：husky 必须要 git init 后才能用，否则 install 会报错，fix #8681 
2. 在 monorepo 中创建子项目，这和项目根目录有关，所以默认关闭 husky 。
1. monorepo 里创建子项目，应该把 `.npmrc` 放到项目根目录（若没有则创建，若有则放弃）。
2. 使用 pnpm v7 时，需要额外的选项抑制 warning 。
-----
[View rendered docs/docs/tutorials/getting-started.md](https://github.com/MoeYc/umi/blob/fix/max-should-init-git/docs/docs/tutorials/getting-started.md)
> feat(create-umi): improve git and monorepo init project

- packages/bundler-utils/package.json
- pnpm-lock.yaml
升级 esbuild 到 0.14.49，解 esbuild 压缩代码后插入 helpers 导致全局变量污染的问题，0.14.46 开始会给压缩代码包裹 iife
> chore(bundler-utils): upgrade esbuild to 0.14.49

- docs/docs/api/runtime-config.md
resolve #8653
键写错了，应该和 react router v6 一致。
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/MoeYc/umi/blob/docs/path-routes-code/docs/docs/api/runtime-config.md)
> docs: patchClientRoutes params

- packages/plugins/libs/locale/localeExports.tpl
workaround 修复 locale 插件 exports 循环依赖有几率导致 fast-refresh 运行时报错的问题，真实原因待排查
> fix(plugins): workaround for circular dep in locale plugin

- packages/bundler-utils/src/https.ts
修复当用户传了 `key, cert` 后还继续检查 `mkcert`
> fix(bundler-utils): resolveHttpsConfig support user config

- docs/docs/api/runtime-config.md
resolve #8724
umi 不自带 `getInitialState` ，这部分内容补充完全。
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/MoeYc/umi/blob/docs/initial-state-docs/docs/docs/api/runtime-config.md)
> docs: initial state supplement

- packages/plugins/src/locale.ts
Close #8751
该问题是因为reexport的时候用了文件名，这导致了 ts 类型的丢失。修改方法是将文件名改成模块名。并不是纯类型的导出，故不需要 .d.ts
> fix(plugins/locale): 修复国际化插件导出的 api ts类型失效的bug

- package.json
- pnpm-lock.yaml
> chore: upgrade father for persistent cache

- packages/plugins/src/tailwindcss.ts
Close #8771 
当使用 `plugin-tailwindcss` 时，如果指定 `APP_ROOT` 到子目录，设置中的 `content` 无法正确解析使用的 classnames
解决方法：在 tailwindcss 插件启动子进程时，指定 `cwd` 到 `process.env.APP_ROOT || api.cwd`
> feat(plugin-tailwindcss): Add support for using APP_ROOT with tailwind plugin

- packages/bundler-webpack/src/config/compressPlugin.ts
- packages/bundler-webpack/src/utils/getEsBuildTarget.test.ts
- packages/bundler-webpack/src/utils/getEsBuildTarget.ts
resolve #8744
默认的 esbuild js minify 不支持 ie 作为 target ，提示用户应该使用 terser 。
> chore(jsMinifier): ie is not supported esbuild tips

- docs/docs/api/config.md
- packages/preset-umi/src/commands/verify-commit.ts
resolve https://github.com/umijs/umi/issues/8709
1、scope不区分大小写
2、`git revert` `git merge` 和 `changesets` 产生的 commit message 默认通过校验
3、文档标示scope默认值
-----
[View rendered docs/docs/api/config.md](https://github.com/zzcan/umi/blob/feat/verifyCommit/docs/docs/api/config.md)
> feat: add verify-commit rules

- packages/umi/package.json
修复 Umi 3 项目在 `umi dev` 时 `@umijs/utils` 可能拿到错误的 `@umijs/babel-preset-umi` 版本导致启动失败的问题，比如项目中存在 father 4 时
> 为什么不直接给 `@umijs/utils` 声明 `@umijs/babel-preset-umi`？
因为 `@umijs/babel-preset-umi` 也依赖 `@umijs/utils`，避免出现循环依赖；`umi` 是 `@umijs/utils` 的父级包、也是引发错误的命令起点，所以在父级包声明
> fix(umi): utils resolve wrong babel preset when dev

- docs/docs/max/i18n.md
null
-----
[View rendered docs/docs/max/i18n.md](https://github.com/juetan/umi/blob/patch-1/docs/docs/max/i18n.md)
> docs: props should be wrapped with {} instead of () in umi max i18n example

- packages/server/src/Server/Server.ts
一种场景是服务端设置了cors允许固定域名跨域后，本地没有通过修改host模拟域名，而是使用proxy解决跨域，配置成功后后仍然报403错误。
解决方案参考CRA项目下issue
[#5441](https://github.com/facebook/create-react-app/issues/5441#issue-370191452)
> fix(server): proxy throw error 403

- packages/core/src/route/routesConfig.test.ts
- packages/core/src/route/routesConfig.ts
fix #8787
父路由结尾是通配符 `*` 时，子路由的路径应该是 `path: '*'` ，而 `path: ''` 无法匹配上。
> fix(route): path ends with `*` children should inherit `*`

- docs/docs/api/runtime-config.md
- packages/plugins/libs/qiankun/master/types.ts
- packages/plugins/src/dva.ts
- packages/plugins/src/initial-state.ts
- packages/plugins/src/layout.ts
- packages/plugins/src/qiankun/master.ts
- packages/plugins/src/qiankun/slave.ts
- packages/plugins/src/request.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/defineApp.tpl
- packages/preset-umi/templates/plugin.tpl
- packages/umi/src/constants.ts
- packages/umi/src/index.ts
实现思路：
插件约定输出一个 `runtimeConfig.d.ts` 作为插件的运行时配置
通过动态生成 `defineApp` ，使用交叉类型合并所有插件导出的运行时配置
修改点：
1，为自带的 layout、dva、qiankun 添加` runtimeConfig.d.ts `生成逻辑
2，在 tmpFile 中生成 `defineApp`，添加了一个 `defineApp.tpl `用于生成代码
3，修改了 `plugin.tpl`，添加了一个 __defaultExport 用于处理 `export default `的场景
4，【文档】添加 defineApp 使用指引
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/umijs/umi/blob/mr/master/define_app/docs/docs/api/runtime-config.md)
> feat: add defineApp

- packages/bundler-webpack/src/dev.ts
fix #8796
mfsu 应该处理配置的 `extraBabelIncludes` ，否则 mfsu 打包时无法对 `node_modules` 里的源码进行 auto css module。
> fix(mfsu): babel should transform `extraBabelIncludes`

- packages/bundler-webpack/src/plugins/RuntimePublicPathPlugin.ts
修复 runtimePublicPath 里对 `globalThis` 的判断
ref: #8650
> fix(bundler-webpack): globalThis check logic

- packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
更新 mfsu 的 babel-preset-env 配置，消除 babel 抛出的配置不兼容警告：
> fix(preset-built-in): babel warn from mfsu

- docs/docs/api/api.md
- packages/renderer-react/src/index.ts
部分情况下需要在程序中手动渲染带参数的路由，在 react router v6 中，需要通过 generatePath 方法来实现。
当前版本的 umi 并未导出该函数，这里补充上。
-----
[View rendered docs/docs/api/api.md](https://github.com/ye-will/umi/blob/master/docs/docs/api/api.md)
> feat(renderer-react): export generatePath from react-router-dom

- packages/plugins/libs/qiankun/master/common.ts
修复 qiankun 动态插入的重定向路由不生效的问题（燕鸥站点场景）
> fix(plugins): patched redirect routes not working in qiankun

- packages/preset-umi/src/features/mock/getMockData.ts
- packages/preset-umi/src/features/mock/mock.ts
Close #8889 
- 解决 demo例子里： 更改name的值，需要改2次，才有第一次更改的数据，延迟了一次的问题。
- 解决 demo例子里：引用CustomData['/api.php']时，标识重复mock路由，改用exclude: ['mock/custom-data/**']后正常，并保证watch时，热更新正常，watch时，不要排除exclude，只在normalizeMockFile入口方法排除exclude，现在mock逻辑和umi3基本一致
> fix: mock bug

- packages/preset-umi/src/commands/dev/createRouteMiddleware.ts
- packages/preset-umi/src/commands/dev/getAssetsMap.ts
- packages/preset-umi/src/features/configPlugins/schema.ts
1. 4.0.9 的时候有一个 [PR](https://github.com/umijs/umi/pull/8647) 优化了 umi.css 的顺序，但是 js 的顺序仍然是放到前面，也会有问题，在 3.x  的时候主文件也是一直是注入到最后的
2. `publicPath` 设置为 'auto' 后，加载 chunk 文件会根据当前的主文件 host 去匹配，这一点在前后端分离并区分CDN环境的情况下非常有用，webpack 也很早就支持了 [Automatic publicPath](https://webpack.js.org/guides/public-path/#automatic-publicpath)
> feat: 支持配置 publicPath 为 auto

- packages/plugins/src/request.ts
需要能够获取axios request 的instance，方便动态加载一些拦截器
> fix: export getRequestInstance

- scripts/bootstrap.ts
使用bootstrap创建子包后运行`npm run build`没有反映
package里用了father命令，单目录缺少father配置文件
在bootstrap阶段生成father配置文件
> chore: fix bootstrap script

- packages/create-umi/templates/max/mock/userAPI.ts
Bug Description：create-umi创建的ant design pro模板项目中，用户选择 CRUD示例 - 查询表格的某一个复选框，会同时选择全部的行，而selectedRowsState只有一条数据。
Reason：查询表格table以id为key，但mock数据中没有id，因此导致混乱。
Solution: 给mock数据加上id。
> fix(create-umi/template): add missing id in mock data.

- packages/plugin-run/package.json
- packages/plugin-run/src/index.ts
- packages/preset-umi/package.json
- packages/preset-umi/src/index.ts
- pnpm-lock.yaml
一些改动，
* 内置到 preset-umi
* 支持 js
* 用 import 的方式引入原 script，避免 script 相对依赖的路径问题
* 临时文件的路径改到 node_modules/.cache 下
cc @txp1035
> chore: improve @umijs/plugin-run

- packages/preset-umi/src/features/legacy/legacy.ts
1. legacy 配置兼容插件打开的场景 from @xiaohuoni 
2. webpack chain 没有返回值 from @xierenyuan
> fix(legacy): webpack chain return value and config scene

- examples/boilerplate-vue/.umirc.ts
- examples/boilerplate-vue/app.tsx
- examples/boilerplate-vue/layouts/index.vue
- examples/boilerplate-vue/pages/docs.vue
- examples/boilerplate-vue/pages/users/login.vue
- packages/preset-vue/src/features/tmpFiles/tmpFiles.ts
解决路由未设置 component 时编译错误 
现在的 空路由使用的是 jsx 语法 目前不支持, 修改成手动创建 vnode
> fix(renderer-vue): fix empty route parsing error if component is not set

- packages/bundler-webpack/src/config/assetRules.ts
- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/config/javaScriptRules.ts
修复编译 `.cjs` 后缀的模块时、将其处理为静态资源的 bug；比如 [@opensumi/ide-extensions](https://unpkg.com/browse/@opensumi/ide-extension@2.19.9/lib/common/vscode/converter.js) 只有 cjs 产物，产物里 require 了 [marked](https://unpkg.com/browse/marked@4.0.19/package.json)、使用了它 `.cjs` 后缀的产物，Umi 在编译后者时就会将其处理为静态资源而不是一个模块
> fix(bundler-webpack): compile cjs module as a wrong asset

- packages/plugins/package.json
- packages/plugins/src/antd.ts
- packages/plugins/src/layout.ts
- pnpm-lock.yaml
做了以下几件事情
- antd@5 的情况下关掉 babel-import
- 如果用了 antd@4 但是用了 antd@5 ，导入以下 antd.less
- 如果用了 antd@5，为less 提供默认变量，防止项目挂掉
- 如果antd@5 ，删除代码 layout 的  less 导入
> feat(antd): support antd@5

- packages/core/src/service/service.ts
```bash
dev, prod, test config files will be auto loaded by env, Do not configure process.env.umi_ENV with these values
```
> fix: umi_ENV > UMI_ENV

- packages/core/src/service/service.ts
原因是 ant-design-pro 默认用了 UMI_ENV=dev，影响面比较大。
> fix: revert UMI_ENV limit

- docs/docs/api/config.md
- packages/preset-umi/src/features/legacy/legacy.ts
1. fix #9124
2. `nodeModulesTransform` : 支持关闭 `node_modules` 转换，反向自己添加需要 `extraBabelIncludes` 的包。 from @xiaohuoni 
-----
[View rendered docs/docs/api/config.md](https://github.com/MoeYc/umi/blob/fix/ie-11-core-js/docs/docs/api/config.md)
> fix(legacy): not transform polyfill for ie11

- packages/bundler-esbuild/src/types.ts
- packages/bundler-vite/src/types.ts
- packages/bundler-webpack/src/types.ts
支持相同 babel plugin 第三个参数（实例 id） 的配置，babel-plugin-import 中经常会用到
```ts
{
plugins: [
['babel-plugin-import', { libraryName: 'components-a' }, 'components-a'],
['babel-plugin-import', { libraryName: 'components-b' }, 'components-b']
]
}
```
https://babeljs.io/docs/en/configuration#pluginpreset-merging
https://www.npmjs.com/package/babel-plugin-import
> fix: IBabelPlugin type

- packages/plugin-run/src/index.ts
> fix(run): tsx bin path

- packages/bundler-webpack/src/server/server.ts
- packages/bundler-webpack/src/types.ts
1. 修复 #8639 支持数组形式 proxy 的类型定义，避免 `defineConfig` 报错
2. **[注意]** 修正 `proxy.onProxyReq` 的调用参数，把 proxy 传入以符合它需要的参数类型
> fix(bundler-webpack): type definition of proxy config

- packages/plugin-docs/package.json
- pnpm-lock.yaml
plugin 中的 client  部分需要 classnames 
之前没有发现是因为影子依赖了。（比如已经安装了 antd，包管理做了提升）
> fix(plugin-docs): 🐛 mv classname to dep

- packages/bundler-webpack/src/config/config.ts
- packages/preset-vue/src/features/config/config.ts
> perf: change webpack hash function to improve speed of hash calculation

- packages/preset-built-in/package.json
fix: bump mime to 1.4.1 to fix CVE-2017-16138
Close https://github.com/umijs/umi/issues/8528
> fix: mime模块拒绝服务漏洞 - mime@1.3.6 - 间接引入

- packages/preset-built-in/package.json
bump ansi-html to ^0.0.8
fix CVE-2021-23424
> fix: bump ansi-html to ^0.0.8

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
修复 `.umirc.ts` 文件中没有智能提示
Close: https://github.com/umijs/umi/issues/9170
> fix: include umirc

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
https://github.com/umijs/umi/pull/9246 只包含了`.umirc.ts`，导致 tsconfig.json 无法正确发现其他的 `.ts(x)` 文件。。。
现在使用 `create-umi@latest` 新建工程的话，源文件中全是报错。。。
> 修复 tsconfig.json 的文件 include 问题

- docs/docs/max/request.md
`message.error('Response status:', error.response.status);` 这样会导致提示只显示：`Response status：`，而且还不能正常自动关闭。
-----
[View rendered docs/docs/max/request.md](https://github.com/hqwlkj/umi/blob/patch-4/docs/docs/max/request.md)
> doc(request): 修改 message.error 不能自动关闭的问题。

- docs/docs/max/request.md
https://umijs.org/docs/max/request
中文文档的Umi Max模块的request引用缺少单引号，原文如下
**_通过 import { request } from '@@/plugin-request 你可以使用内置的请求方法_**
'@@/plugin-request 缺少反单引号
-----
[View rendered docs/docs/max/request.md](https://github.com/YqxLzx/umi/blob/fix_documentText/docs/docs/max/request.md)
> docs:中文文档的Umi Max模块的request引用缺少单引号

- packages/preset-umi/templates/history.tpl
回退到原来的代码，并加上丢失的 getter 。
这个地方改 `history.push` 其实是改了引用，`h` 也被影响了，这样是不对的。会导致内部 `navigate` / `Link` 等多一层 basename 。
根本原因是解构拷贝的时候把 [getter](https://github.com/remix-run/history/blob/3e9dab413f4eda8d6bce565388c5ddb7aeff9f7e/packages/history/index.ts#L530-L535) 弄丢了。。。
花了三个小时才发现 🤯
fix #9209 
fix #9287
> fix(history): push and replace patch with getter

- packages/bundler-webpack/src/config/javaScriptRules.ts
Webpack 默认使用软链接解析后的地址、但 `extraBabelIncludes` 自动生成的 include 使用了软链接之前的地址（`resolve` 这个包的 `preserveSymlink` [默认值为 `true`](https://github.com/browserify/resolve#resolveid-opts-cb)），导致`extraBabelIncludes` 配置项不生效
> fix(bundler-webpack): `extraBabelIncludes` not working with tnpm

- packages/plugin-docs/client/theme-doc/Search.tsx
> fix: 文档搜索结果不能滚动

- packages/utils/src/Generator/Generator.ts
修复 @umijs/utils 中 Generator 的 prompts 无法取消, 现在cmd+c中断还会copy模版文件
> fix: 修复prompts无法cancel

- packages/plugin-docs/client/theme-doc/tailwind.css
修复文档页面的`layout shift`问题
原因是异步chunk执行之前滚动条消失
> fix: fix doc page layout shift

- packages/core/src/config/config.ts
16.9.0 之前的 node 版本，不支持 cause ，所以真实的 error 打印不出来。
如果16.9.0 之前的直接抛错到下游。
```text
> max  dev
info  - @local
fatal - Error: code error
at Object.<anonymous> (/Users/umi/git/umi-playground/.umirc.ts:34:7)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Module._compile (/Users/umi/git/umi-next/packages/utils/compiled/pirates/index.js:1:1668)
at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Object.newLoader [as .ts] (/Users/umi/git/umi-next/packages/utils/compiled/pirates/index.js:1:1684)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:93:18)
at Function.getUserConfig …
```
> refactor: 🎨 node version < v16.9.0 , show config error directly

- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/dev.ts
why：解决切换配置时仍然需要删除 cache 目录的问题
mfsu.normal cache 路径  node_modules/.cache/bundler-webpack/default-development/
mfsu.eager   cache 路径  node_modules/.cache/bundler-webpack/eager-development/
cache name 规则 ref：https://webpack.js.org/configuration/cache/#cachename
为什么依赖构建不改
* 两种模式下，mf 的 exposes 的配置会有不同
* 两种模式下，重新构建的策略不同，不会相互影响
> refactor: 🎨 mfsu.eager 情况下项目代码构建使用不同的 cache 路径

- packages/plugins/src/qiankun/slave.ts
当 tern 应用启动 mfsu eager 的配置下，原先的主线程获取配置是 slave 的环境变量没有生效，所以未修改 mfName 值
当 编译构建 worker 线程启动时，环境变量已经生效，salve 插件又修改了 mfName 为 mf_{pkg.name}
那么主线程构建的应用 使用 mf 远端名称，远端应用使用的是 mf_{pkg.name} 导致加载失败。
最终配置  会使用 config 和 default config 合并，所以将 mfName 修改的行为放到 modifyDefaultConfig 中，这样主线程和 work 线程配置就一致了。
> fix: 🐛 move mfsu.mfName  modify to defaultConfigModify hook

- packages/mfsu/src/dep/dep.ts
- packages/mfsu/src/mfsu/mfsu.ts
```bash
error - Can not resolve dependence : 'lodash.sample', please install it
error - [MFSU][eager] build failed AssertionError [ERR_ASSERTION]: dependence not found: lodash.sample
at Dep.buildExposeContent (/Users/umi/git/umi-next/packages/mfsu/dist/dep/dep.js:73:31)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async DepBuilderInWorker.writeMFFiles (/Users/umi/git/umi-next/packages/preset-umi/dist/commands/dev/depBuildWorker/depBuilder.js:131:23)
at async DepBuilderInWorker.build (/Users/umi/git/umi-next/packages/preset-umi/dist/commands/dev/depBuildWorker/depBuilder.js:102:7)
```
```bash
error - MFSU dist file: /Users/umi/git/umi-playground/node_modules/.cache/mfsu/mf-va_remoteEntry.js not found
error - MFSU latest build error  AssertionError …
```
> feat(mfsu): ✨ MFSU 因为依赖缺失 报错优化

- packages/bundler-webpack/src/dev.ts
change cache path  when mfsu.eager
dont overwrite config name
```bash
$ls .cache/
.
..
bundler-webpack
bundler-webpack-eager
logger
mfsu
mfsu-deps
```
```text
event - [Webpack] Compiled in 19630 ms (7395 modules)
wait  - [Webpack] Compiling...
event - [MFSU][eager] start build deps
info  - [MFSU] skip buildDeps
event - [Webpack] Compiled in 1259 ms (7225 modules)
wait  - [Webpack] Compiling...
event - [MFSU][eager] start build deps
info  - [MFSU] skip buildDeps
event - [Webpack] Compiled in 920 ms (7225 modules)
```
> fix: 🐛 恢复项目编译webpack 日志 name 为 “Wepack”

- packages/mfsu/src/depInfo.ts
- packages/mfsu/src/staticDepInfo/staticDepInfo.ts
如果 JSON 文件损坏，直接使用一个空对象作为依赖信息；根据扫描结果重新构建依赖
**不能** 简单的用空对象替代解析结果；如果使用空对象，项目代码编译时有缓存，只能分析到部分项目代码，所以收集到的依赖是不完整的。因此构建出来的依赖MF 模块也是不完整的。
因此，日志打 ERROR 提示 删 .cache, 透传 error 。
> fix(MFSU): 🐛 修复 cache 解析错误

- examples/with-dva/models/count.ts
- packages/plugins/src/dva.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
增加导出类型 `ConnectProps`，`ConnectRC`，`Reducer`，`Effect`，`SubscriptionsMapObject`，`DvaModel`
用例：
```ts
import type { DvaModel } from 'umi';
export interface CountModelState {
num: number;
}
const CountModel: DvaModel<CountModelState> = {
namespace: 'count',
state: {
num: 0,
},
reducers: {
add(state: any): any {
state.num += 1;
},
},
effects: {
*addAsync(_action: any, { put }: any) {
yield put({ type: 'add' });
},
*throwError(_action: any) {
throw new Error('effect error');
},
},
};
export default CountModel;
```
Closes:  https://github.com/umijs/umi/issues/8638 https://github.com/umijs/umi/issues/9355
> feat: add dva types

- packages/preset-umi/src/features/configPlugins/configPlugins.ts
> feat(preset-umi): ignoreMomentLocale enabled by default

- packages/mfsu/src/babelPlugins/awaitImport/MFImport.ts
- packages/mfsu/src/mfsu/strategyStaticAnalyze.ts
- packages/mfsu/src/staticDepInfo/simulations/babel-plugin-import.test.ts
- packages/mfsu/src/staticDepInfo/simulations/babel-plugin-import.ts
- packages/preset-umi/src/features/configPlugins/configPlugins.ts
- packages/preset-umi/src/libs/folderCache/AutoUpdateSourceCodeCache.ts
1. 修复 eager 模式下 chunkName 不生效的问题（使用 stringLiteral 替换参数，参数的注释就被无意的删除了; 这个场景下直接修改 value 更加合理
2. 默认开启 eager 模式，修复 windows 路径问题
3. 调优文件等待参数
> fix(mfsu-eager): 🐛 默认开启 mfsu eager 模式

- packages/renderer-react/src/link.tsx
修复`Link`组件透传`prefetch`导致的warning
> fix Link warning

- packages/preset-umi/src/features/tmpFiles/routes.ts
修复从隐藏目录下引入路由组件会产出隐藏 chunk 产物的问题，比如 dumi 的 `.dumi/theme/layouts` 下可能会有路由组件
> fix(preset-umi): unexpected hidden route chunk from hidden dir

- docs/docs/max/antd.md
- packages/plugins/src/antd.ts
antd 插件支持配置 v5 版本的 theme token
-----
[View rendered docs/docs/max/antd.md](https://github.com/umijs/umi/blob/feature/antd-v5-theme/docs/docs/max/antd.md)
> feat(plugins): support antd v5 theme token for antd plugin

- examples/with-request/readme.md
I'm lost when migrate v3 to v4, especially **useRequest**. Helpfully I found the example here.
And I found a small mistake in readme that might mislead newbies
-----
[View rendered examples/with-request/readme.md](https://github.com/wujunyi792/umi/blob/fix-example/examples/with-request/readme.md)
> fix: example README

- packages/preset-umi/package.json
- packages/preset-umi/src/features/appData/appData.ts
- packages/preset-umi/src/features/overrides/overrides.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/src/index.ts
- pnpm-lock.yaml
支持约定式的 `overrides.less`，不同于 `global.less`，它的所有选择器会被自动提升优先级，以确保即便在路由按需、存在异步 css chunk 的情况下，也能达到覆盖样式的效果
close #8326
> feat: conventional overrides.less to override 3rd-party styles

- packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl
`useMatch` might returns 'null' which will cause a crash
> fix: fix useMatch empty return

- packages/umi/deps.d.ts
- packages/umi/deps.js
- packages/umi/package.json
将 Bigfish 依赖的 desp 单独导出，实现 Bigfish 只依赖 umi 不依赖其他子包
> feat(umi): export deps that bigfish depend on

- codecov.yml
- packages/mfsu/src/staticDepInfo/staticDepInfo.ts
原先以为 alias 和 external 会影响 代码依赖而的扫描结果，就没加。
在查内部 marked external 方式的时候发现，调整 external 不使用 script 的方式后，期望重新构建依赖，但是没有。
参考 mfsu normal 增加 cachedepencies 来修复此缺陷
> fix(mfsu.eager): 🐛  mfsu.eager  缓存增加 cache dep 字段。

- package.json
- pnpm-lock.yaml
Turbo v1.6 大幅加快了缓存的读写，从而提升项目 build 和 ci 的执行速度。
See https://turborepo.org/blog/turbo-1-6-0
> dep: upgrade turbo to v1.6

- packages/preset-umi/src/features/overrides/overrides.ts
改用 body 提升 overrides.less 里的样式优先级，解决 antd 动态插入到 body 下的 DOM 不受覆盖影响的问题
> fix(preset-umi): overrides.less not working for antd dynamic dom

- docs/docs/max/analytics.md
- packages/plugins/src/analytics.ts
- packages/server/src/server.ts
- 支持 GA 4 最新版本谷歌统计。（ resolve #9654 ）
- 修复输出 html 标签时，值为 `false` 的属性还被输出 （ 如：`async="false"` 本质上还是 `async` ）。  （ fix #9626 ）
-----
[View rendered docs/docs/max/analytics.md](https://github.com/MoeYc/umi/blob/chore/221031/docs/docs/max/analytics.md)
> feat(analytics): support ga4

- docs/docs/api/config.md
- packages/preset-umi/src/features/404/404.ts
- packages/preset-umi/src/features/exportStatic/exportStatic.ts
1. `exportStatic` 支持 `extraRoutePaths` 配置项，值可以是 `string[]` 或返回 `string[]` 的函数
2. 修复约定式 404 的 route 对象里 `absPath` 不正确的问题
3. `exportStatic` 支持将 `/*` 生成 `404.html`，多数静态站点托管服务会约定这个文件作为 404 页面
> feat: allow extraRoutePaths for exportStatic

- docs/docs/api/config.md
- packages/preset-umi/src/constants.ts
- packages/preset-umi/src/features/polyfill/polyfill.ts
1. 修复`umi build`时polyfill的`targets`为`undefined`的问题
这个问题也会导致`umi dev`时第二次编译的时候`mfsu` `buildDeps`
原因是第二次编译时`targets`已经被`bundler-webpack`修改为正确的`targets`
2. 修复文档，`targets` 默认是`{ chrome: 80 }`
-----
[View rendered docs/docs/api/config.md](https://github.com/2239559319/umi/blob/fix-preset-umi-polyfill-targets/docs/docs/api/config.md)
> Fix preset umi polyfill targets

- packages/preset-umi/src/features/crossorigin/crossorigin.ts
> fix(preset-umi): crossorigin config schema field error

- packages/bundler-utils/src/index.ts
效果对比：
parse before: 
parse after: 
transform before: 
transform after:
> fix: 优化 parse 出错提示

- packages/bundler-vite/src/config/transformer/react.ts
删除`@vite/plugin-react`的`include`属性，这个属性是过滤使用`fast Refresh`的文件
这里使用了这个属性并使用了vite会导致vite的热更新失效。
```ts
import { defineConfig } from 'umi';
export default defineConfig({
npmClient: 'yarn',
extraBabelIncludes: [
'debug',
],
vite: {}
});
```
以上配置会使vite的热更新失效全是`full-reload`
> fix: remove include config of @vite/plugin-react

- packages/preset-umi/src/features/exportStatic/exportStatic.ts
修复 404 页面预渲染的时候传入 `/*` 路由，导致路由匹配失败、预渲染结果为空的问题
> fix(preset-umi): pre-render failed for 404 page

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
使用 appData 上的 appJS 路径而不是单独获取，这样可以允许插件修改 appJS 的路径
> refactor(preset-umi): allow modify appjs path

- docs/docs/api/api.md
- packages/preset-umi/templates/server.tpl
- packages/renderer-react/package.json
- packages/renderer-react/src/index.ts
- packages/renderer-react/src/server.tsx
- packages/server/src/ssr.ts
- pnpm-lock.yaml
react ssr 支持渲染 helmet 添加的标签，比如用于 tdk 生成，关键变更：
1. renderer-react 内置 `react-helmet-async`、以兼容 react@18 流式渲染，导出 `Helmet` 给页面使用
2. ssr 阶段自动收集 helmetContext 里的数据、转换成 `head` 下的标签内容（比如 title、meta 等），实现 helmet 的 ssr 支持
> feat(preset-umi): react ssr support helmet tags

- packages/preset-umi/src/features/tmpFiles/routes.ts
使用 tnpm 安装依赖、且使用了 `node_modules` 下的文件作为路由组件的情况下，会生成带 `@` 的无效 chunk name，比如：
```bash
node_modules__dumi@2.0.0@dumi_dist_xxx.async.xxx.js
```
> fix(preset-umi): invalid chunk name when use tnpm

- packages/renderer-react/src/browser.tsx
修复使用了内置的 `Helmet`、导致 client 渲染失败的问题
> fix(renderer-react): client render failed when use builtin helmet

- docs/docs/max/access.md
modify `useAcces` to `useAccess`
-----
[View rendered docs/docs/max/access.md](https://github.com/learnsomesome/umi/blob/patch-1/docs/docs/max/access.md)
> docs: Modify the spelling of useAcces

- packages/preset-umi/src/features/tmpFiles/routes.test.ts
- packages/preset-umi/src/features/tmpFiles/routes.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
1. 移除 `code/route.ts` 中 `routes` 对象里的 `file` 字段，避免磁盘路径被打进产物
2. 移除原来处理 `api.addLayouts` 里 `file` 字段的逻辑
> refactor(preset-umi): discard file field for client routes

- packages/preset-umi/src/features/exportStatic/exportStatic.ts
修复 Helmet head 标签在 SSR 下丢失的问题
后续优化：把 markupGenerator 的返回值做拓展，正则匹配不稳定
> fix(preset-umi): helmet head lost after ssr

- packages/mfsu/src/mfsu/mfsu.test.ts
- packages/mfsu/src/mfsu/mfsu.ts
fix: #9785 
改动点：
1. 如果 webpack 配置中没有指定 `output` 或者 `output.publicPath`，则设置为 `'/'`
2. 对使用函数形式的 `publicPath` 进行提示（不确定这样提示是不是友好）
> fix: add default publicPath

- did-you-know/package.json
- docs/docs/guides/generator.md
- packages/preset-umi/src/commands/generators/precommit.ts
- packages/preset-umi/src/index.ts
添加微生成器-precommit
-----
[View rendered docs/docs/guides/generator.md](https://github.com/wyy0512/umi/blob/feat/generators-precommit/docs/docs/guides/generator.md)
> feat(preset-umi): add precommit generator

- docs/docs/guides/generator.md
- packages/preset-umi/src/commands/generators/api.test.ts
- packages/preset-umi/src/commands/generators/api.ts
- packages/preset-umi/src/commands/generators/component.test.ts
- packages/preset-umi/src/commands/generators/component.ts
fix #9780
大小写错误的问题，只需要提升首字母到大写。
-----
[View rendered docs/docs/guides/generator.md](https://github.com/MoeYc/umi/blob/fix/g-upper-case/docs/docs/guides/generator.md)
> fix(generator): component file name case

- examples/boilerplate-vue/.umirc.ts
- examples/boilerplate/.umirc.ts
- packages/preset-umi/src/features/configPlugins/schema.ts
> refactor: 🎨 base config valiate endsWith('/')

- packages/plugins/src/layout.ts
解决 pro layout 引用没有类型提示的问题。
fix #9374 
fix #9721 
fix #9733
> fix(layout): pro layout types declare

- packages/preset-umi/templates/umi.tpl
Close #9761
app.ts
```
import { history } from 'umi'
export function render(oldRender: any) {
console.log('history',history);
oldRender();
}
```
undefined
{createHref: ƒ, push: ƒ, replace: ƒ, …}
> fix: history is undefined on render

- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/dev.ts
why:
1. 源码依赖构建已经 serve 了public 下的静态资源，依赖构建就不需要重复 copy 了。
2. 避免新增 mfsu 的[中间件](https://github.com/umijs/umi/blob/bc95b76bac0b8b42e67f723509e25304d3541266/packages/mfsu/src/mfsu/mfsu.ts#L354-L356)兜底 serve  node_modules/.cache/mfsu/时， 拦截了 devServer 的 serve 和 其他 middleware。
> fix: 🐛 mfsu 依赖构建不使用 CopyPlugin

- packages/preset-umi/src/features/favicons/favicons.ts
如果设定了 `publicPath` ，也应该在带 `publicPath` 上提供 favicon 。
和这里保持一致：
https://github.com/umijs/umi/blob/47281f6dfa3de3a24bb8214cfbed83145190ed5c/packages/preset-umi/src/features/favicons/favicons.ts#L61-L69
> fix(favicon): intercept path should with public path

- packages/preset-umi/src/features/monorepo/redirect.ts
- packages/preset-umi/src/features/tmpFiles/routes.ts
路由文件 chunkName 的生成逻辑支持处理 monorepo 仓库中 root node_modules 里的路由文件，比如 dumi 默认的 Layout 有可能在根目录的 node_modules 内
> fix(preset-umi): route chunk compatible with monorepo root dep

- packages/preset-umi/src/features/codeSplitting/codeSplitting.ts
换掉 base64 中可能在 url 中被转义的字符。
resolve #9845
> fix(splitChunks): prevent escape of base64 chars

- packages/mfsu/src/dep/dep.ts
- packages/mfsu/src/dep/getExposeFromContent.ts
- packages/mfsu/src/depInfo.ts
- packages/mfsu/src/moduleGraph.test.ts
- packages/mfsu/src/moduleGraph.ts
1. Dep  新增  importer 字段，取值为 imprters 集合里面的第一个，获取依赖地址时，优先基于 cwd 来解析包地址，兜底用 `dirname(importer)` 。
2. normal 模式下依赖比较忽略 importer 字段，以避免额外的依赖构建
3. mf-va_*  模块使用依赖的<del>绝对路径 ，需要讨论这样的路径容易失效</del>；使用依赖的软链地址，避免升级物理文件地址不存在，导致编译错误。
> fix: 🐛 mfsu resovle in monorepo

- packages/mfsu/src/mfsu/strategyStaticAnalyze.ts
在 monorepo 的情况，webpack 会 监听在非常当前的源码目录的文件，这类文件不能进入，srcCache 的列表。
PS 
eager  模式下 monorepo 中的子包源码和所有依赖都会在 项目代码一起构建，mfsu 加速效果不佳。
close https://github.com/umijs/umi/issues/9752
> fix: 🐛 修复 monorepo 下非 src 下文件改动进入到代码列表

- docs/docs/api/plugin-api.md
- packages/preset-umi/src/types.ts
文档和类型定义都写了 `httpEquiv`。但实际在后面拼接 meta 的时候并没有处理 `httpEquiv` -> `http-equiv`。
如下：
```ts
api.addHTMLMetas(() => [
{
httpEquiv: 'cache-control',
content: 'no-cache',
},
{
'http-equiv': 'refresh',
content: '10000',
},
])
```
-----
[View rendered docs/docs/api/plugin-api.md](https://github.com/simonwong/umi/blob/feature/meta-http-equiv/docs/docs/api/plugin-api.md)
> docs(preset-umi,docs): modify metas type httpEquiv to http-equiv

- examples/boilerplate/app.tsx
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/TestBrowser.tpl
- packages/preset-umi/templates/umi.tpl
来自于 resolve #9761 的问题
umi v3 中的一个修改 render 入参的功能在 v4 中支持。
> feat: modifyClientRenderOpts

- packages/plugins/libs/qiankun/slave/lifecycles.ts
修复用 qiankun `MircroApp` 传入字符串 history 时，子应用没有转换导致 history 参数异常的问题
该转换在 Umi 3 时是支持的，改回去以解决父/子应用 history 类型不相同时渲染异常的问题
> fix(plugins): string history not working in qiankun slave

- scripts/bin/umi-scripts.js
> fix(script): script path may contain space

- packages/plugins/libs/qiankun/slave/lifecycles.ts
- packages/preset-umi/templates/umi.tpl
- packages/renderer-react/src/browser.tsx
1. 重新支持 render callback，用于支持 qiankun `MicroApp` 的 `onHistoryInit` 回调函数
2. 将 qiankun slave lifecycle 中的 callback 触发方式改回原样，实现精准触发
3. 将 qiankun slave lifecycle 中的 onHistoryInit 回调重新启用，实现子应用 history 回传，在海兔场景下需要它控制子应用页面切换
> feat: support callback for browser render

- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/config/speedMeasureWebpackPlugin.ts
fix #9897
解决 `mini-css-extract-plugin` 在和 speed measure 插件一起用会保存的问题。
FYI ：
- https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/167#issuecomment-1318684127
> fix(plugin): `mini-css-extract-plugin` with speed measure

- packages/lint/src/config/eslint/index.ts
- packages/lint/src/config/eslint/legacy.ts
- packages/preset-umi/src/features/polyfill/polyfill.ts
修复项目里存在 `.babelrc` 时 polyfill 可能生成不正确的问题
> fix(preset-umi): wrong polyfill when user put .babelrc

- .umirc.ts
- packages/mfsu/src/babelPlugins/awaitImport/checkMatch.test.ts
- packages/mfsu/src/babelPlugins/awaitImport/checkMatch.ts
使用 APP_ROOT 的方式会让 client.js  babel 编译两次，导致 react-error-overlay 依赖丢失
通过此 PR 解决类似多次编译的问题。
> fix: 🐛  src code compiled twice problme

- packages/ast/src/setConfigByName/setConfigByName.test.ts
- packages/ast/src/setConfigByName/setConfigByName.ts
- packages/preset-umi/src/commands/config/set.ts
why:
需要在测试中设置切换不同的 mfsu 配置
原来 ` max config  set  '{"strategy":"normal", esbuild:true}' `  会报错
> feat: ✨ umi config set 命令支持复杂 JSON 值

- packages/preset-umi/src/commands/config/config.test.ts
params from cli are all string type
> chore:  🐛 test case use the wrong param

- packages/plugins/src/utils/modelUtils.test.ts
- packages/plugins/src/utils/modelUtils.ts
fix sorting models by deps in plugin-model.
see also: [https://github.com/umijs/umi/issues/9837](https://github.com/umijs/umi/issues/9837)
> fix: sort models by deps

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
应该可以通过 `test: false` 关闭测试功能，此时不需要写入 export 。
> fix(test): not export component when test set false

- .github/workflows/ci.yml
- .github/workflows/compressed-size.yml
- .github/workflows/coverage.yml
- .github/workflows/doc.yml
- .github/workflows/e2e-basic.yml
- .github/workflows/e2e-boilerplate.yml
- .github/workflows/e2e-mfsu.yml
- .github/workflows/e2e-qiankun.yml
- .npmrc
- package.json
- pnpm-lock.yaml
前排感谢 [fz6m](https://github.com/fz6m) 大佬的 [提醒](https://github.com/umijs/umi/pull/9800#issuecomment-1326073435)。
1. 升级 pnpm 至 7.17.0
2. 指定 `auto-install-peers=false` (协商后不做指定，具体请见[下方对话](https://github.com/umijs/umi/pull/9853#discussion_r1032265744))
3. 更新即将废弃的 `::set-output` 的语法
4. 合并 pnpm 的缓存逻辑到 setup-node 中
---
如果有同学全局设置了 pnpm 的 `auto-install-peers` 为 `true`，会出现在本地和 CI 生成的 lockfile 会不一致的情况：
```bash
pnpm config set auto-install-peers true
```
举例来说，下面是 `packages/renderer-vue/package.json` 的内容：
```json
"dependencies": {
"@babel/runtime": "7.18.9"
},
"peerDependencies": {
"vue": ">=3.2.31",
"vue-router": ">=4.0.12"
}
```
对于上面这个包，设置 `auto-install-peers=true` 后，会把 `peerDependencies` 的依赖也安装上：
```diff
packages/renderer-vue:
specifiers:
'@babel/runtime': 7.18.9
+      vue: '>=3.2.31'
+ …
```
> chore: update pnpm version

- docs/docs/max/introduce.md
null
-----
[View rendered docs/docs/max/introduce.md](https://github.com/FriedRiceNoodles/umi/blob/master/docs/docs/max/introduce.md)
> fix(doc): 修复了文档站点中对国际化(多语言)的错误指向

- packages/ast/src/setConfigByName/setConfigByName.ts
close #9937
`setConfigByName` 的逻辑改动没和之前对齐，之前有大量非 `string` 的调用，这里尝试去字符串化 `value` 。
> fix(ast): try stringify config value

- packages/plugins/src/qiankun/slave.ts
process.env.PORT 可能取不到正确的端口，会导致302重定向异常（hostname:undefined），因此使用 api.appData.port 兜底。
> fix: process.env.PORT 可能取不到正确的端口

- packages/plugins/src/valtio.ts
可控的 break change，用户需要在配置里加 `valtio: {}`。
> feat(plugins/valtio): change enableBy to by config (breaking change)

- packages/bundler-utils/package.json
- packages/testing/package.json
- pnpm-lock.yaml
升级 esbuild 版本。
在 `0.15.18` 中有 1.7x 的性能提升。
- https://github.com/evanw/esbuild/releases/tag/v0.15.18
> dep: upgrade esbuild to `0.15.18`

- packages/plugins/libs/qiankun/slave/lifecycles.ts
修复 qiankun 子应用 `onHistoryInit` 传入的 history 不是应用 history 的 bug
> fix(plugins): wrong history from qiankun slave

- docs/docs/api/api.md
- packages/renderer-react/src/appContext.ts
- packages/renderer-react/src/index.ts
多次遇到有人提问：
1. 如何获取 `routes` 的自定义参数
2. 如何在 layout 里条件渲染
3. 如何查看当前所有命中的路由
故新增 `useSelectedRoutes` 来解决这些问题。
命名灵感来自于 https://beta.nextjs.org/docs/api-reference/use-selected-layout-segments
> feat: add `useSelectedRoutes`

- packages/preset-umi/src/commands/generators/jest.ts
why 
目前如果 jest.config.ts 中有错误，报错栈是在 jest 里面，不方便排查
解：
如果配置升级有错，打印错误栈。
> chore: 🎨 jest.config.ts 增加可追踪性

- packages/core/src/route/routesConfig.test.ts
- packages/core/src/route/routesConfig.ts
fix #10061
`absPath` 深层嵌套的用例没覆盖到。
> fix(route): `absPath` missing slash

- packages/bundler-webpack/src/dev.ts
昨天群里的问题，在插件里修改 `define` 时，mfsu 的缓存不会失效，导致还是上一次的数据。
> fix: mfsu cache invalid when define changes

- packages/bundler-esbuild/src/plugins/style.ts
close #10023
在 css 文件内使用内联图片的类型 loader ，需要补全一下。
> fix(esbuild): css file inline image url loader

- packages/bundler-webpack/src/types.ts
srcTranspiler类型错误导致配置的时候srcTranspiler类型提示为undefined
> fix(bundler-webpack type): wrong srcTranspiler type

- packages/plugins/src/antd.ts
1. antd 插件允许为 antd v5 开启 `import` 配置项，启用 babel-plugin-import 以节省编译开销
2. antd 插件不允许为 antd v5 指定 `style` 配置项，因为 antd v5 没有 style 文件
> refactor(plugins): allow import option for antd v5 in antd plugin

- packages/utils/src/isStyleFile.ts
vite 兼容引入的 `import.meta.xxx` 会导致 es-module-lexer 解析到 `undefined` 的 import 。
fix #10144
> fix(esbuild): `import.meta.x` parsed name undefined

- packages/bundler-webpack/src/dev.ts
- packages/mfsu/src/depInfo.ts
修复 getCacheDependency 内容包含 function 导致的缓存失效
mfsu 可以通过 `chainWebpack` 配置额外的 webpack 配置,  写缓存文件时 会忽略 function 导致缓存结果与实际配置永远不相等, 触发重新编译
> fix(mfsu): fix a cache failure caused by the getCacheDependency content containing a function

- packages/preset-umi/templates/TestBrowser.tpl
去掉 `<TestBrowser />` 的 polyfill 。
`<TestBrowser />` 带来了一个 `./core/polyill` 的入口，导致 ssr 在开发时会把这部分 corejs 的 polyfill 打包进去。
但是 core-js 含有在 nodejs 里无法使用的 polyfill （这里是 `core-js/modules/web.dom-exception.stack.js` ），导致 ssr 没法用了，类似的问题见 https://github.com/vuejs/vuepress/issues/3065 。
另外 `<TestBrowser />` 在本地 nodejs 里测试用，不需要 polyfill 。
> fix(ssr): corejs polyfill not available in nodejs

- packages/mfsu/src/mfsu/strategyStaticAnalyze.ts
- packages/mfsu/src/staticDepInfo/staticDepInfo.ts
- packages/preset-umi/src/libs/folderCache/LazySourceCodeCache.ts
如果  `npm link   ../pkg_a_src`,  修改 pkg_a_src 下的内容，期望 mfsu eager 不用加载和分析这个改动的文件的。
由于 webpack 的 bug ，会出发两个文件修改的事件 
1.   ./node_modules/pkg_a/src/index.ts （未过滤）
2.  ../pkg_a/src/index.ts  （过滤不关注）
未过滤的文件，fileCache 会加载失败
> fix: 🐛  mfsu 错误的去读取通过 npm link 过的包的源码文件

- packages/server/src/server.ts
修复在 Vite 模式下无法指定 script type 的 bug
背景：燕鸥场景下会插入一个 `type="tern-app-config"` 的 script，这个 script 会交给燕鸥服务端生成最终的 `tern-site-config`，如果标记为 `module` 就会被 Vite 处理成远程的临时 js，导致原有功能失效
> fix(server): specific script type not working for vite mode

- packages/create-umi/templates/max/package.json.tpl
create-umi脚手架创建max项目后，
package.json文件中的author字段与模版之间缺少一个空格，
如果在package.json修改某个字段后，commit提交会触发lint-staged中的"prettier --cache --write"逻辑，
由此而引发author会附带着这处commit信息
> style(create-umi): 🎨 author与模版之间增加空格

- packages/mfsu/src/depBuilder/depBuilder.ts
- packages/preset-umi/src/commands/dev/depBuildWorker/depBuildWorker.ts
- packages/preset-umi/src/commands/dev/depBuildWorker/depBuilder.ts
close https://github.com/umijs/umi/issues/10265
原先 worker builder 里面 onComplete 在 webpack 构建中，即使构建失败按照成功调用。导致下游的错误的写下 mfsu 缓存 （认为自己构建成功了）。
当项目安装缺失的依赖，代码未修改不满足重新构建的条件，继续使用构建失败产物。
* buildWithXXX 的实现中，只调用成功构建的 onComplete 回调
* 错误情况在 catch 中统一处理
* 调整消息结构，构建结束时只发一条消息, 通过消息内容表征构建是否成功
* 简化了日志输出，内部的采用 logger.debug
> fix: 🐛 修复 MFSU 提前生成 cache 文件的错误

- packages/preset-umi/src/features/exportStatic/exportStatic.ts
修复当 `publicPath` 设置为相对路径时，`exportStatic` 产出的资源引用路径错误的问题，原因是遍历处理 `markupArgs` 时原始对象被修改了
> fix(preset-umi): incorrect relative public path when export static

- packages/core/src/config/config.ts
- packages/core/src/types.ts
- packages/preset-umi/src/commands/build.ts
- packages/preset-umi/src/commands/dev/dev.ts
- packages/preset-umi/src/commands/setup.ts
- packages/preset-umi/src/features/appData/appData.ts
- packages/preset-umi/src/features/configPlugins/configPlugins.ts
- packages/preset-umi/src/features/icons/icons.ts
- packages/preset-umi/src/types.ts
fix #10137
这个解决方案的思路是：
1. 提供一个 `api.refreshRoutes` 方法，和 `appData` 的逻辑在一个文件方便管理，以后如果有任何刷新 routes appData 的需求都可以用这个方法。
2. 用户 `routes` 的配置变化时，触发函数，先 `api.refreshRoutes` 刷新 routes 数据，再重新生成临时文件，不需要 restart dev server 。
> fix: refresh `appData.routes` when config routes change

- packages/bundler-webpack/package.json
- pnpm-lock.yaml
why? 
---
from @fz6m 
现状就是 react-error-overlay 没法用了，控制台报错 process undefined。
看了下，这个问题前年就有了，我也不用 react-error-overlay ，不太晓得这个问题：
https://github.com/facebook/create-react-app/issues/11773
https://github.com/facebook/create-react-app/issues/12212
CRA 官方摆烂了，最新版本也是去年 4 月的，都快 1 年没更新了，一些网上的解法：
https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined
目前社区里看起来靠谱的解法是回退到 6.0.9 ，问题的原因是 6.0.10 开始 CRA 把构建工具换成 webpack5 了，但是没配 webpack5 的 node polyfill （webpack 5 开始不包含 polyfill），导致 process 被原模原样输出来了。
还有一个可能的解法，参考：https://github.com/facebook/create-react-app/pull/11799 ，自己 fork 改一下 webpack 配置自己构建一份 react-error-overlay ，但我觉得他这个 PR 有点小问题，process 用 process/browser.js 感觉会更好。
> fix(bundler-webpack): process undefined problem with hmr

- libs/valtio/package.json
- libs/valtio/src/index.ts
- packages/plugins/src/valtio.ts
- pnpm-lock.yaml
升级 valtio 到 1.19.0 版本，导出 useProxy 方法
相关 [issue](https://github.com/umijs/umi/issues/10306)
> feat: upgrade valtio to 1.19.0

- packages/plugins/package.json
- pnpm-lock.yaml
- scripts/.internal/constants.ts
- scripts/release.ts
close #10317
发布的时候会去检查独立版本的包，目前只有 `libs/valtio` 一个。
会用 git diff 对比一下从 **上次 tag** 之后发生的变化，如果没变化，就默认继续 release ，如果有变化，提示要去发包了。
如果回答 `n` ，就中断流程，去发包，发完再回来发布。
如果回答 `y` ，证明你已经发过包了，会自动把新版本刷到所有使用的位置，把他变成 `^${newVersion}` ，这样可以解升级 umi 依赖版本但是 umi 依赖的包没有更新的问题，之后继续进行 release 流程。
> chore: check independent version pkgs publish when release

- packages/preset-umi/src/features/icons/esbuildPlugins/esbuildExternalPlugin.ts
- packages/preset-umi/src/features/icons/icons.ts
fix #10338 
修复：
1. `@` 和 `@@` 开头的别名导入被 external 掉了，导致不识别的 BUG 。（因为 tsconfig 不能自定义 `paths` 的关系，等价于没法拓展显示的 alias ，先只做这两个）
2. `icons.tsx` 是异步生成的，第一次没有，esbuild 解析报错了，所以在初始化的时候写个空的。
> fix(icons): import start with alias `@`

- packages/preset-umi/src/commands/dev/depBuildWorker/depBuildWorker.ts
eager 模式下 copy plugin 未禁用 
fix: https://github.com/umijs/umi/issues/10329
> fix: 🐛 MFSU[eager] webpack copy plugin 未禁用

- packages/plugins/src/mf.ts
内部一个插件， 默认开启 hash ，导致 dev 时 remote 的产物是 remote.xxx.js  ，调试非常不方便（需要开启 writeToDisk 才知道文件 hash 是什么）
> fix: 🐛 dev 模式下不使用 hash， 方便调试

- docs/docs/api/config.md
- packages/preset-umi/src/features/exportStatic/exportStatic.ts
允许对 `exportStatic.extraRoutePaths` 配置的路由部分禁用预渲染
背景是 dumi 会利用该配置将所有 demo 的独立访问路由（例如 `/~demos/button-demo-basic`）变成静态路由，但 demo 路由不需要被搜索引擎爬取，且 demo 数量很多时（比如 antd 项目）会导致构建极慢
虽然预渲染以后有首屏加载优势，但独立打开 demo 链接的场景不多，平衡之下还是默认禁用比较好，故 Umi 层增加该配置，随后 dumi 再做修改
> feat(preset-umi): disable prerender for partial routes in exporStatic

- packages/preset-umi/src/commands/config/set.ts
修复初始化调用 ```npx umi g tailwindcss``` 时，
```.umirc.ts``` 中自动写入配置缺失 ```tailwindcss: {}``` 的问题
> fix(preset-umi): 修复不存在 .umirc.ts时，多次调用 set ， .umirc.ts 被覆写的问题

- packages/preset-umi/src/features/prepare/prepare.ts
星期五晚上群里反馈的问题，用 alias 前先把循环引用解开。
cc @hanzebang 
最小复现：
```ts
// .umirc.ts
alias: {
'@/page': '@/pages'
}
```
```ts
// src/pages/index.tsx
import Page from '@/page/other' // src/pages/other.tsx
```
> fix(prepare): unwrap alias

- packages/utils/src/logger.ts
近日发现，只要是用 `umi run` / `umi --help` 都会生成日志到当前目录的 `node_modules/.cache` 下，正确的位置应该是和最近的 `package.json` 同级，而不是无脑在 cwd 生成。
> fix(logger): logger file should in `package.json` dir

- examples/with-workerize-loader/.umirc.ts
- examples/with-workerize-loader/package.json
- examples/with-workerize-loader/pages/index.tsx
- examples/with-workerize-loader/pages/worker.ts
- packages/bundler-webpack/bundles/webpack/bundle.js
- packages/bundler-webpack/bundles/webpack/packages/BasicEvaluatedExpression.js
- packages/bundler-webpack/bundles/webpack/packages/ExternalsPlugin.js
- packages/bundler-webpack/bundles/webpack/packages/FetchCompileAsyncWasmPlugin.js
- packages/bundler-webpack/bundles/webpack/packages/FetchCompileWasmPlugin.js
- packages/bundler-webpack/bundles/webpack/packages/LimitChunkCountPlugin.js
- packages/bundler-webpack/bundles/webpack/packages/NodeTargetPlugin.js
- packages/bundler-webpack/bundles/webpack/packages/NodeTemplatePlugin.js
- packages/bundler-webpack/bundles/webpack/packages/StringXor.js
- packages/bundler-webpack/bundles/webpack/packages/WebWorkerTemplatePlugin.js
- packages/bundler-webpack/bundles/webpack/packages/deepImports.json
- packages/bundler-webpack/compiled/webpack/BasicEvaluatedExpression.js
- packages/bundler-webpack/compiled/webpack/ExternalsPlugin.js
- packages/bundler-webpack/compiled/webpack/FetchCompileAsyncWasmPlugin.js
- packages/bundler-webpack/compiled/webpack/FetchCompileWasmPlugin.js
- packages/bundler-webpack/compiled/webpack/LimitChunkCountPlugin.js
- packages/bundler-webpack/compiled/webpack/NodeTargetPlugin.js
- packages/bundler-webpack/compiled/webpack/NodeTemplatePlugin.js
- packages/bundler-webpack/compiled/webpack/StringXor.js
- packages/bundler-webpack/compiled/webpack/WebWorkerTemplatePlugin.js
- packages/bundler-webpack/compiled/webpack/deepImports.json
- packages/bundler-webpack/compiled/webpack/package.json
- pnpm-lock.yaml
workerize-loader 实现使用了 `webpack/lib/node/NodeTargetPlugin` 和 `webpack/lib/webworker/WebWorkerTemplatePlugin` umi 中预打包后无法正确访问
在 bundles 中 导出 通过 `deepImports` `requireHook` 自动映射
> feat(bundler-webpack): webpack pre-compiled support workerize-loader

- packages/preset-umi/src/features/mpa/extractExports.ts
在 `examples/mpa` 里 dev 报如下错误：
此 PR 尝试修复。
> fix: mpa resolve error on Windows

- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/parcelCSS.ts
- pnpm-lock.yaml
[`@parcel/css`](https://www.npmjs.com/package/@parcel/css?activeTab=versions) 命名改成 lightningcss 后，已经 5 个月没有同步版本了，这个包已经被放弃了，新的更新都在 [lightningcss](https://www.npmjs.com/package/lightningcss) ，所以替换他。
> chore: replace `@parcel/css` with `lightningcss`

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
在 #10412 发现了更多循环依赖问题，其中 `defineApp` 在 max 中 `app.ts` 使用会崩溃 `undefined` ，所以把 #9708 这个 PR 一部分致命的问题先拆出来解掉。
> fix(app.ts): `defineApp` undefined

- packages/plugins/src/mf.ts
> feat: check mf.name is valid identifier

- did-you-know/package.json
> docs(did-you-know): beautify link

- packages/preset-umi/package.json
- packages/preset-umi/src/features/depsOnDemand/depsOnDemand.ts
- packages/preset-umi/src/features/icons/icons.ts
- packages/preset-umi/src/features/icons/svgr.ts
- packages/utils/src/npmClient.ts
- pnpm-lock.yaml
Close #10442 
进展：图标库已发版，支持自定义安装
我想的是把现有的安装包的工具扩展下，可以支持单独安装同时不影响之前的。
> perf: cnpm and tnpm are supported

- packages/bundler-webpack/src/config/javaScriptRules.ts
- packages/preset-umi/src/features/legacy/legacy.ts
修复编译时意外读取 `babel.config.js` 的问题
> fix: respect unexpectedly for babel config file

- .github/workflows/pr-checker.yml
这个ci未生效，查原因。 #10461 
执行发消息步骤时被跳过了，应该是if判断没有通过。
我在自己仓库复制了umi一样的回去，能够正常运行，排除'true'是字符串导致的问题。
判断有3个条件
1. 没有权限
2. 名字不在文件里
3. 必须被merged才会触发
建了个小号模拟，发现github.actor和needs.check-permission.outputs.require-result都是点合并的人的权限
所以前两个条件没通过，这块看一下获取创建pr的名字
> fix: pr_check and log

- docs/docs/max/request.md
在我的项目中后端返回给前端的字段不是 `success`，因此在 `errorThrower` 使用过程中，无法 catch `Error`。
查看源码以后才发现默认是对 `data.success` 进行判断，所以我的项目中只能使用拦截器进行判断。
这块的文档需要做一下补充。
-----
[View rendered docs/docs/max/request.md](https://github.com/october-rain/umi/blob/docs/request/docs/docs/max/request.md)
> docs: :memo: 给 request 文档中 errorThrower 添加备注

- packages/plugins/src/antd.ts
背景：
antd 5 的包目录格式已经不符合 babel-plugin-import 的要求，开启 plugin-layout 会触发此问题。
为什么不让 antd5 支持 babel-plugin-import ，做了 benchmark 
内部一个中等规模项目
| import |构建时间 | 产物大小|
| ----:| ----:| ----:|
|   关闭| 1m8.43 | 6394942 |
| 开启| 1m10.96 | 6394920 | 
因此 直接 antd 插件 禁止开启 import
> fix: 🐛 antd5 下 禁用 antd 插件开启 import=true 

- packages/preset-umi/src/features/prepare/build.ts
- packages/preset-umi/src/features/prepare/esbuildPlugins/esbuildExternalPlugin.ts
修理 【prepare 没有覆盖通过 umi > exports > plugin-xxx/index.ts 链路引入的文件】 这个问题。
是因为对 alias 导入判断逻辑不完整导致的。
> fix(prepare): alias handle

- packages/preset-umi/src/features/icons/esbuildIconPlugin.ts
参考
> Keep in mind that many callbacks may be running concurrently. In JavaScript, if your callback does expensive work that can run on another thread such as fs.readFileSync(), you should make the callback async and use await (in this case with fs.promises.readFile()) to allow other code to run in the meantime. In Go, each callback may be run on a separate goroutine. Make sure you have appropriate synchronization in place if your plugin uses any shared data structures.    
> 
> --from https://esbuild.github.io/plugins/#on-load
> refactor: 🎨 improve performance onLoad should better use async function

- packages/ast/src/setConfigByName/setConfigByName.ts
- packages/create-umi/templates/max/src/access.ts
- packages/create-umi/templates/max/src/app.ts
1. 代码和注释中存在指向 `next.umijs.org` 的链接，替换为 `umijs.org`
2. 修复 `@umijs/bundler-utils/compiled/babel/parser` 导入顺序（lint 自动引入）
> chore: replace next.umijs.org into current domain

- examples/max/components/decorator.jsx
- examples/max/pages/index.tsx
- packages/preset-umi/src/features/icons/esbuildIconPlugin.ts
修复开启  icon  配置，js[x] 中使用 decorator 在 prepare 阶段报错的问题。
p.s  语法形式 1 , esbuild 目前[刚支持](https://github.com/microsoft/TypeScript/pull/52582), 所以我们的框架如果出现 ，暂时可以先绕过。
```ts
export @decorator class XXX {}   // 1
// 绕过
@decorator export class XXX {}  
```
> fix: 🐛 onload esbuild plungin call  override js[x] file loader

- packages/umi/src/cli/cli.ts
- packages/umi/src/cli/node.ts
修复 Node.js v14 下 `UnhandledPromiseRejectionWarning` 只会 warning 不会进程退出的问题；比如在 `onBuildComplete` 钩子里有 Promise 调用且异常没有 `catch`，整个 `build` 命令仍然是成功的，这会导致雨燕等云构建平台给用户传递错误的构建状态
解法：对 <= Node.js v14 监听 `unhandledRejection` 事件手动抛出异常
备注：对 Node.js v15 以上版本无影响，因为 `--unhandled-rejections` 默认值改为 `throw` 了，http://nodejs.cn/api/cli/unhandled_rejections_mode.html
> fix(umi): catch unhandled promise rejction for node 14

- packages/preset-umi/src/features/ssr/webpack/webpack.ts
修复使用 webpack 作为 SSR builder 时 dev 下产物不实时更新的问题，之前的用法是无效的
ref https://github.com/umijs/umi/pull/10510
> fix(preset-umi): ssr webpack builder watch mode in dev

- packages/plugins/src/request.ts
在使用这个参数的时候，类型提示里生成的是个空字符串，这里应该是个字符串，我看是加了一些判定条件最终导致了生成的类型是个空字符串。这里直接改成`Joi.string()`可以吗 @PeachScript .我觉得这里不会有人去填写奇怪的东西，毕竟是基于接口里面的变量来填写的，json帮我们限制了不能用特殊符号
> chore: add type

- packages/bundler-utils/src/index.ts
- packages/bundler-webpack/src/build.ts
- packages/bundler-webpack/src/dev.ts
- packages/plugins/src/layout.ts
- packages/preset-umi/src/commands/config/remove.ts
- packages/preset-umi/src/commands/config/set.ts
- packages/preset-umi/src/commands/mfsu/mfsu.ts
- packages/preset-umi/src/features/appData/appData.ts
- packages/preset-umi/src/features/icons/icons.ts
- packages/preset-umi/src/features/polyfill/polyfill.ts
- packages/preset-umi/src/features/ssr/ssr.ts
- packages/preset-umi/src/features/tmpFiles/configTypes.ts
- packages/preset-umi/src/features/transform/transform.ts
- packages/preset-umi/src/registerMethods.ts
- packages/utils/src/logger.ts
- packages/utils/src/updatePackageJSON.ts
这个 PR 做的事：
1. 性能优化，详见 #10645
2. 改掉历史代码里不规范的 lazy import 写法
> perf: module lazy import

- packages/preset-umi/src/features/appData/appData.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/umi.tpl
background: https://github.com/umijs/dumi/issues/1463
> feat: global loading is obtained from appData

- packages/plugins/src/request.ts
本次发版先回滚 #10627 ，因为改动前允许空串，改动后不允许空串，会对存量项目造成影响
This reverts commit 878255ebb68cd78d2db9af9525115652340004ad.
> revert: "chore: add type (#10627)"

- packages/lint/src/config/eslint/rules/recommended.ts
移除已经废弃的 eslint 规则，否则项目执行会提示规则找不到
Breaking change from eslint-plugin-jest: https://github.com/jest-community/eslint-plugin-jest/releases/tag/v27.0.0
Ref: #10609
> fix(lint): remove deprecated eslint rule

- packages/bundler-webpack/src/plugins/EsbuildMinifyFix.ts
改善和修复一些 esbuild minify iife 的问题。
cc @xierenyuan
> fix(iife): improve esbuild iife

- docs/docs/api/config.md
- packages/bundler-utils/src/https.ts
- packages/bundler-utils/src/types.ts
背景：
https 基于 spdy 实现，开启 https 后多刷几次会报「ERR_HTTP2_PROTOCOL_ERROR」的问题
方案：
https 增加 http2 配置项，配置 https: { http2: false } 后不走 spdy，降级回普通的 https
> feat: add http2 switch into https user config

- packages/bundler-utils/compiled/babel/index1.js
#10608 升 babel 依赖但是没预打包，所以 `satisfies` 还用不了。
close #10715
> dep: bundle babel 7.21

- examples/ant-design-pro/package.json
- packages/preset-umi/src/commands/deadcode.ts
- packages/utils/src/getFileGitIno.ts
- packages/utils/src/index.ts
增强 deadcode 功能：
metion：#10623
默认直接输出文件 url，通过命令行点击进入文件，可输出json文件，开启verbose模式，可在生成文件中记录更多信息；
很多 老旧业务、多人协作水平不均 的业务，需要定期记录 deadcode 的情况，以做治理规划；
增加cli 参数：
- --out-file 是否生成文件，默认生成未使用文件数组json；
- --verbose 生成文件携带更多信息，包括文件创建时及最新修改的信息（通过git）；
- --path-prefix monorepo .git 文件夹通常不在项目文件夹，需添加路径前缀寻找；
ant-design-pro example 测试：
`node_modules/.bin/max deadcode`
`node_modules/.bin/max deadcode --out-file --verbose --path-prefix=../..`
> feat: deadcode with more args

- packages/preset-umi/src/features/exportStatic/exportStatic.ts
当前在 `exportStatic` 中配置了 `prerender: false` 的页面仍然会在客户端注水，因为 dom 不匹配会导致 SSR 警告转为 CSR。
比如 antd 官网的 demo 页：https://ant-design.antgroup.com/~demos/components-button-demo-basic
配置了 `prerender: false` 的页面直接客户端渲染，不走注水逻辑。
> fix: page not prerendered should not hydrate

- packages/bundler-webpack/src/server/server.ts
- packages/preset-umi/src/types.ts
给 onDevCompileDone 回调增加 ws 参数
暂时是在这里有用， https://github.com/umijs/Mongchhi/blob/18dd72f372ec87c062a5c28332028dfbb0a023b2/packages/plugin-socket/src/index.ts#L42
```ts
g_ws.wss.on('connection', async (ws, req: any) => {
// 做一些 socket 相关的通信
});
```
后续 ui 应该也可以用它。
> feat: onDevCompileDone add ws opts

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
允许跳过 `routeProps` 插件且不报错，比如 dumi 需要用到约定式路由但又不需要该插件
> refactor(preset-umi): allow skip routeProps plugin

- packages/preset-umi/src/features/clickToComponent/clickToComponent.ts
`click-to-react-component` 组件虽然做了如下处理，但在生产模式下启用的话其组件仍然会被打包，且默认不会走构建，会导致低版本浏览器兼容问题
``` js
// index.js
export const ClickToComponent =
process.env.NODE_ENV === 'development' ? Component : () => null
// ContextMenu.js
if (!open) onClose?.()
```
> fix(c2c): clickToComponent only in dev mode

- docs/docs/tutorials/getting-started.md
- packages/create-umi/src/template.ts
删去 `umi-xxx-template` 这种包的初始化。
但我觉得可以不用去，因为可以精确指定 `--template @umijs/electron` or `--template @umijs/electron-template` ，会自动补全 + 查找。
> chore: remove `umi-` prefix template pkg

- docs/config/README.md
- docs/config/README.zh-CN.md
- packages/bundler-webpack/src/getConfig/getConfig.webpack5.test.ts
- packages/preset-built-in/src/plugins/features/devServer.ts
- packages/server/src/Server/Server.test.ts
- packages/server/src/Server/Server.ts
- packages/server/src/Server/utils.test.ts
- packages/server/src/Server/utils.ts
This PR implements the same functionality as #10693 but in umi3.
> feat(Server): allow devServer be configured *not* to use http2 when in https mode

- docs/docs/guides/mpa.md
- docs/docs/guides/routes.md
- docs/docs/max/data-flow.md
- docs/docs/max/i18n.md
- docs/docs/max/mf.md
- docs/docs/max/micro-frontend.md
- docs/docs/max/request.md
1.  经 #10824 反馈发现，现在无法在配置文件里使用 tsx ，序列化写文件的过程中函数都会被清除掉，故删除 qiankun 在配置文件中使用 `errorBoundary` 的部分。
2. 所有匿名函数改为具名函数，防止误导导致 react refresh 不生效。
> docs: use named component export and improve qiankun config

- packages/utils/src/setNoDeprecation.ts
学习 umi 源码的时候有这段代码：
点进 🔗 发现对应的代码是这一行
有点疑惑，搜了下这个文件发现 95 行才有这个代码
翻了下历史记录发现这个引用 🔗 是这个 [commit](https://github.com/umijs/umi/commit/4e6e61d6acc2b68b96b36f93872f9b6db34deda2) 带来的
推测那个时候的 77 行是现在的 95 行
> fix(setNodeprecation): update the reference url

- packages/bundler-webpack/src/plugins/EsbuildMinifyFix.ts
如果当前资源存在 soucemap 时不进行包含处理 
存在 sourcemap 包含时会导致当前 chunk 出错
> feat(bundler-webpack): esbuildMinifyFix exist sourcemap does not handle

- packages/mfsu/src/dep/getExposeFromContent.ts
- packages/preset-umi/src/features/prepare/prepare.ts
- packages/utils/src/index.ts
- packages/utils/src/isJavaScriptFile.ts
- packages/utils/src/isStyleFile.ts
1. esbuild 的 meta.inputs 会包含 json 文件，未来可能当有其他类型文件；解析前过滤 js 文件。
2. 顺手优化 isStyleFile
> fix(prepare): 过滤仅仅 js 文件进行解析

- packages/bundler-webpack/src/plugins/EsbuildMinifyFix.ts
fix #10901
iife 不要去污染用户的 js 文件，cc @xierenyuan
> fix(esbuild-iife): do not handle copied files

- packages/plugins/src/qiankun/slave.ts
- 因为存在 qiankun 应用 appName 与 pkg.name 对不上的情况，所以允许用户自行指定 appName
> feat(plugin-qiankun): qiankun 本地研发支持设置 appName

- packages/lint/src/config/stylelint/index.ts
默认禁用 [`color-function-notation`](https://stylelint.io/user-guide/rules/color-function-notation/) styelint 规则，避免自动 `fix` 导致启用 Less `{ math: 'always' }` 时编译报错
> refactor(lint): disable color-function-notation stylelint rule

- packages/bundler-vite/src/build.ts
assetsDir 不能指定成 publicPath  使用默认值
补齐下背景 从 vite 2 开始  assetsDir 就作为 join 的参数, 如果设置 publicPath 会导致   生成路径包含 publicPath 当指定CDN 的场景会有问题 https://github.com/vitejs/vite/blob/main/packages/vite/src/node/build.ts#L614
> fix(bundler-vite): unexpected assets url if configure publicPath

- packages/deps/package.json
- packages/deps/taskfile.js
- yarn.lock
修复 Umi 3 babel 在编译 unicode 正则时报错的问题，原因和解法同 https://github.com/umijs/umi/pull/8846
**注意：由于 Umi 3 的 ncc 重新打包产物 diff 非常巨大，为了避免引发其他问题，实际产物是手动修正的**
> fix(deps): unicode regex compile failed since babel bundle

- packages/bundler-utils/src/index.ts
- packages/plugins/src/utils/modelUtils.ts
升级的应用大量使用 Dva，在 umi 4 中往往检测出问题，优化日志方便排查
```
/Users/umi_playground/git/umi-next/examples/with-dva/models/countx.js:
13 |   },
14 |   reducers: {
> 15 |     add(state:any){
|             ^ Expected ")" but found ":"
16 |       state.num += 1;
17 |     },
18 |   },
fatal - Error: Transform failed with 1 error:
/Users/umi_playground/git/umi-next/examples/with-dva/models/countx.js:15:13: ERROR: Expected ")" but found ":"
at failureErrorWithLog (/Users/umi_playground/git/umi-next/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1604:15)
at /Users/umi_playground/git/umi-next/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:837:29
at responseCallbacks.<computed> (/Users/umi_playground/git/umi-next/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/mai …
```
> refactor: 🎨 优化 dva 模型错误展示

- packages/bundler-webpack/src/server/server.ts
让 onBeforeMiddleware 真正优先于内置的 Middleware
使用的场景：需要给构建产物的 http 响应增加特殊的 http 头，需要在后面的 static 中间件之前配置好。
> chore: 🐛 调整 dev server onBeforeMiddleware 调用顺序

- examples/mpa/pages/foo/index.tsx
- packages/core/src/service/service.ts
- packages/preset-umi/src/features/mpa/mpa.ts
- packages/preset-umi/src/features/prepare/prepare.ts
close https://github.com/umijs/umi/issues/10765
之前基于文件扫描没有个问题，现在基于 prepare 的 filelist 就需要补全上所有的 entry 文件
> fix: 🐛 mpa 下文件扫描遗漏 mpa 入口文件的问题

- packages/create-umi/src/index.ts
#10913 的第二步对策。
在 pnpm v8 初始化项目时，直接 up 到最新。
> fix(pnpm): pnpm v8 auto upgrade deps when init project

- packages/mfsu/src/dep/dep.ts
close https://github.com/umijs/umi/issues/10893 
close https://github.com/umijs/umi/issues/10868
close https://github.com/umijs/umi/issues/10973
> fix: 🐛 dep 文件路径过长 生产 hash ，保留 200 个字符方便查看按照文件名查找文件

- packages/lint/src/config/stylelint/index.ts
禁止意外的 `font-family` 配置，通常是来源于从 Sketch 中复制的 CSS 样式，单一的 `font-family` 会导致在没有该字体的设备上渲染异常
cc @afc163
> feat(lint): disallow unexpected font-family from sketch

- packages/plugins/src/antd.ts
修复 antd 插件没有自动为 antd v5 引入 `reset.css` 的问题，这可能导致部分情况下样式异常
cc @zombieJ
> fix(plugins): reset style missing for antd v5

- packages/plugins/src/layout.ts
经反馈，使用绝对路径的 ts types 引用，在使用 npm / yarn 的时候有大小写问题，所以我们跳过这些包管理器的绝对路径解析，因为他们有幽灵依赖，可以直接解析到。
from #10947
> fix: use absolute path to types reference

- packages/create-umi/templates/vue-app/tsconfig.json.tpl
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> feat: vue tsconfig update

- examples/lint/src/test.less
- packages/lint/src/config/stylelint/index.ts
优化 `font-family` Stylelint 规则的错误提示，避免用户看不懂原因，进而增加答疑成本
ref #11001
> refactor(lint): improve message for font-family rule

- packages/plugins/src/layout.ts
- packages/plugins/templates/locale/SelectLang.tpl
> fix: 🐛 支持开启 layout + ant3应用 显示右上的退出登陆的按钮

- packages/plugins/src/locale.ts
> fix(locale): 修复 locale 空配置时 antd 缺失部分内容的情况

- packages/babel-preset-umi/package.json
- packages/utils/package.json
修复 Umi 3.3.x 中 @umijs/utils 和 @umijs/babel-preset-umi 的幽灵依赖问题
背景：Smallfish 仍然基于 3.3.x，其组件库方案在集成 dumi 2 的时候会出现依赖错位的问题
> fix: phantom dep problem for utils and babel-preset

- packages/bundler-webpack/src/dev.ts
- packages/preset-umi/src/commands/dev/depBuildWorker/dev-config.ts
原来会在项目代码 bundle 和依赖代码 bundle 的时候同时搞 tscheck 影响执行效率。
> fix: 🐛 关闭 mfus webpack 配置的 的 tscheck 插件

- packages/preset-umi/src/commands/lint.ts
`lint` 命令用不到 Umi 的用户配置文件，将配置解析模式设置为 `loose`，提升命令执行速度
> perf(preset-umi): avoid resolve config for lint command

- packages/preset-built-in/src/plugins/features/analyze.ts
- packages/preset-built-in/src/plugins/features/fastRefresh.ts
- packages/preset-built-in/src/plugins/features/forkTSChecker.ts
- packages/preset-built-in/src/plugins/features/mfsu/mfsu.test.ts
- packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
修复 `@umijs/preset-built-in` 对 `umi` 的幽灵依赖，在 Umi 3/4 混用的场景下会有问题
> fix(preset-built-in): avoid phantom dependency

- examples/ant-design-pro/config/config.ts
- ui/components/routes/routeChart.tsx
- ui/components/routes/routeDrawer.tsx
- ui/hooks/useAppData.ts
- ui/layouts/index.tsx
- ui/utils/g6LongText.ts
- ui/utils/realizeRoutes.ts
适配手动声明 routes 导致 id 为数字造成的现实问题，使用 absPath 的结尾来作为 label，如果为空时再取 id，适配 globalLayout
手动声明：
自动生成：
> Feature/lyy umi UI fix 0607

- .github/workflows/ci.yml
- examples/max/pages/index.tsx
- package.json
- packages/preset-umi/src/features/icons/icons.ts
- pnpm-lock.yaml
fix #11256
修复 Icon 组件的 spin 属性透传下去导致非预期的警告问题
> fix: icon spin prop warning

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
lockfileVersion: '6.1' 之前的 pnpm 不能跑，改回 6.0
pnpm 最新的版本 8.6.2 又把 lock version 回退到了 6.0 ，所以这里统一把版本指定为 8.6.2 ，详见 https://github.com/pnpm/pnpm/releases/tag/v8.6.2
> chore: set pnpm version

- docs/docs/api/api.md
The state prop of the Link component should be any according to the LinkProps type definition.
> Doc/fix: Corrected type definition of state in Link component

- examples/config-locale/.umirc.ts
- examples/config-locale/locales/en-US.js
- examples/config-locale/locales/zh-CN.js
- examples/config-locale/package.json
- examples/config-locale/pages/index.tsx
- package.json
- packages/plugins/templates/locale/localeExports.tpl
- pnpm-lock.yaml
修复使用 addLocale 追加 messages 时，原有 momentlocal 丢失问题。
```ts
addLocale('zh-CN', {
welcome: '欢迎！',
});
```
修复前，在追加 locale 之后，antd 内置的 locale 会丢失
修复后
Closes: https://github.com/umijs/umi/issues/10694
> fix: momentlocal lose when use addLocale

- examples/umi-3-compat-mode/layouts/index.tsx
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/history.tpl
- packages/preset-umi/templates/historyIntelli.tpl
Uncaught TypeError: s.history.goBack is not a function
开启 `reactRouter5Compat: {}` 配置的时候，旧的 api 应该兼容一下。
https://github.com/umijs/umi/blob/27937cdfbcb6e604917cd1b288f726b4c4f4fe3d/docs/docs/api/api.md?plain=1#L801
> fix: s.history.goBack is not a function

- packages/babel-preset-umi/src/index.ts
resolve #11103
目前几个信息如下：
1. ecma 官配 deco 虽然已经正式出台，但功能是超级阉割版，与 TS deco 相比十分逊色。
2. 目前 esbuild 对此持观望态度，没有实施计划（ https://github.com/evanw/esbuild/issues/3045#issuecomment-1501238674 、https://github.com/evanw/esbuild/issues/104 ）
3. 目前 swc 对此只是有了实施，但未开放 api （ https://github.com/swc-project/swc/issues/7193 、 https://github.com/swc-project/swc/discussions/5053#discussioncomment-5543835 ）
所以我们先把 deco 配置项放出来，但不做过多的假定。
> feat: support modify babel deco plugin opts

- docs/docs/api/plugin-api.md
- packages/core/src/types.ts
场景：进入旧的链接时，需要自动跳转到新链接
在 `modifyRoutes` 新增一项把 `file` 换成 `redirect` 即可，但是 `file` 在 ts 定义中为必填，直接替换会报错
> type: update type

- examples/ssr-demo/src/pages/index.tsx
- packages/preset-umi/src/features/ssr/ssr.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/server.tpl
- packages/renderer-react/src/server.tsx
- packages/server/src/ssr.ts
之后  antd  的 css in js ssr  就可以这样写了
```tsx
'use client';
import React from 'react';
import { useServerInsertedHTML } from 'umi';
import { createCache, extractStyle, StyleProvider } from '@ant-design/cssinjs';
const cache = createCache();
export default function StyledComponentsRegistry({
children,
}: {
children: React.ReactNode;
}) {
useServerInsertedHTML(() => {
const styleText = extractStyle(cache, true);
return (
<style
dangerouslySetInnerHTML={{
__html: styleText,
}}
/>
);
});
if (typeof window !== 'undefined') return <>{children}</>;
return <StyleProvider cache={cache}>{children}</StyleProvider>;
}
```
> feat(ssr): support useServerInsertedHTML

- examples/qiankun-master/.umirc.ts
- examples/qiankun-master/app.ts
- examples/qiankun-master/pages/index.tsx
- examples/qiankun-master/pages/never.tsx
- examples/qiankun-slave/cypress/e2e/example.cy.ts
- packages/plugins/libs/qiankun/master/common.ts
- packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl
- packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
- packages/plugins/libs/qiankun/master/types.ts
- packages/plugins/libs/qiankun/slave/slaveRuntimePlugin.ts
- 新增了 `qiankun.master.routes[].mode: 'match' | 'prepend'`，`match` 时仅作为匹配规则，不会作为 router 前缀
- ~~修复了主子应用路由相同时，优先匹配主应用路由的 bug，可能会有 breakingChange~~
> feat: support routeMode prepend & match

- packages/bundler-webpack/package.json
- pnpm-lock.yaml
升一下 swc 依赖的版本，太久没更新了，很老了。
另外 https://github.com/umijs/swc-plugin-auto-css-modules 这个仓库辛苦帮加下推送权限，现在我 Push 不进去。
未来可能的话，还是要依赖整套 rust 编译工具（如 mako ），swc 内核变化太快，插件的更新跟不上。
> dep: upgrade swc version

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/server/src/ssr.ts
follow up #11227
在 dev 下，`useServerInsertedHTML` hook 仍然需要一个占位方法。否则会报错：
SSR 下 OOM 是因为 staticRes 没有释放导致：
> fix: hooks should keep alive even when not in ssr

- packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl
fix #11447
master 的 base 尾部有斜线的情况，要去掉，不然多拼一个斜线，比如 `/base/` + `/url` 。
> fix(qiankun): master base ends with slash

- examples/ssr-demo/.umirc.ts
- packages/preset-umi/src/features/exportStatic/exportStatic.ts
Pre-render 产出的 HTML 中 umi.js 没有带上 async，导致阻塞了后面的 script，也就是 react 替换 Suspense 内的 HTML 的脚本：
因为渲染 HTML 时 Suspense 内的 HTML 是 append 到最开始打出的 HTML 后面的，也就是在 `<html>` 标签外边，所以一开始浏览器不会渲染这部分。但是由于 umi 有一个 router 级别的 Suspense，所以导致的结果就是会白屏直到 umi.js 执行完。这会严重影响 FCP 和 LCP，优化后 antd 官网的 FCP 从 2s 降低到了 400ms。
看了一眼 SSR 是有给 umi.js 加 async 的，不知道有没有更好的写法？
> fix: script in pre-render html should be defer or async

- examples/boilerplate/plugin.ts
- packages/core/src/types.ts
当 hook 是异步的并且使用 stage 的场景, 类型错误
修复下列场景使用类型错误
```tsx
api.addHTMLScripts({
async fn() {
return [`console.log('async scripts hello world')`];
},
stage: 100,
});
```
> feat(core): IAdd type fix

- docs/docs/max/micro-frontend.md
- packages/plugins/libs/qiankun/master/types.ts
- packages/plugins/src/qiankun/master.ts
`autoSetLoading` 只能加载默认的动画，灵活性较差，用户希望可以通过统一的方式扩展子应用的加载动画。
用户期望可以像 `initialState.loading` 配置的方式一样：
```
initialState: { loading: "@/initialLoading", qiankunLoading: '@/initialLoading' }
```
扩展 qiankun master 配置，支持传递文件路径，使用姿势如下：
```
qiankun: {
master: {
enable: true,
loader: '@/initialLoading',
},
},
```
> feat(plugins): custom loading component for qiankun

- .github/workflows/pr-checker.yml
pull_request_target 会基于 master 分支运行且生成的 GITHUB_TOKEN 具备写权限，可能导致仓库密钥被恶意 pr 窃取。改成 pull_request 的唯一副作用是当一个新的 contributor 提交了 pr 并修改了 contributors.json 时（将自己的 id 加入到了列表），当前 pr 被合并后可能不会触发加群通知，因为对照的是当前 pr 分支的 contributors.json 而不是 master 分支的 contributors 列表
see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/11512)
> fix: use pull_request event instead of pull_request_target for security reason

- docs/docs/docs/api/config.md
- packages/preset-umi/src/features/exportStatic/exportStatic.ts
现在 Pre-render 失败时仍会跑完整个构建，用户不注意的话就不会发现有编译问题。
1. Pre-render 失败时抛错并终止进程
2. 添加 `exportStatic.ignorePreRenderError` 配置，开启后会和以前的行为一样
> feat(preset-umi): throw by default when pre-render error

- examples/with-antd-5/.umirc.ts
- examples/with-antd-5/pages/index.tsx
- packages/plugins/src/antd.ts
- packages/plugins/templates/antd/runtime.ts.tpl
ref: https://github.com/umijs/umi/issues/11418#issuecomment-1635755725
> feat(plugins): support to configure token algorithm for antd 5

- docs/docs/docs/max/micro-frontend.md
- packages/plugins/src/qiankun/slave.ts
- ref https://github.com/umijs/plugins/pull/948
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/11530)
> feat(plugins): use app name as qiankun library name by default

- packages/bundler-utils/src/proxy.ts
#10692 
我修改了一下这段代码，默认情况下不修改Header中的Origin字段，以避免CORS问题
在开启changeOrigin的情况下，http-proxy库会修改Header中的host字段，但是不会修改Origin字段，所以也会导致CORS问题
我加了个判定，changeOrigin开启的时候，修改Origin字段。 这样做既可以让changeOrgin这个控制参数更符合预期，同时避免了CORS问题
修改之后的changeOrigin行为：
* changeOrigin为false：默认行为，不改变请求的origin和host
* changeOrigin为true：请求的origin和host会替换为target的origin
两种模式都不会有CORS问题
> fix: Http proxy CORS problem, Keep origin by default.

- packages/plugins/src/antd.ts
ref: https://github.com/umijs/umi/issues/11156#issuecomment-1554052622
Co-authored-by: xiaohuoni <xiaohuoni@users.noreply.github.com>
---
把 #11163 拆分来解决
> refactor(plugins): check algorithm option for antd plugin

- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/config/fastRefreshPlugin.ts
- pnpm-lock.yaml
参考 ice 的实现 https://github.com/alibaba/ice/pull/6442 修复路由组件导出 clientLoader 或者 routeProps 时 react 组件热更新失效导致的应用级别刷新
> fix(bundler-webpack): Fix hmr failure caused by exporting clientLoader or routeProps from routing components

- examples/with-valtio/.umirc.ts
- libs/valtio/package.json
- libs/valtio/src/index.ts
- packages/plugins/src/valtio.ts
- pnpm-lock.yaml
> feat(valtio): ✨ add ref、watch api and upgrades valtio

- packages/bundler-utils/src/index.ts
fix https://github.com/umijs/umi/discussions/11646#discussioncomment-7054052 
当 jsx 文件中使用了装饰器，我们应该还使用 tsx loader 去解析他，因为 esbuild transform 不支持在 js 里用装饰器（最新版除外，因为从 [v0.18.5](https://github.com/evanw/esbuild/releases/tag/v0.18.5) 开始已经支持了 ecma 新版 deco ）
> fix: using tsx loader to parse jsx files

- docs/docs/docs/guides/generator.md
- packages/preset-umi/templates/generate/component/index.ts.tpl
fix #11664
修复一个历史问题，这个地方上次改动支持了用户自己定义要生成的模板文件有哪些，做出的修改和文档出现了一些偏差，现在将它们保持一致。
> fix: umi g component file name

- packages/preset-umi/src/features/tmpFiles/__snapshots__/routes.test.ts.snap
- packages/preset-umi/src/features/tmpFiles/routes.ts
解决在收集 ssr 路由相关信息时遗漏 layout 文件的问题
目前在编译时收集路由 serverLoader 时只包含了页面文件，layout 文件也需要支持配置 serverLoader、clientLoader
- 改变收集数据的位置，调整到 add layout 之后执行
> fix: add layout file when collect ssr loader

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
基于某些特殊场景我需要通过插件执行`addRuntimePluginKey`，处于umi限制我无法知道哪些key已经被添加，所以我可能会重复add，但最终产物中会产生重复的`key`，例如两个`layout`、两个`qiankun`等等，所以我想它需要被去重。
> fix: repeat runtime plugin key

- packages/plugins/src/qiankun/slave.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/11690)
> fix(qiankun): 线上环境默认启用 shouldNotAddLibraryChunkName

- docs/docs/docs/api/config.md
- packages/bundler-webpack/src/config/cssRules.ts
- packages/bundler-webpack/src/schema.ts
一些业务 会配置静态资源目录 比如
```ts
config.output
.filename(`js/[name].[contenthash:8].js`)
.chunkFilename('js/[name].[contenthash:8].async.js');
if (!api.config.styleLoader) {
config.plugin('mini-css-extract-plugin').tap(([options]) => {
return [
{
...options,
filename: 'css/[name].[contenthash:8].css',
chunkFilename: 'css/[name].[contenthash:8].chunk.css',
ignoreOrder: true,
},
];
});
}
```
这时  `publicPath` 默认是 `./` 时资源访问会有问题、 通过 chainWebpack 手动改的成本较高. 参考 vue-cli  新增了 `cssPublicPath` 允许自定义
> feat(bundler-webpack): css support config cssPublicPath

- packages/preset-umi/src/features/ssr/ssr.ts
- packages/preset-umi/src/features/ssr/utils.ts
- packages/preset-umi/src/features/ssr/webpack/webpack.ts
- packages/preset-umi/templates/server.tpl
- packages/renderer-react/src/server.tsx
- packages/server/src/ssr.ts
- createUmiHandler只返回根节点的内容，不要返回整个 html 的
- SSR输出的server.js路径带上hash
- server.js中的build-manifest.json文件路径支持SSR_RESOURCE_DIR环境变量
- 返回流式response renderToPipeableStream，提升SSR首字节时间
> SSR适配ER render

- packages/preset-umi/src/features/tmpFiles/routes.ts
对路由表中引用 node_modules 下的路由组件 chunk name 做优化，主要处理 pnpm 和 tnpm 的文件结构，对比效果：
```bash
nm__.pnpm__dumi_2.1.19_xxxx__node_modules__dumi__dist__client__pages__404
nm__dumi__dist__client__pages__404
nm____umijs_utils_4.0.83__umijs__utils__dist__index
nm___umijs__utils__dist__index
```
问题背景：之前 dumi 为了解 chunk name 引起的 CDN 资源托管问题（包括但不限于 https://github.com/umijs/dumi/issues/1487 ），用 alias 实现了 chunk name 的优化（见 https://github.com/umijs/dumi/pull/1601 ），但这个实现的前提是 layouts 不会被 server loader 处理，因为 server loader 解析 route component 时不会处理 alias，在 https://github.com/umijs/umi/pull/11666 后 layouts 也会被 server loader 处理，导致 4.0.84 发布后 dumi 应用报错
解决方案：把 chunk name 的简化交给 Umi 来处理 + dumi 回滚之前的方案
为什么不让 server loader 对路由组件的解析支持 alias：加上 alias 的处理也会比较麻烦，需要使用 enhanced-resolve，需要把 getRoutes 变成 async，问题会被扩大
> refactor(preset-umi): make 3rd-party chunk name clean

- packages/bundler-webpack/src/config/config.ts
- packages/utils/src/npmClient.ts
检测 tnpm 和 cnpm 的相关逻辑支持 rapid 模式，主要有两处：
1. 设置 webpack 持久缓存 snapshot：将 tnpm 安装目录结构的判定从 `__npminstall_done` 标记改为软链的目标文件夹名称，以解决在 tnpm npminstall mode + rapid mode 时 snapshot 配置未设置导致缓存序列化 OOM 的问题
2. 判断 npmClient 的工具方法：将 `__npminstall_done` + `_resolved` 的判定组合改为 `_resolved` + `.package-lock.json` 的组合，以解决在 rapid 模式下没有 `__npminstall_done` 字段导致 npmClient 识别错误的问题
问题原因：和 tnpm 同学确认在 rapid 模式下使用 npminstall 模式安装，package.json 里不会有 `__npminstall_done` 和 `_resoved` 标记，而雨燕云构建环境默认是 rapid 模式
穷举情况：
- npminstall mode + native fs => generate _resolved field in package.json
- npminstall mode + rapid fs => generate .package-lock.json in node_modules
- npm mode + native fs => generate .package-lock.json in node_modules
- npm mode + rapid fs => generate .package-lock.json in node_modules
注1：为什么 Bigfish 4 …
> refactor: handle rapid mode for tnpm and cnpm detection

- docs/docs/docs/max/mf.md
- packages/plugins/src/mf.ts
新增remoteHash参数来控制mf的产物是否启用hash
> feat(mf): 新增remoteHash参数控制mf的产物是否启用hash(#11711)

- packages/preset-umi/src/features/ssr/utils.ts
修复 server 产物路径添加 hash 后（关联 PR：#11698 ）引入的两个问题：
1. 配置 `publicPath` 时 server 产物路径获取错误的问题
2. 重复构建且 hash 不一致时 server 产物路径获取错误的问题
> refactor(ssr): correct logic for get dist path

- docs/docs/docs/api/config.md
- packages/bundler-webpack/src/schema.ts
`config.srcTranspiler`中没有支持`none`，文档和类型中却显示可用。短时间可能也不会支持？https://github.com/umijs/umi/issues/11727
> fix: 剔除srcTranspiler无用none枚举

- docs/.dumirc.ts
> docs: highlight menu

- packages/plugins/src/antd.ts
- packages/plugins/templates/antd/runtime.ts.tpl
- packages/plugins/templates/antd/types.d.ts.tpl
- packages/umi/client/client/plugin.js
> fix(antd-plugin): fix console deprecation warning

- packages/plugins/templates/locale/SelectLang.tpl
nl-BE is correctly using the label 'Vlaams'. nl-NL is not the same. This should use the label 'Nederlands'. Changed that in this PR.
> fix: Make nl-NL use correct label

- examples/max/cypress/e2e/smoke.cy.ts
- examples/max/locales/en-US.js
- examples/max/locales/zh-CN.js
- examples/max/pages/index.tsx
- packages/plugins/templates/locale/localeExports.tpl
locales的语言文件编写支持对象引入的方式。这个写法主要是为了配合umi的官方文档上编写的demo。文档上是支持使用对象编写，但是实际查看源码后发现不支持。
个人觉得支持对象的方式，前缀可以不用在每次定义字符串名称时重复写多次，即使使用“.”隔开也显得很长和冗余。特别是对于前缀不止一个的情况下会更友好。
在locales/zh-CN.js文件中支持对象嵌套的写法
```
// 编辑如下
"user.welcome": '嗨,朋友',
user:{
welcome: '你好, 朋友',
}
};
```
```
// 使用如下：
<FormattedMessage id="user.welcome" />
<div>{intl.formatMessage({ id: 'user.welcome' })}</div>
```
注意："user.welcome"和 对象嵌套的写法效果一致，后者会覆盖前者。并且使用方式一样，都是通过id值为"user.welcome"。
closes #11208
> feat: locales的语言文件编写支持对象引入的方式

- examples/ant-design-pro/config/config.ts
- packages/bundler-webpack/src/config/ssrPlugin.ts
- packages/preset-umi/src/features/exportStatic/exportStatic.ts
- packages/server/src/ssr.ts
This reverts commit a8303837e2f33c8a82642b302ac57cf367af1bee.
先回退该 PR 的改动发版，回退原因：
1. `route.path` 的判定会影响 `index.html` 的生成，因为首页的 `route.path` 默认是 `''`
2. 了解到 1 的改动是为了解 `undefined.html` 的问题，但还没有复现该问题，需要找到真正原因，理论上 `route` 对象都应该有 `path`，在这里判定也许不是本质解
3. `helmetContext.helmet` 默认情况下是一定存在的，如果不存在说明 `HelmetProvider` 的注入存在问题，这里做 `?.` 只是避免报错但没有解决 ssr helmet 信息丢失的问题，在 pro 项目里可以复现该问题，但 dumi 同样用了 ssr + exportStatic 却工作正常，需要看下真正原因
> revert: "fix(ssr): support ant design pro ssr (#11702)"

- packages/core/src/service/service.ts
- packages/plugins/src/styled-components.ts
- packages/preset-umi/src/features/appData/appData.ts
- packages/preset-umi/src/features/vite/vite.ts
仅在 webpack 和 vite 构建器时应用 styled-componets 的 babel 插件，因为 Mako 不支持 babel 插件避免抛出警告，未来会以其他方式支持 styled-components babel 插件提供的能力
> feat: check bundler before apply styled babel plugin

- docs/docs/docs/max/layout-menu.md
procomponents 已经该配置改为 ErrorBoundary
> docs: corrent layout config

- docs/docs/docs/max/antd.md
- examples/with-antd-5/app.ts
- examples/with-antd-5/pages/index.tsx
- examples/with-antd-5/tsconfig.json
- packages/plugins/src/antd.ts
- packages/plugins/templates/antd/runtime.ts.tpl
提供 useAntdConfig 和 useAntdConfigSetter 供用户在项目中修改 antd 的配置。
```tsx
import { Layout, Space, Button, version, theme } from 'antd';
import { useAntdConfig, useAntdConfigSetter } from 'umi';
const { darkAlgorithm, defaultAlgorithm } = theme;
export default function Page() {
const setAntdConfig = useAntdConfigSetter();
const antdConfig = useAntdConfig();
return (
<Layout>
<h1>with antd@{version}</h1>
<Space>
isDarkTheme
<Switch
checked={antdConfig?.theme?.algorithm.includes(darkAlgorithm)}
onChange={(data) => {
setAntdConfig({
theme: {
algorithm: [
data ? darkAlgorithm : defaultAlgorithm,
],
},
});
}}
></Switch>
</Space>
</Layout>
);
}
```
需要注意的是，该方法只能修改 antd 支持的配置，不支持 umi 相关的几个配置，如 dark 。
这是之前和 @fz6m 讨论的结果，导致用户在一键切换暗黑风格的操作上，需要在业务侧处理更多的逻辑，如 examples/with-antd-5/pages/index.tsx
```tsx
const …
```
> feat: add useAntdConfig

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
重排 `exports.ts` 的导出顺序，让插件方法最先导出，让有循环依赖的最后导出，这应该在一定程度上可以提升体验。
> chore: reorder exports

- packages/plugins/src/react-query.ts
- packages/plugins/src/styled-components.ts
- packages/preset-umi/src/features/icons/icons.ts
问题描述： umi/max 项目package.json显示安装 react@16 后，开启 reactQuery , styledComponents , icons 插件，页面打开会报错 `React is not defined`
解决方案：插件模板文件中添加 `import React from 'react';` 语言
> fix(plugins): import react while using react16

- packages/preset-umi/src/commands/generators/tailwindcss.ts
It needs to add postcss tailwindcss plugins when umi g tailwindcss
> fix .less file using tailwind @apply not working

- packages/plugins/src/access.ts
- packages/plugins/src/dva.ts
- packages/plugins/src/layout.ts
在 max 时，用户没有导入 `umi` 的类型提示，这里用来源替代。
close #12030
> fix: type (resolve #12030)

- packages/preset-umi/src/commands/build.ts
- packages/preset-umi/src/commands/dev/dev.ts
目前主要是给 mako 用，让 mako 能自适配 react 的 runtime 类型。
> chore: add opts.react for bundler

- docs/docs/docs/guides/lint.md
目前手动安装stylelint时默认安装v16版本，与@umijs/lint使用的v14版本有冲突，会导致校验异常，因此文档中表明了需要手动安装v14版本
> docs: add stylelint version tip

- packages/preset-umi/src/features/overrides/transform.ts
> fix: overrides `:root` pseudo class

- packages/preset-umi/src/features/exportStatic/exportStatic.ts
fix #12108
修理开启 `exportStatic` 时， `api.modifyHtml($, path)` 第二个参数不正确的问题。
> fix: `modifyHtml#path` when `exportStatic` is enabled

- packages/plugin-run/package.json
- packages/plugin-run/src/index.ts
- pnpm-lock.yaml
- scripts/bin/umi-scripts.js
1. 固定 `tsx` 到 `3.12.2` ，因为 `3.14.0` 没法在 node `v18.19.0` 以上运行，我们也没法升级更高的版本，因为再升级就没法兼容 node 14 了。
2. 禁掉 tsx 的 node warning ，对于一个小脚本来说，禁掉 node warning 无关紧要。
如果用户有条件的话，应该是自己安装最新的 tsx 来运行脚本，或者 `umi run` 应该是一个按需安装 tsx 的设计（根据 node 版本不同安装不同版本的 tsx ）。
更多上下文信息：#11981
cc @stormslowly
> chore: disable tsx node warning

- docs/docs/blog/legacy-browser.md
`polyfill.io` 原服务由于被收购，现该服务问题频出：
- https://github.com/polyfillpolyfill/polyfill-service/issues/2833
- https://github.com/polyfillpolyfill/polyfill-service/issues/2835
根据 https://github.com/polyfillpolyfill/polyfill-service/issues/2834 与 `polyfil.io` 主要贡献者之一的 [发言](https://twitter.com/triblondon/status/1761852117579427975) 表示，我们应该立即取消使用不安全、不稳定的 `polyfill.io` 。
> docs: remove unstable url

- packages/preset-umi/src/features/routePreloadOnLoad/routePreloadOnLoad.ts
修复 #12095 存在的两个问题：
1. chunk 文件及其依赖遍历拉平的逻辑有问题：
a. chunkFiles 和 chunkMap 写入源不一致，嵌套层级较深时会导致后续 map 访问缺少文件导致报错，之前验证的应用产物比较简单所以没有发现
b. 一个路由文件可能会关联多个 chunk，也就是说不同的 chunk.origins 可能出现相同的文件，原逻辑会导致重复遍历及错误添加不必要的 chunk.files，PR 去掉了不必要的 while 递归遍历，改为基于 origins 文件合并 chunk.files 的方式确保结果正确
2. route 对应的 index 存在重复的问题，改用 Set 防止重复
另外重新梳理了逻辑，提升可读性
> fix(preset-umi): chunk files not found error in route preload feature

- docs/docs/blog/legacy-browser.md
添加 CF 新推出的 polyfill.io 托管服务链接，拥有足够的影响力和访问速度以及可用性。
Refer：https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
> docs: add CF polyfill.io url

- docs/docs/docs/guides/env-variables.md
> docs: update env-variables.md

- packages/preset-umi/src/features/routePreloadOnLoad/utils.ts
导出路由资源预加载 utils 的类型，便于内部工具对该模块进行预打包再分发
> refactor(preset-umi): export route preload types for prebundle

- packages/preset-umi/src/features/routePreloadOnLoad/routePreloadOnLoad.ts
修复子路由资源预加载特性在不必要的情况下也执行所引发的问题：
1. 报错的场景：开启 vite 模式，因为尚未适配 vite 的 stats，先禁用后续再支持
2. 浪费构建耗时：开启 MPA、`routeLoader: cjs` 这两种情况
3. 浪费 HTML 尺寸：`import to require` 的情况
Case 整理自 @fz6m ref: https://github.com/umijs/umi/issues/12185#issuecomment-1985126804
Close #12185
> fix(preset-umi): disable route preload feature if unnecessary

- docs/docs/docs/max/antd.md
添加了对 Antd 运行时配置的一些说明。参考自源码: https://github.com/umijs/umi/blob/b90b8b56cdac4f1425b455358fd3d05a7f144ca4/packages/plugins/src/antd.ts#L385
> docs(antd): conditions for runtime config to take effect

- docs/.dumi/theme/builtins/HashAnchorCompat/index.tsx
- docs/docs/docs/api/runtime-config.md
close #12158
因为：
- https://github.com/umijs/umi/commit/0a666fc535d89d95bb6d71200b1b969081c9c6f5
- https://github.com/umijs/umi/commit/5d64b5c81048647c5804e90de3305d8f87d535a0
以上两个对文档 title 的改动，导致以前的 hash 锚点失效了，大面积历史 url 无法正常跳转。
由于大量历史锚点（特别是 `patchClientRoutes` 等）使用的十分频繁，所以影响面非常大，比较严重。
此 PR 兼容了历史锚点并跳转到新锚点。
注：若以后还需改动 title ，应考虑将跳转逻辑变为 map 映射，防止过多兼容逻辑反复运行的成本。
> docs: compat with old hash anchors

- packages/preset-umi/src/features/ssr/webpack/webpack.ts
修复 ssr 产物构建前，触发 `chainWebpack` 钩子缺少参数的问题，以及加上了 `ssr: true` 的标记便于插件区分当前的 webpack 配置目标
> fix(preset-umi): chainWebpack hook args for ssr bundling

- packages/preset-umi/src/features/exportStatic/exportStatic.ts
修复静态站点预渲染的时候，可能出现错误的 async script 标记的问题，原因是 `markupArgs` 对象被重复使用了，解法是根据是否开启预渲染拆分为 `defaultMarkupArgs` 和 `asyncMarkupArgs`，这样也能避免重复执行带来不必要的开销
ref: #11469 
cc @MadCcc
> fix(preset-umi): wrong async script mark for pre-prendered static site app

- packages/preset-umi/src/commands/dev/getMarkupArgs.ts
修复在大型静态站点应用（比如 antd 官网）中，开启 `exportStatic` 可能导致 `modifyHTML` 钩子 OOM 的问题，原因是 cheerio 默认使用 parse5 作为 HTML 解析器，但在动辄一两百个页面的静态站点应用中 parse5 很容易消耗过量内存导致 OOM，解决方案是将 cheerio 的 HTML 解析器切换为内存开销更小的 `htmlparser2`。
为什么之前 antd 官网没出现 OOM？推测是由于子路由资源预加载方案 #12095 追加了一个 inline script，且站点越大它的尺寸会越大，这成了 OOM 的导火索。
切换 HTML 解析器有什么副作用？此前 cheerio 切换默认解析器是为了解一系列的问题，详见 https://github.com/cheeriojs/cheerio/pull/985 但其中属于缺陷的问题在 htmlparser2 中已经修复，其他已知副作用对 Umi 的场景应该不受影响：
1. 不对 HTML 字符串默认套 `<html><head></head><body></body></html>`
2. 不自动补全标签，例如自动补全 `table` 中的 `tbody`、`tr` 等
3. 不自动转义实体字符，比如 `<div><=</div>` 会原样输出（现代浏览器会正确处理 `<`）
4. 缺少闭合标签的行为不一致，比如 `<ul>1<ul>2<ul>` 会变成嵌套而不是并集
> fix(preset-umi): modifyHTML hook oom in large static site app

- packages/create-umi/templates/plugin/tsconfig.json
来源 https://github.com/umijs/father/issues/746
修复 father 没有添加 tsconfig `include` 设置会构建失败的问题。
> fix(template): tsconfig include source

- packages/plugins/src/layout.ts
想了一下，这个场景：
```
// config.ts
npmClient: "tnpm"
// package.json
tnpm: { mode: "npm" }
```
应该算是预期的场景，期望使用的 npm 工具确实是`tnpm`，比如`installWithNpmClient`确实期望使用`tnpm`进行安装。只不过 layout 这个场景确实需要判断 tnpm.mode 是否是`npm`
> fix: 修复 npmClient 配置为 tnpm，但 tnpm mode 为 npm 时 layout 插件注入绝对路径 types 问题

- packages/bundler-webpack/src/cli.ts
`bundler-webpack  build --config  ../../../../../common/config.js`
`bundler-webpack  build --config /abs/path/to/config.js`
> refactor(bundler-webpack): 🎨 支持使用绝对路径指定配置文件

- examples/ssr-demo/package.json
- examples/ssr-demo/src/layouts/index.tsx
- examples/ssr-demo/src/pages/index.tsx
- packages/server/src/ssr.ts
- pnpm-lock.yaml
1. 在 SSR 渲染时加入 ServerInsertedHTML 上下文，并在流式输出的最后一并拼在末尾
2. 与 React 分段 SSR 处理一样，添加一段 script 把所有 serverInsertedHTML 移动到 head 末尾
测试了 antd 和多个 serverInsertedHTML，SSR 渲染未出现闪烁，可能需要更极端的情况测试。
由于需要将上下文里的内容放置在 head 标签中，当前 chunk 不包含 `</head>` 时就已经无法插入了，因此 Suspense 下的 useServerHTML 会失效，如果等流结束统一处理又会失去流的效果。
> feat: SSR support useServerInsertedHTML

- packages/bundler-webpack/compiled/webpack-5-chain/package.json
- packages/bundler-webpack/compiled/webpack-5-chain/types/index.d.ts
- packages/bundler-webpack/package.json
- pnpm-lock.yaml
close #12382
close #11969
升级依赖（这个依赖包的升级不涉及源码变化，只修复了 types 里的 typo）
> dep: upgrade webpack-5-chain

- packages/preset-umi/src/features/configPlugins/configPlugins.ts
- packages/preset-umi/src/features/mpa/mpa.ts
> feat: support react 19

- packages/preset-umi/src/features/routePreloadOnLoad/routePreloadOnLoad.ts
子路由资源预加载时跳过 absPath 不合法的路由，避免在匹配时出现问题，比如 `*` 会导致正则实例化报错
> refactor(preset-umi): handle illegal route absPath in route preload

- examples/mf-v2-host/package.json
- examples/mf-v2-remote/package.json
- examples/qiankun-master/package.json
- packages/preset-vue/src/features/config/config.ts
修复社区反馈的 requireHook 调整导致的 yarn 安装依赖 vue webpack requireHook 失败
> fix(preset-vue): yarn mode webpack require hook is invalid

- docs/.dumi/components/Hero/index.tsx
首页跳转逻辑有误，手动点击快速上手按钮时，路由会进入/docs/tutorials/getting-started，但页面仍然停留在首页。
修复方案为直接把快速上手按钮的跳转路由改为/docs/guides/getting-started。
tutorials 改为 guides。
> docs: hero link in homepage

- docs/docs/docs/api/config.md
codeSplitting 配置项增加 `null` 值的描述，避免用户误以为是不分包
> docs: describe null value for codeSplitting

- packages/core/src/route/routesConvention.ts
- packages/core/src/route/utils.ts
时间复杂度太高, antv 场景会卡死接近 20 min.
const childRouteIds = routeIds.filter(
(id) => findParentRouteId(routeIds, id) === parentId,
);
这段代码在有 2700 个路由时, 执行时间为 400ms ~ 500ms, 循环百万次, 这里用空间换时间新建 Map 来解决.
> refactor: getConventionRoutes

- packages/preset-umi/src/utils/transformIEAR.ts
#10212 
原因是绝对路径匹配时只匹配了mac 或者linux的/ 开头，而windows 路径开始都是盘符开头（C: D:）等。
> fix: build error when using vite mode on windows

- did-you-know/src/plugin.ts
当指定APP_ROOT，did-you-know插件在创建cacheDir目录时，会抛出异常`No such file or directory`
> fix(did-you-know): 修复mkdirSync可能的报错

- packages/preset-umi/src/features/mako/mako.ts
- packages/preset-umi/src/features/webpack/webpack.ts
- packages/preset-umi/src/utils/extractEntryAssets.ts
Add html plugin for mako, based on https://github.com/umijs/umi/pull/9859.
When use codeSplitting granular, need this plugin to insert entry's dependencies chunks
> feat: add html plugin for mako

- packages/preset-umi/src/features/mako/mako.ts
When building SSR server side, the entry is "umi.server".
> fix: html plugin for mako

- packages/preset-umi/src/features/mako/mako.ts
error:  Error: Cannot find module '@umijs/mako-win32-x64-msvc'
> fix(mako): enable mako on windows failed

- packages/preset-umi/src/features/ssr/ssr.ts
ssr + worker 模式下，本地开发时的 middleware 是无效的，暂时也不支持本地预览，所以先跳过
> feat: skip invalid ssr middleware in dev for worker mode

- packages/preset-umi/src/features/test/test.ts
```text
error - Can not resolve dependence : 'true', please install it
```
loadingComponent should be a path of a component  other than a boolean.
> fix: 🐛 test browser template use wrong loadingComponent value

- examples/with-unocss/.umirc.ts
- packages/plugins/src/unocss.ts
问题如 #12777  描述, 开发模式下，unocss插件并没有等待unocss进程完全启动，导致.umi/uno.css文件还没有生成，而在.umi/umi.ts中已经写了 uno.css的导入，导致启动时报错
> fix #12777 failed to start unocss with mako

- docs/docs/docs/api/api.en-US.md
- docs/docs/docs/api/api.md
- packages/renderer-react/src/browser.tsx
> fix: route preload with Link tag

- docs/docs/docs/max/request.en-US.md
- docs/docs/docs/max/request.md
> docs: add cancel request

- docs/.dumi/components/Contributing/index.less
- docs/.dumi/components/Contributing/index.tsx
> docs: image max-width and height

- docs/docs/docs/max/data-flow.en-US.md
- docs/docs/docs/max/data-flow.md
- packages/plugins/src/model.ts
> feat(plugin/model): support sort

- docs/docs/docs/api/api.en-US.md
- docs/docs/docs/api/api.md
- docs/docs/docs/api/config.en-US.md
- docs/docs/docs/api/config.md
- packages/preset-umi/src/features/routePrefetch/routePrefetch.ts
- packages/renderer-react/src/link.tsx
- packages/renderer-react/src/useIntersectionObserver.ts
> feat: improve link with prefetch

- docs/docs/docs/api/runtime-config.en-US.md
- docs/docs/docs/api/runtime-config.md
- docs/docs/docs/max/data-flow.en-US.md
- docs/docs/docs/max/data-flow.md
1、fix `getInitialState` description
2、named `useModel`  `Page` is inappropriate
> docs: fix getInitialState description

- .github/workflows/ci.yml
- packages/runtime/src/Plugin/Plugin.ts
close https://github.com/umijs/mako/issues/1657
> fix: 🐛 workaround due mako's interop add default to a empty file

- packages/bundler-webpack/compiled/webpack/package.json
一些插件会使用版本号判断兼容 webpack4 和 5，如
https://github.com/webpack-contrib/worker-loader/blob/a37f4b2caff11bb0bad5b54090a6de940504a3cb/src/index.js#L25
```ts
const useWebpack5 = require("webpack/package.json").version.startsWith("5.");
```
这里版本号丢失，会导致程序错误
> fix: webpack version lose

- docs/docs/docs/max/dva.en-US.md
- docs/docs/docs/max/dva.md
https://dvajs.com/变更为https://dva.mxlab.top/
> fix: 更新dva文档中官网url地址

- packages/lint/src/config/stylelint/index.ts
某些用户需要在网页端实现多行文本溢出显示省略号的要求，但在stylelint中被禁止使用供应商前缀。针对该问题，框架层默认禁用该规则。
- 修改前报错效果：
- 复现项目包：
[no-vendor-prefix.zip](https://github.com/user-attachments/files/18408620/no-vendor-prefix.zip)
> chore: stylelint-value-no-vendor-prefix

- docs/docs/docs/guides/env-variables.en-US.md
- docs/docs/docs/guides/env-variables.md
- packages/preset-umi/src/commands/dev/dev.ts
> feat(dev): add STRICT_PORT environment variable for port availability check

- docs/docs/docs/max/tailwindcss.md
- packages/plugins/src/tailwindcss.ts
> feat(tailwindcss): support config CHECK_TIMEOUT
