packages/core/src/Service/Service.ts
packages/core/src/Service/enums.ts

fix spell error 
Close https://github.com/umijs/umi/issues/4700

fix: uninitialized spell error

---

docs/docs/contributing.md
package.json
yarn.lock

- any feature?
-----
[View rendered docs/docs/contributing.md](https://github.com/umijs/umi/blob/chore-update-dumi/docs/docs/contributing.md)

chore: update dumi

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts

这样可以被 `api.modifyDefaultConfig` 改了
- any feature?

chore: ssr enableBy in modifyDefaultConfig

---

docs/plugins/api.md
docs/plugins/api.zh-CN.md
packages/preset-built-in/src/fixtures/api-writeTmpFile-ts-check/plugin.js
packages/preset-built-in/src/fixtures/api-writeTmpFile-ts/plugin.js
packages/preset-built-in/src/fixtures/api-writeTmpFile/plugin.js
packages/preset-built-in/src/index.test.ts
packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts
packages/preset-built-in/src/plugins/commands/build/build.ts
packages/preset-built-in/src/plugins/commands/dev/mock/createMiddleware.ts
packages/preset-built-in/src/plugins/commands/dev/mock/utils.ts
packages/preset-built-in/src/plugins/features/exportStatic.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/registerMethods.ts
packages/preset-built-in/src/plugins/utils.test.ts
packages/preset-built-in/src/plugins/utils.ts
packages/types/index.d.ts

feat: fork ts support

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/bundler-webpack/src/getConfig/getConfig.ts
packages/types/index.d.ts

chore: chainWebpack without type param

---

packages/preset-built-in/src/plugins/features/exportStatic.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.ts
packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts

Close https://github.com/umijs/umi/issues/4747
- any feature?

fix: ssr load all chunks when enable dynamicImport

---

examples/ssr-with-eggjs/README.md
examples/ssr-with-eggjs/package.json

- any feature?
-----
[View rendered examples/ssr-with-eggjs/README.md](https://github.com/rockhentai/umi/blob/master/examples/ssr-with-eggjs/README.md)

docs: add build script

---

docs/guide/plugin-develop.zh-CN.md

文档修正
- any feature?
-----
[View rendered docs/guide/plugin-develop.zh-CN.md](https://github.com/linyongkangm/umi/blob/patch-1/docs/guide/plugin-develop.zh-CN.md)

docs: Update plugin-develop.zh-CN.md

---

docs/docs/ssr.md

- any feature?
-----
[View rendered docs/docs/ssr.md](https://github.com/umijs/umi/blob/afc163-patch-1/docs/docs/ssr.md)

docs: Update ssr.md

---

.gitattributes

忽略某些文件作为 Github 仓库语言探测
- any feature?

chore: language detect

---

packages/babel-plugin-import-to-await-require/README.md
packages/babel-plugin-import-to-await-require/package.json
packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts
packages/babel-preset-umi/package.json
packages/babel-preset-umi/src/index.test.ts
packages/babel-preset-umi/src/index.ts
packages/preset-built-in/src/plugins/generateFiles/umi.ts
packages/runtime/src/dynamic/loadable.test.tsx
yarn.lock

- any feature?
-----
[View rendered packages/babel-plugin-import-to-await-require/README.md](https://github.com/umijs/umi/blob/feat/babel-plugin-import-to-await-require/packages/babel-plugin-import-to-await-require/README.md)

feat: babel-plugin-import-to-await-require

---

packages/preset-built-in/src/plugins/features/devScripts.ts

Close https://github.com/umijs/umi/issues/4601
- any feature?

fix: HMR dev bug

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

feat(babel-plugin-import-to-await-require): support alias and ImportNamespaceSpecifier

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

feat(babel-plugin-import-to-await-require): support export syntax

---

packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl
packages/preset-built-in/src/plugins/generateFiles/umi.tpl
packages/renderer-react/src/renderClient/renderClient.tsx
packages/renderer-react/src/renderRoutes/renderRoutes.tsx

chore(renderer-react): make it pure

---

packages/preset-built-in/src/plugins/generateFiles/umi.tpl

feat: support hmr with async routes module

---

docs/plugins/plugin-dva.md
docs/plugins/plugin-dva.zh-CN.md

- 增加 dva 运行时配置说明
- close https://github.com/umijs/umi/issues/4233

docs: plugin-dva.md dva 运行时配置

---

packages/preset-built-in/src/plugins/generateFiles/core/plugin.tpl
packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts

chore: use import for plugin generation

---

examples/ssr-with-eggjs/tsconfig.json

- added `tsconfig.json` in `examples/srr-with-eggjs`
- `tsconfig.json` was copied from project generated by command `npm init egg --type=ts`
- close https://github.com/umijs/umi/issues/4786

chore: add tsconfig.json in examples/srr-with-eggjs

---

docs/docs/html-template.zh-CN.md

close https://github.com/umijs/umi/issues/4674
-----
[View rendered docs/docs/html-template.zh-CN.md](https://github.com/kyo4311/umi/blob/patch-1/docs/docs/html-template.zh-CN.md)

docs: 修改默认模板时增加配置title提示。

---

packages/bundler-webpack/src/webpackHotDevClient/webpackHotDevClient.ts

feat: server support force reload page

---

docs/docs/ssr.md
docs/docs/ssr.zh-CN.md
docs/plugins/api.md
docs/plugins/api.zh-CN.md

- 更新部分 markdown 代码样式
-----
[View rendered docs/docs/ssr.md](https://github.com/GoodbyeNJN/umi/blob/master/docs/docs/ssr.md)
[View rendered docs/docs/ssr.zh-CN.md](https://github.com/GoodbyeNJN/umi/blob/master/docs/docs/ssr.zh-CN.md)
[View rendered docs/plugins/api.md](https://github.com/GoodbyeNJN/umi/blob/master/docs/plugins/api.md)
[View rendered docs/plugins/api.zh-CN.md](https://github.com/GoodbyeNJN/umi/blob/master/docs/plugins/api.zh-CN.md)

docs: update some code styles

---

docs/docs/how-umi-works.zh-CN.md

- any feature?
-----
[View rendered docs/docs/how-umi-works.zh-CN.md](https://github.com/VSirrr/umi/blob/patch-1/docs/docs/how-umi-works.zh-CN.md)

docs: 将“完整”修改为“完成”

---

packages/create-umi-app/templates/AppGenerator/package.json.tpl

- 修复脚手架缺失 @ant-design/pro-layout 依赖的问题
- close #4746
- close #4704

fix(create-umi-app): pro-layout dep lost

---

packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.tsx
packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts

- 调整 scripts 在 root 后，利于 SEO
- 修复 Stream 渲染匹配 bug
- any feature?

chore: ssr scripts behind root html

---

packages/bundler-webpack/src/getConfig/nodeModulesTransform.ts

fix(bundler-webpack): rule include throw error when no package.json

---

docs/docs/ssr.md
docs/docs/ssr.zh-CN.md
packages/preset-built-in/src/fixtures/ssr-beforeRenderServer/.umirc.ts
packages/preset-built-in/src/fixtures/ssr-beforeRenderServer/app.ts
packages/preset-built-in/src/fixtures/ssr-beforeRenderServer/pages/index.tsx
packages/preset-built-in/src/index.test.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/features/ssr/templates/renderServer/renderServer.tsx
packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl
packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.ts
packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts
packages/renderer-react/src/renderRoutes/renderRoutes.tsx

- any feature?
-----
[View rendered docs/docs/ssr.md](https://github.com/umijs/umi/blob/feat-ssr-beforeRenderServer/docs/docs/ssr.md)
[View rendered docs/docs/ssr.zh-CN.md](https://github.com/umijs/umi/blob/feat-ssr-beforeRenderServer/docs/docs/ssr.zh-CN.md)

feat: support ssr.beforeRenderServer hook for polyfill

---

docs/docs/cli.md
docs/docs/cli.zh-CN.md

- any feature?
-----
[View rendered docs/docs/cli.md](https://github.com/edtam/umi/blob/docs-fix-typo/docs/docs/cli.md)
[View rendered docs/docs/cli.zh-CN.md](https://github.com/edtam/umi/blob/docs-fix-typo/docs/docs/cli.zh-CN.md)

docs: fix typo

---

packages/types/index.d.ts

fix(types): babel plugin and preset could be Function

---

docs/docs/deployment.md
docs/docs/deployment.zh-CN.md
docs/docs/navigate-between-pages.zh-CN.md

- [x ] documentation is changed or added
- [x ] commit message follows commit guidelines
- 中文文档地址有误，zh -> zh-CN
- qiankun 的文档也有误，但似乎本身还没写完，所以就没改
-----
[View rendered docs/docs/deployment.md](https://github.com/hbrls/umi/blob/master/docs/docs/deployment.md)
[View rendered docs/docs/deployment.zh-CN.md](https://github.com/hbrls/umi/blob/master/docs/docs/deployment.zh-CN.md)
[View rendered docs/docs/navigate-between-pages.zh-CN.md](https://github.com/hbrls/umi/blob/master/docs/docs/navigate-between-pages.zh-CN.md)

docs: zh -> zh-CN

---

docs/plugins/plugin-dva.md
docs/plugins/plugin-dva.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-dva.md](https://github.com/mytheart/umi/blob/fix_dva_redux-logger/docs/plugins/plugin-dva.md)
[View rendered docs/plugins/plugin-dva.zh-CN.md](https://github.com/mytheart/umi/blob/fix_dva_redux-logger/docs/plugins/plugin-dva.zh-CN.md)

docs: redux-logger usage

---

packages/preset-built-in/src/plugins/generateFiles/core/plugin.tpl
packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts

Revert "chore: use import for plugin generation"

---

docs/plugins/plugin-request.md
docs/plugins/plugin-request.zh-CN.md

- 依赖 https://github.com/umijs/plugins/pull/262

chore: umi hooks to ahooks

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts

ref: https://github.com/umijs/umi/pull/4845
- any feature?

chore: ssr html hash

---

docs/plugins/api.md

- any feature?
-----
[View rendered docs/plugins/api.md](https://github.com/zollero/umi/blob/patch-2/docs/plugins/api.md)

docs: type error

---

docs/plugins/api.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/api.zh-CN.md](https://github.com/zollero/umi/blob/patch-1/docs/plugins/api.zh-CN.md)

docs: api type error

---

packages/preset-built-in/src/plugins/generateFiles/umi.tpl

Revert "feat: support hmr with async routes module"

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/preset-built-in/src/index.ts
packages/preset-built-in/src/plugins/features/runtimeHistory.ts
packages/preset-built-in/src/plugins/generateFiles/core/history.runtime.tpl
packages/preset-built-in/src/plugins/generateFiles/core/history.tpl
packages/preset-built-in/src/plugins/generateFiles/core/history.ts
packages/types/index.d.ts

- 支持动态修改 history 类型及属性，见：https://github.com/umijs/plugins/pull/267

feat: 支持动态修改 history 类型及属性

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/docs/fix-qiankun/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/docs/fix-qiankun/docs/plugins/plugin-qiankun.zh-CN.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/4934)

docs(qiankun): fix typo and add useModel link

---

packages/core/src/Service/Service.test.ts
packages/core/src/Service/Service.ts
packages/core/src/Service/fixtures/asyncPluginRegister/foo.js
packages/core/src/Service/utils/isPromise.ts

feat: support async plugin register

---

docs/plugins/api.zh-CN.md

[View rendered docs/plugins/api.zh-CN.md](https://github.com/Ariel-Cheng/umi/commit/5e5691e2c847a56bdbd8f57456eeeddaeae143e9)
-----
[View rendered docs/plugins/api.zh-CN.md](https://github.com/Ariel-Cheng/umi/blob/docs/plugin-api/docs/plugins/api.zh-CN.md)

doc: update docs for plugin api

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

pending by https://github.com/umijs/plugins/pull/284 release
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/feat/finish-todo/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/feat/finish-todo/docs/plugins/plugin-qiankun.zh-CN.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/4951)

docs(qiankun): finish stuff in roadmap

---

packages/bundler-webpack/package.json
packages/types/package.json
yarn.lock

- upgrade webpack-chain to 6.5.0 for rule.resolve support https://github.com/neutrinojs/webpack-chain/pull/265

dep: upgrade webpack-chain@6.5.0 for rule.resolve support

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

null
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/chore/typo/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/chore/typo/docs/plugins/plugin-qiankun.zh-CN.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/4971)

chore(qiankun): typo

---

packages/babel-preset-umi/src/index.ts

feat(babel-preset-umi): support modify with fn

---

package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/utils/package.json
yarn.lock

dep: upgrade fork-ts-checker-webpack-plugin@5, immer@7

---

packages/preset-built-in/src/plugins/features/forkTSChecker.ts

https://github.com/umijs/umi/pull/4976
fork-ts-checker-webpack-plugin 从 4.x 升级到 5.0.6 后，options 有修改
- any feature?

fix: fork-ts-webpack-plugin options

---

packages/types/index.d.ts

fix(types): duplicated stream import

---

docs/docs/convention-routing.md
docs/docs/convention-routing.zh-CN.md
docs/docs/routing.md
docs/docs/routing.zh-CN.md

doc improvement of routing
-----
[View rendered docs/docs/convention-routing.md](https://github.com/leftstick/umi/blob/master/docs/docs/convention-routing.md)
[View rendered docs/docs/convention-routing.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/docs/convention-routing.zh-CN.md)
[View rendered docs/docs/routing.md](https://github.com/leftstick/umi/blob/master/docs/docs/routing.md)
[View rendered docs/docs/routing.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/docs/routing.zh-CN.md)

docs: improvement of routing

---

docs/config/README.md
docs/config/README.zh-CN.md

- 完善`metas`配置说明文档
-----
[View rendered docs/config/README.md](https://github.com/7kms/umi/blob/master/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/7kms/umi/blob/master/docs/config/README.zh-CN.md)

docs: update metas config description

---

examples/ssr-koa/server.js

chore: ssr-koa server example

---

packages/preset-built-in/src/plugins/features/exportStatic.ts

chore: SSG keep server file when failed

---

package.json
packages/bundler-webpack/package.json
packages/core/package.json
packages/server/package.json
yarn.lock

dep: upgrade less to 3.12

---

packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl

fix beforeRenderServer not working, before routes require
- any feature?

fix(ssr): beforeRenderServer before routes require

---

docs/docs/deployment.zh-CN.md

docs: fix code highlight

---

examples/ssr-koa/src/app.js

docs: koa-ssr 示例的注释错别字

---

packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts

- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5108)

fix(runtime-config): add modifyClientRenderOpts to runtime plugin keys

---

packages/preset-built-in/src/plugins/features/exportStatic.ts

chore: prerender path error log

---

docs/docs/ssr.md
docs/docs/ssr.zh-CN.md
docs/docs/ssrUsers.tsx

- any feature?
-----
[View rendered docs/docs/ssr.md](https://github.com/umijs/umi/blob/docs-ssr-demo/docs/docs/ssr.md)
[View rendered docs/docs/ssr.zh-CN.md](https://github.com/umijs/umi/blob/docs-ssr-demo/docs/docs/ssr.zh-CN.md)

docs: ssr users

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/generateFiles/umi.tpl
packages/preset-built-in/src/plugins/generateFiles/umi.ts
packages/renderer-react/src/renderClient/renderClient.test.tsx
packages/renderer-react/src/renderRoutes/renderRoutes.test.tsx
packages/renderer-react/src/renderRoutes/renderRoutes.tsx

Close https://github.com/umijs/umi/issues/4891
Close https://github.com/umijs/umi/issues/4104
- any feature?

fix: dynamicImport rerender

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts

tweak: ssr perf duration time

---

docs/plugins/api.md
docs/plugins/api.zh-CN.md

- any feature?
Close: https://github.com/umijs/umi/issues/5113
-----
[View rendered docs/plugins/api.md](https://github.com/umijs/umi/blob/docs-add-plugin-API-reference-doc/docs/plugins/api.md)
[View rendered docs/plugins/api.zh-CN.md](https://github.com/umijs/umi/blob/docs-add-plugin-API-reference-doc/docs/plugins/api.zh-CN.md)

docs: add plugin api reference

---

packages/types/index.d.ts

- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5140)

feat(types): export BaseIConfig interface

---

docs/docs/ssrUsers.tsx

docs: alipay ac

---

packages/renderer-react/src/index.ts

add missing field

---

examples/ssr-koa/package.json
examples/ssr-koa/server.js
examples/ssr-with-eggjs/.gitignore
examples/ssr-with-eggjs/app/controller/home.js
examples/ssr-with-eggjs/app/view/index.html
examples/ssr-with-eggjs/app/web/config/config.ts
examples/ssr-with-eggjs/config/config.default.js
examples/ssr-with-eggjs/config/config.local.js
examples/ssr-with-eggjs/config/plugin.js
examples/ssr-with-eggjs/package.json
packages/preset-built-in/src/plugins/features/manifest.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts

fix: SSR dev 模式下 require 缓存带来的 OOM 问题

---

docs/plugins/plugin-antd.md

- any feature?
-----
[View rendered docs/plugins/plugin-antd.md](https://github.com/umijs/umi/blob/xiaohuoni-patch-2/docs/plugins/plugin-antd.md)

docs: add antd plugin config

---

docs/docs/ssrUsers.tsx

docs: ssr cases

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/chore/qiankun-doc/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/chore/qiankun-doc/docs/plugins/plugin-qiankun.zh-CN.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5189)

doc(qiankun): update qiankun plugin doc

---

packages/server/src/Server/Server.ts

to fix #4540 #4539 #4537 #4527

fix: dev server proxy with onProxyRes

---

package.json
packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl
packages/preset-built-in/src/plugins/generateFiles/core/plugin.tpl
packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts
packages/preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl
packages/preset-built-in/src/plugins/generateFiles/umi.tpl

- 重新实现 #4789 和 #4794
- 修复 plugin 未初始化好之前 undefined 的问题

feat: use import syntax(esm) for plugin and routes

---

docs/plugins/api.md
docs/plugins/api.zh-CN.md
packages/preset-built-in/src/plugins/generateFiles/constants.ts
packages/preset-built-in/src/plugins/generateFiles/core/history.ts
packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts
packages/preset-built-in/src/plugins/generateFiles/core/routes.ts
packages/preset-built-in/src/plugins/generateFiles/umi.ts
packages/preset-built-in/src/plugins/registerMethods.ts
packages/types/index.d.ts

- 提速方案需要，Umi 内部和插件里的依赖信息需要收集起来
-----
[View rendered docs/plugins/api.md](https://github.com/umijs/umi/blob/feat/api-modifyDepInfo/docs/plugins/api.md)
[View rendered docs/plugins/api.zh-CN.md](https://github.com/umijs/umi/blob/feat/api-modifyDepInfo/docs/plugins/api.zh-CN.md)

feat: new plugin api, api.modifyDepInfo

---

docs/plugins/plugin-locale.md

Reverts umijs/umi#5155
-----
[View rendered docs/plugins/plugin-locale.md](https://github.com/umijs/umi/blob/revert-5155-patch-1/docs/plugins/plugin-locale.md)

Revert "Update plugin-locale.md"

---

docs/docs/faq.md
docs/guide/migrating-create-react-app-to-umi.md
docs/guide/migrating-create-react-app-to-umi.zh-CN.md

- any feature?
Close: https://github.com/umijs/umi/issues/3601
-----
[View rendered docs/docs/faq.md](https://github.com/umijs/umi/blob/docs-Migrating-create-react-app-to-umi/docs/docs/faq.md)
[View rendered docs/guide/migrating-create-react-app-to-umi.md](https://github.com/umijs/umi/blob/docs-Migrating-create-react-app-to-umi/docs/guide/migrating-create-react-app-to-umi.md)
[View rendered docs/guide/migrating-create-react-app-to-umi.zh-CN.md](https://github.com/umijs/umi/blob/docs-Migrating-create-react-app-to-umi/docs/guide/migrating-create-react-app-to-umi.zh-CN.md)

docs: migrating-create-react-app-to-umi

---

packages/preset-built-in/src/plugins/generateFiles/core/routes.tpl
packages/preset-built-in/src/plugins/generateFiles/umi.tpl

refactor: use function to get routes

---

packages/bundler-webpack/src/getConfig/getConfig.ts

fix: umi dir undefined in ci

---

packages/preset-built-in/src/plugins/registerMethods.ts

fix: webpack compile multiple times after files changed

---

packages/preset-built-in/src/plugins/generateFiles/umi.tpl

fix: patchRoutes should be after render

---

packages/core/src/Html/Html.ts

Close https://github.com/umijs/umi/issues/5236
- any feature?

fix: Chinese html encoding in build

---

docs/docs/routing.md

- any feature?
-----
[View rendered docs/docs/routing.md](https://github.com/marcosalberto/umi/blob/patch-1/docs/docs/routing.md)

Translate routing.md to English

---

docs/docs/env-variables.zh-CN.md

- any feature?
-----
[View rendered docs/docs/env-variables.zh-CN.md](https://github.com/zhanyuzhang/umi/blob/patch-1/docs/docs/env-variables.zh-CN.md)

删除重复文字“默认”

---

packages/preset-built-in/src/plugins/features/devScripts.ts

- any feature?
- close https://github.com/umijs/umi/issues/4441

fix: process.env.SOCKET_SERVER config not working 

---

packages/babel-plugin-import-to-await-require/src/index.ts

feat(babel-plugin-import-to-await-require): add hook onTransformDeps

---

packages/preset-built-in/src/plugins/features/devScripts.ts

- any feature?
- fix writing errors for https://github.com/umijs/umi/pull/5288

fix(dev-scripts): fix SOCKET_SERVER replace error

---

docs/docs/env-variables.md
docs/docs/env-variables.zh-CN.md
packages/bundler-webpack/package.json
packages/bundler-webpack/src/getConfig/getConfig.ts

feat: webpack profile plugin

---

packages/bundler-webpack/package.json
yarn.lock

fix(bundler-webpack): terser-webpack-plugin dep lost

---

packages/bundler-webpack/mini-css-extract-plugin/.fatherrc-next.ts
packages/bundler-webpack/mini-css-extract-plugin/dist/CssDependency.js
packages/bundler-webpack/mini-css-extract-plugin/dist/cjs.js
packages/bundler-webpack/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js
packages/bundler-webpack/mini-css-extract-plugin/dist/index.js
packages/bundler-webpack/mini-css-extract-plugin/dist/loader.js
packages/bundler-webpack/mini-css-extract-plugin/dist/options.json
packages/bundler-webpack/mini-css-extract-plugin/package.json
packages/bundler-webpack/mini-css-extract-plugin/src/hmr/hotModuleReplacement.js
packages/bundler-webpack/mini-css-extract-plugin/src/index.js
packages/bundler-webpack/mini-css-extract-plugin/src/loader.js
packages/bundler-webpack/package.json
packages/bundler-webpack/src/getConfig/css.ts
packages/bundler-webpack/src/getConfig/getConfig.test.ts
packages/bundler-webpack/src/getConfig/getConfig.ts

fix: built-in mini-css-extract-plugin

---

docs/plugins/plugin-qiankun.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/doc/plugin-qiankun-fix/docs/plugins/plugin-qiankun.md)

doc: reset plugin-qiankun doc

---

docs/docs/env-variables.md
docs/docs/env-variables.zh-CN.md

- any feature?
-----
[View rendered docs/docs/env-variables.md](https://github.com/umijs/umi/blob/docs-stats/docs/docs/env-variables.md)
[View rendered docs/docs/env-variables.zh-CN.md](https://github.com/umijs/umi/blob/docs-stats/docs/docs/env-variables.zh-CN.md)

docs: profile

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- 修复 `@umijs/plugin-qiankun` 例子里面多了一个中括号的问题
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/mortalYoung/umi/blob/fix/typo/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/mortalYoung/umi/blob/fix/typo/docs/plugins/plugin-qiankun.zh-CN.md)

fix(plugins): improve plugin-qiankun examples

---

.circleci/config.yml
examples/ssr-koa/package.json
examples/ssr-koa/server.js
yarn.lock

Close https://github.com/umijs/umi/issues/5350
Clsoe https://github.com/umijs/umi/issues/5345
- any feature?

fix: koa ssr demo

---

packages/core/src/Route/routesToJSON.test.ts
packages/core/src/Route/routesToJSON.ts

feat: use esm for wrappers when dynamicImport is configured

---

docs/docs/convention-routing.md

Translated `convention-routing.md` to English.
-----
[View rendered docs/docs/convention-routing.md](https://github.com/MasterCarl/umi/blob/patch-1/docs/docs/convention-routing.md)

Translate `convention-routing.md` to English

---

docs/guide/upgrade-antd-pro-to-umi-3.md
docs/guide/upgrade-antd-pro-to-umi-3.zh-CN.md
docs/plugins/plugin-locale.md
docs/plugins/plugin-locale.zh-CN.md

- any feature?
-----
[View rendered docs/guide/upgrade-antd-pro-to-umi-3.md](https://github.com/luckymore/umi/blob/master/docs/guide/upgrade-antd-pro-to-umi-3.md)
[View rendered docs/guide/upgrade-antd-pro-to-umi-3.zh-CN.md](https://github.com/luckymore/umi/blob/master/docs/guide/upgrade-antd-pro-to-umi-3.zh-CN.md)
[View rendered docs/plugins/plugin-locale.md](https://github.com/luckymore/umi/blob/master/docs/plugins/plugin-locale.md)
[View rendered docs/plugins/plugin-locale.zh-CN.md](https://github.com/luckymore/umi/blob/master/docs/plugins/plugin-locale.zh-CN.md)

:memo: docs(plugins): link not exist because the branch name 'main'

---

examples/ssr-koa/server.js

fix: ssr compress

---

docs/docs/faq.md
docs/docs/faq.zh-CN.md

修改FAQ中关于loading的描述错误，并且修改title的方法换成了使用插件。
- any feature?
https://github.com/umijs/umi/issues/5361#issuecomment-687990560
-----
[View rendered docs/docs/faq.md](https://github.com/umijs/umi/blob/fix-faq-error/docs/docs/faq.md)
[View rendered docs/docs/faq.zh-CN.md](https://github.com/umijs/umi/blob/fix-faq-error/docs/docs/faq.zh-CN.md)

fix: faq error

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl

Close https://github.com/umijs/umi/issues/5300
Close https://github.com/umijs/umi/issues/5376
Close https://github.com/umijs/umi/pull/5391
- any feature?

fix(SSR): LoadingComponent undefined while enabling dynamicImport

---

packages/bundler-utils/package.json
packages/bundler-utils/src/getBabelOpts.test.ts
packages/bundler-utils/src/getBabelOpts.ts

Close: https://github.com/umijs/umi/issues/5356

fix: babel cache directory error when use APP_ROOT

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/bundler-webpack/src/fixtures/copy/config.ts
packages/bundler-webpack/src/fixtures/copy/expect.ts
packages/bundler-webpack/src/getConfig/getConfig.ts
packages/preset-built-in/src/plugins/features/copy.ts
packages/types/index.d.ts

- any feature?
Close: https://github.com/umijs/umi/issues/5277

feat: copy config support from-to

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5452)

doc(qiankun): add loading doc

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5455)

doc: fix qiankun autoSetLoading introduction

---

packages/preset-built-in/src/plugins/generateFiles/core/history.runtime.tpl
packages/preset-built-in/src/plugins/generateFiles/core/history.ts

- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5457)

feat: add getCreateHistoryOptions api to get runtime history options

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/5459)

doc: 增加微应用引入提示

---

docs/docs/routing.md
docs/docs/routing.zh-CN.md

- any feature?
-----
[View rendered docs/docs/routing.md](https://github.com/kaoding/umi/blob/master/docs/docs/routing.md)
[View rendered docs/docs/routing.zh-CN.md](https://github.com/kaoding/umi/blob/master/docs/docs/routing.zh-CN.md)

doc: routing exact default true

---

modules.d.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts

Close https://github.com/umijs/umi/issues/5501
- any feature?

fix: ssr dev hot fresh bug

---

docs/config/README.md
docs/config/README.zh-CN.md

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/ppxu/umi/blob/master/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/ppxu/umi/blob/master/docs/config/README.zh-CN.md)

docs: update config scripts link

---

docs/docs/runtime-config.md

fix a spell mistake
just fix a spell mistake in documentation, no source code was involved.
- any feature?
-----
[View rendered docs/docs/runtime-config.md](https://github.com/yorshka20/umi/blob/patch-1/docs/docs/runtime-config.md)

docs: Update runtime-config.md

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
- close https://github.com/umijs/plugins/issues/397
-----

doc: use another variable name to avoid conflict

---

packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
packages/umi-ui/yarn.lock

fix(umi-ui): GUmiUIFlag blacklist support React.createElement

---

README.md

- Change 飞猪 to Fliggy that may be better
-----
[View rendered README.md](https://github.com/FishPlusOrange/umi/blob/fix/optimize-readme/README.md)

docs: change 飞猪 to Fliggy

---

docs/docs/getting-started.md

'Local authentication' is a misleading term that could suggest user that app at this point authenticates user somehow.
-----
[View rendered docs/docs/getting-started.md](https://github.com/chomamateusz/umi/blob/patch-1/docs/docs/getting-started.md)

Local verification not authentication

---

docs/config/README.md
docs/config/README.zh-CN.md

- Fix punctuation typo
-----
[View rendered docs/config/README.zh-CN.md](https://github.com/xrkffgg/umi/blob/patch-1/docs/config/README.zh-CN.md)

docs: fix punctuation typo

---

packages/types/index.d.ts

copy 的类型是数组里面包括string或者ICopy类型, 而不是数组第一项必须为string

fix: copy type

---

docs/docs/directory-structure.md

change 'outpput' to 'output'
- any feature?
-----
[View rendered docs/docs/directory-structure.md](https://github.com/Verena99/umi/blob/patch-1/docs/docs/directory-structure.md)

'output' was written as 'outpput' incorrectly

---

azure-pipelines.yml
packages/bundler-webpack/src/getConfig/getConfig.ts

Close https://github.com/umijs/umi/issues/5594
Close https://github.com/umijs/umi/issues/4190
Close https://github.com/umijs/umi/issues/4786
Close https://github.com/umijs/umi/issues/4834
- any feature?

fix: missing module loader when using APP_ROOT

---

docs/config/README.md

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/kuigoo/umi/blob/patch-1/docs/config/README.md)

docs: change 'ignoreMomentLocale' type to 'boolean'

---

packages/preset-built-in/package.json
packages/runtime/package.json
yarn.lock

fix: history query lose types

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/preset-built-in/src/plugins/commands/htmlUtils.ts

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/fix-runtimePublicPath-with-egg/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/fix-runtimePublicPath-with-egg/docs/config/README.zh-CN.md)

fix: runtimePublicPath with eggjs when using dynamicImport

---

.prettierrc
docs/plugins/plugin-layout.md
docs/plugins/plugin-layout.zh-CN.md
docs/plugins/plugin-locale.md
docs/plugins/plugin-locale.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-layout.md](https://github.com/umijs/umi/blob/docs-layout/docs/plugins/plugin-layout.md)
[View rendered docs/plugins/plugin-layout.zh-CN.md](https://github.com/umijs/umi/blob/docs-layout/docs/plugins/plugin-layout.zh-CN.md)
[View rendered docs/plugins/plugin-locale.md](https://github.com/umijs/umi/blob/docs-layout/docs/plugins/plugin-locale.md)
[View rendered docs/plugins/plugin-locale.zh-CN.md](https://github.com/umijs/umi/blob/docs-layout/docs/plugins/plugin-locale.zh-CN.md)

📖 docs(layout): 修改文档，使其符合现在的推荐用法

---

.circleci/config.yml
.github/workflows/benchmark.yml
.github/workflows/ci.yml
azure-pipelines.yml
jest.config.js
packages/bundler-webpack/src/index.test.ts

ref: https://github.com/terser/terser/pull/872
- any feature?

chore: test build oom

---

docs/docs/convention-routing.md

- any feature?
-----
[View rendered docs/docs/convention-routing.md](https://github.com/Rezahasani1378/umi/blob/patch-1/docs/docs/convention-routing.md)

Added 'routes' to routing arrays

---

packages/bundler-webpack/package.json
yarn.lock

chore: upgrade terser plugin

---

packages/runtime/src/dynamic/loadable.js

chore: print error when dynamic load component failed

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/docs/qiankun/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/docs/qiankun/docs/plugins/plugin-qiankun.zh-CN.md)

docs(qiankun): 新增运行时配置微应用路由文档

---

docs/config/README.md
docs/config/README.zh-CN.md
docs/guide/boost-compile-speed.md
docs/guide/boost-compile-speed.zh-CN.md

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/docs-splitChunks/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/docs-splitChunks/docs/config/README.zh-CN.md)
[View rendered docs/guide/boost-compile-speed.md](https://github.com/umijs/umi/blob/docs-splitChunks/docs/guide/boost-compile-speed.md)
[View rendered docs/guide/boost-compile-speed.zh-CN.md](https://github.com/umijs/umi/blob/docs-splitChunks/docs/guide/boost-compile-speed.zh-CN.md)

docs: splitChunks using minimize will oom

---

docs/config/README.md
docs/config/README.zh-CN.md

Close https://github.com/umijs/umi/issues/5708
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/fix-secondary-layer-routes/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/fix-secondary-layer-routes/docs/config/README.zh-CN.md)

docs: publicPath doc

---

docs/docs/faq.md
docs/docs/faq.zh-CN.md

- any feature?
-----
[View rendered docs/docs/faq.md](https://github.com/umijs/umi/blob/docs-module-faq/docs/docs/faq.md)
[View rendered docs/docs/faq.zh-CN.md](https://github.com/umijs/umi/blob/docs-module-faq/docs/docs/faq.zh-CN.md)

docs: cannot assign exports faq

---

docs/plugins/plugin-dva.zh-CN.md

fix: typo
- any feature?
-----
[View rendered docs/plugins/plugin-dva.zh-CN.md](https://github.com/JackLLLLL/umi/blob/patch-1/docs/plugins/plugin-dva.zh-CN.md)

Update plugin-dva.zh-CN.md, fix typo

---

package.json
yarn.lock

chore: upgrade father-build 1.19

---

docs/docs/faq.md
docs/docs/faq.zh-CN.md

Close https://github.com/umijs/umi/issues/5742
- any feature?
-----
[View rendered docs/docs/faq.md](https://github.com/umijs/umi/blob/docs-react-17/docs/docs/faq.md)
[View rendered docs/docs/faq.zh-CN.md](https://github.com/umijs/umi/blob/docs-react-17/docs/docs/faq.zh-CN.md)

docs: react 17

---

docs/docs/faq.md
docs/docs/faq.zh-CN.md

HTML 标签会被转移为 JSX 进行编译，所以书写的时候如果不需要渲染，则需要使用 `&lt;` `&gt;` 转译一下，否则会导致编译失败
-----
[View rendered docs/docs/faq.md](https://github.com/umijs/umi/blob/support/fix-doc-deploy/docs/docs/faq.md)
[View rendered docs/docs/faq.zh-CN.md](https://github.com/umijs/umi/blob/support/fix-doc-deploy/docs/docs/faq.zh-CN.md)

docs: use html entities to avoid deploy error

---

.github/workflows/now.yml
now.json

chore: now

---

.github/workflows/now.yml
now.json

chore: now deploy

---

docs/guide/boost-compile-speed.md
docs/guide/boost-compile-speed.zh-CN.md

- any feature?
-----
[View rendered docs/guide/boost-compile-speed.md](https://github.com/umijs/umi/blob/docs-monaco-plugin/docs/guide/boost-compile-speed.md)
[View rendered docs/guide/boost-compile-speed.zh-CN.md](https://github.com/umijs/umi/blob/docs-monaco-plugin/docs/guide/boost-compile-speed.zh-CN.md)

docs: monaco-editor

---

packages/bundler-webpack/src/fixtures/less/b.less
packages/bundler-webpack/src/fixtures/less/expect.ts

ref: https://github.com/postcss/autoprefixer/issues/776
- any feature?

chore: add box-orient css test case

---

docs/plugins/plugin-qiankun.zh-CN.md

change the line 28 `cd packages/plguin-qiankun && yarn start` to `cd packages/plugin-qiankun && yarn start`
- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/hackers267/umi/blob/patch-2/docs/plugins/plugin-qiankun.zh-CN.md)

docs: qiankun the spelling mistake

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml

```yml
paths-ignore:
- '.github/**/*.md'
- 'examples/**'
- 'docs/**'
- '*.md'
```

chore: skip workflows via paths-ignore

---

packages/server/package.json
packages/server/src/index.test.ts
packages/server/src/index.ts
yarn.lock

chore: export proxy middleware from umi-server

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/getConfig/getConfig.ts
packages/preset-built-in/package.json
yarn.lock

chore(webpack): upgrade plugins support webpack 5

---

packages/types/index.d.ts

copy 的类型是数组里面包括string或者ICopy类型, 而不是数组只能有一个元素类型是string或者ICopy
- any feature?

fix: config `copy` type

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/getConfig/css.ts
yarn.lock

Close https://github.com/umijs/umi/issues/5801
- any feature?

fix: css modules esModule error

---

packages/bundler-webpack/bundled/webpackHotDevClient.js

Close https://github.com/umijs/umi/issues/4958
- any feature?

chore: remove devScripts warning

---

packages/create-umi-app/templates/AppGenerator/package.json.tpl

Close https://github.com/umijs/umi/issues/5823
- any feature?

chore: pkg format

---

.umirc.ts
docs/plugins/best-practice.md
docs/plugins/best-practice.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/best-practice.md](https://github.com/umijs/umi/blob/docs-plugin-order/docs/plugins/best-practice.md)
[View rendered docs/plugins/best-practice.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin-order/docs/plugins/best-practice.zh-CN.md)

docs: plugin order

---

packages/preset-built-in/src/plugins/generateFiles/core/history.runtime.tpl
packages/preset-built-in/src/plugins/generateFiles/core/history.tpl
packages/runtime/src/index.ts

Close https://github.com/umijs/umi/issues/5038
- any feature?

fix: history type

---

packages/bundler-webpack/src/fixtures/css-modules/c.less
packages/bundler-webpack/src/fixtures/css-modules/expect.ts
packages/bundler-webpack/src/fixtures/css-modules/index.ts

chore: css modules global test case

---

packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.tsx
packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts

Close https://github.com/umijs/umi/issues/5840
ref: https://github.com/umijs/umi/pull/5842
add test caes
- any feature?

chore: ssr replace $ with test case

---

docs/api/README.zh-CN.md

- any feature?
-----
[View rendered docs/api/README.zh-CN.md](https://github.com/justjavac/umi/blob/patch-1/docs/api/README.zh-CN.md)

fix: defineConfig link

---

packages/create-umi-app/templates/AppGenerator/package.json.tpl
packages/create-umi-app/templates/AppGenerator/src/pages/index.less
packages/create-umi-app/templates/AppGenerator/tsconfig.json

chore: update create app template

---

docs/docs/runtime-config.md

- any feature?
-----
[View rendered docs/docs/runtime-config.md](https://github.com/sibyo/umi/blob/patch-2/docs/docs/runtime-config.md)

grammar issue

---

docs/docs/config.md

- any feature?
-----
[View rendered docs/docs/config.md](https://github.com/sibyo/umi/blob/patch-1/docs/docs/config.md)

Fix type issue, environemtns to environments

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts

when set mode, then it become true in server.ts
- [x ] `npm test` passes

fix(ssr): Mode should be 'stream' or 'string'

---

packages/types/index.d.ts

close: https://github.com/umijs/umi/issues/5482

fix(types): export missing types

---

docs/docs/cli.md
docs/docs/cli.zh-CN.md
packages/preset-built-in/src/plugins/commands/webpack/webpack.test.ts

- feat: add test and docs for umi webpack command in production mode
- close #5899
-----
[View rendered docs/docs/cli.md](https://github.com/yingzhiji/umi/blob/feat/improve-umi-webpack-docs/docs/docs/cli.md)
[View rendered docs/docs/cli.zh-CN.md](https://github.com/yingzhiji/umi/blob/feat/improve-umi-webpack-docs/docs/docs/cli.zh-CN.md)

feat: add test and docs for umi webpack in production

---

docs/docs/assets-css.md

Translating the Use CSS article present in : https://umijs.org/docs/assets-css to english
-----
[View rendered docs/docs/assets-css.md](https://github.com/Hessabra/umi/blob/patch-1/docs/docs/assets-css.md)

docs: Translate assets-css.md to english

---

docs/guide/boost-compile-speed.md
docs/guide/boost-compile-speed.zh-CN.md

- any feature?
-----
[View rendered docs/guide/boost-compile-speed.md](https://github.com/umijs/umi/blob/docs-dynamicImport/docs/guide/boost-compile-speed.md)
[View rendered docs/guide/boost-compile-speed.zh-CN.md](https://github.com/umijs/umi/blob/docs-dynamicImport/docs/guide/boost-compile-speed.zh-CN.md)

docs: dynamicImport docs

---

packages/types/package.json

保持 `@types/cheerio` 的版本和 `@umijs/utils`中的 一致，以规避同时依赖 `@umijs/types` 和 `@umijs/utils` 时 father(gulp-typescript) 编译提示 `error TS2300: Duplicate identifier 'cheerio'` 的问题
临时方案：可通过 `skipLibCheck` 绕过

chore: upgrade cheerio types

---

docs/guide/boost-compile-speed.md

- any feature?
-----
[View rendered docs/guide/boost-compile-speed.md](https://github.com/umijs/umi/blob/docs-boot-compile/docs/guide/boost-compile-speed.md)

docs: add $ back

---

.github/workflows/ci.yml
packages/bundler-webpack/src/getConfig/getConfig.ts
packages/preset-built-in/src/fixtures/build/config/config.ts
packages/preset-built-in/src/plugins/commands/build/build.test.ts

chore: ie 11 test case

---

packages/preset-built-in/src/plugins/generateFiles/core/configTypes.ts

fix: prettier comment error

---

docs/docs/cli.md
docs/docs/cli.zh-CN.md
packages/bundler-webpack/src/index.ts
packages/preset-built-in/src/plugins/commands/buildDevUtils.ts
packages/preset-built-in/src/plugins/commands/dev/dev.ts
packages/preset-built-in/src/plugins/commands/webpack/webpack.ts

feat: show full webpack config with util.inspect

---

packages/create-umi-app/templates/AppGenerator/.umirc.ts.tpl
packages/create-umi-app/templates/AppGenerator/package.json.tpl
packages/create-umi-app/templates/AppGenerator/src/pages/index.tsx
packages/preset-built-in/package.json
packages/preset-built-in/src/plugins/commands/generate/PageGenerator/createPageGenerator.ts
packages/preset-built-in/src/plugins/commands/generate/PageGenerator/page.js.tpl
packages/preset-built-in/src/plugins/commands/generate/PageGenerator/page.tsx.tpl
packages/renderer-mpa/package.json
packages/renderer-react/package.json
packages/runtime/package.json
packages/umi/package.json

feat: compatible with react 17 and enable fastRefresh for boilerplate

---

packages/renderer-react/src/index.ts

feat: expose routes in IRouteComponentProps

---

packages/utils/src/BabelRegister/BabelRegister.ts

feat: fix the only option of babel-register is invalidated for symbolic link file

---

packages/create-umi-app/templates/AppGenerator/src/pages/index.tsx
packages/create-umi-app/templates/AppGenerator/tsconfig.json

chore: use react-jsx for create-app react 17 template

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/umi/src/cli.ts

- close #6009
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/fix/cli-SIGINT-process-exit/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/fix/cli-SIGINT-process-exit/docs/config/README.zh-CN.md)

fix: process exit code for SIGINT (c-c)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/issue-reply.yml
README.md
README.zh-CN.md
docs/README.md
docs/README.zh-CN.md

- any feature?
-----
[View rendered .github/ISSUE_TEMPLATE/bug_report.md](https://github.com/umijs/umi/blob/chore-codesandbox/.github/ISSUE_TEMPLATE/bug_report.md)
[View rendered docs/README.md](https://github.com/umijs/umi/blob/chore-codesandbox/docs/README.md)
[View rendered docs/README.zh-CN.md](https://github.com/umijs/umi/blob/chore-codesandbox/docs/README.zh-CN.md)

chore: codesandbox reproduce

---

.github/workflows/ci.yml
packages/bundler-webpack/src/fixtures/alias/config.ts
packages/preset-built-in/src/fixtures/dev-writeToDisk/.umirc.ts
packages/preset-built-in/src/fixtures/dev-writeToDisk/pages/index.css
packages/preset-built-in/src/fixtures/dev-writeToDisk/pages/index.js
packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts
packages/preset-built-in/src/plugins/commands/dev/dev.test.ts
packages/preset-built-in/src/plugins/commands/dev/dev.ts

fix(devServer): support html asset emit when using writeToDisk

---

.github/workflows/release-notify.yml

chore: release action

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/chore/qiankun-doc/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/chore/qiankun-doc/docs/plugins/plugin-qiankun.zh-CN.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/6126)

docs(qiankun): 优化升级文档内容

---

packages/preset-built-in/src/index.ts

Close https://github.com/umijs/umi/issues/6113
Close https://github.com/umijs/umi/issues/6096
- any feature?

fix: dynamicImportSyntax not registered

---

packages/preset-built-in/src/plugins/commands/dev/createRouteMiddleware.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts

Close https://github.com/umijs/umi/issues/5634
- any feature?

fix(ssr): unnecessary server render when .hot-update path

---

packages/preset-built-in/src/plugins/features/html/links.ts
packages/preset-built-in/src/plugins/features/html/metas.ts
packages/preset-built-in/src/plugins/features/html/utils.ts

- [-] `npm test` passes
- [] tests are included
- [] documentation is changed or added
- [-] commit message follows commit guidelines
- any feature?
- close https://github.com/umijs/umi/issues/6140

fix: deduplicate metas/styles/scripts/links(#6140)

---

packages/preset-built-in/src/plugins/features/ssr/constants.ts
packages/preset-built-in/src/plugins/features/ssr/serverTypePlugin.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/types/index.d.ts

`umi.server.js` 引用有类型提示 !!!
- any feature?

feat(ssr): server file require add types intelligent code

---

packages/create-umi-app/templates/AppGenerator/package.json.tpl

fix: template types

---

packages/renderer-react/src/renderRoutes/Route.tsx
packages/renderer-react/src/renderRoutes/Switch.tsx
packages/renderer-react/src/renderRoutes/renderRoutes.tsx

- use Switch and Route `props.location`

feat: use props.location

---

docs/api/README.md
packages/core/src/Config/Config.test.ts
packages/core/src/Config/Config.ts
packages/core/src/Config/fixtures/custom-config-file-ts/.foorc.ts
packages/core/src/Config/fixtures/custom-config-file-ts/.umirc.ts
packages/core/src/Config/fixtures/custom-config-file/.foorc.js
packages/core/src/Config/fixtures/custom-config-file/.umirc.js
packages/core/src/Service/Service.ts

Service类支持传入自定义的配置文件：
```
new Service({ configFiles: ['.mycustomrc.ts', 'config/mycustomrc.ts'] })
```

feat: support custom config files

---

packages/server/package.json
yarn.lock

Close https://github.com/umijs/umi/issues/6127
Ref https://github.com/umijs/umi/issues/6078
- any feature?

chore: upgrade immer 8

---

packages/server/package.json
yarn.lock

Revert "chore: upgrade immer 8"

---

packages/bundler-webpack/src/index.ts
packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts

fix(ssr): render not work in dev

---

package.json
scripts/release.js
yarn.lock

chore release script

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/webpack/plugins/terser-webpack-plugin/src/index.js
packages/server/package.json
packages/types/index.d.ts
packages/types/package.json
yarn.lock

chore: polish @umijs/deps usage, less deps

---

packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts
packages/preset-built-in/src/plugins/commands/htmlUtils.ts

- 扩展 modifyHTMLChunks 参数，使之具备获取源码的能力
- close https://github.com/umijs/umi/discussions/6086

feat: add assets for modifyHTMLChunks args

---

packages/bundler-webpack/src/getConfig/css.ts

fix: style-loader resolve failed

---

packages/preset-built-in/src/plugins/commands/generateFiles.ts

fix: wathers not set in generate files

---

packages/types/index.d.ts

- any feature?
-----
[View rendered docs/docs/fast-refresh.md](https://github.com/umijs/umi/blob/chore-types-deprecated/docs/docs/fast-refresh.md)
[View rendered docs/docs/fast-refresh.zh-CN.md](https://github.com/umijs/umi/blob/chore-types-deprecated/docs/docs/fast-refresh.zh-CN.md)

chore(types): types deprecated middleware

---

packages/bundler-webpack/package.json
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

fix: style-loader runtime lost

---

packages/bundler-webpack/src/requireHook.ts
packages/umi/package.json
packages/umi/src/cli.ts
packages/umi/src/forkedDev.ts
packages/umi/src/initWebpack.ts

fix: webpack require failed in config file

---

packages/bundler-webpack/package.json
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

fix: webpack 5 deprecated warnings

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/chore/qiankun-doc/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/chore/qiankun-doc/docs/plugins/plugin-qiankun.zh-CN.md)

docs(qiankun): 文档勘误

---

packages/bundler-webpack/package.json
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

fix: fork-ts-checker-webpack-plugin bundle problem

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/DevCompileDonePlugin.ts
packages/bundler-webpack/src/index.ts
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

chore: fix build failed, revert any type declaration from #6236

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts

fix(ssr): serialize-javascript dep lost

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/getConfig/getConfig.test.ts
packages/bundler-webpack/src/getConfig/getConfig.ts
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

fix: analyze and manifest feat don't work

---

packages/bundler-webpack/package.json
packages/core/package.json
packages/preset-built-in/package.json
packages/preset-built-in/src/plugins/features/webpack5.ts
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

feat: upgrade webpack 5 to 5.24.4, fix lazy compilation and deprecated warnings

---

packages/core/src/Route/Route.ts
packages/core/src/Route/routesToJSON.test.ts
packages/core/src/Route/routesToJSON.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts

Close https://github.com/umijs/umi/issues/5536
Close https://github.com/umijs/umi/issues/5657
`dynamic({ loader: import })` 在 server 端执行，内存会常驻，不会释放，需要改成 `require()` 方式使用
- any feature?

fix(ssr): dynamicImport render OOM

---

package.json
yarn.lock

ref: https://github.com/umijs/umi/issues/6078
- any feature?

dep: upgrade open to 8

---

packages/preset-built-in/src/plugins/features/ssr/constants.ts
packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.tsx
packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts

Close https://github.com/umijs/umi/issues/6259
- any feature?

fix(ssr): dynamicImport css chunks lost

---

packages/preset-built-in/src/index.test.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/features/ssr/templates/clientExports.tpl
packages/runtime/src/index.ts
packages/runtime/src/utils/index.ts
packages/umi/src/index.ts

Close https://github.com/umijs/umi/issues/4779
- any feature?

fix(ssr): built-in `isBrowser` into umi with client

---

docs/plugins/plugin-initial-state.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-initial-state.zh-CN.md](https://github.com/fynmm/umi/blob/patch-1/docs/plugins/plugin-initial-state.zh-CN.md)

docs: update plugin-initial-state.zh-CN.md

---

packages/preset-built-in/src/plugins/generateFiles/umi.ts

fix: add specified umi version to defInfo by default

---

packages/bundler-webpack/bundled/webpackHotDevClient.js
packages/bundler-webpack/package.json
packages/preset-built-in/package.json
packages/renderer-react/package.json
packages/runtime/package.json
yarn.lock

ref: https://github.com/umijs/umi/issues/6078
- any feature?

dep: upgrade react-error-overlay and use-subscription

---

docs/plugins/plugin-qiankun.md
docs/plugins/plugin-qiankun.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/doc/qiankun-2/docs/plugins/plugin-qiankun.md)
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/umijs/umi/blob/doc/qiankun-2/docs/plugins/plugin-qiankun.zh-CN.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/6302)

docs(qiankun): 增加 credentials 配置

---

packages/babel-preset-umi/src/index.test.ts
packages/bundler-webpack/package.json
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

dep: upgrade babel to 7.13, support syntax for typescript 4.2

---

packages/umi/bin/umi.js
packages/umi/package.json
yarn.lock

feat: add v8-compile-cache for faster init speed

---

docs/config/README.md
docs/config/README.zh-CN.md

Remove `browse `
Fix #6109 
-----
[View rendered docs/config/README.md](https://github.com/drizzlesconsin/umi/blob/fix-doc-externals-example/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/drizzlesconsin/umi/blob/fix-doc-externals-example/docs/config/README.zh-CN.md)

docs: optimize externals example

---

docs/docs/config.zh-CN.md

Code snippet conflict with description above
-----
[View rendered docs/docs/config.zh-CN.md](https://github.com/xiaoyaojian/umi/blob/patch-1/docs/docs/config.zh-CN.md)

docs: fix code snippet conflict with description above

---

packages/bundler-webpack/src/fixtures/postcss-flexbugs-fixes/expect.ts
packages/bundler-webpack/src/fixtures/postcss-flexbugs-fixes/font-varian.less
packages/bundler-webpack/src/fixtures/postcss-flexbugs-fixes/grid.css
packages/bundler-webpack/src/fixtures/postcss-flexbugs-fixes/index.ts
packages/bundler-webpack/src/fixtures/postcss-flexbugs-fixes/media.css

chore(postcss): test case for postcss-preset-env

---

packages/bundler-webpack/src/getConfig/getConfig.ts

fix: process undefined when webpack 5 is enabled

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/requireHook.ts
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

fix: monaco-editor-webpack-plugin don't work in 3.4

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/requireHook.ts
packages/core/package.json
packages/preset-built-in/package.json
packages/server/package.json
packages/types/package.json
packages/umi/package.json
packages/utils/package.json
yarn.lock

fix: webpack pkg info wrong

---

.gitignore
packages/umi/src/cli.ts

- any feature?
Ref: https://github.com/umijs/umi/issues/6303

feat: check node version

---

packages/core/src/Service/Service.ts

fix: .env.local should take precedence over .env

---

packages/preset-built-in/src/plugins/commands/build/build.ts

fix: clear tmp dir without cache dirs for build stage

---

packages/bundler-webpack/src/getConfig/getConfig.ts
packages/umi/src/cli.ts

- any feature?
- close https://github.com/umijs/umi/issues/6318

feat: enable stream polyfill for webpack 5

---

docs/plugins/plugin-esbuild.md
docs/plugins/plugin-esbuild.zh-CN.md

Refs: https://github.com/umijs/plugins/pull/571
- any feature?
-----
[View rendered docs/plugins/plugin-esbuild.md](https://github.com/umijs/umi/blob/docs-esbuild/docs/plugins/plugin-esbuild.md)
[View rendered docs/plugins/plugin-esbuild.zh-CN.md](https://github.com/umijs/umi/blob/docs-esbuild/docs/plugins/plugin-esbuild.zh-CN.md)

docs(esbuild): target config

---

docs/docs/mock.md

- any feature?
-----
[View rendered docs/docs/mock.md](https://github.com/rlongying/umi/blob/patch-1/docs/docs/mock.md)

Translate mock.md

---

docs/plugins/plugin-esbuild.md
docs/plugins/plugin-esbuild.zh-CN.md

Refs: umijs/plugins#575
+ [#7012](https://github.com/ant-design/ant-design-pro/issues/7012)
+ [#5266](https://github.com/ant-design/ant-design-pro/issues/5266)
+ [#3766](https://github.com/ant-design/ant-design-pro/issues/3766)
+ [#6540](https://github.com/ant-design/ant-design-pro/issues/6540)
-----
[View rendered docs/plugins/plugin-esbuild.md](https://github.com/drizzlesconsin/umi/blob/docs-esbuild-pure/docs/plugins/plugin-esbuild.md)
[View rendered docs/plugins/plugin-esbuild.zh-CN.md](https://github.com/drizzlesconsin/umi/blob/docs-esbuild-pure/docs/plugins/plugin-esbuild.zh-CN.md)

docs(esbuild): support pure config

---

.github/workflows/ci.yml
packages/umi/src/cli.ts

feat: support node 15

---

docs/docs/fast-refresh.md
docs/docs/fast-refresh.zh-CN.md

- close #6432
-----
[View rendered docs/docs/fast-refresh.md](https://github.com/Map1en/umi/blob/docs-fastrefresh-add-faq/docs/docs/fast-refresh.md)
[View rendered docs/docs/fast-refresh.zh-CN.md](https://github.com/Map1en/umi/blob/docs-fastrefresh-add-faq/docs/docs/fast-refresh.zh-CN.md)

docs(fastRefresh): add 'forEach' of undefined FAQ

---

packages/types/index.d.ts

> update types for api:registerGenerator

fix: update types for api:registerGenerator

---

.github/workflows/ci.yml

feat: support node 16

---

docs/api/README.zh-CN.md

-----
[View rendered docs/api/README.zh-CN.md](https://github.com/youngjuning/umi/blob/patch-1/docs/api/README.zh-CN.md)

docs: plugin -> Plugin

---

package.json
packages/bundler-webpack/src/requireHook.ts
packages/deps/bundles/webpack/bundle4.js
packages/deps/bundles/webpack/bundle5.js
packages/deps/bundles/webpack/innerFiles.js
packages/deps/bundles/webpack/packages/Chunk.js
packages/deps/compiled/webpack/5/minify.js
packages/deps/compiled/webpack/Chunk.js

feat: upgrade webpack 5 to 5.35.1 and hook webpack/lib/Chunk

---

packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/features/ssr/templates/renderServer/renderServer.tsx

Refs: https://github.com/umijs/umi/pull/6454#issuecomment-828182973, https://github.com/umijs/plugins/pull/601, https://github.com/umijs/umi/pull/6463
Close: https://github.com/umijs/umi/issues/6404, https://github.com/umijs/umi/issues/6499
Related:  https://github.com/umijs/plugins/pull/603
Thanks @robinv8  !
- any feature?

fix(ssr): dev server render stuck and add ctx props

---

.github/workflows/ci.yml

chore(ci): improve github ci stability

---

CONTRIBUTING.md
package.json
scripts/example.js

支持单独启动用例，
- any feature?
-----
[View rendered CONTRIBUTING.md](https://github.com/umijs/umi/blob/dev-examples/CONTRIBUTING.md)

chore: add example script, easy to develop example

---

docs/plugins/plugin-esbuild.md
docs/plugins/plugin-esbuild.zh-CN.md

增加target类型及默认值说明。
增加一个IE使用esbuild插件出现模版字符串错误的解决说明
-----
[View rendered docs/plugins/plugin-esbuild.md](https://github.com/Map1en/umi/blob/docs-esbuild-add-faq/docs/plugins/plugin-esbuild.md)
[View rendered docs/plugins/plugin-esbuild.zh-CN.md](https://github.com/Map1en/umi/blob/docs-esbuild-add-faq/docs/plugins/plugin-esbuild.zh-CN.md)

docs(plugin-esbuild): add FAQ & improve document

---

packages/preset-built-in/src/plugins/features/webpack5.ts

fix: webpack 5 fs cache don't work in tnpm/cnpm

---

.github/workflows/ci.yml
packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts
packages/preset-built-in/src/plugins/commands/build/build.test.ts
packages/preset-built-in/src/plugins/features/exportStatic.test.ts
packages/preset-built-in/src/plugins/features/exportStatic.ts

fix: fix onPatchRoute will 404 error

---

packages/bundler-webpack/src/getConfig/getConfig.ts

fix: fs polyfill module not found

---

packages/preset-built-in/src/plugins/commands/dev/mock/createMiddleware.test.ts
packages/umi/src/cli.ts

fix: webpack not found on umi generate

---

examples/config-alias/.umirc.ts
examples/config-alias/README.md
examples/config-alias/package.json
examples/config-alias/src/components/Footer.tsx
examples/config-alias/src/components/Header.tsx
examples/config-alias/src/components/index.tsx
examples/config-alias/src/pages/index.tsx
examples/config-alias/tsconfig.json

Create aliases to import or require certain modules more easily.
- any feature?
-----
[View rendered examples/config-alias/README.md](https://github.com/umijs/umi/blob/chore-example-config-alias/examples/config-alias/README.md)

chore: add example for alias

---

packages/types/index.d.ts

fix: plugin api type

---

package.json
yarn.lock

chore: lock prettier to 2.2.1

---

packages/umi/src/cli.ts

fix: webpack resolve failed when using other commands

---

packages/umi/src/cli.ts

feat: set process.title to umi

---

docs/guide/plugin-develop.md
docs/guide/plugin-develop.zh-CN.md

fix: spelling mistake of `puppeteer`
- any feature?
-----
[View rendered docs/guide/plugin-develop.md](https://github.com/fengsx/umi/blob/master/docs/guide/plugin-develop.md)
[View rendered docs/guide/plugin-develop.zh-CN.md](https://github.com/fengsx/umi/blob/master/docs/guide/plugin-develop.zh-CN.md)

docs: fix spelling mistake of `puppeteer`

---

packages/babel-preset-umi/package.json
packages/bundler-webpack/src/webpack/plugins/mini-css-extract-plugin/src/loader.js

- fix: unexcepted react bundle
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/chore/mfsu-improve-2/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/chore/mfsu-improve-2/docs/config/README.zh-CN.md)
[View rendered docs/docs/mfsu.md](https://github.com/umijs/umi/blob/chore/mfsu-improve-2/docs/docs/mfsu.md)
[View rendered docs/docs/mfsu.zh-CN.md](https://github.com/umijs/umi/blob/chore/mfsu-improve-2/docs/docs/mfsu.zh-CN.md)
[View rendered docs/guide/plugin-develop.md](https://github.com/umijs/umi/blob/chore/mfsu-improve-2/docs/guide/plugin-develop.md)

fix: unexcepted react bundle

---

.gitignore
scripts/bootstrap-examples.js

1、修改一下 example bootstrap 命令，已经写好的代码，不应该被脚本重置
2、所有的 example 下的 node_modules 都应该被忽略
- any feature?

chore: change example bootstrap

---

examples/with-yarn-workspaces/README.md
examples/with-yarn-workspaces/package.json
examples/with-yarn-workspaces/packages/app/.umirc.js
examples/with-yarn-workspaces/packages/app/package.json
examples/with-yarn-workspaces/packages/app/pages/index.js
examples/with-yarn-workspaces/packages/footer/index.jsx
examples/with-yarn-workspaces/packages/footer/package.json
examples/with-yarn-workspaces/packages/head/index.jsx
examples/with-yarn-workspaces/packages/head/package.json
examples/with-yarn-workspaces/tsconfig.json

增加使用 yarn-workspaces 的例子
- any feature?
- https://github.com/umijs/umi/issues/6598
-----
[View rendered examples/with-yarn-workspaces/README.md](https://github.com/umijs/umi/blob/chore-example-with-yarn-workspaces/examples/with-yarn-workspaces/README.md)

chore: add example with-yarn-workspaces

---

examples/plugin-initial-state/README.md
examples/plugin-initial-state/app.js
examples/plugin-initial-state/package.json
examples/plugin-initial-state/pages/index.js
scripts/bootstrap-examples.js

添加 plugin-init-state 插件的用例，为了答复这个问题 https://github.com/umijs/umi/discussions/6568
- any feature?
-----
[View rendered examples/plugin-initial-state/README.md](https://github.com/umijs/umi/blob/chore-example-plugin-init-state/examples/plugin-initial-state/README.md)

chore: add example for plugin-init-state

---

.circleci/config.yml
packages/preset-built-in/src/plugins/features/ssr/constants.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.test.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/preset-built-in/src/plugins/features/ssr/templates/utils.test.tsx
packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts

Refs: https://github.com/umijs/umi/pull/6634
Fixes #6259 Closes #4978
Thanks @dominicleo
- any feature?

fix(ssr): incomplete loading of css chunks in ssr and dynamicImport enable for avoiding page flashing

---

packages/bundler-webpack/src/getConfig/getConfig.ts

fix: terser failed in internal flow platform

---

packages/preset-built-in/src/index.test.ts
packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts
packages/preset-built-in/src/plugins/commands/build/build.test.ts

fix: do no replace in other os

---

packages/babel-preset-umi/package.json
packages/preset-built-in/src/plugins/features/mfsu/build.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

chore: mfsu improve 3

---

docs/config/README.md
docs/config/README.zh-CN.md

update cssnano docs url & fix type and default content
-----
[View rendered docs/config/README.md](https://github.com/kongmoumou/umi/blob/fix-doc/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/kongmoumou/umi/blob/fix-doc/docs/config/README.zh-CN.md)

docs: fix cssnano config

---

packages/preset-built-in/src/plugins/features/mfsu/build.ts

fix: @babel/core not found

---

examples/with-dva/README.md
examples/with-dva/package.json
examples/with-dva/src/app.tsx
examples/with-dva/src/global.less
examples/with-dva/src/layouts/index.tsx
examples/with-dva/src/models/global.ts
examples/with-dva/src/pages/admin.tsx
examples/with-dva/src/pages/delay.tsx
examples/with-dva/src/pages/index/components/Count.tsx
examples/with-dva/src/pages/index/index.css
examples/with-dva/src/pages/index/index.tsx
examples/with-dva/src/pages/index/model.tsx
examples/with-dva/src/pages/list/_layout.tsx
examples/with-dva/src/pages/list/index.css
examples/with-dva/src/pages/list/index.tsx
examples/with-dva/src/pages/list/list.tsx
examples/with-dva/src/pages/list/search/index.tsx
examples/with-dva/src/pages/list/search/model.tsx
examples/with-dva/src/pages/login.tsx
examples/with-dva/tsconfig.json
examples/with-dva/typings.d.ts

整合 dva 数据流
- any feature?
-----
[View rendered examples/with-dva/README.md](https://github.com/umijs/umi/blob/chore-example-with-dva/examples/with-dva/README.md)

chore: examples add with-dva

---

examples/config-proxy/.umirc.ts
examples/config-proxy/README.md
examples/config-proxy/package.json
examples/config-proxy/src/pages/index.tsx
examples/config-proxy/tsconfig.json

proxy 代理配置example
- any feature?
-----
[View rendered examples/config-proxy/README.md](https://github.com/ahwgs/umi-start/blob/chore-config-proxy/examples/config-proxy/README.md)

chore: add example for config-proxy

---

examples/config-base/.umirc.ts
examples/config-base/README.md
examples/config-base/package.json
examples/config-base/pages/hello.tsx
examples/config-base/pages/index.tsx

base 主要是非根目录部署的演示
- any feature?
-----
[View rendered examples/config-base/README.md](https://github.com/umijs/umi/blob/chore-example-config-base/examples/config-base/README.md)

chore: add example config base

---

packages/preset-built-in/package.json
packages/preset-built-in/src/plugins/features/mfsu/build.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix(mfsu): add core-js dep info and remove prebuild  alias

---

packages/preset-built-in/src/plugins/generateFiles/umi.tpl
packages/preset-built-in/src/plugins/generateFiles/umi.ts

fix: history require failed when mpa

---

packages/bundler-webpack/src/getConfig/getConfig.ts

fix: remove noParse for css hmr client

---

packages/bundler-webpack/src/webpack/plugins/mini-css-extract-plugin/src/loader.js
packages/preset-built-in/src/plugins/features/mfsu/build.ts

fix(mfsu): win path

---

examples/config-dynamicImport/.umirc.ts
examples/config-dynamicImport/README.md
examples/config-dynamicImport/package.json
examples/config-dynamicImport/pages/about.tsx
examples/config-dynamicImport/pages/index.tsx

add example config dynamicImport
- any feature?
-----
[View rendered examples/config-dynamicImport/README.md](https://github.com/umijs/umi/blob/chore-example-config-dynamicImport/examples/config-dynamicImport/README.md)

chore: add example config dynamicImport

---

examples/with-kea/README.md
examples/with-kea/package.json
examples/with-kea/src/app.ts
examples/with-kea/src/pages/index.tsx
examples/with-kea/src/pages/logic.ts

add example with-kea
- any feature?
-----
[View rendered examples/with-kea/README.md](https://github.com/umijs/umi/blob/chore-example-with-kea/examples/with-kea/README.md)

chore: add example with-kea

---

examples/convention-mock/README.md
examples/convention-mock/mock/api.js
examples/convention-mock/mock/status.js
examples/convention-mock/package.json
examples/convention-mock/src/pages/index.tsx

mock 约定 example
- any feature?
-----
[View rendered examples/convention-mock/README.md](https://github.com/ahwgs/umi-start/blob/chore-convention-mock/examples/convention-mock/README.md)

chore: add example for convention-mock

---

examples/with-dva/package.json
examples/with-mobx/README.md
examples/with-mobx/package.json
examples/with-mobx/src/app.tsx
examples/with-mobx/src/layouts/index.tsx
examples/with-mobx/src/pages/admin.tsx
examples/with-mobx/src/pages/delay.tsx
examples/with-mobx/src/pages/index/components/Count.tsx
examples/with-mobx/src/pages/index/index.css
examples/with-mobx/src/pages/index/index.tsx
examples/with-mobx/src/pages/index/model.tsx
examples/with-mobx/src/pages/list/_layout.tsx
examples/with-mobx/src/pages/list/index.css
examples/with-mobx/src/pages/list/index.tsx
examples/with-mobx/src/pages/list/list.tsx
examples/with-mobx/src/pages/list/search/index.tsx
examples/with-mobx/src/pages/login.tsx
examples/with-mobx/src/stores/count.ts
examples/with-mobx/src/stores/createMobxStores.ts
examples/with-mobx/src/stores/global.ts
examples/with-mobx/src/stores/search.ts
examples/with-mobx/src/utils/useStores.tsx
examples/with-mobx/tsconfig.json

example add with-mobx
- any feature?
-----
[View rendered examples/with-mobx/README.md](https://github.com/umijs/umi/blob/chore-example-with-mobx/examples/with-mobx/README.md)

chore: example add with-mobx

---

examples/with-ant-design/.umirc.ts
examples/with-ant-design/README.md
examples/with-ant-design/global.less
examples/with-ant-design/package.json
examples/with-ant-design/pages/index.tsx

add example with-ant-design
- any feature?
-----
[View rendered examples/with-ant-design/README.md](https://github.com/umijs/umi/blob/chore-example-with-antd/examples/with-ant-design/README.md)

chore: add example with-ant-design

---

examples/with-sentry/README.md
examples/with-sentry/config/config.ts
examples/with-sentry/mock/app.ts
examples/with-sentry/package.json
examples/with-sentry/src/app.tsx
examples/with-sentry/src/models/index.ts
examples/with-sentry/src/pages/index/index.less
examples/with-sentry/src/pages/index/index.tsx
examples/with-sentry/src/pages/some/[index].tsx
examples/with-sentry/src/pages/some/index.less
examples/with-sentry/src/services/api.ts
examples/with-sentry/tsconfig.json
examples/with-sentry/typings.d.ts

add example with-sentry
- any feature?
-----
[View rendered examples/with-sentry/README.md](https://github.com/umijs/umi/blob/chore-example-with-sentry/examples/with-sentry/README.md)

chore: add example with-sentry

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

feat: import-to-await babel plugin support import call expression

---

package.json
packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
yarn.lock

feat: import-to-await-require babel plugin support matchAll mode

---

packages/preset-built-in/package.json
packages/preset-built-in/src/plugins/features/mfsu/babel-import-redirect-plugin.test.ts
packages/preset-built-in/src/plugins/features/mfsu/babel-modify-remote-entry-plugin.test.ts
packages/preset-built-in/src/plugins/features/mfsu/build.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.test.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.test.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.ts

feat(mfsu): figure out default export

---

packages/preset-built-in/src/plugins/features/mfsu/build.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix(mfsu): return when onBuildComplete failed

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu await import match duplicate

---

packages/bundler-webpack/src/getConfig/css.ts
packages/bundler-webpack/src/getConfig/getConfig.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

feat: improve mfsu

---

packages/umi/src/initWebpack.ts

fix: webpack 5 don't work when APP_ROOT is used

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/umi/src/initWebpack.ts

fix: mfsu don't work with externals config

---

packages/preset-built-in/src/plugins/commands/dev/dev.ts

chore: add mfsu ad when dev server is slow

---

packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu don't work with svg as react component

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/preset-built-in/src/plugins/features/webpack5.ts
packages/umi/src/initWebpack.ts

- any feature?
- close https://github.com/umijs/umi/pull/6774

feat: mfsu enable webpack5 and dynamicImport by default

---

packages/preset-built-in/src/plugins/features/mfsu/utils.test.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.ts

feat(mfsu): adapt cjs mode esm

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix(mfsu): dumi redirect

---

packages/preset-built-in/src/plugins/commands/dev/dev.ts

feat: only show mfsu ad when mfsu is not enabled

---

packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.test.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.ts

fix: cjs esm parse in mfsu

---

packages/preset-built-in/src/plugins/commands/dev/devCompileDone/devCompileDone.ts
packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts

fix: throw onCompileDone error and fix mfsu error stack

---

packages/preset-built-in/src/plugins/features/mfsu/fixtures/getFilePath/js-file-first/foo/package.json
packages/preset-built-in/src/plugins/features/mfsu/fixtures/getFilePath/package-json-second/foo/package.json
packages/preset-built-in/src/plugins/features/mfsu/getFilePath.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getFilePath.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.ts

fix: improve the logic of find file of importFrom

---

packages/preset-built-in/src/plugins/generateFiles/umi.ts

chore: remove addDepInfo

---

packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.ts

fix: mfsu invalid package version found

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix: mfsu lock chunks to umi

---

packages/preset-built-in/src/plugins/features/mfsu/fixtures/getFilePath/package-json-directory/foo/package.json
packages/preset-built-in/src/plugins/features/mfsu/getFilePath.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getFilePath.ts

fix: mfsu getFilePath with package.json point to directory

---

packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts

fix(mfsu): no parse css file

---

docs/docs/mfsu.md
docs/docs/mfsu.zh-CN.md

- any feature?
-----
[View rendered docs/docs/mfsu.md](https://github.com/umijs/umi/blob/docs/mfsu_doc/docs/docs/mfsu.md)
[View rendered docs/docs/mfsu.zh-CN.md](https://github.com/umijs/umi/blob/docs/mfsu_doc/docs/docs/mfsu.zh-CN.md)

docs: typo

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

fix: cache path include local cwd

---

docs/docs/mfsu.md
docs/docs/mfsu.zh-CN.md
packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

- 文档
- 缓存的绝对路径没被替换为 CWD 问题
-----
[View rendered docs/docs/mfsu.md](https://github.com/umijs/umi/blob/feat/mfsu_improve_28/docs/docs/mfsu.md)
[View rendered docs/docs/mfsu.zh-CN.md](https://github.com/umijs/umi/blob/feat/mfsu_improve_28/docs/docs/mfsu.zh-CN.md)

fix(mfsu):mfsu improve 28

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu babel plugin export transform

---

packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu babel plugin don't match webpack loader syntax

---

packages/babel-plugin-import-to-await-require/src/index.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/types/index.d.ts

feat: mfsu support export all in project files

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu exportAllMembers support empty array

---

packages/bundler-webpack/src/getConfig/getConfig.ts

fix: webpack 5 should target es5

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu export all variable conflicts

---

docs/plugins/api.md

- any feature?
-----
[View rendered docs/plugins/api.md](https://github.com/OhIAmFine/umi/blob/patch-1/docs/plugins/api.md)

[README] Update addHTMLScripts api description

---

packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu svgr don't support windows

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix: mfsu don't work when publicPath is set

---

packages/renderer-mpa/package.json

fix: mfsu don't work with mpa mode

---

packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts
packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts
packages/preset-built-in/src/plugins/features/mfsu/RuntimePublicPathPlugin.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix: mfsu don't support runtimePublicPath

---

packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts
packages/preset-built-in/src/plugins/features/mfsu/constants.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/types/index.d.ts

feat: mfsu support config mfName

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

feat: improve mfsu error handler

---

packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.ts
packages/preset-built-in/src/plugins/features/mfsu/utils.ts

fix: mfsu don't support monorepo

---

packages/preset-built-in/src/plugins/features/mfsu/getFilePath.ts

close https://github.com/umijs/umi/issues/6863
- any feature?

fix(mfsu): fix path is empty , mfsu will error

---

.github/workflows/emoji-helper.yml

ci: add emoji helper

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

fix(mfsu): should build path error

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/preset-built-in/src/plugins/features/webpack5.ts

feat: enable top-level-await when webpack5 is configured

---

packages/babel-plugin-auto-css-modules/package.json
packages/babel-plugin-auto-css-modules/src/index.test.ts
packages/babel-plugin-auto-css-modules/src/index.ts
packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts
packages/babel-preset-umi/src/index.ts

fix: mfsu css priority problem

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

chore: code style for mfsu monaco-editor hack

---

docs/config/README.md
docs/config/README.zh-CN.md
docs/docs/mfsu.md
docs/docs/mfsu.zh-CN.md

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/docs/mfsu-doc-improve/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/docs/mfsu-doc-improve/docs/config/README.zh-CN.md)
[View rendered docs/docs/mfsu.md](https://github.com/umijs/umi/blob/docs/mfsu-doc-improve/docs/docs/mfsu.md)
[View rendered docs/docs/mfsu.zh-CN.md](https://github.com/umijs/umi/blob/docs/mfsu-doc-improve/docs/docs/mfsu.zh-CN.md)

docs(mfsu): update mfsu doc

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts
packages/babel-preset-umi/src/index.ts

fix: mfsu css priority problem again

---

packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts

- close https://github.com/umijs/umi/issues/6887
- close https://github.com/umijs/umi/issues/6895

fix(mfsu): webpack export support

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

- close https://github.com/umijs/umi/issues/6885

fix: mfsu await require support export as default

---

packages/bundler-webpack/src/webpack/plugins/mini-css-extract-plugin/src/CssLoadingRuntimeModule.js

fix(mini-css-extract-plugin): fix ES5语法

---

packages/preset-built-in/package.json
yarn.lock

dep: upgrade es-module-lexer to 0.7.1

---

packages/preset-built-in/src/plugins/features/globalCSS.ts

fix: mfsu global css priority

---

packages/deps/package.json
packages/deps/reexported/esbuild.d.ts
packages/deps/reexported/esbuild.js
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts
yarn.lock

fix: mfsu support file parse with jsx and tsx

---

packages/babel-plugin-auto-css-modules/src/index.test.ts
packages/babel-plugin-auto-css-modules/src/index.ts

fix: mfsu auto css modules transform should affect css only

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

fix: mfsu rebuild when externals changed

---

packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts

fix: mfsu disable library

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/types/index.d.ts

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/fix/mfsu-config-chunks/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/fix/mfsu-config-chunks/docs/config/README.zh-CN.md)

feat: mfsu support config chunks

---

packages/create-umi-app/templates/AppGenerator/tsconfig.json

fix: typecheck error while importing .json

---

packages/bundler-webpack/src/getConfig/getConfig.ts
packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts

fix: webpack 5 buffer undefined

---

docs/docs/mfsu.zh-CN.md

Correct typo.
-----
[View rendered docs/docs/mfsu.zh-CN.md](https://github.com/imaegoo/umi/blob/patch-1/docs/docs/mfsu.zh-CN.md)

fix: mfsu doc typo

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

feat: mfsu improve error message when package.json not found

---

packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.ts

fix: mfsu support native modules

---

packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepVersion.ts

feat(mfsu): support webpack strict alias

---

packages/bundler-webpack/src/getConfig/getConfig.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

feat: mfsu support assets files

---

packages/preset-built-in/src/plugins/features/mfsu/babel-plugin-warn-require.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

feat: mfsu warn require usage

---

packages/preset-built-in/src/plugins/features/devScripts.ts
packages/preset-built-in/src/plugins/features/mfsu/babel-plugin-auto-export.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
packages/preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl

feat: mfsu add export automatically when no export found

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix: mfsu don't work with publicPath

---

docs/plugins/plugin-request.md
docs/plugins/plugin-request.zh-CN.md

- fix spelling mistakes
-----
[View rendered docs/plugins/plugin-request.md](https://github.com/Zhhanou/umi/blob/master/docs/plugins/plugin-request.md)
[View rendered docs/plugins/plugin-request.zh-CN.md](https://github.com/Zhhanou/umi/blob/master/docs/plugins/plugin-request.zh-CN.md)

docs: fix spelling mistakes

---

packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts

fix: mfsu support qiankun sandbox

---

packages/preset-built-in/src/plugins/features/mfsu/DepBuilder.ts

fix: mfsu clean queue after build complete

---

packages/preset-built-in/src/plugins/features/mfsu/babel-plugin-auto-export.test.ts
packages/preset-built-in/src/plugins/features/mfsu/babel-plugin-auto-export.ts

fix: mfsu auto export support cjs

---

packages/preset-built-in/package.json
yarn.lock

- any feature?
- close https://github.com/umijs/umi/issues/7052

fix: mfsu mime version, upgrade to 1.3.6

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

fix: mfsu rebuild when umi version if differenent

---

packages/types/package.json

fix IRouteComponentProps type exports

fix: fix IRouteComponentProps type exports

---

packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getDepReExportContent.ts

fix: mfsu none export when only has __esModule export

---

packages/preset-built-in/src/plugins/features/mfsu/fixtures/getFilePath/package-json-not-found-module/foo/package.json
packages/preset-built-in/src/plugins/features/mfsu/getFilePath.test.ts
packages/preset-built-in/src/plugins/features/mfsu/getFilePath.ts

fix: mfsu filePath not found when module is set but not found

---

packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts

fix: mfsu deps on bigfish version

---

packages/preset-built-in/src/plugins/features/mfsu/getFilePath.ts

fix: code style problem caused by prettier

---

packages/babel-plugin-import-to-await-require/src/index.test.ts
packages/babel-plugin-import-to-await-require/src/index.ts

fix: mfsu externals support function and array

---

packages/babel-plugin-import-to-await-require/src/index.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix: mfsu externals again

---

docs/plugins/plugin-qiankun.md

- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.md](https://github.com/umijs/umi/blob/docs/qiankun-plugin-doc/docs/plugins/plugin-qiankun.md)

docs: add doc for autoCaptureError and errorBoundary api

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

chore: add emoji

---

docs/config/README.zh-CN.md

- any feature?
fixed mfsu error because of filename config

fix: mfsu error because of filename config

---

docs/plugins/best-practice.md
docs/plugins/best-practice.zh-CN.md

-----
[View rendered docs/plugins/best-practice.zh-CN.md](https://github.com/hiyangguo/umi/blob/patch-2/docs/plugins/best-practice.zh-CN.md)

docs: Update read more url for TDD

---

docs/config/README.md
docs/config/README.zh-CN.md
packages/preset-built-in/src/fixtures/ssr-prerender-no/.umirc.ts
packages/preset-built-in/src/fixtures/ssr-prerender-no/pages/index.tsx
packages/preset-built-in/src/fixtures/ssr-prerender/.umirc.ts
packages/preset-built-in/src/fixtures/ssr-prerender/pages/index.tsx
packages/preset-built-in/src/index.test.ts
packages/preset-built-in/src/plugins/features/exportStatic.ts
packages/preset-built-in/src/plugins/features/ssr/ssr.ts
packages/types/index.d.ts

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/hubcarl/umi/blob/feature/ssr-prerender/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/hubcarl/umi/blob/feature/ssr-prerender/docs/config/README.zh-CN.md)

feat: add ssr.prerender configuration for umi build prerender

---

packages/core/src/Service/PluginAPI.ts

- any feature?
根据 utils.lodash.isPlainObject(fn) 可知，fn还可能是Object类型。

fix: add union type for fn

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.test.ts
packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

fix(preset-built-in): mfsu monaco worker

---

docs/plugins/plugin-access.md
docs/plugins/plugin-access.zh-CN.md

https://github.com/umijs/plugins/pull/636
-----
[View rendered docs/plugins/plugin-access.md](https://github.com/umijs/umi/blob/docs-plugin-access/docs/plugins/plugin-access.md)
[View rendered docs/plugins/plugin-access.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin-access/docs/plugins/plugin-access.zh-CN.md)

docs: plugin access

---

packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts

RT
- any feature?  - No
- close 
- https://github.com/umijs/umi/issues/7319
- https://github.com/umijs/umi/issues/7235 
- https://github.com/umijs/umi/issues/7513

fix(mfsu): 修复 dev 时读取字体/图片等二进制文件使用 utf8 格式导致出错的问题

---

docs/plugins/plugin-antd-mobile.md
docs/plugins/plugin-antd-mobile.zh-CN.md
docs/plugins/plugin-antd.md
docs/plugins/plugin-antd.zh-CN.md

- any feature?
-----
[View rendered docs/plugins/plugin-antd-mobile.md](https://github.com/umijs/umi/blob/docs-plugin-antd-mobile/docs/plugins/plugin-antd-mobile.md)
[View rendered docs/plugins/plugin-antd-mobile.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin-antd-mobile/docs/plugins/plugin-antd-mobile.zh-CN.md)
[View rendered docs/plugins/plugin-antd.md](https://github.com/umijs/umi/blob/docs-plugin-antd-mobile/docs/plugins/plugin-antd.md)
[View rendered docs/plugins/plugin-antd.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin-antd-mobile/docs/plugins/plugin-antd.zh-CN.md)

docs: plugin antd-mobile

---

packages/core/src/Config/types.d.ts
packages/preset-built-in/src/plugins/features/exportStatic.ts
packages/types/index.d.ts

feat: exportStatic support supportWin config

---

docs/config/README.md
docs/config/README.zh-CN.md

- any feature?
-----
[View rendered docs/config/README.md](https://github.com/hangyangws/umi/blob/doc/fix-localsConvention-symbol/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/hangyangws/umi/blob/doc/fix-localsConvention-symbol/docs/config/README.zh-CN.md)

doc: 文档符号修复

---

packages/babel-preset-umi/src/index.test.ts
packages/babel-preset-umi/src/index.ts

feat: 增加 svgr 的配置项

---

packages/bundler-webpack/src/fixtures/node-prefix/expect.ts
packages/bundler-webpack/src/fixtures/node-prefix/index.ts
packages/bundler-webpack/src/getConfig/getConfig.ts

Revert "fix(bundler-webpack): support node: prefix import"

---

packages/babel-preset-umi/src/index.test.ts
packages/babel-preset-umi/src/index.ts

feat: 增加 emitDecoratorMetadata 选项

---

docs/plugins/api.md
docs/plugins/api.zh-CN.md

-----
[View rendered docs/plugins/api.md](https://github.com/chiaweilee/umi/blob/patch-3/docs/plugins/api.md)
[View rendered docs/plugins/api.zh-CN.md](https://github.com/chiaweilee/umi/blob/patch-3/docs/plugins/api.zh-CN.md)

doc: 修复 joi 网址

---

packages/preset-built-in/src/plugins/generateFiles/umi.ts

fix(preset-built-in): umi 18 version check

---

packages/preset-umi/src/features/tmpFiles/routes.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
packages/preset-umi/templates/route.tpl

修复vue route 模板生成错误 , resolve https://github.com/umijs/umi/issues/8209

fix(preset-umi): fix vue route template generation error (resolve #8209)

---

docs/docs/guides/boilerplate.md
docs/docs/max/introduce.md
docs/docs/tutorials/getting-started.md
packages/create-umi/templates/app/src/pages/docs.tsx
packages/create-umi/templates/max/src/pages/Access/index.tsx
packages/create-umi/templates/max/src/pages/Home/index.tsx

- 模板更新支持 vite 热更新 https://github.com/umijs/umi/issues/8195
- 脚手架使用文档增加 @latest https://github.com/umijs/umi/issues/8194
-----
[View rendered docs/docs/guides/boilerplate.md](https://github.com/xierenyuan/umi/blob/feature/fix_template_vite_reload/docs/docs/guides/boilerplate.md)
[View rendered docs/docs/max/introduce.md](https://github.com/xierenyuan/umi/blob/feature/fix_template_vite_reload/docs/docs/max/introduce.md)
[View rendered docs/docs/tutorials/getting-started.md](https://github.com/xierenyuan/umi/blob/feature/fix_template_vite_reload/docs/docs/tutorials/getting-started.md)

feat(create-umi): update template support vite hot update

---

packages/plugins/src/qiankun/master.ts

feat(plugin-qiankun):export MicroAppWithMemoHistory

---

examples/test-vitest/.umirc.ts
examples/test-vitest/components/Greet/Greet.test.tsx
examples/test-vitest/components/Greet/Greet.tsx
examples/test-vitest/components/Greet/__snapshots__/Greet.test.tsx.snap
examples/test-vitest/package.json
examples/test-vitest/pages/index.tsx
examples/test-vitest/tsconfig.json
examples/test-vitest/vitest.config.ts
packages/umi/src/test.ts
pnpm-lock.yaml

1. 导出获取 umi alias 的方法，为了测试用。
2. 添加一个 vitest 测试的例子。

feat(umi/test): export get umi alias method for test

---

packages/preset-umi/src/features/tmpFiles/routes.ts

resolve https://github.com/umijs/umi/issues/8187

feat(preset-umi): conventional layout supports js suffix

---

docs/docs/guides/env-variables.md
packages/bundler-webpack/src/dev.ts

debug 情况下希望关闭 hmr ，网络原因 ws 链接一直不成功。

feat: hmr 环境变量控制是否关闭

---

docs/docs/api/api.md

文档多了一个误字
-----
[View rendered docs/docs/api/api.md](https://github.com/pengyw97/umi/blob/patch-1/docs/docs/api/api.md)

docs:  Delete wrong word

---

docs/docs/api/config.md

Imported module is not used correctly
-----
[View rendered docs/docs/api/config.md](https://github.com/pengyw97/umi/blob/patch-1/docs/docs/api/config.md)

docs: Imported module is not used correctly

---

docs/docs/api/runtime-config.md
docs/docs/guides/routes.md
docs/docs/tutorials/blog.md

由 #8292 ，修正 routes 相关的 api 和配置说明。
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/MoeYc/umi/blob/docs/routes-completion/docs/docs/api/runtime-config.md)
[View rendered docs/docs/guides/routes.md](https://github.com/MoeYc/umi/blob/docs/routes-completion/docs/docs/guides/routes.md)
[View rendered docs/docs/tutorials/blog.md](https://github.com/MoeYc/umi/blob/docs/routes-completion/docs/docs/tutorials/blog.md)

docs: patch routes

---

.github/workflows/e2e.yml

保证 @umijs/test 库相关功能 放进一起放进e2e

ci: 👷 @umijs/test e2e test

---

docs/docs/api/config.md
docs/docs/guides/plugins.md

* mfsu  文档更新
-----
[View rendered docs/docs/api/config.md](https://github.com/umijs/umi/blob/doc/mfsu_eager_doc/docs/docs/api/config.md)

docs(mfsu-eager): 📝  mfsu eager doc update

---

docs/docs/guides/lint.md
packages/lint/src/linter/eslint.ts
packages/lint/src/linter/stylelint.ts
packages/lint/src/types.ts
packages/preset-umi/src/commands/lint.ts

https://github.com/umijs/umi/issues/8269
-----
[View rendered docs/docs/guides/lint.md](https://github.com/zzcan/umi/blob/feat/lint-support-no-quiet/docs/docs/guides/lint.md)

feat(lint): support --no-quiet

---

docs/docs/guides/test.md

souce map is enable by default now.
-----
[View rendered docs/docs/guides/test.md](https://github.com/umijs/umi/blob/doc/jest_update/docs/docs/guides/test.md)

docs: 📝  remove unnecessary lines

---

packages/bundler-webpack/src/config/copyPlugin.ts

ref: https://github.com/ant-design/ant-design-pro/issues/9460

fix(bundler-webpack): do not minimize files in public dir

---

packages/create-umi/src/index.ts

refactor(create-umi): fix any type

---

packages/create-umi/src/index.ts
packages/create-umi/templates/app/package.json.tpl
packages/create-umi/templates/max/package.json.tpl
packages/create-umi/templates/plugin/package.json.tpl
packages/create-umi/templates/vue-app/package.json.tpl
packages/utils/src/getGitInfo.ts
packages/utils/src/index.ts

为 create-umi 脚手架模板中 package.json 文件增加作者字段
从全局 git 配置中取，不存在则置为空

feat(create-umi): add author for package.json

---

packages/bundler-vite/src/server/server.ts
packages/bundler-webpack/src/server/server.ts
packages/preset-umi/src/commands/preview.ts

fix: use localhost instead of 127.0.0.1

---

packages/core/src/config/config.ts
packages/utils/src/register.ts

feat: improve error message for config parsing error

---

docs/docs/guides/styling.md

null
-----
[View rendered docs/docs/guides/styling.md](https://github.com/sakuraNouta/umi/blob/master/docs/docs/guides/styling.md)

docs: update styling.md add @unocss/cli, fix 8414

---

docs/docs/api/runtime-config.md

resolve(https://github.com/umijs/umi/issues/8397)
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/umijs/umi/blob/docs/update_0706_renhong/docs/docs/api/runtime-config.md)

docs: update runtime-config.md fix onRouteChange demo

---

packages/preset-umi/src/features/apiRoute/apiRoute.ts

Close https://github.com/umijs/umi/issues/8409
把这行 warning 先删了。

chore(preset-umi): remove api routes warning

---

packages/max/src/plugins/maxChecker.ts
packages/max/src/preset.ts

feat(max): don't allow umi in dependencies

---

docs/docs/guides/directory-structure.md

null
-----
[View rendered docs/docs/guides/directory-structure.md](https://github.com/umijs/umi/blob/fix-docs-directory/docs/docs/guides/directory-structure.md)

docs: layout >> layouts

---

docs/docs/api/config.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/sushi-su/umi/blob/fix/config-docs/docs/docs/api/config.md)

docs(config): 隐射 -> 映射

---

docs/docs/introduce/contributing.md

null
-----
[View rendered docs/docs/introduce/contributing.md](https://github.com/umijs/umi/blob/docs/contributing-group/docs/docs/introduce/contributing.md)

docs: update contributing.md, add group info

---

scripts/release.js

1. `3.x` 改 `latest-3`，版本号不能作为 tag
2. Umi 3 才有的包还是发 `latest`

chore: correct release tag

---

examples/boilerplate-vue/.umirc.ts
examples/boilerplate-vue/pages/about/index.vue
packages/preset-umi/src/commands/preview.ts

feat(preset-umi): preview support base visit redirect

---

packages/bundler-webpack/src/index.ts
packages/preset-built-in/src/plugins/commands/dev/devCompileDone/devCompileDone.ts
packages/umi/src/cli.ts
packages/umi/src/forkedDev.ts
packages/utils/src/index.ts
packages/utils/src/printHelp/printHelp.ts

resolve https://github.com/umijs/umi/issues/8402
`process.exit`
`webpack compilation error`

feat: improve error message for guide to feedback

---

docs/docs/api/config.md
examples/boilerplate/.umirc.ts
packages/bundler-webpack/src/build.ts
packages/bundler-webpack/src/dev.ts
packages/bundler-webpack/src/schema.ts

null
-----
[View rendered docs/docs/api/config.md](https://github.com/July-ing/umi/blob/feature/cacheDirectoryPath/docs/docs/api/config.md)

feat(bundler-webpack): support cacheDirectoryPath

---

packages/plugins/src/locale.ts

fix(plugins/locale): add addLocale method

---

packages/plugins/libs/locale/SelectLang.tpl

fix(plugins/locale): lang

---

docs/docs/api/config.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/KieSun/umi/blob/fix/docs/docs/docs/api/config.md)

docs: jsminifier to jsMinifier

---

examples/max/.umirc.ts
examples/max/wrappers/bar.tsx
examples/max/wrappers/foo.tsx
packages/core/src/route/routesConfig.test.ts
packages/core/src/route/routesConfig.ts
packages/plugins/src/layout.ts

Close #8497
解决layout 插件同 路由wrappers 使用冲突

feat(plugins): layout menu support routes wrappers conf

---

packages/core/src/route/routesConvention.test.ts
packages/core/src/route/routesConvention.ts

before 
a/$index.tsx -> a/:
after 
a/$index.tsx -> a/:index

fix: convention routes

---

docs/docs/api/api.md
examples/boilerplate/.umirc.ts
examples/boilerplate/layouts/index.tsx
examples/boilerplate/pages/class-component.tsx
packages/renderer-react/src/index.ts
packages/renderer-react/src/withRouter.tsx

支持 withRouter 参数 尽量与 react-router v5  版本对齐

feat(renderer-react): support withRouter

---

packages/bundler-webpack/package.json
packages/bundler-webpack/src/config/config.ts
pnpm-lock.yaml

启用 `@umijs/case-sensitive-paths-webpack-plugin`
效果截图：

feat: enable case-sensitive-paths-webpack-plugin

---

packages/create-umi/bin/create-umi.js

feat: add env

---

docs/docs/max/dva.md

change 'this.dispatch' to 'this.props.dispatch'
-----
[View rendered docs/docs/max/dva.md](https://github.com/Fengjing95/umi/blob/patch-1/docs/docs/max/dva.md)

docs: Update dva.md

---

docs/docs/api/config.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/umijs/umi/blob/fix-doc-externals/docs/docs/api/config.md)

docs: scripts >> headScripts

---

packages/core/fixtures/service/umi-env-local/config/config.cloud.ts
packages/core/fixtures/service/umi-env-local/config/config.local.ts
packages/core/fixtures/service/umi-env-local/config/config.ts
packages/core/fixtures/service/umi-env-local/plugin.ts
packages/core/src/config/config.ts
packages/core/src/service/service.test.ts

config.local 只在 development 生效

fix(core): config local is only available for development

---

examples/lint/package.json
examples/test-test/package.json
examples/x-design/package.json

examples: fix scripts

---

docs/blog/README.md
docs/blog/mfsu-faster-than-vite.mdx
docs/blog/umi-4-rc.mdx

1. 增加连接方便跳转
2. 连接可能不需要换行
3. 点击blog进入到remote目录，readme目录应该跳转到第一个blog页面
blog增加连接方便跳转阅读，虽然谷歌也能搜索到。修改后效果

docs: fix some problems

---

packages/bundler-webpack/src/requireHook.ts

fix(webpack): hook require absolute path

---

packages/plugins/libs/qiankun/slave/lifecycles.ts

fix(plugin/qiankun): props.history empty

---

examples/config-proxy/.umirc.ts
examples/config-proxy/package.json
examples/config-proxy/pages/index.tsx
examples/config-proxy/readme.md
packages/bundler-webpack/src/schema.ts
packages/bundler-webpack/src/server/server.ts
pnpm-lock.yaml

- 支持数组格式的 proxy 配置
- 支持 bypass 配置
-----
[View rendered examples/config-proxy/readme.md](https://github.com/umijs/umi/blob/feat/improve-proxy/examples/config-proxy/readme.md)

feat: improve proxy

---

docs/docs/guides/env-variables.md

补文档。#8431
-----
[View rendered docs/docs/guides/env-variables.md](https://github.com/iamnotblank/umi/blob/patch-1/docs/docs/guides/env-variables.md)

docs: dot env variable expansion

---

packages/renderer-react/src/browser.tsx

fix(renderer-react): support patchClientRoutes

---

docs/docs/max/dva.md
docs/docs/max/layout-menu.md
docs/docs/max/request.md

null
-----
[View rendered docs/docs/max/dva.md](https://github.com/umijs/umi/blob/docs/sync_bigfish_update/docs/docs/max/dva.md)
[View rendered docs/docs/max/layout-menu.md](https://github.com/umijs/umi/blob/docs/sync_bigfish_update/docs/docs/max/layout-menu.md)
[View rendered docs/docs/max/request.md](https://github.com/umijs/umi/blob/docs/sync_bigfish_update/docs/docs/max/request.md)

docs:  sync bigfish update

---

docs/docs/api/api.md
docs/docs/max/dva.md

null
-----
[View rendered docs/docs/api/api.md](https://github.com/umijs/umi/blob/docs/update_0725/docs/docs/api/api.md)
[View rendered docs/docs/max/dva.md](https://github.com/umijs/umi/blob/docs/update_0725/docs/docs/max/dva.md)

docs: 📝  调整 history 介绍顺序

---

packages/bundler-webpack/src/config/copyPlugin.ts

fix(webpack/copy): not copy dir when public empty

---

packages/bundler-webpack/src/types.ts
packages/plugins/src/access.ts
packages/plugins/src/analytics.ts
packages/plugins/src/antd.ts
packages/plugins/src/dva.ts
packages/plugins/src/initial-state.ts
packages/plugins/src/layout.ts
packages/plugins/src/locale.ts
packages/plugins/src/model.ts
packages/plugins/src/moment2dayjs.ts
packages/plugins/src/qiankun.ts
packages/plugins/src/request.ts
packages/plugins/src/tailwindcss.ts
packages/plugins/src/unocss.ts

1. `jsMinifier` 用 union type 代替枚举，使得用户用字符串配置时不会报错
2. `antd` 等插件实际上支持 false 关闭，但配置 false 时会类型错误，进行修正

fix: jsMinifier type & plugins type in defineConfig

---

packages/renderer-react/src/routes.tsx

close https://github.com/ant-design/ant-design-pro/issues/9945

fix(renderer-react): fix redirect endless loop

---

docs/docs/api/config.md

对象中不应该是分号
-----
[View rendered docs/docs/api/config.md](https://github.com/txp1035/umi/blob/docs_fixvite/docs/docs/api/config.md)

docs: fix Incorrect punctuation marks

---

docs/docs/max/access.md
packages/plugins/src/layout.ts

自定义权限页面api问题
1. 类型定义和api不一
2. 文档不齐全，需要看源码各种找.

fix: wrong permission type name

---

packages/plugins/libs/qiankun/slave/lifecycles.ts
packages/renderer-react/src/browser.tsx
packages/renderer-react/src/index.ts

feat(qiankun): support react 18 unmount

---

packages/plugins/libs/qiankun/master/MicroApp.tsx

ref: https://github.com/umijs/plugins/pull/866

fix(plugins/qiankun): appNameKeyAlias compatible

---

packages/bundler-webpack/.fatherrc.ts
packages/bundler-webpack/client/client/client.js

改用 babel 编译 `client.ts`，因为其中的 `module` 语法在 esbuild 看来是 cjs 模块，会强制做包裹导致 hmr 失效

fix(bundler-webpack): client dist for hmr

---

packages/bundler-vite/src/server/server.ts

feat(bundler-vite): server tip higt light

---

packages/mfsu/src/staticDepInfo/simulations/babel-plugin-import.ts

chore: ✏️ log correct

---

docs/docs/api/config.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/umijs/umi/blob/mr/master/fix_doc_presets/docs/docs/api/config.md)

docs: presets config

---

docs/docs/guides/test.md
packages/create-umi/templates/app/.gitignore.tpl
packages/create-umi/templates/max/.gitignore.tpl
packages/create-umi/templates/vue-app/.gitignore.tpl

resolve #8758
1. 完善文档，max 使用 jest 时候应该从 max 导入。
2. 补全模版的 ignore ，`umi-test` 也需要忽略。 
-----
[View rendered docs/docs/guides/test.md](https://github.com/MoeYc/umi/blob/chore/max-use-jest-docs/docs/docs/guides/test.md)

docs(jest): max use jest import position

---

packages/plugins/src/layout.ts

补充类型： `rightContentRender` `rightRender` `logout`
Close #8606 
Close #8649 
Close #8558

fix(plugin-layout): 完善 RunTimeLayoutConfig 类型

---

packages/preset-umi/src/features/check/check.ts

fix(preset-umi): publicPath is not allow ./ in dev mode

---

packages/preset-umi/src/commands/dev/dev.ts

Close #8610
Close #8608
先加 try..catch 避免退出吧，用 awaitWriteFinish 会让监听变慢。

fix(preset-umi): package.json watch might crash

---

docs/docs/introduce/contributing.md

贡献文档bash多余的 --
-----
[View rendered docs/docs/introduce/contributing.md](https://github.com/txp1035/umi/blob/fix_doc/docs/docs/introduce/contributing.md)

docs: redundant commands

---

packages/preset-umi/src/commands/generators/tsconfig.ts

resolve https://github.com/umijs/umi/issues/8741
@stormslowly pshu老师看下ok不？需要补充一下文档吗？

feat: enhance gen tsconfig

---

docs/docs/max/request.md

修复前
修复后
-----
[View rendered docs/docs/max/request.md](https://github.com/txp1035/umi/blob/fix_hooksdoc/docs/docs/max/request.md)

docs: fixing invalid links

---

docs/docs/api/runtime-config.md
docs/docs/guides/test.md
docs/docs/max/access.md

-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/umijs/umi/blob/chore/docs_correct_0801/docs/docs/api/runtime-config.md)
[View rendered docs/docs/guides/test.md](https://github.com/umijs/umi/blob/chore/docs_correct_0801/docs/docs/guides/test.md)
[View rendered docs/docs/max/access.md](https://github.com/umijs/umi/blob/chore/docs_correct_0801/docs/docs/max/access.md)

chore(docs): ✏️ 更正文档细节

---

docs/docs/api/config.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/findmio/umi/blob/master/docs/docs/api/config.md)

docs(config):  punctuation used incorrectly

---

.github/workflows/issue-check.yml

close https://github.com/umijs/umi/issues/8718

ci: add issue check

---

packages/umi/package.json
packages/utils/package.json

#8821 的方案不好使，只能循环依赖了，两者并非同时调用，功能应当不受影响

fix(utils): declare @umijs/babel-preset-umi

---

packages/preset-vue/src/features/default.ts
packages/preset-vue/src/utils/resolveProjectDep.ts

fix(preset-vue): fix vue get dependency error from project

---

docs/docs/api/runtime-config.md
docs/docs/introduce/upgrade-to-umi-4.md

场景：想在文档查看dva配置参数有什么作用。然后查不到。在v3文档查到了。api还是写在配置后方便看，从v3搬运过来了。
[View rendered docs/docs/introduce/upgrade-to-umi-4.md](https://github.com/txp1035/umi/blob/fix_doc_hmr/docs/docs/introduce/upgrade-to-umi-4.md)

docs: about hmr

---

docs/docs/max/request.md

null
-----
[View rendered docs/docs/max/request.md](https://github.com/zhousg/umi/blob/docs-fix/docs/docs/max/request.md)

docs: punctuation format error

---

packages/preset-umi/src/features/mock/getMockData.ts

fix(preset-umi): mock hmr don't work in win

---

packages/preset-umi/src/features/tmpFiles/tmpFiles.ts

fix(route): nested route not get outlet context value

---

docs/docs/api/runtime-config.md
docs/docs/introduce/upgrade-to-umi-4.md

Reverts umijs/umi#8818
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/umijs/umi/blob/revert-8818-fix_doc_hmr/docs/docs/api/runtime-config.md)
[View rendered docs/docs/introduce/upgrade-to-umi-4.md](https://github.com/umijs/umi/blob/revert-8818-fix_doc_hmr/docs/docs/introduce/upgrade-to-umi-4.md)

Revert "docs: about hmr"

---

docs/docs/api/runtime-config.md
docs/docs/introduce/upgrade-to-umi-4.md

#8843
之前白屏原因：
代码没有处理解析错误了
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/txp1035/umi/blob/fix_aboutHmr/docs/docs/api/runtime-config.md)
[View rendered docs/docs/introduce/upgrade-to-umi-4.md](https://github.com/txp1035/umi/blob/fix_aboutHmr/docs/docs/introduce/upgrade-to-umi-4.md)

fix: mdx compile

---

packages/server/src/Server/Server.ts

fix(server): remove dev server backlog limit

---

docs/docs/introduce/upgrade-to-umi-4.md

ref: [8359#issuecomment-1173393160](https://github.com/umijs/umi/issues/8359#issuecomment-1173393160)
-----
[View rendered docs/docs/introduce/upgrade-to-umi-4.md](https://github.com/drizzlesconsin/umi/blob/patch-1/docs/docs/introduce/upgrade-to-umi-4.md)

docs(layout): fix upgrade umi4

---

.github/workflows/ci.yml
.github/workflows/compressed-size.yml
.github/workflows/coverage.yml
.github/workflows/doc.yml
packages/plugin-docs/src/compiler.test.ts
packages/plugin-docs/src/compiler.ts

workflow: add doc workflow for check build doc

---

docs/docs/api/commands.md
docs/docs/tutorials/getting-started.md
packages/bundler-vite/src/dev.ts
packages/bundler-vite/src/server/server.ts
packages/bundler-webpack/src/server/server.ts
packages/utils/src/getDevBanner.ts
packages/utils/src/index.ts

优化 dev server 启动后的输出信息，效果如下：
-----
[View rendered docs/docs/api/commands.md](https://github.com/umijs/umi/blob/feature/better-dev-banner/docs/docs/api/commands.md)
[View rendered docs/docs/tutorials/getting-started.md](https://github.com/umijs/umi/blob/feature/better-dev-banner/docs/docs/tutorials/getting-started.md)

feat: improve dev server banner

---

packages/core/src/route/routesConfig.test.ts
packages/core/src/route/routesConfig.ts

fix(route): wrappers should inherit `layout: false`

---

packages/plugins/libs/qiankun/master/common.ts
packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx

ref: 
https://github.com/umijs/umi-next/pull/342
https://github.com/umijs/plugins/pull/796

feat(plugins/qiankun): support insertBefore and appendChildTo

---

packages/bundler-utils/package.json
pnpm-lock.yaml

ref: https://github.com/umijs/umi/pull/8846

fix(bundler-utils): regenerate dep lost

---

packages/plugins/src/layout.ts

fix(plugins): layout plugin vite compile error

---

packages/utils/src/getDevBanner.ts

修复 host 太长的时候 footer 的右边框会缺少空格补齐的问题

fix(utils): dev banner style when host is long

---

docs/docs/api/api.md

fix: https://github.com/umijs/umi/issues/8933 https://github.com/umijs/umi/issues/8943
-----
[View rendered docs/docs/api/api.md](https://github.com/drizzlesconsin/umi/blob/patch-3/docs/docs/api/api.md)

docs: fix useOutletContext type

---

packages/bundler-webpack/src/types.ts

fix cssMinifier & depTranspiler type

fix(type): CSSMinifier & Transpiler

---

packages/plugin-docs/src/index.ts

支持 md 文件热更新
**标题热更新后还会触发 reload 因为文件变更会触发route.tsx**

feat(plugins-docs): support md file hot update

---

packages/preset-umi/src/features/mock/getMockData.ts

fix(preset-umi): mock hmr don't work in win (#8882)

---

.github/workflows/issue-checker.yml

`github.event.issue.actor.site_admin` 用法不对，改一下判断方式，不校验有 write 权限的 issue 。

ci(issue): not close issue for user with write auth

---

packages/utils/src/getDevBanner.ts

emoji 的字符似乎在不同设备上长度表现不一致，换成箭头解决 dev banner 边框对齐的问题
Close #8956

fix(utils): dev banner emoji length

---

packages/renderer-react/src/withRouter.tsx

refactor(renderer-react): withRouter RouteComponentProps change to optional

---

docs/docs/max/micro-frontend.md

null
-----
[View rendered docs/docs/max/micro-frontend.md](https://github.com/umijs/umi/blob/PeachScript-patch-3/docs/docs/max/micro-frontend.md)

docs: route wildcard explanation for micro app

---

docs/docs/introduce/upgrade-to-umi-4.md

null
-----
[View rendered docs/docs/introduce/upgrade-to-umi-4.md](https://github.com/xiaohp/umi/blob/patch-1/docs/docs/introduce/upgrade-to-umi-4.md)

docs: fix plugin api link

---

docs/docs/max/introduce.md
docs/docs/max/moment2dayjs.md
docs/docs/max/tailwindcss.md

好久没写文档了
-----
[View rendered docs/docs/max/introduce.md](https://github.com/umijs/umi/blob/docs/add_tailwind_moment2dayjs/docs/docs/max/introduce.md)
[View rendered docs/docs/max/moment2dayjs.md](https://github.com/umijs/umi/blob/docs/add_tailwind_moment2dayjs/docs/docs/max/moment2dayjs.md)
[View rendered docs/docs/max/tailwindcss.md](https://github.com/umijs/umi/blob/docs/add_tailwind_moment2dayjs/docs/docs/max/tailwindcss.md)

docs: 📝 补充 tailwindcss 和 moment2dayjs 文档

---

packages/bundler-webpack/src/server/server.ts

fix(bundler-webpack): cannot access ws before initialization

---

packages/bundler-webpack/src/dev.ts
packages/bundler-webpack/src/server/server.ts
packages/mfsu/src/mfsu/mfsu.ts
packages/preset-umi/src/commands/dev/dev.ts

fix(mfsu): cannot be access from none localhost

---

docs/docs/api/plugin-api.md
docs/docs/max/moment2dayjs.md
docs/docs/max/tailwindcss.md

null
-----
[View rendered docs/docs/api/plugin-api.md](https://github.com/xiaohp/umi/blob/patch-1/docs/docs/api/plugin-api.md)
[View rendered docs/docs/max/moment2dayjs.md](https://github.com/xiaohp/umi/blob/patch-1/docs/docs/max/moment2dayjs.md)
[View rendered docs/docs/max/tailwindcss.md](https://github.com/xiaohp/umi/blob/patch-1/docs/docs/max/tailwindcss.md)

docs: fix typo and 404 link

---

.github/workflows/e2e.yml
examples/boilerplate-vue/.gitignore
examples/boilerplate-vue/.umirc.ts
examples/boilerplate-vue/cypress.config.ts
examples/boilerplate-vue/cypress/e2e/detail.cy.ts
examples/boilerplate-vue/cypress/e2e/smoke.cy.ts
examples/boilerplate-vue/cypress/fixtures/example.json
examples/boilerplate-vue/cypress/support/commands.ts
examples/boilerplate-vue/cypress/support/e2e.ts
examples/boilerplate-vue/layouts/index.vue
examples/boilerplate-vue/package.json
pnpm-lock.yaml

test(e2e): add test case for boilerplate-vue

---

docs/docs/api/plugin-api.md

补充文档
-----
1.  onPatchRoute
2. writeTmpFile
@sorrycc  我描述不准确的地方云谦老师补充下哈
暂时不格式化了，单独提个issues讨论下

docs(plugin-api): add onPatchRoute and writeTmpFile

---

packages/preset-umi/src/features/apiRoute/request.ts

fix(apiRoute): application/x-www-form-urlencoded编码方式提交的数据解码方法由decodeURI改为decodeURIComponent

fix(apiRoute): application/x-www-form-urlencoded编码方式提交的数据解码方法由decodeURI改为decodeURIComponent

---

packages/renderer-react/src/browser.tsx

fix: route match in client loader

---

examples/mpa/pages/foo/config.json
packages/preset-umi/src/features/mpa/extractExports.ts
packages/preset-umi/src/features/mpa/mpa.ts

fix(mpa): support hmr (partically)

---

packages/testing/src/transformers/esbuild/index.ts

fix(umi-test): transform `jest.doMock`

---

docs/docs/guides/mpa.md
examples/mpa/.umirc.ts
examples/mpa/pages/foo/config.json
packages/preset-umi/src/features/mpa/mpa.ts

null
-----
[View rendered docs/docs/guides/mpa.md](https://github.com/umijs/umi/blob/feat/mpa-config-json/docs/docs/guides/mpa.md)

feat(preset-umi): mpa use config.json by default

---

packages/core/src/service/service.test.ts
packages/core/src/service/service.ts

test: skip umi env test

---

docs/docs/max/request.md

还是补充文档吧 https://github.com/umijs/umi/issues/9086
-----
[View rendered docs/docs/max/request.md](https://github.com/drizzlesconsin/umi/blob/patch-1/docs/docs/max/request.md)

docs(request): add get request params serialize

---

docs/docs/api/config.md
examples/boilerplate/.umirc.ts
examples/boilerplate/pages/unused/index.ts
packages/bundler-webpack/src/config/detectDeadCode.ts
packages/bundler-webpack/src/config/detectDeadCodePlugin.ts

fix #9154
-----
[View rendered docs/docs/api/config.md](https://github.com/MoeYc/umi/blob/fix/dead-code-exclude/docs/docs/api/config.md)

fix(deadCode): deadCode exclude not working

---

packages/core/src/service/service.ts

调用 lodash.merge 时修改了 this.configDefaults

fix(chore): 修复merge config 时修改了defaultConfig的问题

---

docs/docs/api/config.md

文档mdx配置说明
-----
[View rendered docs/docs/api/config.md](https://github.com/txp1035/umi/blob/docs_mdx/docs/docs/api/config.md)

docs(config): add mdx

---

examples/umi-run/scripts/zx.ts
packages/plugin-run/src/index.ts

feat: run command support args

---

docs/docs/guides/mpa.md
examples/mpa/.umirc.ts
examples/mpa/templates/default.html
packages/preset-umi/src/features/mpa/mpa.ts

null
-----
[View rendered docs/docs/guides/mpa.md](https://github.com/umijs/umi/blob/feat/mpa-default-template/docs/docs/guides/mpa.md)

feat(preset-umi): mpa support default template config

---

packages/bundler-webpack/compiled/webpack/package.json
scripts/bundleDeps.ts

chore(bundler-webpack): webpack compiled add version

---

packages/plugins/src/qiankun/slave.ts

fix: qiankun环境isMasterApp判断逻辑运行报错问题(#9202)

---

docs/docs/api/runtime-config.md

close #9249
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/MoeYc/umi/blob/chore/220906/docs/docs/api/runtime-config.md)

docs: fix link

---

.github/workflows/e2e.yml
docs/blog/mfsu-faster-than-vite.mdx
docs/blog/umi-4-rc.mdx
examples/boilerplate-vue/pages/index.vue
examples/mfsu-un-match-libs/pages/index.vue
examples/mpa/templates/default.html

代码风格 格式化
-----
[View rendered docs/blog/mfsu-faster-than-vite.mdx](https://github.com/umijs/umi/blob/feature/code_style/docs/blog/mfsu-faster-than-vite.mdx)
[View rendered docs/blog/umi-4-rc.mdx](https://github.com/umijs/umi/blob/feature/code_style/docs/blog/umi-4-rc.mdx)

chore: code style

---

packages/bundler-webpack/package.json
packages/preset-built-in/package.json

dep: bump terser to 5.14.2

---

packages/plugins/src/tailwindcss.ts

fix(tailwind): bin path

---

examples/max/.umirc.ts
examples/max/cypress/e2e/access.cy.ts
examples/max/cypress/e2e/data-flow.cy.ts
examples/max/cypress/e2e/smoke.cy.ts

fix: 🐛 max demo dev error

---

docs/docs/api/config.md
packages/preset-umi/package.json
packages/preset-umi/src/features/configPlugins/schema.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
packages/renderer-react/src/appContext.ts
packages/renderer-react/src/browser.tsx
packages/renderer-react/src/routes.tsx
pnpm-lock.yaml

null
-----
[View rendered docs/docs/api/config.md](https://github.com/umijs/umi/blob/sorrycc-kgd1/docs/docs/api/config.md)

feat: new config historyWithQuery

---

packages/plugins/src/layout.ts

fix(plugin-layout): fixed missing base for breadcrumbs

---

docs/docs/guides/env-variables.md
packages/preset-umi/src/index.ts

null
-----
[View rendered docs/docs/guides/env-variables.md](https://github.com/umijs/umi/blob/sorrycc-3558/docs/docs/guides/env-variables.md)

feat(preset-umi): support disable did-you-know with DID_YOU_KNOW=none

---

package.json
pnpm-lock.yaml

chore: upgrade father to 4.0.4

---

packages/preset-umi/src/features/tmpFiles/__snapshots__/routes.test.ts.snap
packages/preset-umi/src/features/tmpFiles/routes.test.ts
packages/preset-umi/src/features/tmpFiles/routes.ts

fix(routes): absolute component path

---

packages/preset-umi/src/features/mpa/mpa.ts

fix(mpa): entry file win path

---

docs/docs/guides/mpa.md
examples/mpa/.umirc.ts
examples/mpa/layouts/basic.tsx
packages/preset-umi/src/features/mpa/mpa.ts

null
-----
[View rendered docs/docs/guides/mpa.md](https://github.com/umijs/umi/blob/sorrycc-8lst/docs/docs/guides/mpa.md)

feat(preset-umi): mpa support global layout config

---

packages/bundler-esbuild/src/build.ts

feat(mfsu):add .wasm esbuild loader

---

packages/bundler-webpack/client/client/client.js
packages/bundler-webpack/src/client/client.ts

修复`pingTimer `类型，这里`setInterval`返回的类型是`number`

fix: bundler-webpack client timer type

---

docs/docs/api/runtime-config.md
packages/renderer-react/src/browser.tsx

null
-----
[View rendered docs/docs/api/runtime-config.md](https://github.com/umijs/umi/blob/sorrycc-3gne/docs/docs/api/runtime-config.md)

feat: add basename to onRouteChange

---

docs/docs/guides/mpa.md
examples/mpa/.umirc.ts
examples/mpa/templates/default.html
packages/preset-umi/src/features/mpa/mpa.ts

null
-----
[View rendered docs/docs/guides/mpa.md](https://github.com/umijs/umi/blob/sorrycc-2a62/docs/docs/guides/mpa.md)

feat: mpa support config entry globally

---

packages/plugins/src/access.ts

close https://github.com/ant-design/ant-design-pro/issues/10103

fix(access): remove access error,and use children replace routes

---

packages/plugins/src/access.ts

Revert "fix(access): remove access error,and use children replace routes"

---

packages/plugin-docs/package.json

fix(plugin-docs): 🐛 miss tailwind.out.css

---

docs/docs/api/config.md
examples/with-mobx/.umirc.ts
examples/with-mobx/pages/hello.tsx
examples/with-mobx/stores/index.ts
examples/with-mobx/stores/modules/hello.ts
examples/with-mobx/tsconfig.json
packages/babel-preset-umi/src/index.test.ts
packages/babel-preset-umi/src/index.ts
packages/bundler-utils/bundles/babel/bundle.js
packages/bundler-utils/bundles/babel/packages/plugin-proposal-class-properties.js
packages/bundler-utils/bundles/babel/packages/plugin-proposal-private-methods.js
packages/bundler-utils/bundles/babel/packages/plugin-proposal-private-property-in-object.js
packages/bundler-utils/compiled/babel/plugin-proposal-class-properties.js
packages/bundler-utils/compiled/babel/plugin-proposal-private-methods.js
packages/bundler-utils/compiled/babel/plugin-proposal-private-property-in-object.js
packages/preset-umi/src/features/classPropertiesLoose/classPropertiesLoose.ts
packages/preset-umi/src/features/enableClassPropertiesLoose/enableClassPropertiesLoose.ts
packages/preset-umi/src/index.ts

增加 enableClassPropertiesLoose 支持 mobx  decorators 能力是可选的不对原有功能有影响

feat(preset-umi): add classPropertiesLoose

---

examples/max/package.json
packages/bundler-vite/src/config/transformer/optimizeDeps.test.ts
packages/bundler-vite/src/config/transformer/optimizeDeps.ts
pnpm-lock.yaml

feat(bundler-vite): optimizeDeps supports webpack suffix $

---

packages/preset-umi/src/features/vite/vite.ts

vite 模式 开发环境 禁用 polyfill 开启 polyfill 会导致 加载东西过多 白屏时间过长 close #9359

feat(preset-umi): vite development disable polyfill

---

packages/plugins/src/layout.ts

chore(plugins): layout add comment

---

.github/workflows/e2e.yml
.gitignore
docs/docs/max/valtio.md
libs/valtio/.fatherrc.ts
libs/valtio/package.json
libs/valtio/src/index.ts
package.json
packages/max/src/preset.ts
packages/plugins/package.json
packages/plugins/src/valtio.ts
pnpm-lock.yaml
pnpm-workspace.yaml
theme.config.ts

null
-----
[View rendered docs/docs/max/valtio.md](https://github.com/umijs/umi/blob/sorrycc-2oth/docs/docs/max/valtio.md)

feat: valtio plugin

---

packages/preset-umi/src/features/configPlugins/configPlugins.ts
packages/preset-umi/src/libs/folderCache/AutoUpdateSourceCodeCache.ts

fix(mfus): 🎨  支持 js 文件中使用 jsx 语法

---

packages/plugins/libs/locale/runtime.tpl
packages/plugins/src/access.ts
packages/plugins/src/layout.ts
packages/preset-umi/src/features/tmpFiles/routes.ts
packages/renderer-react/src/routes.tsx

Revert "Remove route from chenshuai2144"

---

packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl

To keep the same logic with umi 3.x qiankun plugin
ref: https://github.com/umijs/plugins/blob/master/packages/plugin-qiankun/src/master/getMicroAppRouteComponent.ts.tpl#L27

fix: Fix qiankun route match

---

packages/plugins/src/antd.ts

refactor(plugins): correct config logic in antd plugin

---

packages/preset-umi/src/commands/dev/depBuildWorker/depBuildWorker.ts
packages/umi/src/cli/cli.ts
packages/umi/src/cli/forkedDev.ts
packages/umi/src/cli/node.ts
packages/utils/src/index.ts
packages/utils/src/setNoDeprecation.ts

防止 mfsu eager 模式的 `Worker` 提示警告

chore: prevent deprecated warning in mfsu eager worker

---

packages/plugins/libs/qiankun/master/MicroApp.tsx
packages/plugins/libs/qiankun/master/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/9548)

feat: prefetch 增加 threshold 配置，避免低端机场景 prefetch 造成的 oom

---

examples/max/.umirc.ts
packages/mfsu/src/mfsu/mfsu.ts
packages/mfsu/src/mfsu/strategyStaticAnalyze.ts
packages/mfsu/src/staticDepInfo/staticDepInfo.ts
packages/mfsu/src/utils/webpackUtils.test.ts
packages/mfsu/src/utils/webpackUtils.ts

Close https://github.com/umijs/umi/issues/9522

fix(mfsu-eager): 🐛  eager 模式 babel-plugin-import 的依赖实际 import 配置

---

codecov.yml
packages/preset-umi/src/commands/dev/dev.ts
packages/preset-umi/src/libs/folderCache/AutoUpdateSourceCodeCache.ts

1. 忽略其他非项目代码目录
2. 提示 eager 模式最好 有 `src` 目录

fix(mfsu-eager):  忽略 .umi-test 目录

---

packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts

支持环境变量禁用 app.ts 自动注册，避免与组件库项目的目录结构冲突

feat(preset-built-in): add env to disable app runtime plugin

---

packages/preset-umi/src/libs/folderCache/AutoUpdateSourceCodeCache.ts

chore: 增加代码依赖扫描忽略

---

packages/umi/src/service/service.ts

service 支持传 frameworkName  及 defaultConfigFiles 参数

feat(umi): service support custom param

---

packages/core/fixtures/service/service-custom-paths/config/config.cloud.ts
packages/core/fixtures/service/service-custom-paths/config/config.local.ts
packages/core/fixtures/service/service-custom-paths/config/config.ts
packages/core/fixtures/service/service-custom-paths/plugin.ts
packages/core/src/service/service.test.ts
packages/core/src/service/service.ts

feat(core): service support custom paths

---

docs/docs/api/config.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/umijs/umi/blob/sorrycc-c4sj/docs/docs/api/config.md)

docs: add config writeToDisk

---

docs/docs/api/plugin-api.md
examples/boilerplate/plugin.ts
packages/core/src/service/pluginAPI.ts
packages/utils/src/logger.ts

resolve #9412
-----
[View rendered docs/docs/api/plugin-api.md](https://github.com/MoeYc/umi/blob/feat/logger-profile-method/docs/docs/api/plugin-api.md)

feat(logger): measure time method

---

examples/boilerplate/.umirc.ts
examples/boilerplate/tsconfig.json
packages/preset-umi/src/features/tmpFiles/configTypes.ts

fix(type): `chainWebpack` intersection type never

---

packages/preset-umi/package.json
packages/preset-umi/src/features/ssr/ssr.ts
packages/preset-umi/src/features/ssr/webpack/webpack.ts
pnpm-lock.yaml

1. 修复 ssr 开发阶段的 middleware 顺序错误导致的静态资源 404 问题
2. 修复 ssr 产物里缺少 css modules map 的问题

fix: middleware & css modules in ssr bundle

---

examples/ant-design-pro/package.json
examples/ant-design-pro/src/pages/dashboard/analysis/components/Charts/Bar/index.tsx
examples/ant-design-pro/src/pages/dashboard/analysis/components/Charts/Pie/index.tsx
examples/ant-design-pro/src/pages/dashboard/analysis/components/Charts/TagCloud/index.tsx
examples/ant-design-pro/src/pages/dashboard/monitor/components/Charts/Pie/index.tsx
examples/ant-design-pro/src/pages/dashboard/monitor/components/Charts/TagCloud/index.tsx
pnpm-lock.yaml

fix: example dependency missing

---

packages/preset-umi/src/features/tmpFiles/tmpFiles.ts

fix(ssr): `build-manifest.json` file win path

---

packages/preset-umi/src/features/exportStatic/exportStatic.ts

refactor(preset-umi): correct no helmet ssr content

---

packages/preset-umi/src/features/appData/umiInfo.ts
packages/preset-umi/src/index.ts

支持 wappalyzer 浏览器插件检测技术栈。
检测依据：
https://github.com/wappalyzer/wappalyzer/blob/f846a555afd4be9f6454a605bf7c5a0544c09592/src/technologies/u.json#L269

feat(info): detect version for wappalyzer

---

examples/ant-design-pro/tsconfig.json

resolve #9781
补上缺失的 tsconfig 文件，防止 IDE 报错。

example: tsconfig.json

---

packages/preset-umi/templates/umi.tpl

bug 表现 乾坤子应用无法匹配路由渲染
This reverts commit 2d0ed66835ca96272c087db191cdbb1ef54b8490.

Revert "fix: history is undefined on render (#9765)"

---

packages/umi/src/cli/fork.ts

Close https://github.com/umijs/umi/issues/9623

fix(umi): wait for port release when restart

---

packages/utils/src/isStyleFile.ts

fix(utils): improve syntax in utils

---

examples/boilerplate-vue/.umirc.ts
examples/boilerplate/.umirc.ts
packages/preset-umi/src/features/configPlugins/schema.ts

Revert "refactor: 🎨 base config valiate endsWith('/') (#9776)"
This reverts commit 86bcacd9cd8a07671cc6d67f00efaab665ba10d1.

fix: 回滚 base config 校验

---

packages/preset-umi/src/commands/dev/getAssetsMap.ts

ant.design 仓库 npm start，m1 下这里平均耗时 1s+。

fix(preset-umi): stats.toJson() is slow

---

packages/preset-umi/src/commands/build.ts

feat: ✨ onBuildHtmlComplete 事件增加 htmlFiles 字段

---

package.json
pnpm-lock.yaml

feat: upgrade father version to support sourcemap

---

packages/preset-umi/src/commands/generators/precommit.ts

windows 系统下不需要执行 chmod
Close #9828

fix(preset-umi): do not need to run chmod on windows

---

docs/docs/api/config.md
docs/docs/guides/mfsu.md

null
-----
[View rendered docs/docs/api/config.md](https://github.com/umijs/umi/blob/doc/mfsu_worker/docs/docs/api/config.md)
[View rendered docs/docs/guides/mfsu.md](https://github.com/umijs/umi/blob/doc/mfsu_worker/docs/docs/guides/mfsu.md)

docs: 📝  mfsu vs worker work around 文档更新

---

docs/docs/api/config.md
docs/docs/guides/mfsu.md

null
-----
[View rendered docs/docs/guides/mfsu.md](https://github.com/umijs/umi/blob/doc/mfsu_worker_typo/docs/docs/guides/mfsu.md)

chore: fix mfsu worker doc typo

---

packages/umi/client/client/plugin.js
packages/umi/client/client/utils.js

chore: 🔧 项目重新构建 client 代码更新

---

packages/preset-umi/src/features/codeSplitting/codeSplitting.ts

来自 @xiaohuoni 的反馈。
当 `require` 一个大的相对路径的 `.js` 时，需要去除前导 `.` 和路径分隔符。
同时跳过处理大号的 css 文件导入，因为他可能是游离的，没有 js 文件引导他进入页面。
```ts
// package/index.js
export { View } from './path/to/some'
import './path/to/style.css'
```
```ts
import { View } from 'package'
```
此时，`./path/to/style.css` 是一个副作用，需要跳过处理。
这和 gatsby 中的做法一致：https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L651

fix(splitChunks): prune name when require big pkg with relative path

---

packages/preset-umi/src/features/check/check.ts

close #9908
反馈这个问题的人多于 3 个，故补充更详细的解决提示信息。

chore: publicPath start with relative path print tip

---

packages/preset-umi/src/commands/build.ts
packages/preset-umi/src/commands/dev/dev.ts
packages/preset-umi/src/types.ts

fix(preset-umi): onGenerateFiles arg type

---

packages/preset-umi/src/features/configPlugins/configPlugins.ts

feat(preset-umi): routes config default change type adjust to regenerateTmpFiles

---

docs/docs/api/config.md
docs/docs/guides/env-variables.md
packages/bundler-webpack/src/config/bundleAnalyzerPlugin.ts
packages/bundler-webpack/src/types.ts
packages/preset-umi/src/features/configPlugins/schema.ts

resolve #9940
支持 analyze 插件的自定义配置。

feat(analyze): support analyze config

---

packages/create-umi/src/index.test.ts
packages/create-umi/templates/max/package.json.tpl

refer to: [更新 @umi/max 对 antd 的版本依赖为 >= 4.20.6 ](https://github.com/umijs/umi/issues/9906)

feat(create-umi): add Antd version Select

---

examples/max/cypress.config.ts
examples/mf-host/cypress.config.ts
examples/mf-remote/cypress.config.ts
examples/mfsu-e2e/cypress.config.ts
examples/qiankun-master/.umirc.ts
examples/qiankun-master/package.json
examples/qiankun-master/pages/manual-slave.tsx
examples/qiankun-slave/.umirc.ts
examples/qiankun-slave/cypress.config.ts
examples/qiankun-slave/cypress/e2e/example.cy.ts
packages/plugins/libs/qiankun/slave/slaveRuntimePlugin.ts
packages/preset-umi/templates/umi.tpl
pnpm-lock.yaml

修复 乾坤 slave 插件在没有 basename 和  type 的情况下会破坏渲染参数的问题

fix: qinkun slave modify render context corrupt basename 

---

docs/docs/guides/styling.md
examples/with-unocss/.umirc.ts

更新 unocss 文档问题
详见 issue: #9994

docs: update unocss watch file path

---

packages/create-umi/templates/app/.umirc.ts.tpl
packages/create-umi/templates/vue-app/.umirc.ts.tpl

默认模板中，加入 defineConfig 获取更好的 config 提示支持

feat: add defineConfig in cli templates

---

docs/docs/guides/use-plugins.md
theme.config.ts

resolve #10045
补充文档解决 很多人的一个疑惑：umi 不附带插件，怎么单独用 max 的功能 。

docs: how to use the plugin

---

examples/with-request/.umirc.ts
examples/with-request/pages/index.tsx
packages/preset-umi/templates/plugin.tpl

fix(preset-umi): fix vite hot update pluginManager bug with null

---

packages/plugins/libs/qiankun/master/MicroApp.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/10072)

feat(qiankun): 增加默认的微应用容器样式

---

packages/bundler-vite/package.json
packages/bundler-vite/src/index.ts
pnpm-lock.yaml

requireHook vite 不生效, 手动补齐 less 依赖

fix(bundler-vite): add less deps

---

docs/docs/introduce/faq.md

继 #10021
utf8 的切换方式，不改配置了，补文档。

docs: use `utf8` charset config

---

packages/core/src/route/routesConfig.test.ts
packages/core/src/route/routesConfig.ts

Revert "fix(route): `absPath` missing slash"

---

docs/docs/max/antd.md
packages/plugins/src/antd.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts

需求背景：antd5 预设算法配置需要设置动态/函数参数，参考：[使用预设算法](https://ant.design/docs/react/customize-theme-cn#%E4%BD%BF%E7%94%A8%E9%A2%84%E8%AE%BE%E7%AE%97%E6%B3%95)

feat(plugin-antd): antd 插件支持运行时配置

---

docs/docs/tutorials/getting-started.md

bun 发布 0.4.0 ，使用 bunx 初始化项目非常快。
https://github.com/oven-sh/bun/releases

docs: use bunx create command

---

docs/docs/guides/directory-structure.md

docs: describe conventional overrides.less

---

docs/docs/api/api.md

docs: 📝 update history.push state docs

---

packages/plugins/src/qiankun/slave.ts

本地研发时设置__QIANKUN_DEVELOPMENT__ 为true

fix(qiankun-plugin): 修复本地研发时热更新报错

---

packages/renderer-react/src/types.ts

用户反馈，我们的类型不够精准：https://github.com/umijs/umi/discussions/10182#discussioncomment-4549071

chore(type): `IRoute` type refactor

---

packages/preset-umi/src/commands/dev/dev.ts

修理之前群里有人反馈 public 文件夹第一次创建不生效的问题

fix(public): watch public create and delete event restart server

---

packages/bundler-esbuild/src/types.ts
packages/bundler-utils/src/https.ts
packages/bundler-webpack/src/config/javaScriptRules.ts
packages/core/src/config/config.ts
packages/core/src/service/plugin.ts
packages/lint/src/linter/base.ts
packages/plugin-docs/src/compiler.ts
packages/preset-umi/src/commands/lint.ts
packages/preset-umi/src/features/mock/getMockData.ts
packages/preset-umi/src/features/transform/transform.ts
packages/utils/src/register.ts
tsconfig.base.json

chore: error cause

---

packages/preset-umi/fixtures/icons/normal/@/alias.ts
packages/preset-umi/fixtures/icons/normal/alias-3.ts
packages/preset-umi/fixtures/icons/normal/foo.ts
packages/preset-umi/fixtures/icons/normal/index.ts
packages/preset-umi/fixtures/icons/normal/index.tsx
packages/preset-umi/fixtures/icons/normal/jsx.jsx
packages/preset-umi/package.json
packages/preset-umi/src/commands/setup.ts
packages/preset-umi/src/features/icons/buildForIconExtract.ts
packages/preset-umi/src/features/icons/esbuildAliasPlugin.ts
packages/preset-umi/src/features/icons/esbuildCollectIconPlugin.ts
packages/preset-umi/src/features/icons/esbuildExternalPlugin.ts
packages/preset-umi/src/features/icons/extractIcons.test.ts
packages/preset-umi/src/features/icons/extractIcons.ts
packages/preset-umi/src/features/icons/generateSVGR.ts
packages/preset-umi/src/features/icons/icons.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
packages/preset-umi/src/index.ts
pnpm-lock.yaml

feat: icons

---

packages/lint/package.json
pnpm-lock.yaml

chore(lint): update deps

---

packages/bundler-webpack/src/config/progressPlugin.ts

fix(bundler-webpack): compiling log lost in dev command

---

docs/blog/webpack-5-prod-cache.md
theme.config.ts

https://github.com/umijs/umi/issues/9810
https://github.com/umijs/umi/issues/10159#issuecomment-1373701452
新增一篇配置构建物理缓存的说明，部分人有这个需求。

docs: add webpack 5 cache blog

---

examples/ant-design-pro/package.json
examples/ant-design-pro/src/components/NoticeIcon/NoticeIcon.tsx
examples/ant-design-pro/src/pages/TableList/components/UpdateForm.tsx
examples/ant-design-pro/src/pages/TableList/index.tsx
examples/ant-design-pro/src/pages/list/basic-list/components/OperationModal.tsx
examples/ant-design-pro/src/pages/list/basic-list/index.tsx
examples/ant-design-pro/src/pages/list/table-list/components/CreateForm.tsx
examples/ant-design-pro/src/pages/list/table-list/components/UpdateForm.tsx
examples/ant-design-pro/src/pages/list/table-list/index.tsx
examples/ant-design-pro/src/pages/user/register/index.tsx
examples/antd-pro-create/src/components/NoticeIcon/NoticeIcon.tsx
examples/antd-pro-create/src/pages/TableList/components/UpdateForm.tsx
examples/antd-pro-create/src/pages/TableList/index.tsx
examples/create-umi-pro/package.json
examples/create-umi-pro/src/pages/Table/components/CreateForm.tsx
examples/create-umi-pro/src/pages/Table/components/UpdateForm.tsx
examples/create-umi-pro/src/pages/Table/index.tsx
packages/create-umi/templates/max/src/pages/Table/components/CreateForm.tsx
packages/create-umi/templates/max/src/pages/Table/components/UpdateForm.tsx
packages/create-umi/templates/max/src/pages/Table/index.tsx
pnpm-lock.yaml

antd 组件属性 `visible` 将在下一个大版本中移除，变更为 `open`
解决控制台 Warning

fix: 🐛 antd 组件属性 visible 更换为 open

---

packages/preset-umi/src/features/polyfill/polyfill.ts

在 qiankun 的时候，排掉这俩会崩溃的 polyfill 。
更详细的问题描述我发到这篇文章了：https://sakina.blog.csdn.net/article/details/128703220

fix(qiankun): not polyfill esnext.math.constant

---

packages/plugin-docs/client/theme-doc/NavBar.tsx
packages/plugin-docs/client/theme-doc/context.ts
theme.config.ts

close #10216 and #10325
不要在 nav 导航上使用重定向，否则会导致浏览器返回按钮无法返回上一级。

docs: not use navigate redirect

---

packages/plugins/src/access.ts

1. useAccess 返回值类型添加
2. 导出类型 AccessInstance

feat(plugin-access): plugin-access 类型定义添加

---

docs/docs/guides/mpa.md

mpa 文档有多误，修正他们。
resolve #10351

docs: improve mpa

---

packages/preset-umi/src/features/appData/appData.ts
packages/preset-umi/src/features/icons/icons.ts
packages/preset-umi/src/features/mpa/mpa.ts
packages/preset-umi/src/features/polyfill/polyfill.ts
packages/preset-umi/src/registerMethods.ts

feat(preset-umi): improve umi launch time

---

packages/preset-umi/src/features/mpa/extractExports.ts

根据 https://github.com/umijs/umi/issues/10353#issuecomment-1409913530 反馈，mpa 有 win path 的问题。

fix(mpa): win path

---

did-you-know/package.json
did-you-know/src/plugin.ts
scripts/.internal/constants.ts
scripts/release.ts

补充常见问题的 did you know ，去掉 dva 的提示，因为不维护、社区也不推荐用 sagas 了。

docs: update did you know

---

.github/workflows/e2e-basic.yml
docs/docs/max/mf.md
examples/mf-host/.umirc.ts
examples/mf-remote/.umirc.ts
packages/plugins/src/mf.test.ts
packages/plugins/src/mf.ts
scripts/cypress.ts

feature(plugin): plugin-mf auto work with mfsu

---

packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
packages/preset-umi/templates/history.tpl
packages/preset-umi/templates/historyIntelli.tpl
packages/preset-umi/templates/route.tpl

纯类型体操完成的 `history.push` / `history.replace` 类型提示（支持提示或者输入任意值）。

feat(history): history pathname intelli

---

docs/docs/api/commands.md
packages/plugin-run/src/index.ts
packages/preset-umi/src/commands/verify-commit.ts

docs: add description for run

---

packages/preset-umi/src/features/apiRoute/apiRoute.ts

fix: middlewares winpath

---

docs/docs/api/config.md
packages/plugin-docs/client/theme-doc/components/Message.tsx
packages/preset-umi/src/features/monorepo/redirect.ts

这是 monorepo 中一种比较好的约定设计，可以解决多实例的问题，自由选择是否启用。

feat(monorepo): support redirect peer deps

---

docs/docs/api/config.md

我在看文档使用的时候按文档步骤来会使用失败看不到效果。
绿色是我操作的第一步，红色是第二步。结果就是看不到效果。原因现在搞懂了就很清楚。但这个说明不利于新人学习。

docs: perf description

---

packages/umi/plugin-utils.d.ts

fix(umi/plugin-utils): export type

---

packages/preset-umi/src/features/appData/appData.ts

feat(preset-umi): 提升 appData 插件注册时间

---

.github/workflows/pr-checker.yml

检查ci是否正确执行，发现出错了~检查了下代码，发现缩进有问题。

fix: ci style

---

packages/bundler-webpack/src/build.ts
packages/preset-umi/src/types.ts

`@umijs/bunlder-webpack` 的 build 方法支持 watch 模式，将用于 father 的 umd 打包支持 watch

feat(bundler-webpack): build support watch mode

---

packages/plugins/src/request.ts

fix: export type RequestOptions and Request

---

packages/plugins/libs/qiankun/master/MicroApp.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/10536)

feat(qiankun): 支持在应用配置中配置微应用 settings

---

contributors.json

chore: add yuaanlin

---

packages/preset-umi/fixtures/prepare-build/with-alias/index.ts
packages/preset-umi/fixtures/prepare-build/with-alias/lib/home-made.ts
packages/preset-umi/src/features/prepare/build.test.ts
packages/preset-umi/src/features/prepare/build.ts
packages/preset-umi/src/features/prepare/esbuildPlugins/esbuildExternalPlugin.ts

fix case 
```ts
alias: {
'some/pkg/utils/request': 'umi-request'
}
```

fix(preset-umi): fix prebuild esbuild alias resolve error

---

packages/bundler-webpack/src/build.ts

close #10572
close #10579
cc @hanzebang 
这为 esbuild 压缩失败时提供了友好的提示解决方案

chore: esbuild minify error tips

---

packages/preset-umi/src/utils/routeExportExtractor.ts

fix(routeProps): async await

---

scripts/cypress.ts

chore(ci): ✅ try ci with chrome

---

examples/antd-pro-create/package.json
examples/boilerplate-vue/package.json
examples/create-umi-pro/package.json
examples/create-umi-simple/package.json
examples/max/package.json
examples/mf-host/package.json
examples/mf-remote/package.json
examples/mfsu-e2e/package.json
examples/mfsu-independent-e2e/package.json
examples/qiankun-slave/package.json
examples/vite-e2e/package.json
pnpm-lock.yaml

close https://github.com/umijs/umi/issues/10589

chore: ⬆️ cypress 12

---

packages/preset-umi/src/index.ts

解决顺序问题，ssr 要等 routeProps 文件准备好了再打包。
cc @PeachScript

fix(ssr): in the last run

---

docs/docs/max/micro-frontend.md

本 PR 更新了之前撰写的 Umi Max 微前端文档，修复其中的过时内容。
- 基于项目实践，更新组件引入子应用章节的文档。
- 删除设置 `<MicroApp />` 子应用路由前缀的过时内容，使用 `base` 属性实现。
- 其他文本、措辞优化。

docs(micro-frontend): update docs & fix oudated content

---

packages/plugins/src/request.ts

https://github.com/umijs/umi/pull/10627
https://github.com/umijs/umi/pull/10660

chore: type for block and string

---

packages/preset-umi/src/features/appData/appData.ts

fix: loading file win path

---

examples/ssr-webpack/.umirc.ts
examples/ssr-webpack/package.json
examples/ssr-webpack/src/pages/bar.css
examples/ssr-webpack/src/pages/foo.less
examples/ssr-webpack/src/pages/index.tsx
packages/preset-umi/src/features/helmet/helmet.ts
packages/preset-umi/templates/server.tpl
packages/renderer-react/src/server.tsx
packages/server/src/ssr.ts
pnpm-lock.yaml

修复 ssr 下 helmet context 冲突导致 helmet 标签不生效的问题
ref: #10633

fix(helmet): helmet context conflicts in ssr

---

packages/core/src/route/routesConvention.test.ts
packages/core/src/route/routesConvention.ts

fix: 修复约定式路由在文件夹名以 index 结束时生成错误的问题

---

examples/mf-host/.umirc.prod.ts

for issue  https://github.com/umijs/umi/issues/10704

chore(example): 🐛  fix eager consumer error in mf

---

docs/docs/max/micro-frontend.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/10734)

docs(qiankun): 新增 FAQ

---

package.json
ui/hooks/useAppData.ts
ui/pages/plugins/components/PluginList.tsx
ui/pages/plugins/index.tsx
ui/utils/getPluginRegisterTime.ts

Feature/lyy umi UI plugins

---

packages/preset-umi/src/commands/generators/page.test.ts
packages/preset-umi/src/commands/generators/page.ts
packages/preset-umi/src/commands/generators/utils.ts
packages/preset-umi/templates/generate/page/index.styled-components.tsx.tpl

chore: optimize SC templates

---

packages/bundler-webpack/package.json
packages/mfsu/package.json
pnpm-lock.yaml

升级来解决一个任意代码执行漏洞。
CVE：https://github.com/advisories/GHSA-hc6q-2mpp-qw7j

dep: upgrade webpack

---

packages/server/src/server.ts

feat(server): add DEV_SERVER_REDIRECT allow redirect to be disabled

---

docs/docs/api/config.md
docs/docs/introduce/faq.md

docs: update

---

packages/create-umi/templates/app/package.json.tpl
packages/create-umi/templates/max/package.json.tpl
packages/create-umi/templates/plugin/package.json.tpl
packages/create-umi/templates/vue-app/package.json.tpl
packages/preset-umi/src/features/appData/appData.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts

feat: upgrade template ts to v5

---

packages/bundler-vite/package.json
packages/preset-umi/package.json
pnpm-lock.yaml

https://github.com/vitejs/vite/issues/9986#issuecomment-1469192805 修复 max  vite 启动 问题  Close #10433

feat: vite deps upgrade to 4.2

---

scripts/release.ts

build: correct release script

---

package.json
pnpm-lock.yaml
scripts/changelog.ts
scripts/release.ts
scripts/utils/openai.ts

ci: update scripts for tsc

---

docs/docs/guides/mpa.md
packages/preset-umi/src/features/mpa/mpa.ts

支持通过`env. MPA_FILTER ` 指定需要启动项目

feat(mpa): support filter project

---

docs/docs/max/i18n.md
examples/max/app.ts
examples/max/locales/en-US.js
examples/max/locales/zh-CN.js
examples/max/pages/index.tsx
packages/plugins/libs/locale/localeExports.tpl
packages/plugins/src/locale.ts

feat: support react-intl config

---

packages/bundler-webpack/src/utils/depMatch.ts
packages/bundler-webpack/src/utils/pkgUpContainsName.ts

eg. https://www.unpkg.com/browse/jose@4.13.1/dist/browser/package.json  
需要找到主包的 pkg.json

fix: 🐛 匹配时找到有版本信息 pkg.json

---

packages/preset-umi/src/features/esbuildHelperChecker/esbuildHelperChecker.test.ts
packages/preset-umi/src/features/esbuildHelperChecker/esbuildHelperChecker.ts
packages/preset-umi/src/index.ts

说明，
1、jsMinifier 为 esbuild 且未配置 esbuildMinifyIIFE 时会自动执行
2、也可以手动执行命令校验，比如 `umi esbuildHelperChecker ./dist`

feat: esbuild helper conflict checker

---

docs/docs/api/runtime-config.md
packages/preset-umi/templates/defineApp.tpl
packages/renderer-react/src/browser.tsx

给 `onRouteChange` 钩子增加 `isFirst` 参数，用于判断是不是页面首次加载，计算首屏或白屏时间

feat(renderer-react): pass isFirst for onRouteChange hook

---

packages/preset-umi/package.json
pnpm-lock.yaml

es-module-parser@0.0.7
1. 优化了异步并发控制
2. 增加了一个同步实现

chore: ⬆️ es-module-parser

---

examples/mpa/.umirc.ts
packages/preset-umi/src/features/mpa/mpa.ts

Close #10872
支持读取 `api.userConfig.mountElementId`

feat(mpa): support global mountElementId

---

packages/plugins/libs/qiankun/master/MicroApp.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/10877)

fix(qiankun): 兼容微应用 updating 阶段触发了 unmount 的场景

---

packages/create-umi/src/index.ts

pnpm v8 不再需要 `strict-peer-dependencies` 选项了。

chore(create-umi): pnpm 8 not need strict peer deps config

---

packages/create-umi/templates/app/package.json.tpl
packages/create-umi/templates/max/.umirc.ts.tpl
packages/create-umi/templates/max/package.json.tpl
packages/create-umi/templates/plugin/package.json.tpl
packages/create-umi/templates/vue-app/package.json.tpl

See #10913 ，这是解决 pnpm v8 默认版本策略带来问题的一环。

fix: upgrade template deps version

---

packages/plugins/libs/qiankun/master/MicroApp.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/10972)

fix(qiankun): update deps 需要做 deep compare 避免频繁更新

---

docs/docs/guides/generator.md
packages/preset-umi/src/commands/generators/component.test.ts
packages/preset-umi/src/commands/generators/component.ts

feat(preset-umi): support add custom file in micro generator

---

packages/mfsu/src/loader/esbuild.ts

feat(mfsu): esbuild loader support mjs

---

examples/boilerplate-vue/.umirc.ts
examples/boilerplate-vue/cypress.config.ts
examples/boilerplate-vue/cypress/e2e/jsx.cy.ts
examples/boilerplate-vue/layouts/index.vue
examples/boilerplate-vue/pages/demo-jsx/index.tsx
packages/babel-preset-umi/src/index.ts
packages/preset-vue/package.json
packages/preset-vue/src/features/default.ts
packages/preset-vue/src/features/vite/vite.ts
pnpm-lock.yaml

支持 vue jsx (在 father 支持 vue 打包 需要支持下 随带在 umi 支持 father 直接复用)

feat(preset-vue): support vue jsx

---

packages/plugins/libs/qiankun/master/MicroApp.tsx

unmount 操作是异步的，通过给微应用新增一个全局的标记，用于过滤 unmount 开始后可能触发的更新操作
* ref https://github.com/umijs/plugins/pull/936
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/11008)

fix(qiankun): unmount 开始后不再触发 update

---

ui/.umirc.ts
ui/components/plugin/PluginList.tsx
ui/contants/index.ts
ui/pages/config.tsx
ui/pages/index.tsx
ui/utils/getOverviewNumber.ts

feat: umi ui overview

---

packages/bundler-webpack/package.json
pnpm-lock.yaml

关联 https://github.com/umijs/umi/issues/10935

feat(bundler-webpack): fork-ts-checker-webpack-plugin deps upgrade

---

packages/preset-umi/src/features/ui/ui.ts

fix: 执行语句性能优化

---

ui/app.tsx
ui/components/imports/ViewChart.tsx
ui/components/imports/ViewList.tsx
ui/components/plugin/PluginList.tsx
ui/components/routes/routeChart.tsx
ui/components/routes/routeDrawer.tsx
ui/models/global.ts
ui/pages/index.tsx
ui/utils/getOverviewNumber.ts

1. 删除 doctor ，后续以 bigfish 插件引入
2. 删除 routes 展开动画和蒙层
3. 修复 dark 模式下部分字体颜色无法看清
4. 修改 imports chart 中颜色分类，和箭头方向

feat(ui): ui 部分页面优化

---

packages/plugins/templates/locale/localeExports.tpl

close: #11029
没有找到好的测试方法，感觉我做的好像太简单了。
请问 TPL 文件一般是怎么测试结果呢？ @fz6m

fix(plugin): change locale type

---

packages/server/src/routes.ts
packages/server/src/types.ts

chore(server): narrow return type

---

packages/bundler-webpack/src/schema.ts

feat(bundler-webpack): devtool type of restoration

---

examples/bundler-webpack-demo/package.json
packages/babel-preset-umi/package.json
packages/plugins/package.json
pnpm-lock.yaml

上次聊到的 sc 依赖问题已经由 peach 老师修复了👍🏻 （ https://github.com/styled-components/styled-components/pull/3995 ）
升级最新版本解决这个致命问题。
cc @PeachScript

dep: upgrade SC

---

packages/bundler-webpack/src/build.ts
packages/bundler-webpack/src/dev.ts

执行 father build 的时候 public 目录下的文件会被复制到每一个 umd 产物文件夹中

feat: father umd copy public

---

docs/docs/api/plugin-api.md

fix ConfigChangeType spelling mistake

docs: fix ConfigChangeType spelling mistake

---

libs/valtio/package.json
pnpm-lock.yaml

fix: valtio types

---

docs/docs/api/config.md

根据 #11138 反馈，文档有些描述的不准确和出入，修正它。

docs: update favicon

---

examples/plugin-antd-e2e/.umirc.ts
examples/plugin-antd-e2e/cypress/e2e/smoke.cy.ts
examples/plugin-antd-e2e/package.json
examples/plugin-antd-e2e/src/pages/index.tsx
packages/plugins/templates/antd/runtime.ts.tpl
pnpm-lock.yaml

feat(plugins): auto pass antd theme to ConfigProvider.config

---

docs/docs/max/antd.md
examples/plugin-antd-e2e/.umirc.ts
examples/plugin-antd-e2e/cypress/e2e/smoke.cy.ts
examples/plugin-antd-e2e/src/pages/index.less
examples/plugin-antd-e2e/src/pages/index.tsx
packages/plugins/package.json
packages/plugins/src/antd.ts
packages/plugins/templates/antd/runtime.ts.tpl
pnpm-lock.yaml

当检测到 targets 包含 IE 或者配置 legacy 时，自动注入 StyleProvider 对样式进行降级。

feat(plugins): auto inject antd StyleProvider for legacy project

---

packages/preset-umi/src/features/hmrGuardian/babelPlugin.test.ts
packages/preset-umi/src/features/hmrGuardian/babelPlugin.ts
packages/preset-umi/src/features/hmrGuardian/hmrGuardian.ts
packages/preset-umi/src/index.ts

一周一问题：解HMR 失效问题。
1. 使用 react.production 提示会破坏 hmr
2. 沿用 Umi 中的 修改 匿名的 default 导出为具名。
3. 默认关闭，bigfish 先跑，然后社区再开。

feat: ✨ hmr guardian

---

packages/preset-umi/src/commands/generators/prettier.ts

fix: host.fileExists is not a function

---

packages/plugins/src/layout.ts

Revert "feat(layout): use css instead of less"

---

docs/docs/guides/plugins.md

ref: https://github.com/umijs/dumi/issues/1763#issuecomment-1623452042

docs: correct code example for plugin

---

packages/plugins/src/tailwindcss.ts

fix(plugins/tailwindcss): start build after tailwindcss generate completed

---

docs/docs/api/runtime-config.md

doc: fix  umi doc中 useRoutes 链接不存在问题

---

packages/bundler-vite/src/plugins/deleteOutputFiles.test.ts
packages/bundler-vite/src/plugins/deleteOutputFiles.ts

修复答疑群反馈的 vite 模式 windows 设备下 构建错误

fix(bundler-vite): build error on windows

---

README.md

Noticed a typo, pushing a quick fix

docs: Fix typo on README.md

---

docs/docs/max/mf.md

一个小 typo。
如果太小不方便合的话可以等等，正在研究 MF 这块，万一发现有别的 typo 一起合。

docs: correct typo in mf

---

docs/docs/api/config.md
packages/preset-umi/src/features/configPlugins/configPlugins.ts
packages/preset-umi/src/features/configPlugins/schema.ts
packages/preset-umi/src/features/tmpFiles/routes.ts

feat: config routeLoader

---

.github/workflows/pr-checker.yml

- fix https://github.com/umijs/umi/actions/runs/5874118256
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/11525)

fix: pr-checker permission

---

packages/create-umi/src/template.ts

fix: https://github.com/umijs/umi/issues/11556

fix(create-umi): remove unexpected query for fetch npm

---

docs/.dumirc.ts

docs: fix previous and next navigation for guide

---

docs/docs/docs/guides/typescript.md

docs: improve spelling for typescript word

---

packages/plugins/src/layout.ts

fix(plugins): antd type may lost from layout plugin

---

packages/renderer-react/src/browser.tsx

need to unlisten listener onRouteChange when component unmount

refactor(renderer-react): unlisten history after router unmount

---

packages/bundler-webpack/compiled/webpack/lazy-compilation-node.js
packages/bundler-webpack/compiled/webpack/lazy-compilation-web.js
packages/bundler-webpack/package.json
pnpm-lock.yaml

dep: webpack upgrade to 5.88.2

---

packages/preset-umi/src/features/okam/okam.ts
packages/preset-umi/src/index.ts
packages/umi/src/cli/cli.ts
packages/umi/src/cli/forkedDev.ts
packages/utils/src/index.ts
packages/utils/src/node.ts

Close https://github.com/umijs/mako/issues/300

feat(okam): node 16 is needed when mako is enabled

---

docs/docs/docs/introduce/contributing.md

docs: fix unclear expression

---

docs/docs/docs/api/config.md

docs: correct type

---

packages/bundler-webpack/src/config/cssRules.ts

fix(bundler-webpack): custom css modules ident function should only for ssr with bundler esbuild

---

docs/docs/docs/api/config.md

I copied and pasted the configs and found errors. Trying to fix it.

docs(fix): change ; to , to avoid errors

---

examples/max/package.json
examples/max/pages/dva.tsx
pnpm-lock.yaml

chore: update dva examples

---

packages/plugins/src/dva.ts

dva missing type such as useDispatch、useSelector

fix: import dva use absolute path

---

examples/with-styled-components/global.d.ts
examples/with-styled-components/package.json
examples/with-styled-components/pages/css.tsx
examples/with-styled-components/tsconfig.json
packages/plugins/package.json
packages/plugins/src/styled-components.ts
pnpm-lock.yaml

据 #11888 反馈，SC 的 css prop 方法没法用，修复它。

fix(sc): css props

---

did-you-know/package.json

fix: fix a typo

---

packages/plugins/src/antd.ts

chore(antd-plguin): supplementary type constraints

---

docs/docs/docs/max/layout-menu.md

docs: delete unuseful config

---

docs/docs/docs/api/plugin-api.md

docs: supplyment plugin api documentation

---

packages/plugins/src/layout.ts

去长沙教学发现了两个比较令人迷惑的点
- fix alway show avatar error
- fix alway sometime show plugin-layout error

fix(plugin-layout): fix alway sometime show plugin-layout error

---

packages/preset-umi/src/commands/build.ts
packages/preset-umi/src/commands/dev/dev.ts
packages/preset-umi/src/commands/mfsu/util.ts

feat: use appData umiName in command line info

---

packages/preset-umi/src/commands/generators/tailwindcss.ts

Reverts umijs/umi#12031
原因详见：https://github.com/umijs/umi/pull/12031#discussion_r1443079987

revert: "fix .less file using tailwind @apply not working"

---

packages/preset-umi/src/commands/build.ts
packages/preset-umi/src/commands/dev/dev.ts
packages/preset-umi/src/commands/mfsu/util.ts

Revert "feat: use appData umiName in command line info"

---

packages/bundler-vite/package.json
packages/preset-umi/package.json
packages/preset-umi/src/features/esbuildHelperChecker/esbuildHelperChecker.ts
pnpm-lock.yaml

升级 vite 到 4.5.2 版本
相关 [issue](https://github.com/umijs/umi/issues/12164)

feat: vite deps upgrade to 4.5.2

---

packages/create-umi/src/index.ts

pnpm 从 `8.7.0` 取消了默认安装最低版本的限制，和 npm 、yarn 等保持一致还是安装最新的版本，所以对于新版本 pnpm 不再需要默认升级依赖的过程。
注：pnpm v9 可能快出了。

chore: update deps for lower pnpm 8 versions only

---

examples/antd-pro-create/package.json
pnpm-lock.yaml

升级 pro preset 消除多版本 umi 问题
umi@4.0.0-canary.20220628.2

chore: update pro preset for antd pro example

---

examples/ssr-demo/src/pages/index.tsx
packages/preset-umi/src/features/ssr/ssr.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
packages/renderer-react/src/appContext.ts
packages/renderer-react/src/browser.tsx
packages/renderer-react/src/html.tsx
packages/renderer-react/src/index.ts
packages/renderer-react/src/types.ts
packages/server/src/ssr.ts

1. serverLoader 的数据允许在 clientLoader 中通过 args.serverLoader 调用接口进行获取
2. clientLoader 也可以自己写一份数据请求
3. 两个 loader 的数据统一通过 useLoaderData 获取

feat: provide useLoaderData for fallback serverLoader

---

docs/docs/blog/legacy-browser.en-US.md
docs/docs/blog/legacy-browser.md

See :
- https://sansec.io/research/polyfill-supply-chain-attack
- https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet

docs: remove insecure urls

---

examples/ant-design-pro/config/config.ts
packages/preset-umi/assets/bundle-status.html
packages/preset-umi/src/features/devTool/devTool.ts

feat(preset-umi): devtool loading support mako

---

packages/plugins/src/utils/modelUtils.ts

Reverts umijs/umi#12535
Why revert? e2e is broken.

Revert "fix(@umijs/plugins): model files may be collected more than once in some cases"

---

docs/docs/docs/api/config.md
packages/preset-umi/src/features/mako/mako.ts

增加 mako 配置类型定义 
```
mako: {
plugins?: (Array<{
load?: (((...args: any[]) => unknown) | undefined);
generateEnd?: (((...args: any[]) => unknown) | undefined);
}> | undefined);
px2rem?: ({
root?: (number | undefined);
propBlackList?: (Array<string> | undefined);
propWhiteList?: (Array<string> | undefined);
selectorBlackList?: (Array<string> | undefined);
selectorWhiteList?: (Array<string> | undefined);
selectorDoubleList?: (Array<string> | undefined);
} | undefined);
experimental?: ({
webpackSyntaxValidate?: (Array<string> | undefined);
} | undefined);
flexBugs?: (boolean | undefined);
moduleIdStrategy?: (string | undefined);
optimization?: ({
skipModules?: (boolean | undefined);
} | undefined);
};
```
https://github.com/umijs/mako/issues/1389

feat: add mako types

---

packages/preset-umi/src/features/tmpFiles/tmpFiles.ts

fix: use relative path in tsconfig

---

packages/preset-umi/src/commands/dev/dev.ts

https://github.com/umijs/umi/issues/12560

feat: add mako ad

---

examples/ant-design-pro/src/app.tsx
examples/ant-design-pro/src/loading.tsx

通过这个文档
https://umijs.org/docs/guides/directory-structure#loadingtsxjsx
在 **ant-design-pro** 的示例上添加了一个全局loading功能，并移除了之前多余的代码。

chore(example): add global 'Loading' to **ant-design-pro**

---

packages/preset-umi/src/features/mako/mako.ts

feat(mako): support windows

---

packages/deps/package.json

https://github.com/pillarjs/path-to-regexp/pull/320

fix: use path-to-regexp@1.9.0 to fix redos

---

packages/preset-umi/src/features/clickToComponent/clickToComponent.ts

ref:
https://github.com/umijs/umi/issues/12763
https://github.com/ericclemmons/click-to-component/issues/93

fix: click-to-react-component should only be run in dev

---

examples/ssr-demo/.umirc.ts
examples/ssr-demo/src/pages/index.tsx
packages/preset-umi/src/features/ssr/ssr.ts
packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
packages/preset-umi/templates/server.tpl
packages/preset-umi/templates/umi.tpl
packages/renderer-react/src/browser.tsx
packages/renderer-react/src/routes.tsx
packages/renderer-react/src/server.tsx
packages/renderer-react/src/types.ts
packages/server/src/ssr.ts

feat: ssr mode add config useStream

---

packages/renderer-react/src/html.tsx

fix: delete script cross_origin for cors

---

docs/docs/docs/api/config.en-US.md
docs/docs/docs/api/config.md
packages/preset-umi/src/features/routePrefetch/routePrefetch.ts
packages/renderer-react/src/browser.tsx

Modifies.
1. enable routePrefetch on dev
2. doc: add routePrefetch config
3. doc: translate config.md
ref:
#12790

feat: enable routePrefetch on dev

---

packages/preset-umi/src/features/exportStatic/exportStatic.ts
packages/preset-umi/src/features/routePrefetch/routePrefetch.ts

1. use dynamic import replace of require for type: module in package.json
2. fix route-prefech ssr injectcode

fix: ssr for type module

---

packages/plugins/src/model.ts

fix(model): userConfig.model might be undefined

---

packages/preset-umi/src/commands/dev/plugins/ViteHtmlPlugin.ts

修复使用自定义 frameworkName 时，vite 模式下，dev 错误
Closes: #12866

fix: frameworkName when vite dev

---

docs/docs/docs/max/dva.en-US.md
docs/docs/docs/max/dva.md

Revert "fix: 更新dva文档中官网url地址"

---

packages/bundler-webpack/package.json
yarn.lock

Close https://github.com/umijs/umi/issues/12888
Close https://github.com/umijs/umi/issues/12885

dep: upgrade postcss to 7.0.36 to fix the security problem

---

packages/lint/src/config/stylelint/index.ts

Reverts umijs/umi#12891
ref:
https://github.com/postcss/postcss/pull/2000

Revert "chore: stylelint-value-no-vendor-prefix"

---

docs/docs/faq.md

Close https://github.com/umijs/dumi/issues/1986

fix: 更新 faq.md 中的文档链接

---

docs/scripts/generateLLms.ts

feat: 文档生成 llms-full.txt

---

packages/preset-umi/src/features/appData/appData.ts
packages/preset-umi/src/utils/serializeAppData.ts

fix: TypeError Converting circular structure to JSON with mako build

---

packages/preset-umi/src/commands/build.ts
packages/preset-umi/src/commands/dev/dev.ts
packages/preset-umi/src/features/bundler/bundler.ts
packages/preset-umi/src/index.ts
packages/preset-umi/src/registerMethods.ts
packages/preset-umi/src/types.ts

feat(preset-umi): add support for custom bundler in preset-umi
