umijs/umi

packages/umi-test/src/index.js
close https://github.com/sorrycc/roadhog/issues/563
=> passing through arg as jest testPathPattern

examples/func-test/.umirc.js, examples/func-test/plugin2.js, examples/with-dva-enable-plugin/src/pages/index/page.js, examples/with-dva-enable-plugin/src/pages/list/page.js, packages/af-webpack/src/getConfig.js, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/UserConfig.js, packages/umi-build-dev/src/constants.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/hd/index.js, packages/umi-build-dev/template/router.js.tpl, packages/umi-plugin-dva/src/index.js, packages/umi-plugin-yunfengdie/src/index.js, packages/umi/src/createHistory.js
=> Improve plugin system

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/constants.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/hash-history.js, packages/umi-build-dev/template/entry.js.tpl
=> feat: support hash history with opts hashHistory, Close #110

docs/using-antd-or-antd-mobile.md
=> doc: use user's antd or and-mobile in package.json

examples/with-dva/src/pages/list/models/a.js, examples/with-dva/src/pages/list/models/b.js, examples/with-dva/src/pages/list/page.js, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-plugin-dva/src/index.js
* dev 模式下全量载 model
* prod 时利用 dva/dynamic 按需载
=> feat(umi-plugin-dva): support dynamic load page models

packages/umi-build-dev/src/getWebpackConfig.js
=> fix(umi-build-dev): service-worker.js don't generated

packages/af-webpack/src/getConfig.js
=> fix: don't minify font values for CSS

packages/umi-build-dev/src/plugins/layout.js
=> fix: layout don't support ts, tsx and jsx affix

packages/af-webpack/src/readRc.js
=> feat(af-webpack): support use comment in eslintrc

packages/umi-plugin-dva/src/index.js
=> fix(umi-plugin-dva): problems with ts

packages/umi-build-dev/src/Service.js, packages/umi-plugin-yunfengdie/src/index.js
e.g.
* http://www.anijue.com/p/h/janowm0d/index.html
* http://www.anijue.com/p/h/janowm0d/list.html
* http://www.anijue.com/p/h/janowm0d/a/b.html
=> fix(umi-plugin-yunfengdie): css publicPath problem

examples/func-test/.umirc.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/output-path.js
=> feat(umi-build-dev): support config outputPath in .umirc.js

packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/getWebpackConfig.js
=> feat(umi-build-dev): support disable HTML generatation via HTML=none

packages/af-webpack/package.json, packages/babel-preset-umi/package.json, packages/eslint-config-umi/package.json, packages/umi-build-dev/package.json, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-plugin-dva/package.json, packages/umi-plugin-routes/package.json, packages/umi-plugin-routes/src/index.js, packages/umi-plugin-yunfengdie/package.json, packages/umi/package.json
=> feat: add umi-plugin-routes

packages/umi-build-dev/src/FilesGenerator.js
=> feat(umi-build-dev): watch _routes.json's change and regenerate router

examples/func-test/global.js, packages/umi-build-dev/src/getWebpackConfig.js
=> fix(umi-build-dev): react-dom/server can't resolve

packages/umi-build-dev/src/getRouteConfig.js
=> fix: winPath problem in nested routes

examples/func-test/.umirc.js, packages/af-webpack/src/build.js, packages/af-webpack/src/getConfig.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/getPaths.js, packages/umi-build-dev/src/getWebpackConfig.js, packages/umi-plugin-dll/README.md, packages/umi-plugin-dll/package.json, packages/umi-plugin-dll/src/buildDll.js, packages/umi-plugin-dll/src/index.js, packages/umi/src/babel.js, packages/umi/src/build.js, packages/umi/src/buildDevOpts.js, packages/umi/src/dev.js
=> umi-plugin-dll

examples/func-test/.umirc.js, examples/func-test/.umirc.mock.js, examples/func-test/mock/user.js, packages/umi-build-dev/src/plugins/mock/HttpMock.js
=> feat(umi-build-dev): load files in mock/ automatically if .umirc.mock.js don't exists

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/plugins/404/index.js, packages/umi-build-dev/src/plugins/404/index.test.js
=> fix(umi-build-dev): 404 page don't work in build

packages/umi-plugin-dll/package.json, packages/umi-plugin-dll/src/index.js
=> feat(umi-plugin-dll): enable cache and gzip for umi.dll.js

packages/af-webpack/src/getConfig.js
=> feat(af-webpack): use HashedModuleIdsPlugin

examples/func-test/.umirc.js, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/getConfig/configPlugins/disableDynamicImport.js, packages/umi-build-dev/src/plugins/global-css.js, packages/umi-plugin-dva/src/index.js
=> feat: disable code-splitting via disableDynamicImport config in .umirc.js

examples/func-test/.umirc.js, packages/umi-build-dev/src/plugins/fastclick.js
=> feat(umi-build-dev): support disable fastclick via opts

packages/umi-build-dev/src/plugins/global-css.js
=> fix(umi-build-dev): global css priority

packages/af-webpack/src/getConfig.js, packages/af-webpack/test/build.test.js, packages/umi-build-dev/src/FilesGenerator.test.js, packages/umi-build-dev/src/getRouteConfig.js, packages/umi-build-dev/src/getRouteConfig.test.js
=> fix(umi-build-dev): variable path should be placed later

packages/umi-plugin-dva/src/index.js
=> fix(umi-plugin-dva): dva-immer winpath

packages/af-webpack/src/choosePort.js
=> feat(af-webpack): support disable detect-port via DETECT_PORT=none

packages/umi-plugin-dva/src/index.js, packages/umi/package.json
Close #323 
比如要配 autoFreeze，可以在 src/global.js 里，
```js
import { setAutoFreeze } from 'immer';
setAutoFreeze(false);
```
=> feat(umi-plugin-dva): expose immer when { immer: true }

packages/umi-build-dev/template/entry.js.tpl
=> fix(umi-build-dev): remove extra image request when route changes

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/createRouteMiddleware.js
(dirty fix, should be refact later)
introduced by #372
=> fix(umi-build-dev): Compiling... problem when request /index.html

packages/af-webpack/src/dev.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/UserConfig.js, packages/umi-build-dev/src/middlewares/createRouteMiddleware.js, packages/umi-build-dev/src/middlewares/createUmiDevMiddleware.js, packages/umi-build-dev/src/plugins/404/NotFound.js, packages/umi-build-dev/src/plugins/404/index.js, packages/umi-build-dev/src/plugins/mock/HttpMock.js, packages/umi-build-dev/src/plugins/mock/index.js, packages/umi-build-dev/src/routes/routesToJSON.js, packages/umi-build-dev/src/routes/routesToJSON.test.js, packages/umi-build-dev/src/routes/stripJSONQuote.js, packages/umi-build-dev/src/routes/stripJSONQuote.test.js, packages/umi-build-dev/src/utils/guessJSFileFromPath.js, packages/umi-build-dev/src/utils/guessJSFileFromPath.test.js, packages/umi-plugin-dll/src/index.js, packages/umi-plugin-routes/src/index.js, scripts/build.js
=> refact: middlewares and 404

packages/umi-plugin-dva/package.json, packages/umi-plugin-dva/src/index.js
=> fix(umi-plugin-dva): winPath problem

packages/umi-build-dev/src/html/HtmlGenerator.js, packages/umi-build-dev/src/html/getHTMLContent.js
=> fix(umi-build-dev): /index.html generate failed when exportStatic is set

packages/umi-build-dev/src/getWebpackConfig.js, packages/umi-build-dev/src/routes/getPageCountFromRoutes.js, packages/umi-build-dev/src/routes/getPageCountFromRoutes.test.js, packages/umi-build-dev/src/routes/routesToJSON.js
=> fix(umi-build-dev): page count incorrent if config routes with _routes.json

packages/umi-plugin-routes/src/index.js
=> fix: umi-plugin-routes (exclude) error under Windows

.gitignore, packages/umi-plugin-dva/src/index.js
=> Repair routing redirection without components

packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/getConfig/configPlugins/disableHash.js, packages/umi-build-dev/src/getWebpackConfig.js, packages/umi/src/build.js
Close #386
Config in `.umirc.js`,
```js
disableHash: true,
};
```
=> feat: support disable hash

packages/umi-build-dev/src/routes/routesToJSON.js, packages/umi-build-dev/src/routes/routesToJSON.test.js
Close https://github.com/umijs/umi/pull/537
=> disableDynamicImport spelling mistakes

packages/af-webpack/src/getConfig.js
=> fix(af-webpack): exports undefined problem if es5ImcompatibleVersions is set

packages/umi-build-dev/src/getWebpackConfig.js, packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js, packages/umi-build-dev/src/routes/getRouteConfigFromConfig.test.js, packages/umi/src/renderRoutes.js
props.params = props.match.params
=> feat: compatible with bigfish's routes via BIGFISH_COMPAT

packages/umi-build-dev/src/routes/getRouteConfigFromDir.js, packages/umi-build-dev/src/routes/getRouteConfigFromDir.test.js
=> fix(umi-build-dev): route order problem if have index/_layout.js

packages/umi-plugin-dva/package.json
=> feat(umi-plugin-dva): upgrade dva-immer to 0.2.0

docs/guide/router.md
Add authRoute example for dynamicRoute
=> docs: enhance explaination for authroute

README.md, docs/.vuepress/override.styl, docs/README.md
=> Improve docs

packages/umi-plugin-dva/src/index.js
=> fix(umi-plugin-dva): opts.loading don't work with umi-plugin-dva

packages/af-webpack/src/getConfig.js
=> copy ignore DS_Store

packages/af-webpack/src/getConfig.js
=> fix: eslint resolve problem

packages/umi-build-dev/src/html/getHTMLContent.js
@sorrycc 这个的单测不太好写，感觉后面 umi@2.0 要考虑下插件功能测试这块。
=> feat: add modifyDefaultTemplate for plugin

packages/umi-build-dev/src/Service.js
similar as: https://github.com/umijs/umi/commit/8df074e94a86784eb1c7036df1d53cdf171196a1#diff-9ce4757cb403ccd024a0d71af3a4a275
=> fix: init config dont updated when build

docs/guide/app-structure.md, docs/guide/faq.md
1.补充复杂应用的目录结构，（嵌套布局）
2.FAQ 增加使用图片和增加动态修改标题的注意事项
=> Supplement docs

docs/guide/router.md
=> update route config doc

docs/.vuepress/config.js, docs/plugin/README.md, docs/plugin/develop.md
=> doc: init umi plugin doc for umi@2.0

packages/babel-preset-umi/src/index.js
Close #736
后续通过 umi 插件加入这些优化类的 babel 插件。
=> remove babel optimize plugins since it will cause unexpected problems

packages/af-webpack/src/dev.js, packages/af-webpack/src/prepareUrls.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/base.js, packages/umi-build-dev/src/plugins/commands/dev/index.js, packages/umi/test/base/pages/list.js
=> feat: open urls with config.base if specified

packages/umi/src/scripts/dev.js
=> fix: pass exit code for umi dev

packages/umi-plugin-react/README.md, packages/umi-plugin-react/package.json, packages/umi-plugin-react/src/index.js, packages/umi-plugin-react/test/normal/.umirc.js, packages/umi-plugin-react/test/normal/pages/a.js, packages/umi-plugin-routes/README.md, packages/umi-plugin-routes/package.json, packages/umi-plugin-routes/src/exclude.js, packages/umi-plugin-routes/src/index.js, packages/umi/src/scripts/dev.js
=> Migrate umi-plugin-routes to umi@2

LICENSE, README.md, packages/af-webpack/package.json, packages/babel-preset-umi/package.json, packages/eslint-config-umi/package.json, packages/umi-build-dev/package.json, packages/umi-plugin-dll/package.json, packages/umi-plugin-dva/package.json, packages/umi-plugin-locale/package.json, packages/umi-plugin-polyfill/package.json, packages/umi-plugin-react/package.json, packages/umi-plugin-routes/package.json, packages/umi-test/package.json, packages/umi-utils/package.json, packages/umi/package.json
=> add MIT LICENSE

packages/umi-build-dev/src/plugins/404/NotFound.js, packages/umi-build-dev/src/plugins/404/NotFound.less, packages/umi-build-dev/src/plugins/404/index.js, packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js
=> Improve dev 404 page

packages/umi-utils/src/compatDirname.js
=> feat(umi-utils): find cwd if cwd !== process.cwd(), it's useful when specified APP_ROOT

packages/af-webpack/src/build.js, packages/umi-build-dev/src/plugins/commands/build/index.js, packages/umi-plugin-dll/src/buildDll.js
The PR is to get `stats` when build is fail.
=> Feat: Add stats param for onFail function in build command

packages/umi/package.json
=> fix: add missing cli.js when npm publish (#812)

packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
ref: https://github.com/umijs/umi/pull/819
=> fix(umi-build-dev): mock don't work (again)

docs/guide/router.md
=> fix: correct description in global layout guide

scripts/startDevServers.js, scripts/test.js
=> Fix coverage test did not kill child process (Issue #820)

packages/af-webpack/src/dev.js
`onCompileDone` should be invoked before `isFirstCompile = false`.
=> fix: isFirstCompile should be true when first compile for dev

packages/af-webpack/package.json, packages/af-webpack/src/getConfig/css.js, packages/umi-build-dev/src/html/HTMLGenerator.js, packages/umi-build-dev/src/html/HTMLGenerator.test.js
=> feat: extract css in umi dev, hot reload with css-hot-loader

packages/umi-build-dev/src/registerBabel.js
=> fix: registerBabel failed in windows

packages/umi-plugin-dll/src/buildDll.js
=> fix(umi-plugin-dll): umi and umi plugins in dependencies

packages/umi-build-dev/src/routes/routesToJSON.js, packages/umi-plugin-react/src/plugins/dynamicImport.js
=> fix: dynamicImport level wrong and support dynamicImport.level for umi-plugin-react

packages/umi-build-dev/package.json, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/atoolMonitor.js, packages/umi/package.json, packages/umi/src/cli.js
- Remove previous code for atool-monitor.
- Add a new plugin named `atoolMonitor` for `umi-build-dev` to report more data.
=> Feat: Upgrade atool monitor to report more data

packages/af-webpack/src/getConfig/index.js
Support config `"jsx": "preserve",` in tsconfig.json
=> fix: transform ts files with babel

packages/umi-test/src/setupTests.js
=> Change the way to retrieve 'window' and 'document' from jsdom

packages/af-webpack/src/dev.js
=> feat: support serverConfig in af-webpack/lib/dev

packages/af-webpack/src/getConfig/index.js
=> fix: yarn global install resolve problem

packages/af-webpack/src/getConfig/index.js
=> fix: mjs should work correctly (#881)

packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/atoolMonitor.js, packages/umi/src/cli.js
=> Fix: Complete the feature of upgrading atool-monitor

packages/umi-build-dev/src/plugins/commands/test.js, packages/umi-test/src/index.js
Close #536 
Close #527 
Close #428
=> feat: improve umi test, support extra args, and specify specs

packages/umi-plugin-polyfills/src/index.js
=> fix(umi-plugin-polyfills): options is undefined

docs/plugin/develop.md, docs/plugin/umi-plugin-react.md, examples/func-test/.umirc.js, examples/func-test/src/pages/test.js, packages/umi-build-dev/src/html/HTMLGenerator.js, packages/umi-build-dev/src/html/HTMLGenerator.test.js, packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js, packages/umi-plugin-react/package.json, packages/umi-plugin-react/src/index.js, packages/umi-plugin-react/src/plugins/title/TitleWrapper.js, packages/umi-plugin-react/src/plugins/title/index.js, packages/umi-plugin-react/src/plugins/title/title.test.js, packages/umi-plugin-react/test/normal.e2e.js, packages/umi-plugin-react/test/normal/.umirc.js, packages/umi-plugin-react/test/normal/pages/a.js, scripts/build.js
=> feat: add plugin title

packages/umi/src/scripts/realDev.js
=> fix: child process exit no need settimeout

docs/guide/getting-started.md, docs/guide/migration.md, packages/umi-plugin-react/src/plugins/library.js
=> fix: crash when set library to preact

packages/umi-build-dev/src/plugins/afwebpack-config.js
=> fix: extraBabelPlugins and extraBabelPresets duplicated

packages/umi-build-dev/src/FilesGenerator.js, packages/umi/src/renderRoutes.js
=> fix: unexpected rerender caused by route.Routes

packages/umi-build-dev/src/UserConfig.js, packages/umi-build-dev/src/registerBabel.js
=> feat: enhance config, support es6 syntax for config/ directory and watch it's change

packages/umi-build-dev/src/plugins/global-css.js
=> feat: move global.css to last

packages/umi-build-dev/src/plugins/global-css.js
=> fix: global.css don't work in windows

packages/af-webpack/src/getConfig/css.js
=> fix: cssnano don't compress url correctly

packages/af-webpack/src/getConfig/index.js
webpack-bundle-analyzer 支持导出 stats 分析文件
=> feat: bundle-analyzer supports generating stats file

packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/commands/build/index.js
=> fix: ANALYZE=1 umi build don't work and disable monitor

docs/guide/app-structure.md
=> doc: improve

packages/umi-plugin-polyfills/src/ie10.js, packages/umi-plugin-polyfills/src/ie11.js, packages/umi-plugin-polyfills/src/ie9.js
=> feat: add Object polyfills for ie

packages/umi-plugin-polyfills/package.json, packages/umi-plugin-polyfills/src/ie10.js, packages/umi-plugin-polyfills/src/ie9.js
=> fix: add setprototypeof polyfill for ie9 and ie10

docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/template/entry.js.tpl, packages/umi-plugin-polyfills/src/index.js
=> feat: add polyfill before global.js, and add a new Plugin API api.addEntryImportAhead

packages/af-webpack/src/getConfig/FilterCSSConflictingWarning.js, packages/af-webpack/src/getConfig/index.js
Close ant-design/ant-design-pro#2152
=> feat: hide conflicting-order-css warnings

packages/umi-plugin-routes/src/index.js
=> fix(umi-plugin-routes): hot reload don't work

docs/api/README.md
文档刚好看到这里，似乎还没写完？
先把现有的补上，后续可按照中文版更新。
=> English translation of docs/api

docs/guide/env-variables.md, docs/zh/guide/env-variables.md
官方文档里面没有指出在使用TypeScript时候的配置，在这里补充一下
=> 添加对FORK_TS_CHECKER的说明

packages/umi-plugin-polyfills/src/ie10.js, packages/umi-plugin-polyfills/src/ie11.js, packages/umi-plugin-polyfills/src/ie9.js
ref: https://github.com/ant-design/ant-design-pro/issues/2312
=> fix(umi-plugin-polyfills): add array polyfills

docs/README.md, docs/api/README.md, docs/config/README.md, docs/guide/app-structure.md, docs/guide/config.md, docs/guide/create-umi-app.md, docs/guide/deploy.md, docs/guide/env-variables.md, docs/guide/examples.md, docs/guide/faq.md, docs/guide/html-template.md, docs/guide/load-on-demand.md, docs/guide/migration.md, docs/guide/navigate-between-pages.md, docs/guide/router.md, docs/plugin/develop.md
Just learning umi and I thought I'd help out with the translations. I used Google Translate to get started and then made some further edits. I'm hoping some more experienced umi users and/or Chinese-English speakers can build on this and help make umi more accessible to the world.
=> English Translations

packages/umi-build-dev/src/html/HTMLGenerator.js
=> fix: document tpl validate failed in some situations

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js, packages/umi-build-dev/src/plugins/mock/index.js
=> feat: improve mock error print

docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/package.json, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/afwebpack-config.js, packages/umi-build-dev/src/plugins/targets.js, packages/umi-build-dev/template/polyfills.js.tpl, packages/umi-plugin-dva/package.json, packages/umi-plugin-dva/src/index.js, scripts/build.js
=> feat: improve polyfills with config.targets

docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/package.json, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/UserConfig.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/commands/build/index.js, packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js, packages/umi-build-dev/src/plugins/commands/dev/index.js, packages/umi-build-dev/src/plugins/commands/generate/index.js, packages/umi-build-dev/src/plugins/commands/generate/page.js, packages/umi-build-dev/src/plugins/commands/getRouteManager.js, packages/umi-build-dev/src/plugins/commands/test.js, packages/umi-build-dev/src/utils/getCodeFrame.js, packages/umi-plugin-polyfills/package.json, packages/umi-plugin-polyfills/src/index.js, packages/umi-plugin-react/src/index.js, packages/umi-plugin-react/src/plugins/pwa/index.js, packages/umi/package.json, packages/umi/src/cli.js
没有 resolve 到插件。
插件没有导出函数。
插件 require 失败。
插件初始化失败。
=> feat: improve error print

packages/af-webpack/package.json, packages/umi-plugin-react/package.json
=> feat: lock webpack's version to 4.19.0

packages/umi-build-dev/src/plugins/commands/test.js
=> fix: umi test exit code

packages/af-webpack/src/getConfig/index.js
=> feat: improve tsl error formatter

packages/umi-build-dev/src/defaultConfigs/browsers.js, packages/umi-build-dev/src/plugins/afwebpack-config.js
=> feat: use config.targets for autoprefixer

packages/umi-test/src/transformers/tsTransformer.js
=> fix: ts test don't work

packages/umi-plugin-dll/src/buildDll.js
=> fix: dll publicPath

packages/af-webpack/src/clearConsole.js, packages/af-webpack/src/getConfig/index.js
=> fix: debug logs clear, default no clear

packages/umi-build-dev/src/FilesGenerator.js
=> support runtime plugin use src/app.js|jsx|ts|tsx

packages/umi-utils/src/chunkName.js, packages/umi-utils/src/endWithSlash.js, packages/umi-utils/src/index.js, packages/umi-utils/src/optsToArray.js
umi-utils add chunkName endWithSlash optsToArray
=> umi-utils add chunkName endWithSlash optsToArray

packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
=> use findjs from umi-utils

packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
fix JS_EXRNANMES is not defined
=> fix JS_EXRNANMES is not defined

docs/api/README.md, docs/zh/api/README.md, packages/umi-build-dev/src/plugins/afwebpack-config.js, packages/umi/src/prompt.js
e.g.
```js
import Prompt from 'umi/prompt';
export default () => {
return (
<>
<h1>Prompt</h1>
<Prompt
when={true}
message={(location) => {
return window.confirm(`confirm to leave to ${location.pathname}?`);
}}
/>
</>
);
}
```
=> feat: add umi/prompt

docs/guide/examples.md, docs/plugin/umi-plugin-react.md, docs/zh/guide/examples.md, docs/zh/plugin/umi-plugin-react.md
=> doc: add description about on-demand compilation of antd-pro

packages/af-webpack/src/dev.js
=> fix: 每次修改代码都会显示 devServer 信息

packages/umi-plugin-locale/src/index.js, packages/umi-plugin-locale/test/index.test.js
android 下大部分 intl 的特性也都不支持，需要添加上polyfill。
=> feat: add intl polyfill when targets has android

packages/umi-utils/src/compatDirname.js
close https://github.com/umijs/umi/issues/1387
=> fix: fix path search in yarn-workspace

packages/umi-build-dev/src/Service.js
=> feat: deprecate browserslist

docs/guide/with-dva.md
first of all, love the work with dva & umi, we are using dvajs with roadhog for our enterprise application at the moment but deciding to upgrade to umijs. I was reading through the documentation and found the typo ;)
=> fix typo models in with-dva.md

packages/af-webpack/src/getConfig/index.js
=> feat: support NO_PROGRESS ENV

packages/af-webpack/package.json, packages/af-webpack/yarn.lock, packages/umi-build-dev/src/plugins/commands/build/index.js
=> fix: upgrade webpackbar and fix build error print

packages/af-webpack/package.json
=> fix: upgrade webpack-dev-server, fix npm audit warning

docs/plugin/umi-plugin-react.md, docs/zh/plugin/umi-plugin-react.md
=> docs: enhance readability for newbies

packages/af-webpack/src/prepareUrls.js
fix private network ip like 30.* display:  
> - Network: undefined
cc @sorrycc @yutingzhao1991
=> fix: undefined network

docs/plugin/umi-plugin-react.md, docs/zh/plugin/umi-plugin-react.md
=> docs: add more information about defaultTitle

packages/af-webpack/package.json
=> fix: umi inspect

packages/umi-plugin-dva/src/index.js, packages/umi-plugin-react/test/with-dva.e2e.js, packages/umi-plugin-react/test/with-dva/pages/a/index.js, packages/umi-plugin-react/test/with-dva/pages/a/models/a.js
close https://github.com/umijs/umi/issues/1483
and open model dynamic when umi dev.
=> fix: use dva model file name as the namespace not work when open dynamic

packages/umi/index.d.ts, packages/umi/index.js
上次 pr 操作错误 ，取消 重新提交
typescript 自动引入文件（auto import) 更加友好
Issues #1493
=> ts 调用umi组件或方法的时候更加友好

docs/plugin/umi-plugin-react.md, docs/zh/plugin/umi-plugin-react.md
=> docs: add deprecated to polyfills option

.travis.yml, packages/af-webpack/src/getUserConfig/configs/devServer.js, packages/af-webpack/yarn.lock, packages/umi-build-dev/src/routes/patchRoutes.js, packages/umi-build-dev/src/routes/patchRoutes.test.js, packages/umi-build-dev/yarn.lock, packages/umi-plugin-locale/yarn.lock, packages/umi-plugin-react/yarn.lock, packages/umi-test/yarn.lock, packages/umi/yarn.lock
=> fix: 404 route with redirect

.travis.yml, package.json, packages/umi-build-dev/src/plugins/commands/ui/.env, packages/umi-build-dev/src/plugins/commands/ui/.umirc.js, packages/umi-build-dev/src/plugins/commands/ui/index.js, packages/umi-build-dev/src/plugins/commands/ui/plugins/config/client.js, packages/umi-build-dev/src/plugins/commands/ui/plugins/config/model.js, packages/umi-build-dev/src/plugins/commands/ui/plugins/config/server.js, packages/umi-build-dev/src/plugins/commands/ui/src/pages/index/model.js, packages/umi-build-dev/src/utils/setConfig.js, scripts/build.js
=> feat(umi ui): support config

packages/umi-build-dev/src/utils/writeNewRoute.js
cc @yutingzhao1991 
查找路由这块逻辑我调整了下，你试试。
=> feat: 区块路由查找兼容 exports.route = []

docs/zh/plugin/umi-plugin-react.md
https://github.com/umijs/umi/issues/1086
=> 添加 #1086 文档

packages/umi-plugin-react/src/index.js
=> fix: allow users to turn off code-splitting of dva model separately

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js, packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.js, packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.test.js, packages/umi-build-dev/src/plugins/commands/block/replaceContent.js, packages/umi-build-dev/src/plugins/commands/block/replaceContent.test.js, packages/umi-build-dev/yarn.lock
Close #1630
提供以下常量供替换，
* ROUTE_PATH
* BLOCK_NAME
* PAGE_NAME
* PAGE_NAME_UPPER_CAMEL_CASE
=> feat(block): replace constants in the content of blocks

packages/af-webpack/src/getConfig/index.js
=> use babelOpts on extraBabelIncludes

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.js, packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.test.js
=> add BLOCK_NAME_CAMEL_CASE

.prettierignore, packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/yarn.lock
1. `umi block` -> `umi block add`
1. add `umi block list`
=> feat: improve block commands

packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
=> fix(mock): res.body lost when method is delete

packages/umi-plugin-locale/index.d.ts, packages/umi-plugin-locale/package.json, packages/umi-plugin-locale/src/index.js, packages/umi-plugin-react/locale/index.d.ts, packages/umi-plugin-react/locale/index.js, packages/umi-plugin-react/package.json
=> feat: add umi-plugin-locale browser export

packages/umi-plugin-locale/index.d.ts
=> fix umi-plugin-locale index.d.ts

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/commands/build/index.js, packages/umi-build-dev/src/plugins/commands/dev/index.js
=> feat: add notify pkg

packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js
fix: https://github.com/umijs/umi/issues/1735
=> fix: cheerio will escape some charactors unexpectedly

packages/af-webpack/src/dev.js
=> feat: support disable system bell via SYSTEM_BELL=none

packages/umi-plugin-routes/src/index.js
=> fix: disable umi-plugin-routes if routes if configured

examples/func-test/.umirc.js, examples/func-test/package.json
开发的时候应该可以直接使用packages里面的react插件吧
还是我的用法不对？
=> use react plugin in packages

packages/af-webpack/src/getConfig/index.js, packages/af-webpack/test/fixtures/alias/expected/index.js, packages/af-webpack/test/fixtures/copy/expected/index.js, packages/af-webpack/test/fixtures/disable-dynamic-import/expected/index.js, packages/af-webpack/test/fixtures/manifest/expected/index.js, packages/af-webpack/test/fixtures/typescript/expected/index.js, packages/af-webpack/test/fixtures/wasm/expected/index.js, packages/umi/test/build.test.js, packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/umi.js, packages/umi/test/fixtures/build/export-static/expected/umi.js, packages/umi/test/fixtures/build/tree-shaking-with-cjs/.umirc.js, packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/index.html, packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/umi.js, packages/umi/test/fixtures/build/tree-shaking-with-cjs/foo.js, packages/umi/test/fixtures/build/tree-shaking-with-cjs/pages/index.js
开启 treeshaking 之后项目代码可能也会存在 cjs 代码，有些场景前后端有公用代码，公用部分通过 cjs 实现。
=> feat: sourceType unambiguous for all files

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
=> mock 支持form-data 请求

docs/config/README.md, docs/zh/config/README.md
=> :memo: Document devServer configuration

packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js
=> fix: custom document don't work if base is configured

examples/func-test/src/pages/index.test.js, jest.config.js, packages/af-webpack/yarn.lock, packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
=> feat: exclude test files when get routes from dir

packages/umi-test/src/index.js
=> fix(umi-test): uncompatible with esm umi api

docs/config/README.md, docs/guide/create-umi-app.md, docs/guide/env-variables.md, docs/zh/config/README.md, docs/zh/guide/create-umi-app.md, docs/zh/guide/env-variables.md
* create project with create-umi
* config
* ESLINT env variable
=> doc: improve docs

.travis.yml, docs/guide/env-variables.md, docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/src/plugins/targets.js
```bash
⚠  warning   Since you have configured the environment variable BABEL_POLYFILL to none, no patches will be included.
```
=> feat: warn if BABEL_POLYFILL is set to none

packages/af-webpack/package.json, packages/af-webpack/yarn.lock
=> feat: upgrade cssnano@4.1.8

packages/umi-plugin-react/src/plugins/antd.js
=> feat(umi-plugin-react/antd): support config libraryDirectory for babel-plugin-import

packages/af-webpack/yarn.lock, packages/babel-preset-umi/package.json, packages/babel-preset-umi/src/index.js, packages/babel-preset-umi/yarn.lock
https://github.com/babel/babel/issues/9376
http://github.com/babel/babel/blob/f6ee26c3da4c903818fd61fd9e5e8e1970185f77/packages/babel-plugin-transform-runtime/src/index.js#L41
=> feat: lock @babel/runtime's version for files in project

packages/umi-build-dev/src/plugins/404/NotFound.js, packages/umi-build-dev/src/plugins/404/NotFound.less
=> feat: use a complex NotFound css name for potential conflict problems when user disabled css modules

docs/config/README.md, docs/guide/html-template.md
=> doc: translate

packages/af-webpack/package.json, packages/af-webpack/yarn.lock, packages/umi-plugin-react/package.json, packages/umi-plugin-react/yarn.lock
Close #1983
Related: https://github.com/webpack/webpack/issues/8656
=> fix: revert webpack to 4.28 since npm breaks webpack@4.29

packages/umi-mock/src/createMiddleware.js
=> fix: mock watch only include _mock.js in pages

packages/umi-mock/src/createMiddleware.js
详细讨论在： [bug-1974](https://github.com/umijs/umi/issues/1974)
=> fix: 解决 windows 下 glob 用反斜杠无法触发watch事件的问题

packages/af-webpack/package.json, packages/af-webpack/src/getConfig/index.js, packages/af-webpack/yarn.lock
Close #3230
Close https://github.com/ant-design/ant-design-pro/issues/3230
=> fix: use a simple progress plugin for windows

packages/umi-build-dev/src/registerBabel.js, packages/umi-serve/bin/umi-serve.js
=> fix: update registerBabel targets to node 8

docs/guide/env-variables.md
=> 增加SOCKET_SERVER

packages/af-webpack/src/getConfig/prod.js
Close #2011
Related: 
* https://github.com/facebook/create-react-app/pull/6387
=> feat: use contenthash instead of chunkhash for better long-term caching

packages/umi-build-dev/CHANGELOG.md, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/plugins/commands/build/index.js, packages/umi-build-dev/src/plugins/commands/dev/index.js, packages/umi-types/index.d.ts
=> feat: add onStartAsync hook for build and dev

packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.js, packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.test.js, packages/umi-build-dev/src/plugins/commands/block/replaceContent.test.js
=> feat: support block path in upper camelcase

packages/umi-library/README.md, packages/umi-library/package.json, packages/umi-library/src/doc.ts
=> feat: add doc deploy

docs/guide/runtime-config.md
Pretty much google translated page with some adjustments.
=> doc: translate runtime config

packages/umi-library/src/fixtures/build/babel-syntax/package.json, packages/umi-library/src/fixtures/build/rollup-import-directory/.umirc.library.js, packages/umi-library/src/fixtures/build/rollup-import-directory/expected/index.esm.js, packages/umi-library/src/fixtures/build/rollup-import-directory/src/foo/index.js, packages/umi-library/src/fixtures/build/rollup-import-directory/src/index.js, packages/umi-library/src/getRollupConfig.ts
=> fix(umi-library): can't import directory

packages/umi-types/index.d.ts
Add some typescript definition of umi block api.
=> feat(umi-types): add block api definition

packages/umi-types/index.d.ts
Fix block IBlockDependencies ts define
=> fix: block IBlockDependencies define

jest.config.js, packages/umi-test/bin/umi-test.js, packages/umi-test/package.json, packages/umi-test/src/index.js, packages/umi-test/src/transformers/jsTransformer.js, packages/umi-test/src/transformers/tsTransformer.js, packages/umi-test/yarn.lock
- use babel for TypeScript transform, instead of ts-jest
- fix enzyme multiple instance problem
=> feat(umi-test): use babel for typescript transform, enzyme multiple instance problem, and etc

docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/src/plugins/history.js
- any feature?
- close https://github.com/umijs/umi/issues/2069
=> fix(umi-library): support array like config in config.history

docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/plugins/commands/build/index.js, packages/umi-types/index.d.ts
=> feat: add plugin hook `onBuildSuccessAsync`

packages/umi-test/src/transformers/jsTransformer.js, packages/umi-test/yarn.lock, packages/umi-utils/src/compatDirname.js
=> fix(umi-test): use project's enzyme dependencies if found

packages/umi-library/README.md, packages/umi-library/src/fixtures/build/rollup-umd-auto-name/.umirc.library.js, packages/umi-library/src/fixtures/build/rollup-umd-auto-name/expected/index.umd.js, packages/umi-library/src/fixtures/build/rollup-umd-auto-name/package.json, packages/umi-library/src/fixtures/build/rollup-umd-auto-name/src/index.js, packages/umi-library/src/getRollupConfig.ts
- 如没有指定 `umd.name`，默认使用 `package.json` 中的 name 来设置
=> feat(umi-library): use package name as umd name by default

packages/umi-plugin-locale/README.md, packages/umi-plugin-locale/examples/base/config/config.js, packages/umi-plugin-locale/examples/base/package.json, packages/umi-plugin-locale/examples/base/src/page/index.js, packages/umi-plugin-locale/template/wrapper.jsx.tpl, packages/umi-plugin-locale/test/locale.test.js, packages/umi-plugin-react/src/plugins/title/template/TitleWrapper.js.tpl
replace alias `umi/locale` in the example and template with `umi-plugin-locale`.
=> replace umi/locale with umi-plugin-locale

packages/umi-types/index.d.ts, packages/umi-types/package.json, packages/umi-types/yarn.lock
=> types: chain webpack

packages/umi-library/README.md
=> docs: enhance readability for umi-library

packages/umi-library/.npmignore, packages/umi-library/package.json
=> fix(umi-library): package size too large

docs/zh/guide/runtime-config.md
=> doc: update runtime-config.md

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/afwebpack-config/index.js, packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js, packages/umi-build-dev/yarn.lock
=> fix: lock core-js's version

packages/umi-build-dev/src/plugins/afwebpack-config/index.js, packages/umi/test/fixtures/build/runtimePublicPath/.umirc.js, packages/umi/test/fixtures/build/runtimePublicPath/expected/index.html, packages/umi/test/fixtures/build/runtimePublicPath/expected/umi.js, packages/umi/test/fixtures/build/runtimePublicPath/pages/index.js
=> fix: setPublicPath path problem

packages/umi/package.json
=> fix: include routerTypes

packages/umi/package.json
=> fix: include index.d.ts

docs/guide/getting-started.md
- [ x ] documentation is added
- [ x ] commit message follows commit guidelines
Close https://github.com/umijs/umi/issues/2080
=> docs: Test and Inspect

docs/zh/guide/getting-started.md
=> docs: [translate] Test and Inspect

packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js
=> fix: core-js's verson lock don't work in windows

packages/umi-library/README.md
=> docs(umi-library): 修复文档中关于css modules使用方式的描述错误

packages/umi-library/package.json, packages/umi-library/yarn.lock
=> fix(umi-library): peerDependencies warning

packages/umi-library/bin/umi-library.js, packages/umi-library/src/build.ts
- throw error is none format is configured
- support specify target in cli
- support specify umd.name in cli
=> feat: improve umi-library

packages/umi-library/src/build.ts
=> fix(umi-library): bundle opts validate typo

packages/eslint-config-umi/package.json
=> dep: upgrade eslint-config-react-app

packages/umi-library/index.d.ts, packages/umi-library/package.json
=> feat(umi-library): add typing definition for umi-library

packages/umi-library/src/doczrc.ts
=> fix(umi-library): enable source-map for doc in dev mode

packages/umi/src/renderRoutes.js, packages/umi/test/fixtures/build/route-sensitive/.umirc.js, packages/umi/test/fixtures/build/route-sensitive/pages/404.js, packages/umi/test/fixtures/build/route-sensitive/pages/login.js, packages/umi/test/fixtures/build/route-sensitive/test.js
=> fix: route could be sensitive

packages/umi/routerTypes.d.ts
=> fix: type definition of RouterTypes

docs/guide/app-structure.md, docs/zh/guide/app-structure.md
=> docs: translate `src/app.js` in guide/app-structure

packages/umi-serve/README.md, packages/umi-serve/bin/umi-serve.js
=> feat(umi-serve): support specify port with PORT env variable

docs/zh/config/README.md
fix docs typo
- any feature? no
=> fix(docs): typo

packages/umi-serve/bin/umi-serve.js, packages/umi-serve/package.json, packages/umi-serve/yarn.lock
- any feature?
- close https://github.com/umijs/umi/issues/2204
=> feat(umi-serve): support for umi-serve Gzip compression.

CONTRIBUTING.md, README.md, README_zh-CN.md, docs/guide/README.md, docs/guide/migration.md, docs/plugin/umi-plugin-react.md, docs/zh/guide/README.md, docs/zh/guide/migration.md, docs/zh/plugin/umi-plugin-react.md, packages/af-webpack/package.json, packages/af-webpack/src/getConfig/dev.js, packages/umi-plugin-react/src/plugins/hardSource.js, packages/umi-plugin-react/test/normal/.umirc.js, packages/umi-plugin-react/test/pwa/.umirc.js
[hardSource] is no longer valid
- close https://github.com/umijs/umi/issues/2213
=> feat: remove hardSource

packages/umi-library/package.json, packages/umi-library/src/doc.ts, packages/umi-serve/yarn.lock
- any feature?
- close https://github.com/umijs/create-umi/pull/51
=> fix(umi-library): docz bin resolve problem

packages/umi-build-dev/src/plugins/commands/ui/plugins/blocks/client.js, packages/umi-build-dev/src/plugins/commands/ui/plugins/config/client.js, packages/umi-build-dev/src/plugins/commands/ui/plugins/routes/client.js
rollup 无法处理 require，目前 `umi ui` 会因为 `require` 报错
目前 `umi ui` 会报错，因为使用的是 require 导致 rollup 打包 umd 时无法解析。
=> fix(ui): use `import` for rollup bundle umd files

packages/umi-library/src/fixtures/build/rollup-resolve-jsx/.umirc.library.js, packages/umi-library/src/fixtures/build/rollup-resolve-jsx/expected/index.esm.js, packages/umi-library/src/fixtures/build/rollup-resolve-jsx/package.json, packages/umi-library/src/fixtures/build/rollup-resolve-jsx/src/Foo.jsx, packages/umi-library/src/fixtures/build/rollup-resolve-jsx/src/index.js, packages/umi-library/src/getRollupConfig.ts
=> fix(umi-library): jsx ext not resolved

jest.config.js, packages/umi-utils/src/winPath.test.js
=> test: add winPath.test.js

packages/umi-plugin-dva/package.json, packages/umi-plugin-dva/src/index.js, packages/umi-plugin-dva/yarn.lock, packages/umi/test/fixtures/build/dva/.umirc.js, packages/umi/test/fixtures/build/dva/models/count.js, packages/umi/test/fixtures/build/dva/pages/index.js, packages/umi/test/fixtures/build/dva/test.js
=> fix(umi-plugin-dva): dva@2.6-beta don't work

packages/umi-plugin-dva/package.json, packages/umi-plugin-dva/src/index.js
=> fix: revert dva@2.6-beta's fix

packages/umi-library/package.json, packages/umi-library/src/doczrc.ts
- 目前只加了 `Built with umi-library`
=> feat(umi-library): use docz-theme-umi

packages/umi-library/README.md, packages/umi-library/src/getRollupConfig.ts, packages/umi-library/src/schema.ts, packages/umi-library/src/types.d.ts
=> feat(umi-library): support minify cjs

packages/umi-library/src/doczrc.ts
=> fix(umi-library): docz's alias problem

packages/umi-library/src/babel.ts
- ref: https://github.com/umijs/umi/issues/2217#issuecomment-482521653
=> fix(umi-library): d.ts should not be tranpiled in babel mode

docs/config/README.md, docs/zh/config/README.md
- [x ] documentation is changed or added
- add some usage about the extraPostCSSPlugins
- close https://github.com/umijs/umi/issues/2252
=> doc: add some usage about the extraPostCSSPlugins

packages/umi-test/package.json, packages/umi-test/src/setupTests.js, packages/umi-test/yarn.lock
- ref: https://jestjs.io/docs/en/configuration#testenvironment-string
=> feat(umi-test): remove jsdom since it's already included in jest

packages/umi-library/package.json
=> dep(umi-library): upgrade docz-theme-umi to ^1.1.0

packages/umi-types/config.d.ts, packages/umi-types/index.d.ts
using in `config/config.ts` / `.umirc.ts`
=> feat(umi-types): config use chainWebpack types

packages/umi-build-dev/template/entry.js.tpl
=> fix: init history before global.js

packages/umi-test/src/index.js
- support config `extraSetupFiles` in jest.config.js
- close #2307
=> feat: support extraSetupFiles

packages/umi-test/src/index.js
=> fix(umi-test): multiple enzyme instance when using tnpm

packages/umi-plugin-locale/README.md, packages/umi-plugin-locale/examples/base/src/app.js, packages/umi-plugin-locale/src/index.js, packages/umi-plugin-locale/template/wrapper.jsx.tpl, packages/umi-plugin-locale/test/index.test.js
=> setDefaultLocal in app.js

docs/config/README.md
Fixed a typo that caused the markdown content not being rendered correctly.
=> doc: fix typo

packages/umi-build-dev/src/plugins/commands/block/index.js
… umi block list
- any feature?  No
=> chore: update doc for `umi help block`

packages/umi-library/src/doc.ts, packages/umi-library/src/doczrc.ts
=> fix(umi-library): can't parse umirc.library config with .ts extname

packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js, packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/template/blockEntry.js.tpl
=> feat: read specVersion for compatible old version block

packages/umi-build-dev/package.json
Code Injection js-yaml https://nodesecurity.io/advisories/813
- any feature?
=> dep: upgrade js-yaml to 3.13.1

packages/umi-types/config.d.ts, packages/umi-types/index.d.ts
=> fix(umi-types): lost definitions for api.writeTmpFile and config.disableGlobalVariabls

packages/umi-build-dev/src/plugins/importFromUmi.js, packages/umi-types/index.d.ts
- 修复 HMR 时会报 key 已存在的错误
- cc @xiaohuoni
=> fix: addUmiExports error in hmr

packages/umi-build-dev/src/plugins/commands/block/index.js
For https://github.com/umijs/rfcs/pull/4#issuecomment-492067047
=> feat: support block dependencies

docs/config/README.md, docs/zh/config/README.md
=> doc: fix uglifyJSOptions e.g.

packages/umi-build-dev/package.json, packages/umi-build-dev/yarn.lock, yarn.lock
=> fix: umi-build-dev add esprima-extract-comments denpendency

packages/umi-build-dev/template/router.js.tpl
export routes in router.js.tpl
=> feat: export router in @tmp/router

packages/umi-build-dev/src/fixtures/block/antdpro/pages/index.js, packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js, packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/index.test.js, packages/umi-build-dev/src/plugins/commands/block/insertComponent.js, packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js, packages/umi-build-dev/src/utils/fixtures/routesWithTypescript.result.ts, packages/umi-build-dev/src/utils/fixtures/routesWithTypescript.resultWithLayout.ts, packages/umi-build-dev/src/utils/fixtures/routesWithTypescript.ts, packages/umi-build-dev/src/utils/writeNewRoute.js, packages/umi-build-dev/src/utils/writeNewRoute.test.js
close https://github.com/umijs/umi/issues/2365
=> feat: support add new route to typescript config when add a block

packages/umi-plugin-locale/src/locale.js
- [x ] documentation is changed or added
- [x ] commit message follows commit guidelines
typo in comments
=> fix: misspell

README.md
=> doc: fix technical terms

docs/config/README.md, docs/zh/config/README.md, packages/af-webpack/src/getConfig/uglifyOptions.js
- 修正了一些不支持的 uglify 配置项
- 修正了相关的文档
=> fix: remove not be supported settings

packages/af-webpack/package.json, packages/af-webpack/yarn.lock
webpack-contrib/webpack-bundle-analyzer#262 vulnerability
- any feature?
=> dep: upgrade webpack-bundle-anaylze for vulnerability

docs/plugin/umi-plugin-react.md, docs/zh/plugin/umi-plugin-react.md
=> docs: typo in description of pwa option

packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.js, packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.result.js, packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.resultWithLayout.js, packages/umi-build-dev/src/utils/writeNewRoute.js
=> fix: wirte route bug when has redirect

docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/index.test.js
Ant Design Pro 插入一个区块的时候，有的区块是作为 layout 插入的，修改路由的时候需要添加 `routes` 对象，这样后面的区块可以插入到里面。
=> feat: block support --layout and config npmClient

packages/af-webpack/src/getConfig/uglifyOptions.js
due to [this change](https://github.com/mishoo/UglifyJS2/issues/3394) in Uglify-js, umi build breaks.
this commit changed the Uglify-js config to support the new grammar
=> fix: Uglify-js update lead to fail in build

packages/umi-plugin-dll/src/buildDll.js
=> fix(umi-plugin-dll): ignore @types packages

packages/af-webpack/src/getConfig/uglifyOptions.js
Update default Uglify-js options based on the [new API doc](https://github.com/mishoo/UglifyJS2#compress-options)
=> fix: Uglify-js option

packages/umi-library/README.md, packages/umi-library/src/getRollupConfig.ts, packages/umi-library/src/schema.ts, packages/umi-library/src/types.d.ts
- any feature?
- close https://github.com/umijs/umi/issues/2494
=> feat: umi-library support postcss extract

packages/umi-build-dev/src/plugins/404/NotFound.less, packages/umi-build-dev/src/routes/getRouteConfigFromDir.js, packages/umi-build-dev/src/routes/getRouteConfigFromDir.test.js
- close #2492
- close #2174
Before:
After:
=> fix: sort problem with routes generated from fs

packages/umi-library/src/babel.ts
=> fix(umi-library): don't exit process when compile failed with babel type

packages/umi-plugin-hd/src/index.js
=> fix(umi-plugin-hd): theme failed with theme file

packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/index.test.js
=> feat: support --page for block add

packages/af-webpack/package.json, packages/af-webpack/src/getConfig/uglifyOptions.js, packages/af-webpack/yarn.lock, packages/umi-plugin-react/yarn.lock
=> fix: revert uglify-webpack-plugin to 1.x

docs/plugin/develop.md, docs/zh/plugin/develop.md
=>  docs onBuildSuccessAsync

packages/umi-plugin-locale/template/wrapper.jsx.tpl
=> fix(umi-plugin-locale): React undefined

packages/af-webpack/package.json, packages/af-webpack/src/getConfig/index.js, packages/af-webpack/test/fixtures/graphql/expected/index.js, packages/af-webpack/test/fixtures/graphql/index.js, packages/af-webpack/test/fixtures/graphql/test.gql, packages/af-webpack/yarn.lock
感谢您贡献代码。请确认下列 checklist 的完成情况。
Bug 修复和新功能必须包含测试。
Support `.graphql`, `.gql` module in af-webpack
- `.graphql`, `.gql` module can be loaded in umi env
- close https://github.com/umijs/umi/issues/2532
=> feat: support .graphql, .gql

packages/umi-plugin-locale/src/locale.js
增加变量的设置，符合 html5 的规范
```
window.navigator = lang;
window.g_lang = lang;
```
=> add set g_lang and navigator

packages/umi-types/config.d.ts
=> fix(umi-types): add block entry to IConfig

packages/umi-build-dev/src/FilesGenerator.js
=> fix: history createMemoryHistory in ssr

packages/af-webpack/package.json, packages/af-webpack/src/getConfig/css.js, packages/umi-build-dev/src/getWebpackConfig.js
Before:
After: 
- any feature?
=> fix: 修复 ssr 下 css 文件重复 build 的问题

packages/umi/index.d.ts
- any feature?
cc @afc163 @ycjcl868
=> fix(umi): @tmp/umiExports module not found error when run tsc

packages/umi-plugin-dva/src/index.js, packages/umi-plugin-react/src/plugins/dynamicImport.js
支持 `dynamicImport` ，`umi.server.js` 不走动态加载，`umi.js` 客户端渲染可动态加载。
- any feature?
=> feat: ssr 支持 dynamicImport

packages/umi-build-dev/src/FilesGenerator.js
=> fix: 使用了 APP_ROOT 时 watch 目录不正确

packages/umi-test/package.json, packages/umi-test/src/index.js
Support alias as `jest-cli`: https://github.com/facebook/jest/blob/master/packages/jest-cli/src/cli/args.ts#L69
=> feat: support alias

packages/umi-build-dev/template/entry.js.tpl, packages/umi-plugin-locale/template/wrapper.jsx.tpl, packages/umi-plugin-prerender/src/index.ts
=> fix: locale 插件兼容 ssr，抛出 umi.server.js 错误

packages/umi-build-dev/src/getWebpackConfig.js, packages/umi-types/config.d.ts
=> tweak ssr warning

packages/af-webpack/src/dev.js, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/getPlugins.js, packages/umi-build-dev/src/plugins/commands/build/index.js, packages/umi-build-dev/src/plugins/commands/dev/index.js, packages/umi-build-dev/src/utils/getCodeFrame.js, packages/umi-build-dev/yarn.lock, packages/umi-core/package.json, packages/umi-core/src/error.js, packages/umi-core/yarn.lock, packages/umi-plugin-dll/src/buildDll.js, packages/umi-types/index.d.ts, packages/umi-utils/package.json, packages/umi-utils/src/umiError.js, packages/umi-utils/yarn.lock, yarn.lock
=> feat: unify umi error handle

packages/umi-build-dev/src/FilesGenerator.js
=> fix: watch 操作不需要传入 cwd

packages/af-webpack/yarn.lock, packages/babel-preset-umi/package.json, packages/babel-preset-umi/src/index.js, packages/babel-preset-umi/src/index.test.js, packages/babel-preset-umi/yarn.lock, packages/umi-build-dev/src/UserConfig.js, packages/umi-test/yarn.lock
=> fix(babel-preset-umi): don't transform object spread in some case

packages/af-webpack/package.json, packages/af-webpack/yarn.lock, packages/eslint-config-umi/package.json, packages/eslint-config-umi/yarn.lock, packages/umi-build-dev/yarn.lock
=> dep: upgrade eslint-config-react-app to 4 for hooks support

packages/umi-plugin-auto-externals/package.json, packages/umi-plugin-auto-externals/src/util/index.ts, packages/umi-plugin-auto-externals/yarn.lock
- 修复 chalk 依赖丢失
- 修改 urllib 为更轻量的 got
=> fix(umi-plugin-auto-externals): chalk dep lost and change urllib to got

.travis.yml
=> feat: support node 12

docs/zh/guide/block.md
增加如何使用 js 的文档说明
- any feature?
=> doc: more doc about use block with js

docs/api/README.md, docs/zh/api/README.md
Documentation of missed `umi-plugin-locale` usage
=> doc: add locale documentation

docs/zh/guide/block.md, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/util.js
相关背景 
https://github.com/ant-design/ant-design-pro/issues/4534
https://github.com/ant-design/ant-design-pro/issues/4379
https://github.com/ant-design/ant-design-pro/issues/4386
https://github.com/umijs/umi-blocks/pull/36
=> feat(block): support submodule

package.json, yarn.lock
=> chore: use father-build to bundle umi's packages

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/plugins/afwebpack-config/index.js, packages/umi-plugin-react/package.json, packages/umi-plugin-react/src/plugins/antd.js, packages/umi-plugin-react/src/plugins/dynamicImport.js
dynamicImport 后，ssr option 没做默认值，所以会报错
Fix #2654
=> fix: dynamic compatibility

packages/umi-plugin-react/src/plugins/dynamicImport.js, packages/umi/package.json
=> fix: notlock types

packages/umi-plugin-dva/src/index.js
=> fix(umi-plugin-dva): immer default is not a function

docs/.vuepress/config.js, docs/config/README.md, docs/plugin/README.md, docs/plugin/umi-plugin-prerender.md, docs/zh/config/README.md, docs/zh/plugin/umi-plugin-prerender.md, packages/umi-plugin-prerender/README.md, packages/umi-plugin-prerender/package.json
=> doc: add docs for prerender

packages/umi-plugin-prerender/src/index.ts
umi/packages/umi-plugin-dva/node_modules/whatwg-fetch/fetch.js
=> fix: prerender plugin add self polyfill

packages/umi-build-dev/src/FilesGenerator.js
=> fix: 修复 findRouter windows 路径问题

packages/umi-build-dev/src/FilesGenerator.js
- close #2657
- complements #2660
=> fix: g_initialData in windows

packages/af-webpack/package.json, packages/af-webpack/yarn.lock, packages/umi-plugin-react/package.json, packages/umi-plugin-react/yarn.lock
=> dep: upgrade webpack to 4.35

packages/umi-build-dev/src/getWebpackConfig.js
=> fix: ssr dev hot files should in memo

packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/util.js
在下载区块的时候是不需要 puppeteer 的，但是 yarn 模式下可能会重复下载，加了个标志位
=> chore: add PUPPETEER_SKIP_CHROMIUM_DOWNLOAD

packages/af-webpack/src/dev.js, packages/af-webpack/src/fork.js
=> feat(af-webpack): remember user choosed port

docs/guide/app-structure.md, docs/zh/guide/app-structure.md
=> docs: more info about .env

packages/umi-core/package.json, packages/umi-core/src/error.js, packages/umi-core/src/error.test.js
重构 error 的构造函数，统一在构造函数中进行探测，方便在其他各个地方进行消费
=> refactor: error constructor

packages/umi-plugin-dll/src/index.js, packages/umi-types/index.d.ts
=> fix: disable dll when use ssr

packages/umi-build-dev/src/plugins/commands/block/download.js, packages/umi-build-dev/src/plugins/commands/block/download.test.js
Add regex to match IP to fix #2191
=> fix(block): allow an IP to be the host of git (#2191)

packages/umi-plugin-locale/template/wrapper.jsx.tpl
Change the `wrapper.jsx.tpl` to support messages file in commonjs module
=> feat(umi-plugin-locale): support locale file in commonjs module format

packages/umi-plugin-locale/index.d.ts
=> fix: 去掉 临时方案 locale @types

packages/umi-build-dev/src/plugins/afwebpack-config/index.js
=> fix: don't resolve versions from user's package.json for react-router, react-router-dom and react-router-config

packages/af-webpack/package.json, packages/af-webpack/webpack-dev-middleware.js, packages/af-webpack/yarn.lock, packages/umi-build-dev/src/plugins/commands/dev/index.js
=> fix: umi.server.js not write when in dev env

packages/umi-plugin-dva/src/index.js
=> feat: support config dva dir from env variable

packages/af-webpack/src/getConfig/index.js
=> fix: speed_measure in ssr

docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/src/Service.test.js, packages/umi-build-dev/src/fixtures/Service/plugin-ssr/externalWhitelist/.umirc.js, packages/umi-build-dev/src/getWebpackConfig.js, packages/umi-types/config.d.ts
`externalWhitelist` 支持配置，用于基于 umi 框架自定义 ssr 不需要 external 的包。（例如 `@alipay/bigfish/...`）
=> feat: ssr support externalWhitelist config

docs/guide/env-variables.md, docs/zh/guide/env-variables.md, packages/af-webpack/src/getConfig/index.js
通过 ANALYZE_MODE 控制生成 webpack stats 文件
=> feat: support generate webpack stats file

packages/af-webpack/package.json
=> fix: ssr af-webpack/webpack-dev-middleware

README.md, README_zh-CN.md
close https://github.com/umijs/umi/issues/2711
=> docs: add Coverage Badge

packages/umi-build-dev/.fatherrc.js, packages/umi-build-dev/package.json, packages/umi-build-dev/src/getWebpackConfig.js, packages/umi-build-dev/src/getWebpackConfig.ts, packages/umi-build-dev/yarn.lock
Close #2737. 
`getWebpackConfig.js` 改成了 `ts` 。build 后，除了加判断的部分，其它没区别。
=> fix: external whitelist

packages/umi-build-dev/src/plugins/commands/block/clearGitCache.js, packages/umi-build-dev/src/plugins/commands/block/download.js, packages/umi-build-dev/src/plugins/commands/block/index.js
[ ] 增加区块缓存清理功能
[ ] 增加对 win 的支持
close https://github.com/ant-design/ant-design-pro/issues/4664
close https://github.com/ant-design/ant-design-pro/issues/4388
close https://github.com/ant-design/ant-design-pro/issues/4675
- any feature?
=> feat: umi block clear

jest.config.js
test coverage exclude `fixtures` dir
=> fix: jest coveragePath

packages/umi-build-dev/template/entry.js.tpl, packages/umi-plugin-locale/src/locale.js
=> fix: umi locale in ssr, and bug when component not exist

packages/umi-build-dev/template/entry.js.tpl, packages/umi/src/renderRoutes.js, packages/umi/test/fixtures/build/ssr/pages/index.js, packages/umi/test/fixtures/build/ssr/pages/news/$id.js, packages/umi/test/fixtures/build/ssr/test.js
Close #2770.  
Close #2774.
Close #2777.
- any feature?
=> fix: ssr with dynamic router & unnecessary div wrapper

packages/af-webpack/package.json, packages/umi-build-dev/package.json, packages/umi-mock/package.json
- any feature?
- close #2768
- close #2769
=> dep: upgrade chokidar to 3.0.2, fix warning under windows

docs/zh/guide/block.md
=> docs: correction of typo

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-utils/package.json, packages/umi-utils/src/index.js, packages/umi-utils/src/prettierFile.js, packages/umi-utils/src/prettierFile.test.js, packages/umi-utils/yarn.lock
before
```js
export default function RouterWrapper(props = {}) {
return (
<RendererWrapper0>
<Router history={history}>
{ renderRoutes(routes, props) }
</Router>
</RendererWrapper0>
);
}
```
after
```js
export default function RouterWrapper(props = {}) {
return (
<RendererWrapper0>
<Router history={history}>
{renderRoutes(routes, props)}
</Router>
</RendererWrapper0>
);
}
```
格式化一下，创建的文件，虽然 `pages/.umi` 下的文件都是临时文件，但是偶尔打开还是很难受的。
=> chore: prettier generate file

packages/umi-plugin-locale/index.d.ts
=> fix: second parameter of 'setLocale' is optional

docs/plugin/develop.md, docs/zh/plugin/develop.md
=> docs: fix typos

packages/umi-build-dev/src/findRoute.js, packages/umi-build-dev/src/findRoute.test.js
=> fix: findRoute recursive bug

packages/umi-build-dev/src/plugins/commands/block/download.js, packages/umi-build-dev/src/plugins/commands/block/download.test.js, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/util.js, packages/umi-utils/src/getFastGithub.js, packages/umi-utils/src/index.js
详情看这里 https://github.com/ant-design/ant-design-pro/issues/4823
- any feature?
=> feat: support auto select fast github

.travis.yml, packages/af-webpack/package.json, packages/af-webpack/test/fixtures/dynamic-import/.webpackrc, packages/af-webpack/test/fixtures/dynamic-import/a.js, packages/af-webpack/test/fixtures/dynamic-import/expected/index.js, packages/af-webpack/test/fixtures/dynamic-import/expected/page_chunk_a.async.js, packages/af-webpack/test/fixtures/dynamic-import/index.js, packages/af-webpack/test/fixtures/json/expected/index.js, packages/af-webpack/yarn.lock, packages/umi-plugin-react/package.json, packages/umi-plugin-react/yarn.lock
=> dep: webpack@4.36.1

packages/umi-utils/package.json
相关问题 https://github.com/ant-design/ant-design-pro/issues/4863
- any feature?
=> fix: node-fetch no found

docs/guide/getting-started.md
Fix a small typo in the document.
=> doc: fix word typo

packages/umi-utils/src/getFastGithub.js
=> fix: delete spaces before the url

packages/umi-utils/src/getFastGithub.js
cc  https://github.com/umijs/umi/pull/2829
- any feature?
=> feat: better fast github

packages/umi-build-dev/src/plugins/commands/block/download.js, packages/umi-build-dev/src/plugins/commands/block/download.test.js
cc @yutingzhao1991 
- any feature?
=> url  auto add .git

packages/af-webpack/yarn.lock, packages/umi-ui/package.json, packages/umi-ui/src/UmiUI.ts
=> feat: compression express static server

packages/umi-build-dev/src/plugins/commands/block/index.js
=> fix: eslint-config-prettier package not found

packages/af-webpack/package.json, packages/af-webpack/yarn.lock, packages/umi-plugin-react/package.json, packages/umi-plugin-react/yarn.lock, packages/umi/bin/umi.js
=> dep: upgrade webpack to 4.38

packages/umi-ui/src/Config.ts, packages/umi-ui/src/UmiUI.ts
=> feat: 支持以特定目录开启 umi ui

packages/af-webpack/package.json, packages/af-webpack/src/getConfig/css.js, packages/af-webpack/yarn.lock, packages/umi/test/dev.e2e.js, packages/umi/test/fixtures/dev/ssr-styles/.umirc.js, packages/umi/test/fixtures/dev/ssr-styles/pages/index.js, packages/umi/test/fixtures/dev/ssr-styles/pages/index.module.less, packages/umi/test/fixtures/dev/ssr-styles/pages/news.js, packages/umi/test/fixtures/dev/ssr-styles/pages/news.less, scripts/startDevServers.js
Close https://github.com/umijs/umi/issues/2921
=> fix: ssr styles shake

packages/umi-build-dev/src/plugins/commands/dev/index.js
=> fix: onStartAsync error handler

circle.yml, docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/src/Service.test.js, packages/umi-build-dev/src/fixtures/Service/plugin-ssr/disableExternal/.umirc.js, packages/umi-build-dev/src/getWebpackConfig.ts, packages/umi-types/config.d.ts
=> feat: ssr disableExternal

packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.js
Change-Id: I8296c08f04f2bf74559e61b14ffae66e5472de6c
- [ x ] `npm test` passes
- [ x ] tests are included
=> fix(umi-plugin-react): pwa srcPath local path error

packages/af-webpack/yarn.lock, packages/babel-preset-umi/yarn.lock, packages/umi-build-dev/yarn.lock, packages/umi-core/yarn.lock, packages/umi-mock/yarn.lock, packages/umi-plugin-auto-externals/yarn.lock, packages/umi-plugin-dll/yarn.lock, packages/umi-plugin-dva/yarn.lock, packages/umi-plugin-locale/yarn.lock, packages/umi-plugin-react/yarn.lock, packages/umi-serve/yarn.lock, packages/umi-test/yarn.lock, packages/umi-types/yarn.lock, packages/umi-utils/yarn.lock, packages/umi/yarn.lock, yarn.lock
=> chore: update yarn.lock

packages/umi-build-dev/src/plugins/history.js
当路由模式改变的时候，需要重新生成 dll 文件才能生效
- close #2945
=> fix: history won't changed after the config changed

packages/umi-build-dev/template/entry.js.tpl, packages/umi/test/fixtures/build/ssr/pages/index.js, packages/umi/test/fixtures/build/ssr/test.js, scripts/startDevServers.js
=> fix: ssr location query not pass

packages/umi-ui/src/UmiUI.ts
=> feat: umi ui 本地开发可以关闭 service 缓存

packages/umi/test/fixtures/build/auto-external/test.js
=> fix: external test ci when version upd

packages/umi-types/ui.d.ts, packages/umi-ui/client/.umirc.ts
=> feat: add xterm to umi ui external

packages/umi-mock/package.json, packages/umi-mock/src/createMiddleware.js
之前提交的pr，把代码逻辑改了。后续看了代码，发现并不是缓存的问题，是Windows平台，路径的问题  
Close #2959
=> fix: windows平台mock文件，不能热更新的问题

packages/umi-plugin-locale/template/wrapper.jsx.tpl, packages/umi-plugin-locale/test/index.test.js
=> fix: judge antd version

packages/umi-ui/client/.eslintrc.js, packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/components/Result/index.less, packages/umi-ui/client/src/components/Result/index.tsx, packages/umi-ui/client/src/layouts/Layout.tsx, packages/umi-ui/client/src/pages/loading/fail.tsx, packages/umi-ui/client/src/pages/loading/index.less, packages/umi-ui/client/src/pages/loading/index.tsx
-----
[View rendered CONTRIBUTING.md](https://github.com/umijs/umi/blob/feat-loading-erroboundry/CONTRIBUTING.md)
=> Feat ui loading erroboundry

packages/umi/package.json
- any feature?
```
> ./node_modules/typescript/bin/tsc --outDir tmp
node_modules/_@types_react@16.8.25@@types/react/index.d.ts:2823:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
2823         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/_@types_react@16.9.1@@types/react/index.d.ts:2816:14
2816         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
~~~~~~~~~~~~~~~~~~~~~~~~
'LibraryManagedAttributes' was also declared here.
node_modules/_@types_react@16.8.25@@types/react/index.d.ts:2949:13 - error TS2717: Subsequent property declarations …
```
=> dep: upgrade @types/react

docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/src/getWebpackConfig.ts, packages/umi-types/config.d.ts
related: https://github.com/umijs/plugins/pull/14
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat-ssr-config/docs/config/README.md)
[View rendered docs/zh/config/README.md](https://github.com/umijs/umi/blob/feat-ssr-config/docs/zh/config/README.md)
=> feat: ssr config for react-helmet, react-document-title

packages/umi-types/ui.d.ts
=> fix: TwoColumnPanel types

packages/umi-plugin-locale/template/wrapper.jsx.tpl, packages/umi-plugin-locale/test/index.test.js
=> fix: antd ConfigProvider not found

packages/umi-ui-tasks/.fatherrc.js
=> fix: tasks fatherrc config

packages/umi-ui-tasks/src/server/core/Tasks/Base.ts, packages/umi-ui-tasks/src/server/core/Tasks/Build.ts, packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts, packages/umi-ui-tasks/src/server/core/Tasks/Test.ts, packages/umi-ui-tasks/src/server/util/index.ts
=> feat: 任务管理可以使用全局的命令

docs/plugin/develop.md, docs/zh/plugin/develop.md
- any feature?
-----
[View rendered docs/plugin/develop.md](https://github.com/KMBaby-zyl/umi/blob/doc-api-writeTnpFile/docs/plugin/develop.md)
[View rendered docs/zh/plugin/develop.md](https://github.com/KMBaby-zyl/umi/blob/doc-api-writeTnpFile/docs/zh/plugin/develop.md)
=> doc: add writeTmpFile api doc

packages/umi-plugin-locale/template/wrapper.jsx.tpl
=> fix: localeWrapper console 

packages/umi-utils/src/getFastGithub.js
https://github.com.cnpmjs.org 因为流量问题，会被 github 限流
切换成了码云的也很快
- umi-block
- pro
- pro-blocks 
都在码云新建了
- any feature?
=> feat: fast gitHub use gitee

docs/config/README.md, docs/zh/config/README.md, packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/findRoute.js, packages/umi-build-dev/src/findRoute.test.js, packages/umi-build-dev/template/entry.js.tpl, packages/umi/src/renderRoutes.js, packages/umi/test/fixtures/build/ssr/pages/locale.js, packages/umi/test/fixtures/build/ssr/test.js
=> feat: ssr pass down location params

packages/umi-types/index.d.ts
add definitions for api.onUiSocket
@ikobe @sorrycc @ycjcl868
=> feat: onUiSocket params types definition

packages/umi-plugin-ui/src/plugins/configuration/locales/en-US.ts, packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/configuration/ui.tsx, packages/umi-types/ui.d.ts, packages/umi-ui/API.md, packages/umi-ui/client/src/layouts/Dashboard.less, packages/umi-ui/client/src/layouts/Dashboard.tsx
=> Feat add panel action btns

packages/umi-ui/src/npmClient.ts
=> feat: skip install puppeteer when create project

packages/umi-ui/client/.umirc.ts, packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/layouts/Footer.less, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/services/logs.ts, packages/umi-ui/client/src/styles/parameters.less
=> feat: clear log, fix: prod umi build

packages/umi-plugin-ui/src/plugins/configuration/index.ts, packages/umi-plugin-ui/src/plugins/configuration/ui/components/InstallConfig.tsx, packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-types/ui.d.ts, packages/umi-ui-tasks/src/server/core/Tasks/Base.ts, packages/umi-ui-tasks/src/server/core/Tasks/Install.ts, packages/umi-ui-tasks/src/ui/components/Install/index.tsx, packages/umi-ui/src/Config.ts, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/npmClient.ts
=> feat: ui 下载开启淘宝加速

packages/umi-ui/src/UmiUI.ts
- any feature?
-----
[View rendered CONTRIBUTING.md](https://github.com/umijs/umi/blob/project-add-failure/CONTRIBUTING.md)
=> Project add failure

packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-ui/src/Config.test.ts
=> Umi plugin react config

packages/umi-plugin-ui/src/plugins/configuration/index.ts, packages/umi-plugin-ui/src/plugins/configuration/ui/components/UIConfig.tsx, packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-ui/src/Config.test.ts, packages/umi-ui/src/Config.ts, packages/umi-ui/src/UmiUI.ts
- any feature?
-----
[View rendered CONTRIBUTING.md](https://github.com/umijs/umi/blob/taobaoSpeedUpConfig/CONTRIBUTING.md)
=> Taobao speed up config

packages/umi-ui-tasks/package.json, packages/umi-ui-tasks/src/server/core/Tasks/Install.ts, packages/umi-ui/package.json, packages/umi-ui/src/npmClient.ts
=> feat: ui install use binary-mirror-config

packages/umi-types/index.d.ts
=> fix: types declaration of onUiSocket

packages/umi-ui/client/src/pages/project/components/import/index.tsx
=> Fix import intl

packages/umi-plugin-ui/src/plugins/configuration/ui/components/BasicConfig.tsx, packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-types/package.json, packages/umi-types/ui.d.ts, packages/umi-ui/API.md, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/layouts/Dashboard.less, packages/umi-ui/client/src/layouts/Dashboard.tsx
-----
[View rendered CONTRIBUTING.md](https://github.com/umijs/umi/blob/feat-plugin-debug-info/CONTRIBUTING.md)
=> Feat plugin debug info

packages/umi-ui-tasks/src/locales/en-US.js, packages/umi-ui-tasks/src/locales/zh-CN.js, packages/umi-ui-tasks/src/server/core/Tasks/Install.ts, packages/umi-ui-tasks/src/ui/components/Install/index.tsx, packages/umi-ui-tasks/src/ui/components/Terminal/index.module.less, packages/umi-ui-tasks/src/ui/components/Terminal/index.tsx, packages/umi-ui-tasks/src/ui/ui.module.less, packages/umi-ui/client/src/pages/project/components/progress/index.less, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/npmClient.ts
=> feat: initNpmClients when loading

packages/umi-ui-tasks/src/server/util/index.ts, packages/umi-ui-tasks/src/ui/components/Build/index.tsx, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui-tasks/src/ui/components/Install/index.tsx, packages/umi-ui-tasks/src/ui/components/Lint/index.tsx, packages/umi-ui-tasks/src/ui/components/Test/index.tsx
=> fix: env fix

packages/umi-ui/client/src/enums/index.ts
https://github.com/ant-design/ant-design-pro/pull/5174
=> fix: locale flag to 🇺🇸

packages/umi-ui/client/src/components/ErrorBoundary/index.less, packages/umi-ui/client/src/components/ErrorBoundary/index.tsx, packages/umi-ui/client/src/layouts/Dashboard.less, packages/umi-ui/client/src/layouts/Dashboard.tsx, packages/umi-ui/client/src/layouts/Layout.tsx, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/scripts.ts
=> Feat ui error track

packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts, packages/umi-plugin-ui/src/plugins/dashboard/locales/zh-CN.ts, packages/umi-ui-tasks/src/locales/en-US.js, packages/umi-ui-tasks/src/locales/zh-CN.js, packages/umi-ui-tasks/src/ui.tsx, packages/umi-ui-tasks/src/ui/components/Build/index.tsx, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui-tasks/src/ui/components/Install/index.tsx, packages/umi-ui-tasks/src/ui/components/Lint/index.tsx, packages/umi-ui-tasks/src/ui/components/Test/index.tsx, packages/umi-ui-tasks/src/ui/util/index.ts, packages/umi-ui/client/src/locales/zh-CN.ts
=> feat: umi ui text intl

packages/umi-ui/client/src/pages/project/components/list/index.less, packages/umi-ui/client/src/pages/project/components/list/index.tsx
=> Ui add project icon

packages/umi-plugin-ui/src/plugins/dashboard/ui/ui.module.less, packages/umi-ui-tasks/src/ui.tsx, packages/umi-ui-tasks/src/ui/util/index.ts, packages/umi-ui/client/src/components/Terminal/index.module.less, packages/umi-ui/client/src/components/Terminal/index.tsx
=> chore: icon 调整

packages/umi-ui-tasks/src/index.ts
=> fix(umi-ui): umd file of ui tasks is lost

packages/umi-ui/src/UmiUI.ts
=> feat(umi-ui): disable local check with UI_CHECK_LOCAL=none

packages/umi-ui-tasks/src/server/core/Tasks/Base.ts, packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts, packages/umi/src/scripts/dev.js
=> fix(umi-ui): dev task exit code

packages/umi-ui-tasks/src/server/core/Tasks/Base.ts
=> fix dev task exit code

packages/umi-ui-tasks/package.json, packages/umi-ui-tasks/src/server/core/Tasks/Base.ts, packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts
=> Stream data

packages/umi-ui/src/Config.ts
=> fix(umi-ui): failed when OPEN_PROJECT run multiple times

package.json, packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx, packages/umi-ui/client/src/layouts/Dashboard.tsx, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/layouts/Layout.tsx, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/pages/project/components/list/index.less, packages/umi-ui/client/src/pages/project/components/list/index.tsx, packages/umi-ui/client/src/pages/project/components/progress/index.tsx, packages/umi-ui/client/src/styles/parameters.less, packages/umi-ui/src/UmiUI.ts
=> fix(umi-ui): improvements

packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/ui.module.less, packages/umi-ui-tasks/src/locales/en-US.js, packages/umi-ui-tasks/src/locales/zh-CN.js, packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts, packages/umi-ui-tasks/src/ui.tsx, packages/umi-ui-tasks/src/ui/components/Build/index.tsx, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui-tasks/src/ui/util/terminal.ts, packages/umi-ui/client/src/components/Terminal/index.tsx, packages/umi-ui/package.json, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/scripts.ts
chore: 调整 tasks ui 部分细节
- any feature?
=> feat(umi-ui): add mac address

docs/.vuepress/config.js, docs/plugin/umi-ui.md, docs/zh/plugin/umi-ui.md
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/doc/umi-ui-api/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/doc/umi-ui-api/docs/zh/plugin/umi-ui.md)
=> doc(umi-ui): move API.md to umijs.org

packages/umi/package.json
=> fix: umi/_Service lost when publish to npm

packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/utils/isDepFileExists.ts
=> fix(umi-ui): Umi 版本过低后刷新有效

packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/src/UmiUI.ts
=> fix(umi-ui): qrcode

packages/umi-ui/client/package.json, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/yarn.lock
=> fix: notify api not pass type

packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/Object.tsx, packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/fields/ObjectField.tsx, packages/umi-ui/client/src/layouts/Layout.tsx, packages/umi-ui/client/src/locales/en-US.ts
=> fix: Umi UI BasicConfig targets validator

docs/.vuepress/config.js, docs/guide/umi-ui.md, docs/zh/guide/umi-ui.md, packages/af-webpack/src/getUserConfig/configs/publicPath.js, packages/umi-ui/src/UmiUI.ts
- any feature?
-----
[View rendered docs/guide/umi-ui.md](https://github.com/umijs/umi/blob/fix/umi-ui-1/docs/guide/umi-ui.md)
[View rendered docs/zh/guide/umi-ui.md](https://github.com/umijs/umi/blob/fix/umi-ui-1/docs/zh/guide/umi-ui.md)
=> fix(umi-ui): version print, publicPath validate and doc

packages/umi-plugin-ui/src/plugins/configuration/locales/en-US.ts, packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/fields/ObjectField.tsx, packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/fields/styles.module.less, packages/umi-ui-tasks/src/locales/en-US.js, packages/umi-ui-tasks/src/locales/zh-CN.js, packages/umi-ui-tasks/src/ui/components/Terminal/index.tsx, packages/umi-ui-tasks/src/ui/ui.module.less, packages/umi-ui/client/src/components/DirectoryForm/index.less, packages/umi-ui/client/src/components/DirectoryForm/index.tsx, packages/umi-ui/client/src/global.less, packages/umi-ui/client/src/layouts/Footer.less, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/pages/project/components/create/Form2.tsx, packages/umi-ui/client/src/pages/project/components/list/index.less, packages/umi-ui/client/src/styles/parameters.less
=> fix(umi-ui): ui details

packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts, packages/umi-ui/client/src/components/ErrorBoundary/index.tsx, packages/umi-ui/client/src/layouts/Footer.less, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/scripts.ts
=> fix(umi-ui): add umi & bigfish version

packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/pages/project/components/list/index.less, packages/umi-ui/client/src/pages/project/components/list/index.tsx
=> fix(umi-ui): bigfish logo style

packages/umi-build-dev/src/plugins/commands/help.js
=> fix: umi help info for umi ui

packages/umi-build-dev/src/plugins/commands/block/index.js
=> fix(block): remoteLog undefined

packages/umi-ui/client/src/pages/loading/index.tsx, packages/umi-ui/src/UmiUI.ts
=> fix(umi-ui): add reinstall button when umi's version unmatch

docs/guide/faq.md, docs/zh/guide/faq.md, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/pages/loading/index.tsx, packages/umi-ui/src/UmiUI.ts
- any feature?
-----
[View rendered docs/guide/faq.md](https://github.com/umijs/umi/blob/fix/umi-ui-version-unmatch-tip/docs/guide/faq.md)
[View rendered docs/zh/guide/faq.md](https://github.com/umijs/umi/blob/fix/umi-ui-version-unmatch-tip/docs/zh/guide/faq.md)
=> doc(umi-ui): improve tips when local umi's version does not match

packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/pages/project/components/list/index.tsx
=> fix(umi-ui): hide project create in bigfish

docs/guide/develop-umi-ui-plugin.md, docs/zh/guide/develop-umi-ui-plugin.md
-----
[View rendered docs/guide/develop-umi-ui-plugin.md](https://github.com/umijs/umi/blob/docs-umi-base-ui/docs/guide/develop-umi-ui-plugin.md)
[View rendered docs/zh/guide/develop-umi-ui-plugin.md](https://github.com/umijs/umi/blob/docs-umi-base-ui/docs/zh/guide/develop-umi-ui-plugin.md)
=> doc: umi base ui use antd 4.x to develop

docs/guide/env-variables.md, docs/zh/guide/env-variables.md, packages/af-webpack/src/getPort.js
- any feature?
-----
[View rendered docs/guide/env-variables.md](https://github.com/umijs/umi/blob/basePortEnv/docs/guide/env-variables.md)
[View rendered docs/zh/guide/env-variables.md](https://github.com/umijs/umi/blob/basePortEnv/docs/zh/guide/env-variables.md)
=> feat: 支持 BASE_PORT 环境变量

docs/plugin/umi-plugin-prerender.md, docs/plugin/umi-plugin-react.md, docs/zh/plugin/umi-plugin-react.md
-----
[View rendered docs/plugin/umi-plugin-prerender.md](https://github.com/umijs/umi/blob/docs-format/docs/plugin/umi-plugin-prerender.md)
[View rendered docs/plugin/umi-plugin-react.md](https://github.com/umijs/umi/blob/docs-format/docs/plugin/umi-plugin-react.md)
[View rendered docs/zh/plugin/umi-plugin-react.md](https://github.com/umijs/umi/blob/docs-format/docs/zh/plugin/umi-plugin-react.md)
=> docs: umi-plugin-react docs format

packages/umi-ui-tasks/src/server/core/Tasks/Install.ts
- any feature?
- close https://github.com/umijs/umi/issues/3153
=> fix(umi-ui): reinstall error

packages/umi-plugin-locale/src/locale.js
修复判断代码错误，IE10上navigator.language为undefined，该处会导致页面报错。
=> fix: 获取浏览器语言设置判断出错

docs/guide/faq.md, docs/zh/guide/faq.md, packages/umi-ui/client/src/components/DirectoryForm/index.tsx, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/pages/project/components/progress/index.tsx, packages/umi-ui/src/installCreator.ts, packages/umi-ui/src/npmClient.ts
Close #3156.
-----
[View rendered docs/guide/faq.md](https://github.com/umijs/umi/blob/fix-ui-permissions/docs/guide/faq.md)
[View rendered docs/zh/guide/faq.md](https://github.com/umijs/umi/blob/fix-ui-permissions/docs/zh/guide/faq.md)
=> fix(Umi UI): permission eror message

packages/umi-ui/client/.env, packages/umi-ui/client/.umirc.ts
=> fix(Umi UI): reduce client bundle size

netlify.toml, website/package.json
PR 主要是自动部署一个 preview umi 官网站点。
可以看到改动的文档，最终在 umijs.org 官网上的展示，避免出现 markdown 看起来没问题，渲染不对。
=> chore: doc preview site

packages/umi-mock/src/createMiddleware.js, packages/umi-serve/bin/umi-serve.js
fix umi-serve console the error message when mock parse error
before:
after:
=> fix: umi-serve console the error message when mock parse error

packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/typings/global.d.ts, packages/umi-ui/client/yarn.lock, packages/umi-ui/src/scripts.ts
=> fix(Umi UI): ga analyse SPA pathname

packages/babel-preset-umi/src/index.test.js, packages/umi-utils/src/findCSS.js, packages/umi-utils/src/findJS.js
=> chore: fix father-build failed since babel@7.6

packages/umi-types/config.d.ts
TS miss mock.exclude options
- any feature?
=> fix(umi-types): Missing mock.exclude

packages/umi-types/package.json, packages/umi-types/ui.d.ts, packages/umi-types/yarn.lock, packages/umi-ui/client/.umirc.ts, packages/umi-ui/client/package.json, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/package.json
=> feat(umi-ui): support dva, add api.registerModel, api.connect

docs/zh/config/README.md
- any feature?
-----
[View rendered docs/zh/config/README.md](https://github.com/hazeFlame/umi/blob/doc_modify/docs/zh/config/README.md)
=> doc: zh doc params miss

docs/config/README.md, docs/zh/config/README.md
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/hazeFlame/umi/blob/master/docs/config/README.md)
[View rendered docs/zh/config/README.md](https://github.com/hazeFlame/umi/blob/master/docs/zh/config/README.md)
=> doc: params miss comma

docs/guide/module-processor.md
Add `tsx` extension to list of supported extesnsinons in Module Processor page.
-----
[View rendered docs/guide/module-processor.md](https://github.com/Grzesie2k/umi/blob/patch-1/docs/guide/module-processor.md)
=> doc: add tsx extension to module list

packages/umi-utils/src/chunkName.ts, packages/umi-utils/src/compatDirname.ts, packages/umi-utils/src/deprecate.ts, packages/umi-utils/src/endWithSlash.ts, packages/umi-utils/src/findCSS.ts, packages/umi-utils/src/findJS.ts, packages/umi-utils/src/isUrl.ts, packages/umi-utils/src/prettierFile.ts, packages/umi-utils/src/winEOL.ts, packages/umi-utils/src/winPath.ts
=> chore: supplementary type

packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
=> fix(Umi UI): TwoColumnPanel rerender

.github/PULL_REQUEST_TEMPLATE.md
- any feature?
-----
[View rendered .github/PULL_REQUEST_TEMPLATE.md](https://github.com/umijs/umi/blob/chore-pr-template/.github/PULL_REQUEST_TEMPLATE.md)
=> chore: PR template text 

packages/umi-ui-theme/dark.less, packages/umi-ui-theme/test/index.test.ts, packages/umi-ui/client/tsconfig.json
=> feat(umi-ui): ui less theme vars

packages/umi-ui-tasks/package.json, packages/umi-ui-tasks/src/server/core/Tasks/Base.ts, packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts
=> fix(Umi UI): task ui remove icon-lite deps

docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/Service.test.js, packages/umi-types/index.d.ts
```js
api.getRoutes();
// IRoute[]
```
-----
[View rendered docs/plugin/develop.md](https://github.com/umijs/umi/blob/feat/umi-plugin-api-getRoutes/docs/plugin/develop.md)
[View rendered docs/zh/plugin/develop.md](https://github.com/umijs/umi/blob/feat/umi-plugin-api-getRoutes/docs/zh/plugin/develop.md)
=> feat(plugin): add api.getRoutes for the latest routes

packages/umi-ui/package.json, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/yarn.lock
=> fix(umi-ui): plugin use promise error

packages/umi-plugin-locale/package.json, packages/umi-plugin-locale/src/locale.js, packages/umi-plugin-locale/yarn.lock
=> fix: react 15 error when using umi-plugin-locale

packages/umi-build-dev/src/plugins/targets.js
- ref: https://github.com/umijs/umi/pull/2550
=> fix: BABEL_POLYFILL env is allowed to set to none in plugin

.github/label-actions.yml
=> chore: add ssr label actions

packages/umi-ui/client/.umirc.ts
=> fix(Umi UI):  prod not show error message

package.json, packages/af-webpack/src/getWebpackConfig/index.test.js
=> fix: ci broken in windows

docs/plugin/umi-ui.md, docs/zh/plugin/umi-ui.md, packages/umi-plugin-ui/bubble/index.jsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/layouts/Layout.tsx
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-showMini/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-showMini/docs/zh/plugin/umi-ui.md)
=> feat(Umi UI): new browser API api.show/hideMini

docs/plugin/develop.md, docs/zh/plugin/develop.md
- any feature?
-----
[View rendered docs/plugin/develop.md](https://github.com/umijs/umi/blob/docs-plugin-develop/docs/plugin/develop.md)
[View rendered docs/zh/plugin/develop.md](https://github.com/umijs/umi/blob/docs-plugin-develop/docs/zh/plugin/develop.md)
=> docs: plugin develop docs

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/util.js, packages/umi-build-dev/yarn.lock
=> feat(block): support realy skipDependencies

packages/umi-plugin-ui/src/index.ts, packages/umi-plugin-ui/src/plugins/blocks/index.ts, packages/umi-plugin-ui/src/plugins/blocks/ui/BlockList/index.module.less, packages/umi-plugin-ui/src/plugins/blocks/ui/BlockList/index.tsx, packages/umi-plugin-ui/src/plugins/blocks/ui/index.module.less, packages/umi-plugin-ui/src/plugins/blocks/ui/index.tsx
=> feat: add block ui tag logic

packages/umi-ui/src/UmiUI.ts, packages/umi/test/ui.e2e.ts, scripts/startUiServers.js, scripts/test.js
=> chore: test Umi UI e2e test

packages/umi-build-dev/.fatherrc.js, packages/umi-build-dev/src/plugins/commands/block/addBlock.js, packages/umi-build-dev/src/plugins/commands/block/clearGitCache.js, packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-build-dev/src/plugins/commands/block/list.js, packages/umi-build-dev/src/plugins/commands/block/ui/.eslintrc.js, packages/umi-build-dev/src/plugins/commands/block/ui/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/package.json, packages/umi-build-dev/src/plugins/commands/block/ui/ui/BlockList/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/util.ts, packages/umi-build-dev/src/plugins/commands/block/util.js
=> add browserFiles and lint

package.json, packages/umi-ui/package.json
require("umi-ui") Error: Cannot find module 'umi-ui'
- fix: import umi-ui fail error
=> fix: import umi-ui fail error

packages/umi-build-dev/src/plugins/commands/block/addBlock.js, packages/umi-build-dev/src/plugins/commands/block/clearGitCache.ts, packages/umi-build-dev/src/plugins/commands/block/ui/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/util.ts
change log
- remove no path router
- add org.umi.block.pageFolders
- add block add logs
- remove login when block add
=> add org.umi.block.pageFolders

packages/umi-plugin-ui/bubble/Error.jsx, packages/umi-plugin-ui/bubble/Loading.jsx, packages/umi-plugin-ui/bubble/index.jsx, packages/umi-plugin-ui/bubble/socket.js, packages/umi-ui-theme/test/index.test.ts
Error handler
Iframe Loading:
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-bubble-error/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-bubble-error/docs/zh/plugin/umi-ui.md)
=> feat(Umi UI): ui bubble error handler

docs/plugin/umi-ui.md, docs/zh/plugin/umi-ui.md, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/layouts/Dashboard.less, packages/umi-ui/client/src/layouts/Dashboard.tsx, packages/umi-ui/client/src/locales/en-US.ts, packages/umi-ui/client/src/locales/zh-CN.ts, packages/umi-ui/client/src/styles/parameters.less
实验室：
```diff
import React from 'react';
import Dashboard from './ui/index';
export default (api) => {
api.addPanel({
+   beta: true,
title: 'org.umi.ui.dashboard.panel',
path: '/dashboard',
icon: {
type: 'dashboard',
theme: 'filled',
},
component: () => <Dashboard api={api} />,
});
};
```
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-lab/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-ui-lab/docs/zh/plugin/umi-ui.md)
=> feat(Umi UI): plugin ui labs

packages/umi-build-dev/src/plugins/commands/block/ui/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/Adder/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/TreeSelect/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.tsx
=> feat: add SelectTree for select route and path

CONTRIBUTING.md, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/npmClient.ts
use `DEBUG=umiui:UmiUI:socket umi ui` to inspect UI server logs.
default only output the error message.
- any feature?
=> tweak: umi ui server terminal log

packages/umi-plugin-ui/bubble/Dragger/index.jsx, packages/umi-plugin-ui/bubble/Dragger/utils.js, packages/umi-ui/client/src/components/ConfigForm/index.less, packages/umi-ui/client/src/layouts/Dashboard.tsx
=> refactor(Umi UI): bubble dragger and boundary detection

packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
=> fix: ui TwoColumnPanel description error when empty

packages/umi-types/index.d.ts
- fix types of `addRendererWrapperWithComponent`
=> fix: types

packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/plugins/commands/block/ui/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.tsx, packages/umi-types/index.d.ts
Add `addBlockUIResource` and `modifyBlockUIResources`
=> feat: add block ui plugin api

packages/umi-ui-tasks/src/server/util/index.ts, packages/umi/src/scripts/dev.js
=> fix: ui task args bug

packages/umi-plugin-ui/src/plugins/configuration/ui.tsx, packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts, packages/umi-plugin-ui/src/plugins/dashboard/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/dashboard/ui.tsx, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/components/Field/Any.tsx, packages/umi-ui/package.json, packages/umi-ui/src/UmiUI.ts
=> feat(Umi UI): launch editor use @umijs/launch-editor

packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Block.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Flow.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Logger.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_update.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/util/exec.ts
=> feat: ui tasks add execa log

packages/umi-build-dev/src/plugins/commands/block/ui/ui/BlockList/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.tsx
=> feat: support search highlight

netlify.toml, scripts/antd-pro.sh
=> chore: pro pre umi netlify config

docs/plugin/umi-ui.md, docs/zh/plugin/umi-ui.md, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx, packages/umi-types/package.json, packages/umi-types/ui.d.ts, packages/umi-types/yarn.lock, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/components/Terminal/index.tsx, packages/umi-ui/client/src/pages/loading/index.tsx, packages/umi-ui/client/src/pages/project/components/progress/index.tsx
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-api-Terminal/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-api-Terminal/docs/zh/plugin/umi-ui.md)
=> feat(Umi UI): api.Terminal

packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Flow.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/types/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/util/exec.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/LogPanel/index.tsx
=> feat: ui blocks cancel task

packages/umi-build-dev/src/plugins/commands/block/installDependencies.js, packages/umi-build-dev/src/plugins/commands/block/ui/server/util/exec.ts
=> fix: fix npm install args and execa buffer to false

packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Flow.ts
=> refactor: blocks server log

packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Flow.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Logger.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_update.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/parse_url.ts
- any feature?
-----
[View rendered CONTRIBUTING.md](https://github.com/umijs/umi/blob/blocksServer/CONTRIBUTING.md)
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/blocksServer/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/blocksServer/docs/zh/plugin/umi-ui.md)
=> Blocks server

scripts/publish.js
=> chore: check ui umd file existed

packages/umi-ui-tasks/src/server/util/stats.ts, packages/umi-ui-tasks/src/ui/components/Analyze/index.module.less, packages/umi-ui-tasks/src/ui/components/Analyze/index.tsx, packages/umi-ui-tasks/src/ui/components/Build/index.tsx, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui-tasks/src/ui/model/index.ts
=> feat: ui task view add reload

packages/umi-build-dev/src/routes/getRouteConfigFromDir.js, packages/umi-build-dev/src/routes/getYamlConfig.js, packages/umi-build-dev/src/routes/getYamlConfig.test.js
- 优化page annotation错误提示，方便开发者更容易找到自己注解不合法的位置
如图：`/data/test.js`就是写了错误注解的代码位置
=> refactor: enhance annotation parsing trouble shooting

docs/api/README.md, docs/zh/api/README.md
- detailed usage about locales
-----
[View rendered docs/api/README.md](https://github.com/leftstick/umi/blob/master/docs/api/README.md)
[View rendered docs/zh/api/README.md](https://github.com/leftstick/umi/blob/master/docs/zh/api/README.md)
=> docs: detail usage about locales

packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/Service.test.js
=> feat: depth first init plugins

docs/plugin/umi-ui.md, docs/zh/plugin/umi-ui.md, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/components/ConfigForm/index.tsx, packages/umi-ui/client/src/components/Field/Boolean.tsx, packages/umi-ui/client/src/components/Field/List.tsx, packages/umi-ui/client/src/components/Field/Object.tsx, packages/umi-ui/client/src/components/Field/String.tsx, packages/umi-ui/client/src/components/Field/StringArray.tsx, packages/umi-ui/client/src/components/Field/TextArea.tsx, packages/umi-ui/client/src/components/Field/fields/ObjectField.tsx, packages/umi-ui/client/src/components/Field/fields/ObjectItemField.tsx, packages/umi-ui/client/src/components/Field/index.tsx
- any feature?
-----
[View rendered docs/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-fieldForm-size-mini/docs/plugin/umi-ui.md)
[View rendered docs/zh/plugin/umi-ui.md](https://github.com/umijs/umi/blob/feat-fieldForm-size-mini/docs/zh/plugin/umi-ui.md)
=> feat(Umi UI): Field form size in Mini

packages/umi-ui-tasks/package.json, packages/umi-ui-tasks/src/server/core/TaskManger.ts, packages/umi-ui-tasks/src/server/index.ts, packages/umi-ui-tasks/src/server/util/stats.ts
=> feat: umi ui tasks, dev server alive

packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx, packages/umi-ui/client/src/layouts/Dashboard.tsx, packages/umi-ui/client/src/utils/index.tsx
=> fix(Umi UI): remove locale error message

packages/umi-build-dev/src/plugins/commands/.eslintrc.js, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Block.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Flow.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/enum/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_update.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/types/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/util/index.ts
=> feat: ui block 增加 retry

packages/umi-ui-tasks/src/ui/components/Analyze/index.module.less, packages/umi-ui-tasks/src/ui/components/Analyze/index.tsx
=> Task view empry

packages/umi-ui-tasks/src/server/core/Tasks/Build.ts
webpack stats 的获取增加 cache，会快很多
=> feat: ui task stats cache

packages/umi-ui/client/.umirc.ts, packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/proxyConsole.ts
Clear console logs in mini, using `debug=umiui:log` in `localStorage` to enable console
- any feature?
=> tweak(Umi UI): clear console in mini env

packages/umi-build-dev/src/plugins/commands/block/ui/ui/Adder/index.tsx, packages/umi-plugin-ui/src/bubble/Bubble.jsx, packages/umi-plugin-ui/src/bubble/Dragger/index.jsx, packages/umi-plugin-ui/src/bubble/Tooltip.jsx, packages/umi-plugin-ui/src/bubble/bubble-locale/en-US.js, packages/umi-plugin-ui/src/bubble/bubble-locale/pt-BR.js, packages/umi-plugin-ui/src/bubble/bubble-locale/zh-CN.js, packages/umi-plugin-ui/src/bubble/bubble-locale/zh-TW.js, packages/umi-plugin-ui/src/bubble/utils.js, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx, packages/umi-ui/client/src/components/TwoColumnPanel/index.less, packages/umi-ui/client/src/layouts/Dashboard.less
=> tweak(Umi UI): bubble tooltip in umi ui mini

packages/umi-ui-tasks/src/locales/en-US.js, packages/umi-ui-tasks/src/locales/zh-CN.js, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
=> feat: task ui 增加 umi ui 环境变量

packages/umi-ui-tasks/src/server/util/index.ts
=> No ipc default

packages/umi-ui-tasks/src/server/util/index.ts, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
=> Windows runscript

packages/umi-build-dev/src/plugins/commands/block/ui/ui/BlockList/getInsertPosition.tsx, packages/umi-plugin-ui/src/bubble/Bubble.jsx, packages/umi-plugin-ui/src/bubble/Dragger/index.jsx, packages/umi-plugin-ui/src/bubble/index.jsx
=> feat(umi-ui): show cancel Text in mini block edit env

packages/umi-plugin-ui/src/bubble/Dragger/index.jsx, packages/umi-plugin-ui/src/bubble/utils.js
=> fix(Umi UI): bubble style and scrollSize compute

packages/umi-ui-tasks/src/server/util/index.ts
=> fix(umi-ui): task parse script error

packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/run_generator.ts
区块应该讲 blockName 配上去
- any feature?
=> fix(umi ui): block add path

packages/umi-plugin-ui/src/bubble/Dragger/index.jsx, packages/umi-plugin-ui/src/bubble/Tooltip.jsx
=> chore: bubble transition, helpDoc

docs/plugin/umi-ui.md, docs/zh/plugin/umi-ui.md, packages/umi-ui/client/src/components/ConfigForm/index.tsx, packages/umi-ui/client/src/proxyConsole.ts
=> Fix mini debug conflict & ConfigForm value reset 

packages/umi-ui/client/src/layouts/Dashboard.tsx
=> fix(umi-ui): set active project when open full umi ui

packages/umi-ui/client/src/pages/project/components/list/index.less
=> fix(Umi UI): umi ui dashboard title overflow

packages/umi-plugin-react/ui/index.js
=> chore(umi-plugin-react): update ui icon for umi-plugin-react config

packages/umi-plugin-ui/package.json, packages/umi-plugin-ui/yarn.lock, packages/umi-ui-tasks/package.json
UI 插件在发布前会走编译，打成 umd 发到 npm 上，所以与 UI 相关的三方包全写在 devDeps ，避免用户安装不必要依赖。
- any feature?
=> fix(Umi UI): ui deps and devDeps

packages/umi-ui/src/detectNpmClients.ts
=> fix(umi-ui): .yarn-integrity must exists for yarn in npmClient detect

docs/guide/develop-umi-ui-plugin.md, docs/zh/guide/develop-umi-ui-plugin.md
- any feature?
-----
[View rendered docs/guide/develop-umi-ui-plugin.md](https://github.com/umijs/umi/blob/docs-ui-plugin-dev/docs/guide/develop-umi-ui-plugin.md)
[View rendered docs/zh/guide/develop-umi-ui-plugin.md](https://github.com/umijs/umi/blob/docs-ui-plugin-dev/docs/zh/guide/develop-umi-ui-plugin.md)
=> docs: Umi UI plugin deps docs

packages/umi/src/isUmiUIEnable.js
=> fix: disable dev ui mini in ssr

packages/umi-build-dev/src/plugins/commands/block/ui/index.ts
=> fix(umi-test): umi test failed

packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts
=> fix(umi-ui): dva detection failed in bigfish

packages/umi-plugin-ui/src/bubble/index.jsx
=> fix: Umi mini url using host not domain in iframe

packages/umi-ui/src/detectLanguage.ts
=> feat(umi-ui): allow to specify detect language with DETECT_LANGUAGE env

packages/umi-plugin-ui/src/bubble/Error.jsx, packages/umi-plugin-ui/src/bubble/bubble-locale/en-US.js, packages/umi-plugin-ui/src/bubble/bubble-locale/pt-BR.js, packages/umi-plugin-ui/src/bubble/bubble-locale/zh-CN.js, packages/umi-plugin-ui/src/bubble/bubble-locale/zh-TW.js, packages/umi-plugin-ui/src/bubble/index.jsx
=> tweak: mini tips when access using remote ip

packages/umi-build-dev/src/plugins/commands/block/sdk/util.ts
=> fix(umi-ui): don't throw error if return statement not found

packages/umi-build-dev/src/plugins/commands/block/typings.d.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/Adder/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/BlockList/BlockItem.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/BlockList/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/ui/model/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/search.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/uiUtil.ts, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/PluginAPI.ts
```js
api._analyze(({ gtag, Tracert, ga }) => {
// recommend gtag rather than ga
gtag('event', 'play', {
'event_category': 'Videos',
'event_label': 'Fall Campaign'
});
// if in Umi, Tracert will not log
Tracert.logPv()
})
```
- any feature?
=> feat(umi-ui): api._analyze for event log

packages/umi-build-dev/src/plugins/commands/block/ui/ui/Adder/ResultPanel.tsx
删除预览按钮，等准确判断服务是否启动再加入
- any feature?
=> chore(umi-ui): remove preview button

azure-pipelines.yml, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.test.ts, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.test.ts, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/utils/index.tsx, packages/umi-ui/src/Config.test.ts, packages/umi/test/build.e2e.ts, packages/umi/test/dev.e2e.js, packages/umi/test/ui.e2e.ts
=> tweak: umi ui code format & windows ci

packages/umi-build-dev/src/plugins/commands/block/__snapshots__/util.test.ts.snap, packages/umi-build-dev/src/plugins/commands/block/arrayToTree.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Block.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts, packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.module.less, packages/umi-build-dev/src/plugins/commands/block/util.test.ts, packages/umi-build-dev/src/plugins/commands/block/util.ts, packages/umi-build-dev/src/plugins/fixtures/util/routerConfig.js
更换了新的算法，速度更快效果更好。
修复了 compentent 配置为不存在时路径时报错的问题。
- any feature?
=> feat(umi-ui): better router get

.gitignore, packages/umi-ui/client/.umirc.ts, packages/umi-ui/client/src/typings/exclude.d.ts
=> tweak: umi ui css modules types

packages/umi-ui/client/src/PluginAPI.ts
=> fix: umi ui showMini,hideMini api condition

packages/af-webpack/package.json, packages/af-webpack/yarn.lock
=> dep: revert webpack-dev-server to 3.2.1

packages/umi-core/src/registerBabel.ts
=> fix: get config failed with UMI_ENV and .umirc.{UMI_ENV}.js

scripts/ui.js
插件构建走串行，插件构建 + BaseUI 构建走并行，减少构建时间。
- any feature?
=> chore: ui build script OOM

packages/umi-plugin-ui/yarn.lock, packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/layouts/Layout.tsx, packages/umi-ui/client/src/pages/loading/index.tsx, packages/umi-ui/client/src/services/project.ts, packages/umi-ui/client/src/utils/index.tsx, packages/umi-ui/src/Config.ts, packages/umi-ui/src/UmiUI.ts
修复：
1. 出错项目无法回退至 `/project/list` 项目列表页
2. loading 页国际化问题
1. 项目出错路由 `/error?key={key}`
1. code format
- any feature?
=> fix(umi-ui): loading page error

packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
=> fix(umi-ui): error message is readOnly object

packages/umi-ui/client/src/app.ts, packages/umi-ui/src/Config.ts, packages/umi-ui/src/UmiUI.ts
=> fix(umi-ui): check valid before list project

jest.config.js, package.json, packages/af-webpack/src/patchConnection.js, packages/umi-build-dev/.fatherrc.js, packages/umi-plugin-ui/.fatherrc.js, packages/umi-ui-tasks/.fatherrc.js, yarn.lock
- close https://github.com/umijs/umi/issues/3445
- close https://github.com/umijs/es5-imcompatible-versions/pull/47
=> fix(umi-ui): bubble syntax error in IE

packages/umi-ui/client/src/layouts/Footer.tsx
=> docs(umi-ui): fix bigfish help doc link

packages/umi-plugin-ui/.fatherrc.js, packages/umi-plugin-ui/src/index.ts
=> fix(umi-ui): don't show umi ui bubble in IE

packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-card/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-card/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-step/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-step/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-PageContainer/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-PageContainer/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-StepForm/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-StepForm/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
- antd 和 tech-ui 的非布局组件不添加 Umi UI 区块的插入节点
- Close #3446
=> fix(umi-ui): add blacklist root node including antd and tech-ui

docs/zh/config/README.md
- Fix minor formatting errors
-----
[View rendered docs/zh/config/README.md](https://github.com/FatDoge/umi/blob/patch-1/docs/zh/config/README.md)
=> docs: minor formatting errors

packages/umi-plugin-ui/src/bubble/utils.js
=> fix(umi-plugin-ui): bubble client height 0 when body, html not set

packages/umi-build-dev/src/plugins/afwebpack-config/index.js
=> fix: extraBabelIncludes merge problem between config and plugin

packages/af-webpack/src/registerBabel.js, packages/umi-server/test/index.test.ts, packages/umi-test/src/index.js
=> WIP: fix(umi-test): modify NODE_ENV to test

packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-not-import/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-not-import/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
=> fix(umi-ui): fix source undefined in flagBabelPlugin

packages/umi-build-dev/src/getWebpackConfig.ts
Before `umi.server.js` :
After:
- any feature?
=> fix: ssr build target should using node env

docs/zh/guide/examples.md
修改社区例子提交作者的个人介绍网站链接
- any feature?
-----
[View rendered docs/zh/guide/examples.md](https://github.com/hqwlkj/umi/blob/patch-2/docs/zh/guide/examples.md)
=> doc: 添加社区例子 umi-dva-antd-mobile

packages/umi-ui/src/UmiUI.ts
=> feat: umi ui app data, cloud url

packages/umi-types/package.json
=> fix: umi-types xterm types 

packages/umi-build-dev/src/plugins/history.js, packages/umi/src/createHistory.js
=> feat: use esm version of history

packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
=> fix(umi-ui): usage of @alipay/bigfish/antd

packages/umi-ui/src/getClientScript.ts
Before,  plugins would be executed after the wrong plugin.
After,
- any feature?
=> fix(umi-ui): plugin exec error hanlder

packages/af-webpack/yarn.lock, packages/umi-plugin-dva/package.json, packages/umi-plugin-dva/yarn.lock, packages/umi-ui/client/yarn.lock, packages/umi-ui/src/getClientScript.test.ts, packages/umi-ui/yarn.lock
=> dep(umi-plugin-dva): upgrade to ^2.6.0-beta.16

packages/umi-build-dev/template/router.js.tpl
=> fix: onRouteChange execute multiple times when dva is enabled

packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
=> fix: give getBasicUI default Value

docs/guide/ssr.md, docs/zh/guide/ssr.md
- any feature?
-----
[View rendered docs/guide/ssr.md](https://github.com/umijs/umi/blob/docs-ssr-spa/docs/guide/ssr.md)
[View rendered docs/zh/guide/ssr.md](https://github.com/umijs/umi/blob/docs-ssr-spa/docs/zh/guide/ssr.md)
=> doc: the difference between SPA and SSR site in SEO

docs/plugin/umi-plugin-react.md, docs/zh/plugin/umi-plugin-react.md
- any feature?
-----
[View rendered docs/plugin/umi-plugin-react.md](https://github.com/umijs/umi/blob/docs-mobile/docs/plugin/umi-plugin-react.md)
[View rendered docs/zh/plugin/umi-plugin-react.md](https://github.com/umijs/umi/blob/docs-mobile/docs/zh/plugin/umi-plugin-react.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3567)
=> docs: hd fastclick docs

packages/umi-build-dev/src/Service.js
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3570)
=> chore: plugin error console when load failed

docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/src/PluginAPI.js, packages/umi/src/scripts/realDev.js
- umi plugin 添加onExit事件 补全目前插件对退出生命周期的缺失
-----
[View rendered docs/plugin/develop.md](https://github.com/karzanOnline/umi/blob/plugin-life-cycle/docs/plugin/develop.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3571)
=> feat(plugin): add api.onExit

packages/umi-ui/src/UmiUI.ts
- close #3534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3581)
=> fix(umi-ui): UMI_UI_PORT env don't work

packages/umi-build-dev/.npmignore, packages/umi-build-dev/src/plugins/commands/__snapshots__/replaceChunkMaps.test.js.snap, packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.test.js, packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.ts
修复 `umi.css` 不存在时，页面的空请求
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3573)
=> fix: ssr render bug when umi.css not exist

packages/af-webpack/package.json, packages/af-webpack/yarn.lock, packages/umi-plugin-dva/yarn.lock, packages/umi-test/package.json, packages/umi-test/yarn.lock
- close #3572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3582)
=> dep: upgrade typescript to 3.7

packages/umi-build-dev/src/Service.js
- close #3574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3583)
=> fix(Service): printUmiError defined twice

packages/umi-build-dev/src/plugins/commands/block/index.js, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3596)
=> fix(umi-ui): block add don't work and task env problem

packages/umi-ui/src/scripts.ts
=> fix(umi-ui): deer log bug

docs/plugin/develop.md, docs/zh/plugin/develop.md, packages/umi-build-dev/src/PluginAPI.js, packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js, packages/umi-types/index.d.ts
null
-----
[View rendered docs/plugin/develop.md](https://github.com/umijs/umi/blob/faeture/midifyPublicPathStr/docs/plugin/develop.md)
[View rendered docs/zh/plugin/develop.md](https://github.com/umijs/umi/blob/faeture/midifyPublicPathStr/docs/zh/plugin/develop.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/3611)
=> feat(plugin): add modifyPublicPathStr api

packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/components/StepForm/StepForm.tsx, packages/umi-ui/client/src/components/StepForm/StepItem.tsx, packages/umi-ui/src/UmiUI.ts
=> feat(UmiUI): bigfish ui extend

packages/umi-ui/client/src/utils/index.tsx
=> Bigfish ui extend

packages/umi-plugin-ui/src/plugins/dashboard/index.ts, packages/umi-plugin-ui/src/plugins/dashboard/ui/layout.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/setting.tsx
=> feat(umi-ui-plugin): support dashboard cards enable order

packages/umi-ui-tasks/src/server/core/TaskManger.ts, packages/umi-ui-tasks/src/server/core/Tasks/Base.ts, packages/umi-ui-tasks/src/server/index.ts, packages/umi-ui-tasks/src/ui/components/Build/index.tsx, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui-tasks/src/ui/components/Install/index.tsx, packages/umi-ui-tasks/src/ui/components/Lint/index.tsx, packages/umi-ui-tasks/src/ui/components/Test/index.tsx, packages/umi-ui-tasks/src/ui/model/index.ts, packages/umi-ui-tasks/src/ui/util/terminal.ts
close https://github.com/umijs/umi/issues/3593
- any feature?
- close https://github.com/umijs/umi/issues/3593
=> fix(umi-ui): umi ui ternmial log use multi instance

packages/umi-plugin-ui/src/plugins/dashboard/index.ts
=> fix: dashboard zaobao api use CDN

packages/umi-ui/src/UmiUI.ts
=> fix: ui version compare

packages/umi-ui/client/src/components/Shell/index.tsx, packages/umi-ui/client/src/components/Terminal/index.tsx, packages/umi-ui/src/UmiUI.ts, packages/umi-ui/src/terminal.ts
=> fix(umi-ui): terminal socket init when app start

docs/guide/faq.md, docs/zh/guide/faq.md, packages/umi-plugin-ui/src/plugins/dashboard/index.ts, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.tsx, packages/umi-ui/src/UmiUI.ts
=> fix: umi bigfish ui version check, jsdelivr use latest

packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts, packages/umi-plugin-ui/src/plugins/dashboard/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/dashboard/ui.tsx
=> chore: improve umi ui

docs/guide/faq.md, docs/zh/guide/faq.md, packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/index.tsx, packages/umi-plugin-ui/package.json, packages/umi-plugin-ui/src/bubble/Bubble.jsx, packages/umi-plugin-ui/src/bubble/Logo.jsx, packages/umi-plugin-ui/src/plugins/configuration/locales/en-US.ts, packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts, packages/umi-plugin-ui/src/plugins/dashboard/ui/action.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/setting.module.less, packages/umi-plugin-ui/src/plugins/dashboard/ui/setting.tsx, packages/umi-types/ui.d.ts, packages/umi-ui-tasks/src/ui.tsx, packages/umi-ui-tasks/src/ui/components/Build/index.tsx, packages/umi-ui-tasks/src/ui/components/Dev/index.tsx, packages/umi-ui-tasks/src/ui/components/Lint/index.tsx, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx, packages/umi-ui/client/src/getAnalyze.ts, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/layouts/Layout.tsx, packages/umi-ui/client/src/pages/loading/actions/openFile.tsx, packages/umi-ui/package.json, scripts/antd-pro.sh
- any feature?
-----
[View rendered docs/guide/faq.md](https://github.com/umijs/umi/blob/fix-ui-title-undefined/docs/guide/faq.md)
[View rendered docs/zh/guide/faq.md](https://github.com/umijs/umi/blob/fix-ui-title-undefined/docs/zh/guide/faq.md)
=> fix: ui title undefined, error page, auto exec in task page, analyze

packages/umi-ui/client/src/components/Shell/index.tsx
=> fix(umi-ui): terminal focus when visible

packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/Foo.js, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/config.json, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/expected.js, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/origin.js, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.test.ts, packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.ts, packages/umi-build-dev/src/plugins/commands/block/sdk/util.ts, packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/AddBlockFormForUI.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/write_routes.ts
之前，
```
+ pages
+ LayoutBlock
+ Block1
+ Block2
- index.js
```
之后，
```
+ pages
+ Block1
+ Block2
- index.js（包含 LayoutBlock）
```
=> feat(block): extract block content when adding layout block

packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.module.less, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReportTitle.tsx, packages/umi-ui-theme/dark.less, packages/umi-ui-theme/test/index.test.ts
=> fix: ui modal zIndex & dashboard card paragraph

packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less
=> fix: umi-ui dashboard welcome card style

packages/umi-plugin-ui/src/plugins/dashboard/index.ts
jsdelivr@latest 有缓存，发了 Purge cache email 邮件还没回复，先用 `unpkg` 吧
- any feature?
=> fix: rss ui cache

packages/umi-ui/client/src/pages/project/components/create/Form2.tsx, packages/umi-ui/client/src/pages/project/components/create/index.less
=> fix: ui question tooltip color

packages/umi-ui/client/src/components/Shell/index.tsx
=> fix: shell socket ins reset

docs/guide/router.md, docs/zh/guide/router.md
1. breakcrumb.js corrected to breadcrumb.js
- any feature?
- close https://github.com/umijs/umi/issues/3604
-----
[View rendered docs/guide/router.md](https://github.com/stxwd46/umi/blob/doc-correct-typos/docs/guide/router.md)
[View rendered docs/zh/guide/router.md](https://github.com/stxwd46/umi/blob/doc-correct-typos/docs/zh/guide/router.md)
=> docs: correct the typo

packages/umi-ui-tasks/src/ui.tsx
=> fix: dev task not display in mini

packages/umi-build-dev/src/plugins/commands/block/ui/client/BlockList/index.tsx
=> fix(umi-ui): pagination problem when change category

packages/umi-plugin-dll/src/index.js
=> fix(umi-plugin-dll): cache path when APP_ROOT is set

packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.module.less, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.tsx
=> fix: Dashboard card ellipsis in Firefox

packages/umi-build-dev/template/entry.js.tpl
Close #3677
Close https://github.com/umijs/umi-server/issues/35
Close https://github.com/umijs/umi-example-ssr-with-egg/issues/24
- any feature?
=> fix: ssr server render history object oom

packages/umi-build-dev/src/html/HTMLGenerator.js, packages/umi-build-dev/src/html/HTMLGenerator.test.js, packages/umi-build-dev/src/html/fixtures/document-partial.ejs, packages/umi-build-dev/src/html/fixtures/document-with-include.ejs
https://www.npmjs.com/package/ejs#options  document.ejs 文件使用 include 依赖 filename 参数
=> feat: enable ejs include api

packages/umi-ui/client/.umirc.ts
=> fix: umi-ui antd version

packages/umi-ui/src/Config.test.ts, packages/umi-ui/src/Config.ts, packages/umi-ui/src/fixtures/Config/illegal.json
=> fix: umi-ui data parse error

packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
=> fix: ignore *.d.ts in convensional routes

README.md, README_zh-CN.md
- any feature?
-----
[View rendered README.md](https://github.com/ts-react/umi/blob/master/README.md)
[View rendered README_zh-CN.md](https://github.com/ts-react/umi/blob/master/README_zh-CN.md)
=> fix: 修复lerna官网链接错误

packages/af-webpack/src/build.js
=> fix(af-webpack): stats undefined when have error

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/src/plugins/afwebpack-config/index.js, packages/umi-build-dev/template/entry.js.tpl, packages/umi-build-dev/template/router.js.tpl, packages/umi/.fatherrc.js, packages/umi/index.d.ts, packages/umi/src/index.js, packages/umi/src/router.js
- 兼容 `@tmp`，umi@3 再移除 `@tmp`  的支持
=> feat: use @@ instead of @tmp

packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/org.umi.block.checkIfCanAdd.ts
=> fix: bigfish ui locale error when add template

docs/zh/api/README.md
Fix wrong syntax in example code.
- any feature?
-----
[View rendered docs/zh/api/README.md](https://github.com/minazukie/umi/blob/patch-1/docs/zh/api/README.md)
=> Remove extra parentheses

packages/umi/src/renderRoutes.js
- any feature?
修改onpopstate的绑定方式，防止覆盖三方库已有的onpopstate回调
=> fix: 修复绑定onpopstate与三方库已有方法冲突

packages/af-webpack/package.json
… rejection
- any feature?
- close #3738
=> dep: upgrade fork-ts-checker-webpack-plugin to fix Unhandled promise rejection

packages/umi-ui-tasks/package.json, packages/umi-ui-tasks/src/server/util/index.ts
Close https://github.com/umijs/umi/issues/3747
- any feature?
=> fix: umi-ui-tasks spawn error in windows

packages/umi-build-dev/package.json, packages/umi-build-dev/template/entry.js.tpl, packages/umi-ui/package.json, packages/umi/package.json
=> fix: ssr location object

packages/umi-build-dev/src/routes/routesToJSON.js, packages/umi-build-dev/src/utils/getChunkMap.test.js, packages/umi-build-dev/src/utils/getChunkMap.ts, packages/umi/test/fixtures/build/umi-plugin-react/pages/$user.js, packages/umi/test/fixtures/build/umi-plugin-react/test.js
=> fix: $ should not appear in prod file name

packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/GUmiUIFlag.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/client/BlockList/getInsertPosition.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/index.ts
Close https://github.com/ant-design/ant-design-pro/issues/5728.
- any feature?
=> fix: GUmiUIFlag Component show in open Umi UI

package.json, packages/umi-ui-tasks/src/package.json, packages/umi/package.json
=> fix: react-router-dom and react types version

packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/index.test.ts, packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/org.umi.block.checkIfCanAdd.ts
=> fix: ui block locale add check

packages/umi/src/buildDevOpts.js, packages/umi/src/buildDevOpts.test.js, packages/umi/src/fixtures/buildDevOpts/.env, packages/umi/src/fixtures/buildDevOpts/.env.local
=> fix: .env and .env.local priority

package.json, packages/umi-types/ui.d.ts, packages/umi-ui/client/.umirc.ts, packages/umi-ui/client/src/PluginAPI.ts, packages/umi-ui/client/src/app.ts, packages/umi-ui/client/src/components/ErrorBoundary/index.tsx, packages/umi-ui/client/src/components/Terminal/index.tsx, packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx, packages/umi-ui/client/src/layouts/BetaPlugin.tsx, packages/umi-ui/client/src/layouts/Dashboard.less, packages/umi-ui/client/src/layouts/Dashboard.tsx, packages/umi-ui/client/src/layouts/Footer.tsx, packages/umi-ui/client/src/pages/loading/index.tsx, packages/umi-ui/client/src/pages/project/components/list/index.tsx, packages/umi-ui/client/src/pages/project/components/progress/index.tsx, packages/umi-ui/client/src/utils/index.tsx
扩展 侧边 菜单位置，用于内部 BUC 登录用户信息展示
Bigfish 层使用见 https://github.com/umijs/umi/pull/3489#issue-330918227
- any feature?
=> feat: extend ui sider footer

packages/umi-build-dev/package.json, packages/umi-build-dev/src/plugins/commands/block/download.js
=> fix: umi ui block download spawn in windows

packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
=> feat(umi-ui): don't show welcome card in dashboard

.gitignore, packages/umi-plugin-ui/package.json
很多 fixtures 发到 npm 了
- any feature?
=> chore(umi-ui): exclude fixtures directory to npm package

packages/umi-ui/client/src/layouts/Dashboard.less, packages/umi-ui/client/src/layouts/Dashboard.tsx
1. Header 没有 `title` 和 `actions` 时，直接隐藏 Header，用于 iframe 嵌入场景。
1. 侧边栏 icon 不 `selected` 时，给灰色。
- any feature?
=> fix: umi-ui header

docs/guide/umi-ui.md, docs/zh/guide/umi-ui.md
- any feature?
-----
[View rendered docs/guide/umi-ui.md](https://github.com/umijs/umi/blob/docs-ui/docs/guide/umi-ui.md)
[View rendered docs/zh/guide/umi-ui.md](https://github.com/umijs/umi/blob/docs-ui/docs/zh/guide/umi-ui.md)
=> docs: umi ui docs

packages/af-webpack/yarn.lock, packages/umi-build-dev/src/Service.js, packages/umi-build-dev/src/Service.test.js, packages/umi-build-dev/src/fixtures/Service/get-routes-components/.umirc.js, packages/umi-build-dev/src/fixtures/Service/get-routes-components/src/pages/index.js, packages/umi-build-dev/src/fixtures/Service/get-routes-components/src/pages/news.js, packages/umi-build-dev/src/plugins/commands/block/ui/index.ts, packages/umi-build-dev/yarn.lock, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less, packages/umi-types/index.d.ts, packages/umi/yarn.lock, yarn.lock
Close https://github.com/umijs/umi/issues/3836.
- any feature?
=> fix: api.getRouteComponents bug

docs/guide/router.md, docs/zh/guide/router.md
-----
[View rendered docs/guide/router.md](https://github.com/baijunyao/umi/blob/master/docs/guide/router.md)
[View rendered docs/zh/guide/router.md](https://github.com/baijunyao/umi/blob/master/docs/zh/guide/router.md)
=> docs: Update config URL in the router.md

docs/api/README.md, docs/zh/api/README.md
Close #3833.
- any feature?
-----
[View rendered docs/api/README.md](https://github.com/umijs/umi/blob/fix-locale-doc/docs/api/README.md)
[View rendered docs/zh/api/README.md](https://github.com/umijs/umi/blob/fix-locale-doc/docs/zh/api/README.md)
=> docs: locale doc

packages/umi-ui-theme/dark.less, packages/umi-ui-theme/test/index.test.ts
Table/Collapse header background color
- any feature?
=> fix: Umi UI header theme style 

packages/umi-plugin-locale/README.md, packages/umi-plugin-locale/examples/multiple-ext/config/config.js, packages/umi-plugin-locale/examples/multiple-ext/package.json, packages/umi-plugin-locale/examples/multiple-ext/src/app.js, packages/umi-plugin-locale/examples/multiple-ext/src/locale/en-US.js, packages/umi-plugin-locale/examples/multiple-ext/src/locale/sk.json, packages/umi-plugin-locale/examples/multiple-ext/src/locale/zh-CN.ts, packages/umi-plugin-locale/examples/multiple-ext/src/page/index.js, packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/index.js, packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/en-US.js, packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/sk.json, packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/zh-CN.ts, packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/model.js, packages/umi-plugin-locale/src/index.js, packages/umi-plugin-locale/test/index.test.js
- Support json locale resources
```
.
├── dist/
├── mock/
└── src/
├── layouts/index.js
├── pages/
└── locales               // 支持 json 格式的国际化文件
├── zh-CN.json
└── en-US.json
├── .umirc.js
├── .env
└── package.json
```
=> feat: locale plugin support .json files

packages/umi/router.d.ts, packages/umi/src/utils.js
- close https://github.com/umijs/umi/issues/3811
=> fix: router type

docs/guide/develop-umi-ui-plugin.md, docs/zh/guide/develop-umi-ui-plugin.md, packages/umi-build-dev/src/plugins/commands/block/ui/client/GlobalSearch.tsx, packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less, packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.module.less, yarn.lock
- any feature?
-----
[View rendered docs/guide/develop-umi-ui-plugin.md](https://github.com/umijs/umi/blob/fix-ui-hooks-compat/docs/guide/develop-umi-ui-plugin.md)
[View rendered docs/zh/guide/develop-umi-ui-plugin.md](https://github.com/umijs/umi/blob/fix-ui-hooks-compat/docs/zh/guide/develop-umi-ui-plugin.md)
=> fix: ui hooks compat

packages/umi-plugin-ui/src/bubble/Bubble.jsx, packages/umi-plugin-ui/src/bubble/Dragger/index.jsx, packages/umi-plugin-ui/src/bubble/Modal.jsx
styled-components 多实例冲突问题：https://www.styled-components.com/docs/advanced#avoiding-conflicts-with-thirdparty-styles-and-scripts
- any feature?
=> fix: umi ui bubble conflict

packages/af-webpack/src/dev.js, packages/umi-build-dev/src/plugins/commands/dev/index.js
- As commit message describes.
=> feat: expose "urls" on "onDevCompileDone" hook.

packages/babel-preset-umi/src/index.test.js, packages/babel-preset-umi/yarn.lock, packages/umi-plugin-ui/src/bubble/Bubble.jsx, packages/umi-types/ui.d.ts, packages/umi-ui/client/src/PluginAPI.ts, packages/umi/src/babel.test.js, packages/umi/yarn.lock
=> fix: ui bubble line-heigth and add umi-request api

packages/umi-ui-theme/dark.less, packages/umi-ui-theme/test/index.test.ts
=> fix: ui dark theme var

package.json, packages/umi-build-dev/src/plugins/commands/block/ui/.fatherrc.js, packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/index.tsx, packages/umi-build-dev/src/plugins/commands/block/ui/client/locales/en-US.js, packages/umi-build-dev/src/plugins/commands/block/ui/client/locales/zh-CN.js, packages/umi-build-dev/src/plugins/commands/block/ui/package.json, packages/umi-plugin-ui/src/plugins/configuration/.fatherrc.js, packages/umi-plugin-ui/src/plugins/configuration/package.json, packages/umi-plugin-ui/src/plugins/dashboard/.fatherrc.js, packages/umi-plugin-ui/src/plugins/dashboard/package.json, packages/umi-ui-tasks/src/.fatherrc.js, packages/umi-ui-tasks/src/package.json, packages/umi-ui/ui/.fatherrc.ts, packages/umi-ui/ui/package.json, yarn.lock
=> chore: upgrade father-build

packages/umi/package.json
=> fix: umi ui flag ts

packages/umi-ui/client/src/components/Logs/index.tsx
=> fix: ui message group error

packages/umi-ui/client/src/layouts/Layout.tsx
=> fix: umi-ui moment locale

packages/umi-ui/src/UmiUI.ts
=> chore: mini redirect blocks

packages/umi-build-dev/package.json, packages/umi-build-dev/yarn.lock, packages/umi-plugin-react/package.json, packages/umi-plugin-react/yarn.lock, packages/umi/package.json, packages/umi/yarn.lock, scripts/uiPlugins.js
=> chore: upgrade umi ui version

packages/umi-types/index.d.ts, packages/umi-types/package.json, packages/umi-types/ui.d.ts, packages/umi-types/yarn.lock
=> Revert "fix: ui types use @umijs/ui-types"

packages/umi-build-dev/package.json, packages/umi-build-dev/yarn.lock, packages/umi-plugin-react/package.json, packages/umi-plugin-react/yarn.lock, packages/umi/package.json, packages/umi/yarn.lock, scripts/uiPlugins.js
=> Revert "chore: upgrade umi ui version"

docs/guide/pro-migrate.md, docs/guide/pro-migrate.zh-CN.md
-----
[View rendered docs/guide/pro-migrate.md](https://github.com/umijs/umi/blob/docs-pro-migrate/docs/guide/pro-migrate.md)
[View rendered docs/guide/pro-migrate.zh-CN.md](https://github.com/umijs/umi/blob/docs-pro-migrate/docs/guide/pro-migrate.zh-CN.md)
=> docs: migrate pro

docs/docs/how-umi-works.md
【完整】 80% 的日常工作 => 【完成】 80% 的日常工作
- any feature?
-----
[View rendered docs/docs/how-umi-works.md](https://github.com/sphawkcn/umi/blob/patch-1/docs/docs/how-umi-works.md)
=> how-umi-works【完整】 => 【完成】

docs/plugins/plugin-request.md, docs/plugins/plugin-request.zh-CN.md
- any feature?
-----
[View rendered docs/plugins/plugin-request.md](https://github.com/umijs/umi/blob/fix/umi-hooks-path/docs/plugins/plugin-request.md)
[View rendered docs/plugins/plugin-request.zh-CN.md](https://github.com/umijs/umi/blob/fix/umi-hooks-path/docs/plugins/plugin-request.zh-CN.md)
=> fix: umi hooks path error

docs/docs/README.md
- [ x ] documentation is changed or added
Translate main README intro to umi to EN
-----
[View rendered docs/docs/README.md](https://github.com/kristianmandrup/umi/blob/translate-umi-intro-en/docs/docs/README.md)
=> translate main README - intro to umi

packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/with-query.js, packages/preset-built-in/src/plugins/commands/dev/mock/utils.test.ts, packages/preset-built-in/src/plugins/commands/dev/mock/utils.ts
Close https://github.com/umijs/umi/issues/4048
=> fix: mock with query

packages/preset-built-in/package.json, packages/preset-built-in/src/plugins/commands/dev/mock/utils.test.ts, packages/preset-built-in/src/plugins/commands/dev/mock/utils.ts, yarn.lock
Close https://github.com/umijs/umi/issues/4048.
Ref: https://github.com/umijs/umi/pull/4057
=> fix: mock path match error

packages/create-umi-app/templates/AppGenerator/package.json.tpl
create-umi-app - remove "git add" part from lint-staged configuration in package.json.tpl
(The git add part is not necessary to include in configuration since lint-staged v10)
=> fix(create-umi-app): remove "git add" part from lint-staged configuration in package.json.tpl

docs/docs/directory-structure.md
translate
-----
[View rendered docs/docs/directory-structure.md](https://github.com/leftstick/umi/blob/master/docs/docs/directory-structure.md)
=> docs: translate directory-structure

packages/test/src/createDefaultConfig/createDefaultConfig.test.ts, packages/test/src/createDefaultConfig/createDefaultConfig.ts
=> feat: read process.env.MAX_WORKERS as jest args maxWorkers

docs/docs/load-on-demand.md, scripts/docs.js
translate `load-on-demand.md`
-----
[View rendered docs/docs/load-on-demand.md](https://github.com/leftstick/umi/blob/master/docs/docs/load-on-demand.md)
=> docs: translate load-on-demand

packages/babel-preset-umi/dependency.js, packages/babel-preset-umi/node.js
=> fix: babel register node opts lost

docs/config/README.md, docs/config/README.zh-CN.md, packages/bundler-webpack/src/getConfig/css.ts, packages/preset-built-in/src/index.ts, packages/preset-built-in/src/plugins/features/postcssLoader.ts, packages/types/index.d.ts
- any feature?
- close #4112
-----
[View rendered docs/config/README.md](https://github.com/chenos/umi/blob/master/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/chenos/umi/blob/master/docs/config/README.zh-CN.md)
=> feat: Additional configuration items for postcss loader

packages/bundler-webpack/src/getConfig/getConfig.ts
=> tweak: bundler exclude antd icons

packages/umi-test/src/index.js
=> feat: read proces.env.MAX_WORKERS as jest args maxWorkers

packages/ast/src/getExportProps/getExportProps.test.ts, packages/ast/src/getExportProps/getExportProps.ts
=> fix: only export the default export's props

azure-pipelines.yml, circle.yml, packages/umi/yarn.lock, yarn.lock
=> fix: 2.x ci

docs/docs/assets-image.zh-CN.md
- any feature?
-----
[View rendered docs/docs/assets-image.zh-CN.md](https://github.com/umijs/umi/blob/xiaohuoni-patch-1/docs/docs/assets-image.zh-CN.md)
=> fix: 修复链接🔗

packages/preset-built-in/src/plugins/generateFiles/core/history.tpl, packages/preset-built-in/src/plugins/generateFiles/core/history.ts
ref https://github.com/umijs/umi/pull/4143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/4145)
=> feat(history): support dynamic setting history options for qiankun scenario

docs/plugins/plugin-dva.zh-CN.md
- any feature?
-----
[View rendered docs/plugins/plugin-dva.zh-CN.md](https://github.com/umijs/umi/blob/xiaohuoni-patch-2/docs/plugins/plugin-dva.zh-CN.md)
=> docs: 增加 dva 类型说明

packages/umi-build-dev/src/plugins/history.js
=> fix: history runtime base

packages/umi/tsconfig.json
Remove duplicated key in packages/umi/tsconfig.json
- any feature?
=> fix: remove duplicated key in tsconfig.json

packages/renderer-react/src/renderRoutes/renderRoutes.tsx
- 修复 wrappers 配置导致多次 render 的问题（有 dva 插件时能轻松复现），例子 https://github.com/exvu/test
- close #4147
- close #4100
- close #4058
=> fix: wrappers render problem

docs/docs/assets-image.md, docs/docs/env-variables.md, docs/docs/env-variables.zh-CN.md, docs/plugins/plugin-dva.md, packages/babel-plugin-lock-core-js-3/README.md, packages/babel-plugin-lock-core-js-3/package.json, packages/babel-plugin-lock-core-js-3/src/index.test.ts, packages/babel-plugin-lock-core-js-3/src/index.ts, packages/babel-preset-umi/app.js, packages/babel-preset-umi/package.json, packages/babel-preset-umi/src/index.ts, packages/preset-built-in/package.json, packages/preset-built-in/src/index.ts, packages/preset-built-in/src/plugins/generateFiles/core/polyfill.tpl, packages/preset-built-in/src/plugins/generateFiles/core/polyfill.ts, yarn.lock
- 添加之前遗漏的补丁方案，并且锁定 core-js 3 的依赖版本
- close #4168
- close #4069
-----
[View rendered docs/docs/assets-image.md](https://github.com/umijs/umi/blob/feat/polyfill/docs/docs/assets-image.md)
[View rendered docs/docs/env-variables.md](https://github.com/umijs/umi/blob/feat/polyfill/docs/docs/env-variables.md)
[View rendered docs/docs/env-variables.zh-CN.md](https://github.com/umijs/umi/blob/feat/polyfill/docs/docs/env-variables.zh-CN.md)
[View rendered docs/plugins/plugin-dva.md](https://github.com/umijs/umi/blob/feat/polyfill/docs/plugins/plugin-dva.md)
[View rendered packages/babel-plugin-lock-core-js-3/README.md](https://github.com/umijs/umi/blob/feat/polyfill/packages/babel-plugin-lock-core-js-3/README.md)
=> feat: polyfill and lock the version of core-js 3

packages/umi-build-dev/template/history.js.tpl
- any feature?
- close #4159
- close #4144
- close #4172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/4162)
=> bug(history): mock dynamic binding as default export not following es spec

packages/umi-build-dev/src/plugins/history.js
=> fix: history basename

packages/preset-built-in/src/plugins/features/base.ts
=> fix: base schema

docs/docs/README.zh-CN.md
fix spelling mistake
- any feature?
-----
[View rendered docs/docs/README.zh-CN.md](https://github.com/hezhongfeng/umi/blob/patch-1/docs/docs/README.zh-CN.md)
=> docs: fix spelling mistake

packages/preset-built-in/src/plugins/generateFiles/core/history.tpl
=> fix: history tpl typo

packages/server/src/Server/Server.ts
ref: https://github.com/ant-design/ant-design-pro/pull/6039#issuecomment-600891632
为什么会不存在呢？
- any feature?
=> fix: windows server

docs/config/README.md, docs/config/README.zh-CN.md, packages/preset-built-in/src/plugins/generateFiles/core/polyfill.tpl, packages/preset-built-in/src/plugins/generateFiles/core/polyfill.ts, packages/types/index.d.ts
提供可以按需引入core-js的配置入口。
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/JhonXY/umi/blob/master/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/JhonXY/umi/blob/master/docs/config/README.zh-CN.md)
=> feat: can import only-required-for-you polyfills by core-js

packages/bundler-webpack/src/getConfig/css.ts, packages/bundler-webpack/src/getConfig/getConfig.ts
=> fix: sourcemap don't work in prod

packages/core/src/Service/Service.test.ts, packages/core/src/Service/Service.ts, packages/core/src/Service/fixtures/api-registerCommand/plugin.js
=> feat: add api.service.runCommand()

packages/server/src/Server/Server.ts
ref: https://github.com/umijs/umi/pull/4209
- any feature?
=> fix: windows server undefined

packages/ast/src/isReactComponent/isReactComponent.ts
=> perf 提前结束jsx遍历，提高运行效率

packages/server/src/Server/Server.ts
=> fix: server https env

packages/core/package.json, packages/core/src/Route/routesToJSON.test.ts, packages/core/src/Route/routesToJSON.ts, packages/server/package.json, yarn.lock
=> fix: webpack chunk name dynamic routes

packages/preset-built-in/package.json, packages/runtime/package.json, packages/runtime/src/index.ts, yarn.lock
=> fix: query is lost in history type definition

docs/plugins/plugin-antd.md, docs/plugins/plugin-antd.zh-CN.md
deps on https://github.com/umijs/plugins/pull/120
-----
[View rendered docs/plugins/plugin-antd.md](https://github.com/umijs/umi/blob/feat-antd-theme-compact/docs/plugins/plugin-antd.md)
[View rendered docs/plugins/plugin-antd.zh-CN.md](https://github.com/umijs/umi/blob/feat-antd-theme-compact/docs/plugins/plugin-antd.zh-CN.md)
=> docs: Add compact theme config to plugin-antd

docs/plugins/plugin-initial-state.md, docs/plugins/plugin-initial-state.zh-CN.md
add docs for https://github.com/umijs/plugins/pull/123
-----
[View rendered docs/plugins/plugin-initial-state.md](https://github.com/umijs/umi/blob/docs/plugin-initial-state/docs/plugins/plugin-initial-state.md)
[View rendered docs/plugins/plugin-initial-state.zh-CN.md](https://github.com/umijs/umi/blob/docs/plugin-initial-state/docs/plugins/plugin-initial-state.zh-CN.md)
=> docs: add APIs for plugin-initial-state

packages/core/src/Route/Route.test.ts, packages/core/src/Route/Route.ts, packages/preset-built-in/src/plugins/commands/config/config.ts
=> fix: route path patch start with http://

packages/umi-build-dev/src/getConfig/configPlugins/runtimePublicPath.js
ref https://github.com/umijs/umi/pull/3975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi/4291)
=> feat(runtimePublicPath): 支持传入字符串变量

docs/plugins/plugin-request.md, docs/plugins/plugin-request.zh-CN.md
-----
[View rendered docs/plugins/plugin-request.md](https://github.com/umijs/umi/blob/docs/request/docs/plugins/plugin-request.md)
[View rendered docs/plugins/plugin-request.zh-CN.md](https://github.com/umijs/umi/blob/docs/request/docs/plugins/plugin-request.zh-CN.md)
=> docs: udpate and fix request plugin doc

docs/docs/directory-structure.md
-----
[View rendered docs/docs/directory-structure.md](https://github.com/carlisliu/umi/blob/master/docs/docs/directory-structure.md)
=> fixed: typo

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/template/entry.js.tpl, packages/umi-plugin-dva/template/dva.js.tpl
ref: https://github.com/umijs/umi/pull/4300
- any feature?
=> fix: ssr initialValue

docs/docs/routing.md
- any feature?
-----
[View rendered docs/docs/routing.md](https://github.com/bibidu/umi/blob/patch-2/docs/docs/routing.md)
=> docs 更新路由文档

packages/core/src/Route/Route.test.ts, packages/core/src/Route/fixtures/conventional-normal/pages/users/add.tsx, packages/core/src/Route/getConventionalRoutes.ts
- any feature?
- close #4288
- close #4289
=> fix: convention routing sort

docs/config/README.md, docs/config/README.zh-CN.md
添加一些关于 `favicon` 配置的说明，降低小白用户开issue的频率
-----
[View rendered docs/config/README.md](https://github.com/leftstick/umi/blob/master/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/config/README.zh-CN.md)
=> docs: enhance favicon part

docs/config/README.md, docs/config/README.zh-CN.md, packages/preset-built-in/src/plugins/commands/dev/dev.ts, packages/preset-built-in/src/plugins/generateFiles/umi.tpl, packages/preset-built-in/src/plugins/generateFiles/umi.ts, packages/renderer-react/src/renderClient/renderClient.tsx
- any feature?
- close #4249
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/feat/support-disable-title/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/feat/support-disable-title/docs/config/README.zh-CN.md)
=> feat: support disable title by set it to false

docs/docs/env-variables.md, docs/docs/env-variables.zh-CN.md, packages/bundler-webpack/src/webpackHotDevClient/webpackHotDevClient.ts
- any feature?
-----
[View rendered docs/docs/env-variables.md](https://github.com/umijs/umi/blob/feat/support-SOCKET_SERVER/docs/docs/env-variables.md)
[View rendered docs/docs/env-variables.zh-CN.md](https://github.com/umijs/umi/blob/feat/support-SOCKET_SERVER/docs/docs/env-variables.zh-CN.md)
=> feat: support custom socket server with env SOCKET_SERVER

docs/docs/env-variables.md, docs/docs/env-variables.zh-CN.md, packages/bundler-webpack/src/index.ts
- any feature?
-----
[View rendered docs/docs/env-variables.md](https://github.com/umijs/umi/blob/feat/env-WATCH_IGNORED/docs/docs/env-variables.md)
[View rendered docs/docs/env-variables.zh-CN.md](https://github.com/umijs/umi/blob/feat/env-WATCH_IGNORED/docs/docs/env-variables.zh-CN.md)
=> feat: support env WATCH_IGNORED for lib debugging

docs/api/README.md, docs/api/README.zh-CN.md
增加 路由相关文档
-----
[View rendered docs/api/README.md](https://github.com/leftstick/umi/blob/master/docs/api/README.md)
[View rendered docs/api/README.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/api/README.zh-CN.md)
=> docs: details of #4311

packages/umi-build-dev/src/plugins/commands/block/download.js, packages/umi-build-dev/src/plugins/commands/block/download.test.js
=> 🙈 code: default shoud use umi@2 branch

.umirc.ts, docs/docs/navigate-between-pages.md, docs/docs/navigate-between-pages.zh-CN.md
- any feature?
-----
[View rendered docs/docs/navigate-between-pages.md](https://github.com/umijs/umi/blob/docs-navigate-between-pages/docs/docs/navigate-between-pages.md)
[View rendered docs/docs/navigate-between-pages.zh-CN.md](https://github.com/umijs/umi/blob/docs-navigate-between-pages/docs/docs/navigate-between-pages.zh-CN.md)
=> docs: navigate-between-pages

packages/create-umi-app/templates/AppGenerator/package.json.tpl
=> feat: add umi g tmp postinstall script to boilerplate

.gitignore, docs/config/README.md, docs/config/README.zh-CN.md, packages/bundler-webpack/package.json, packages/bundler-webpack/src/fixtures/css-modules-typescript-loader/config.ts, packages/bundler-webpack/src/fixtures/css-modules-typescript-loader/expect.ts, packages/bundler-webpack/src/fixtures/css-modules-typescript-loader/index.ts, packages/bundler-webpack/src/fixtures/css-modules-typescript-loader/style.less, packages/bundler-webpack/src/fixtures/css-modules-typescript-loader/style2.css, packages/bundler-webpack/src/getConfig/css.ts, packages/bundler-webpack/src/index.test.ts, packages/types/index.d.ts, yarn.lock
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/zhanba/umi/blob/feat/css-modules-typings/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/zhanba/umi/blob/feat/css-modules-typings/docs/config/README.zh-CN.md)
=> feat: add css-modules-typescript-loader option

packages/umi-build-dev/src/FilesGenerator.js, packages/umi-build-dev/template/entry.js.tpl, packages/umi-plugin-dva/template/dva.js.tpl, packages/umi/yarn.lock, yarn.lock
=> Revert "fix: ssr initialValue"

packages/preset-built-in/src/plugins/features/devScripts.ts
=> fix: webpack hot client don't included in some situation

packages/preset-built-in/src/plugins/features/alias.ts
=> fix: clientDependencies

docs/config/README.md, docs/config/README.zh-CN.md
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/docs-config/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/docs-config/docs/config/README.zh-CN.md)
=> docs: config

docs/plugins/plugin-dva.md, docs/plugins/plugin-dva.zh-CN.md
- any feature?
-----
[View rendered docs/plugins/plugin-dva.md](https://github.com/xg4/umi/blob/master/docs/plugins/plugin-dva.md)
[View rendered docs/plugins/plugin-dva.zh-CN.md](https://github.com/xg4/umi/blob/master/docs/plugins/plugin-dva.zh-CN.md)
=> docs: add ImmerReducer type for plugin-dva

packages/types/index.d.ts
Close https://github.com/umijs/umi/pull/4406
- any feature?
=> chore: nodeModulesTransform exclude is optional

packages/preset-built-in/src/plugins/features/forkTSChecker.ts
=> chore: ts checker options

package.json, packages/umi-plugin-locale/src/index.js, packages/umi-plugin-locale/template/wrapper.jsx.tpl, packages/umi-plugin-locale/test/index.test.js, packages/umi-ui/client/package.json, packages/umi/yarn.lock, yarn.lock
Close https://github.com/ant-design/ant-design/issues/9989#issuecomment-613236968  
Close https://github.com/ant-design/ant-design-pro/issues/6356
- any feature?
=> fix: antd 4.1.2+ locale

docs/docs/config.md, docs/docs/config.zh-CN.md
#4335 ### Checklist
增加对临时配置的注意内容，降低用户开issue提问的频率
-----
[View rendered docs/docs/config.md](https://github.com/leftstick/umi/blob/master/docs/docs/config.md)
[View rendered docs/docs/config.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/docs/config.zh-CN.md)
=> docs: note for local config

docs/config/README.md, docs/config/README.zh-CN.md, packages/preset-built-in/src/plugins/features/cssLoader.ts
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/docs-css-loader/docs/config/README.md)
[View rendered docs/config/README.zh-CN.md](https://github.com/umijs/umi/blob/docs-css-loader/docs/config/README.zh-CN.md)
=> docs: css-loader options types and documents

packages/create-umi-app/templates/AppGenerator/tsconfig.json
Close https://github.com/umijs/umi/issues/4465
- any feature?
=> fix: .umirc.ts types

packages/bundler-webpack/src/getConfig/getConfig.ts, packages/types/index.d.ts
=> ✏️ typos: title should support false

packages/preset-built-in/src/plugins/commands/generateFiles.ts
=> fix: layout watch failed when config.singular is true

packages/renderer-react/src/index.ts
=> fix: enhance route component type

.github/workflows/gitleaks.yml
=> chore: gitleaks action using fetch-depth 1

docs/README.zh-CN.md
- any feature?
-----
[View rendered docs/README.zh-CN.md](https://github.com/LeoYuan/umi/blob/patch-1/docs/README.zh-CN.md)
=> chore(doc): fix typo

README.md, README.zh-CN.md, docs/README.md, docs/README.zh-CN.md, packages/umi/README.md
- any feature?
-----
[View rendered README.md](https://github.com/umijs/umi/blob/docs-umi-next/README.md)
[View rendered README.zh-CN.md](https://github.com/umijs/umi/blob/docs-umi-next/README.zh-CN.md)
[View rendered docs/README.md](https://github.com/umijs/umi/blob/docs-umi-next/docs/README.md)
[View rendered docs/README.zh-CN.md](https://github.com/umijs/umi/blob/docs-umi-next/docs/README.zh-CN.md)
[View rendered packages/umi/README.md](https://github.com/umijs/umi/blob/docs-umi-next/packages/umi/README.md)
=> docs: remove umi next

docs/config/README.md, docs/config/README.zh-CN.md
- any feature?
-----
[View rendered docs/config/README.md](https://github.com/umijs/umi/blob/xiaohuoni-patch-2/docs/config/README.md)
=> docs: 添加 publicPath 说明

docs/api/README.md, docs/api/README.zh-CN.md
for https://github.com/umijs/umi/issues/4510
增加细节描述和使用场景介绍。方便小白用户理解并使用 `dynamic` 模块
-----
[View rendered docs/api/README.md](https://github.com/leftstick/umi/blob/master/docs/api/README.md)
[View rendered docs/api/README.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/api/README.zh-CN.md)
=> docs: enhance dynamic api for newbies

docs/guide/plugin-develop.md, docs/guide/plugin-develop.zh-CN.md
等待 https://github.com/umijs/create-umi/pull/107 合并，并发包。
- any feature?
-----
[View rendered docs/guide/plugin-develop.md](https://github.com/umijs/umi/blob/docs-plugin-develop/docs/guide/plugin-develop.md)
[View rendered docs/guide/plugin-develop.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin-develop/docs/guide/plugin-develop.zh-CN.md)
=> docs: add plugin develop

packages/bundler-webpack/src/getConfig/getConfig.ts
umi3启动后ico文件未被解析产生报错，在images规则中添加ico文件
- any feature?
=> feat: loader support ico format files

packages/preset-built-in/src/plugins/features/nodeModulesTransform.ts
=> fix: nodeModules exclude schema defination

packages/create-umi-app/templates/AppGenerator/typings.d.ts
提升 `import { ReactComponent as xxx} from 'xxx.svg'` 的编程体验，如demo所示：
=> feat: improve .svg component experience

packages/bundler-webpack/src/fixtures/define/expect.ts, packages/bundler-webpack/src/getConfig/getConfig.ts, packages/bundler-webpack/src/getConfig/resolveDefine.test.ts, packages/bundler-webpack/src/getConfig/resolveDefine.ts, packages/bundler-webpack/src/getConfig/utils.ts, packages/preset-built-in/src/plugins/commands/webpack/webpack.test.ts, packages/types/index.d.ts
- 修复使用 process.env.xxx，如果 xxx 不存在会泄露所有环境变量的问题
- close https://github.com/umijs/umi/issues/4550
=> fix: process.env leak all env variables

docs/docs/load-on-demand.md, docs/docs/load-on-demand.zh-CN.md
improve doc of `load-on-demand`
-----
[View rendered docs/docs/load-on-demand.md](https://github.com/leftstick/umi/blob/master/docs/docs/load-on-demand.md)
[View rendered docs/docs/load-on-demand.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/docs/load-on-demand.zh-CN.md)
=> docs: improve doc of load-on-demand

packages/preset-built-in/src/plugins/features/devScripts.ts
devScripts，Umi UI 受影响，
- any feature?
=> fix: devScripts publicPath

docs/docs/assets-image.md, docs/docs/assets-image.zh-CN.md
svg 使用介绍
-----
[View rendered docs/docs/assets-image.md](https://github.com/leftstick/umi/blob/master/docs/docs/assets-image.md)
[View rendered docs/docs/assets-image.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/docs/assets-image.zh-CN.md)
=> docs: svg usage

docs/docs/env-variables.md, docs/docs/env-variables.zh-CN.md, packages/bundler-webpack/src/getConfig/getConfig.ts
- 测试 build 性能时有用，禁用缓存更公平一些。
-----
[View rendered docs/docs/env-variables.md](https://github.com/umijs/umi/blob/feat/terser-cache-env/docs/docs/env-variables.md)
[View rendered docs/docs/env-variables.zh-CN.md](https://github.com/umijs/umi/blob/feat/terser-cache-env/docs/docs/env-variables.zh-CN.md)
=> feat: support disable terser cache with TERSER_CACHE=none

packages/preset-built-in/src/plugins/commands/build/build.ts, packages/preset-built-in/src/plugins/commands/buildDevUtils.ts
Close https://github.com/umijs/umi/issues/4616
- any feature?
=> fix: size printer with APP_ROOT

packages/babel-preset-umi/package.json, packages/babel-preset-umi/src/index.test.ts, packages/babel-preset-umi/src/index.ts, yarn.lock
=> feat: support logical assignment operators

docs/docs/mock.md, docs/docs/mock.zh-CN.md
-----
[View rendered docs/docs/mock.md](https://github.com/umijs/umi/blob/docs/fixmock/docs/docs/mock.md)
[View rendered docs/docs/mock.zh-CN.md](https://github.com/umijs/umi/blob/docs/fixmock/docs/docs/mock.zh-CN.md)
=> docs: fix mock doc link

docs/plugins/plugin-model.md, docs/plugins/plugin-model.zh-CN.md
improve doc of `plugin-model` for newbies
-----
[View rendered docs/plugins/plugin-model.md](https://github.com/leftstick/umi/blob/master/docs/plugins/plugin-model.md)
[View rendered docs/plugins/plugin-model.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/plugins/plugin-model.zh-CN.md)
=> docs: improve of plugin-model

docs/guide/boost-compile-speed.zh-CN.md
语雀的图片看不了。
-----
[View rendered docs/guide/boost-compile-speed.zh-CN.md](https://github.com/umijs/umi/blob/afc163-patch-1/docs/guide/boost-compile-speed.zh-CN.md)
=> fix image url

docs/plugins/plugin-model.md, docs/plugins/plugin-model.zh-CN.md
add missed `useCallback` in example
-----
[View rendered docs/plugins/plugin-model.md](https://github.com/leftstick/umi/blob/master/docs/plugins/plugin-model.md)
[View rendered docs/plugins/plugin-model.zh-CN.md](https://github.com/leftstick/umi/blob/master/docs/plugins/plugin-model.zh-CN.md)
=> docs: add missed useCallback in code example

packages/preset-built-in/src/plugins/features/alias.ts, packages/types/index.d.ts
Include the following changes:
1. correct arg type for `modifyPaths` API
2. fix alias error if paths be updated via `modifyPaths`
=> fix: alias expired if paths be updated via modifyPaths

packages/preset-built-in/src/plugins/features/alias.ts
Correct error field in #4625 🤦‍♂️
=> refactor: correct field for @@ path alias

docs/plugins/plugin-qiankun.zh-CN.md
- any feature?
-----
[View rendered docs/plugins/plugin-qiankun.zh-CN.md](https://github.com/Aledenn/umi/blob/patch-1/docs/plugins/plugin-qiankun.zh-CN.md)
=> docs: update plugin-qiankun

packages/ast/src/utils/parse.ts, packages/babel-preset-umi/package.json, packages/babel-preset-umi/src/index.test.ts, packages/babel-preset-umi/src/index.ts, yarn.lock
=> feat: support top level await syntax

packages/preset-built-in/src/plugins/features/devScripts.ts
=> fix: HMR not work in eggjs

packages/preset-built-in/src/plugins/features/exportStatic.ts, packages/preset-built-in/src/plugins/features/ssr/templates/renderServer/renderServer.tsx
预渲染报错时，错误打印出来，并返回 CSR 内容
- any feature?
=> fix: prerender error

.nowignore
=> chore: now shouldn't ignore docs

.nowignore
=> chore: now ignore

packages/test/src/index.test.ts, packages/test/src/index.ts
修复 https://github.com/umijs/umi/issues/4661， 之前应该是笔误吧
=> fix: #4661

examples/ssr-with-eggjs/README.md, packages/bundler-webpack/src/index.ts
- any feature?
-----
[View rendered examples/ssr-with-eggjs/README.md](https://github.com/umijs/umi/blob/fix-devServer-bug/examples/ssr-with-eggjs/README.md)
=> fix: devServer must use /

packages/preset-built-in/src/plugins/generateFiles/umi.tpl
=> chore: fix title single quotes

packages/core/src/Config/Config.test.ts, packages/core/src/Config/Config.ts, packages/core/src/Config/fixtures/umi-env-dot-env-ext/.env, packages/core/src/Config/fixtures/umi-env-dot-env-ext/config/config.cloud.js, packages/core/src/Config/fixtures/umi-env-dot-env-ext/config/config.cloud.ts, packages/core/src/Config/fixtures/umi-env-dot-env-ext/config/config.js
`config.js` 和 `config.env.ts`，使用 `UMI_ENV=env` 无效的问题。
- any feature?
=> fix: env config should support `.ts` and `.js` extensions

docs/guide/boost-compile-speed.md, docs/guide/boost-compile-speed.zh-CN.md, docs/plugins/plugin-helmet.md, docs/plugins/plugin-helmet.zh-CN.md, docs/plugins/preset-react.md, docs/plugins/preset-react.zh-CN.md
- any feature?
-----
[View rendered docs/guide/boost-compile-speed.md](https://github.com/umijs/umi/blob/docs-plugin/docs/guide/boost-compile-speed.md)
[View rendered docs/guide/boost-compile-speed.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin/docs/guide/boost-compile-speed.zh-CN.md)
[View rendered docs/plugins/plugin-helmet.md](https://github.com/umijs/umi/blob/docs-plugin/docs/plugins/plugin-helmet.md)
[View rendered docs/plugins/plugin-helmet.zh-CN.md](https://github.com/umijs/umi/blob/docs-plugin/docs/plugins/plugin-helmet.zh-CN.md)
[View rendered docs/plugins/preset-react.md](https://github.com/umijs/umi/blob/docs-plugin/docs/plugins/preset-react.md)
[View rendered docs/plugins/preset-react.zh-CN.md](https://github.com/umijs/umi …
=> docs: plugin and monaco-editor

.umirc.ts, packages/renderer-mpa/src/renderClient/renderClient.tsx, packages/renderer-react/src/renderClient/renderClient.tsx
Close https://github.com/ant-design/ant-design-pro/issues/6620
Close https://github.com/umijs/umi/issues/4707
- any feature?
=> chore: flag to show ssr successed

packages/preset-built-in/src/plugins/features/exportStatic.ts
修复 modifyDefaultConfig 修改 `exportStatic` 后，enableBy 值判空问题
- any feature?
=> fix: modifyDefaultConfig not impact enableBy

docs/docs/ssr.md, docs/docs/ssr.zh-CN.md, packages/preset-built-in/src/fixtures/ssr-modifyServerHTML/.umirc.ts, packages/preset-built-in/src/fixtures/ssr-modifyServerHTML/app.ts, packages/preset-built-in/src/fixtures/ssr-modifyServerHTML/pages/index.tsx, packages/preset-built-in/src/index.test.ts, packages/preset-built-in/src/plugins/features/ssr/templates/renderServer/renderServer.test.tsx, packages/preset-built-in/src/plugins/features/ssr/templates/renderServer/renderServer.tsx, packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl, packages/renderer-react/src/renderRoutes/renderRoutes.tsx, packages/runtime/src/Plugin/Plugin.ts
Close https://github.com/umijs/umi/issues/4726
- any feature?
-----
[View rendered docs/docs/ssr.md](https://github.com/umijs/umi/blob/fix-ssr-runtimePlugins/docs/docs/ssr.md)
[View rendered docs/docs/ssr.zh-CN.md](https://github.com/umijs/umi/blob/fix-ssr-runtimePlugins/docs/docs/ssr.zh-CN.md)
=> fix: ssr runtime plugins modify not exec
